microsoft/botbuilder-dotnet

libraries/Microsoft.Bot.Builder.Ai/TranslationMiddleware.cs, libraries/Microsoft.Bot.Builder.BotFramework/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/Adapters/ActivityAdapterBase.cs, libraries/Microsoft.Bot.Builder/Adapters/ConsoleAdapter.cs, libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs, libraries/Microsoft.Bot.Builder/Bot.cs, libraries/Microsoft.Bot.Builder/BotContext.cs, libraries/Microsoft.Bot.Builder/BotStateManager.cs, libraries/Microsoft.Bot.Builder/IBotContext.cs, libraries/Microsoft.Bot.Builder/Middleware/IMiddleware.cs, libraries/Microsoft.Bot.Builder/Middleware/MiddlewareSet.cs, libraries/Microsoft.Bot.Builder/Middleware/PostToAdapterMiddleware.cs, libraries/Microsoft.Bot.Builder/Middleware/TemplateManager.cs, samples/Microsoft.Bot.Samples.CustomMiddleware/Middleware/ExampleMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/BotContext_Tests.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_ComposibilityTests.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_PostActivityTests.cs
Changed the IPostActivity Middleware name to ISendActivity. This change was then pulled through the BotBuilder layer in the SDK, including all Middlware and tests. 
The motivation is that nobody looks for "Post", instead everyone looks for Send.
The underlying protocol + swagger layers use "Send" rather than "Post". This more closely aligns the BotBuilder with the underlying protocol.
=> Renamed PostActivity to SendActivity throughout the BotBuilder layer.

libraries/Microsoft.Bot.Builder.Ai/QnAMaker.cs
Issue with QnA Maker when there is no message text.
User can invoke bot without sending any text eg. by uploading an attachment.
To reproduce:
- Add QnAMaker Middleware
- Use emulator to invoke bot with an attachment (with no text)
=> QnAMaker Middleware bug: Assumes MessageActivity.Text will always have a value

libraries/Microsoft.Bot.Builder/Assertions.cs, libraries/Microsoft.Bot.Builder/Bot.cs, libraries/Microsoft.Bot.Builder/Middleware/BindOutgoingResponsesMiddlware.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_BindOutoingResponsesTests.cs
This PR allows a developer to simple send a new Activity, with no set conversation fields, through the outgoing pipeline. 
The pipeline will correctly apply the ConversationReference fields to the outgoing activity. 
The primary motivatios here are:
1. Allows a developer to simply construct a new activity, set the .Text field, and send it. The framework will apply the remaining fields. 
2. Alignment with [Node SDK, which does this. ](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/bot.ts#L154)
This addresses issue #96
=> Added Conversation Binding to outgoing messages, similar to JS

libraries/Microsoft.Bot.Builder/Bot.cs, libraries/Microsoft.Bot.Builder/BotContext.cs, libraries/Microsoft.Bot.Builder/IBotContext.cs, libraries/Microsoft.Bot.Builder/Middleware/MiddlewareSet.cs, samples/AlarmBot-Cards/Controllers/MessagesController.cs, samples/AlarmBot/Controllers/MessagesController.cs, samples/Microsoft.Bot.Samples.Ai.Luis/Controllers/MessagesController.cs, samples/Microsoft.Bot.Samples.Ai.QnA/Controllers/MessagesController.cs, samples/Microsoft.Bot.Samples.CustomMiddleware/Controllers/MessagesController.cs, samples/Microsoft.Bot.Samples.EchoBot-Console/Program.cs, samples/Microsoft.Bot.Samples.Simplified.Asp/BotController.cs, tests/Microsoft.Bot.Builder.Ai.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.Ai.Tests/QnAMakerTests.cs, tests/Microsoft.Bot.Builder.Tests/Adapter_TestAdapterTests.cs, tests/Microsoft.Bot.Builder.Tests/BotContext_Tests.cs, tests/Microsoft.Bot.Builder.Tests/ContextExtensionTests.cs, tests/Microsoft.Bot.Builder.Tests/Intent_RegExRecognizerTests.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_BindOutoingResponsesTests.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_ComposibilityTests.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_ContextCreatedTests.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_PostActivityTests.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_ReceiveActivityTests.cs, tests/Microsoft.Bot.Builder.Tests/State_BasicTests.cs, tests/Microsoft.Bot.Builder.Tests/Templates_TemplateManagerTests.cs
Addresses issue #114 
This change simplifies the use of OnReceive() as a pattern. The new usage aligns more with the "Expected" behavior, as observed during actual customer usage 
In the previous mechanism, each OnReceive was created as a new Anononymous Middleware component and added to the queue. This worked fine for test scenarios and simple bots, but did NOT have the correct semantics for ASP.Net usage. See issue #114 for more details. 
To fix this, the following has been done:
1. Removed the "Is A" relationship between Bot and MiddlewareSet. This had originally been envisioned by Steve & I as a mechanism by which composibility could be done, but turns out just to be confusing. The Bot is a Bot, and "has a" middleware set (composition instead of inheritance). This also simplifies the …
=> Simplified Construction and Ordering of Bot/MiddlwareSet Interactions

libraries/Microsoft.Bot.Builder.Ai/QnAMakerMiddleware.cs, samples/Microsoft.Bot.Samples.Ai.QnA/Controllers/MessagesController.cs, tests/Microsoft.Bot.Builder.Ai.Tests/QnAMakerTests.cs
Changing QnAMaker to QnAMakerMiddleware to be consistent for #120.
Suffixing with Middleware seems to be consistent with how Microsoft is naming other common types: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces
=> Changing QnAMaker to QnAMakerMiddleware to be consistent for #120.

libraries/Microsoft.Bot.Builder.Ai/QnAMaker.cs, libraries/Microsoft.Bot.Builder.Ai/QnAMakerMiddleware.cs, libraries/Microsoft.Bot.Builder/Bot.cs, samples/Microsoft.Bot.Samples.Ai.QnA/Controllers/MessagesController.cs, tests/Microsoft.Bot.Builder.Ai.Tests/QnAMakerTests.cs
Potential fix to #107. I have created a static instance of HttpClient in the Bot class as it is one of the most core classes of the BotBuilder.
According to the docs HttpClient is thread safe and is encouraged to be shared. 
https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/#considerations
=> QnAMakerMiddleware with static HttpClient

libraries/Microsoft.Bot.Builder/Bot.cs, libraries/Microsoft.Bot.Builder/ContextExtensions/ContextExtensionMethods.cs, libraries/Microsoft.Bot.Schema/ActivityTypes.cs, tests/Microsoft.Bot.Builder.Tests/ContextExtensionTests.cs
When the IActivitie's were being processed ServiceUrl and Conversation were not set. This was preventing the Typing from being sent.
I added the SendActivity method back because there is no flush method in order to force the Typing Activity to show in the chat client.
=> Fixing show typing and delay

libraries/Microsoft.Bot.Builder/ContextExtensions/ContextExtensionMethods.cs
The `ContextExtensions` should be in `Microsoft.Bot.Builder` namespace; in order to use them, users need to see them. They don't see them if they have to import a completely separate namespace. In JS SDK, this hurdle doesn't exist; shouldn’t in .Net.
=> change ContextExtensionMethods namespace

samples/AlarmBot-Cards/DateTimeRecognizerExtensions.cs, samples/AlarmBot/DateTimeRecognizerExtensions.cs
This change allows the extension method to return both date and datetime while still preventing ranges, which was indicated as desired behavior in the comments.
=> DateTimeRecognizerExtension does not return dates without times

libraries/Microsoft.Bot.Builder.Ai/TranslationMiddleware.cs, libraries/Microsoft.Bot.Builder.Ai/Translator.cs, libraries/Microsoft.Bot.Builder.BotFramework/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Connector.AspNetCore/BotAuthenticationHandler.cs, libraries/Microsoft.Bot.Connector/AttachmentsEx.cs, libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EndorsementsRetriever.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs, samples/Microsoft.Bot.Samples.Ai.QnA/Controllers/MessagesController.cs, samples/Microsoft.Bot.Samples.Simplified.Asp/appsettings.json
Enabled reuse of HttpClient throughout the BotBuilder and Connector stack. 
This is needed to allow proper connection management + pooling, and also allows the developer at the very top of the stack to make any necessary changes (timeouts, etc) to the HttpClient used throughout the stack. 
Addresses #60, #106
=> Reuse of HttpClient throughout the Stack.

libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs, tests/Microsoft.Bot.Builder.Tests/Adapter_TestAdapterTests.cs
Addresses #135.
Note that while I added tests, I couldn't get a test that **actually** exercised the new behavior. 
The behavior in this new code is clearly better, but how to get these tests to fault while using the standard semantics is complicated. 
I would be very interested in seeing a solution to how to test this.
=> Pass exceptions on Faulted Tasks as inner Exceptions.

tests/Microsoft.Bot.Builder.Ai.Tests/QnAMakerTests.cs, tests/Microsoft.Bot.Builder.Tests/Adapter_TestAdapterTests.cs
This PR is a remake of #142 to pull to master instead of the PassExceptionsOnTaskFaults branch.
=> Adding test case for aggregate exception

libraries/Microsoft.Bot.Builder.Ai/QnAMaker.cs, libraries/Microsoft.Bot.Builder.Ai/QnAMakerMiddleware.cs, tests/Microsoft.Bot.Builder.Ai.Tests/QnAMakerMiddlewareTests.cs, tests/Microsoft.Bot.Builder.Ai.Tests/QnAMakerTests.cs
Moved `GetAnswers` logic to separate class that is used in middleware and can be reused without it. There are test for QnA but they are commented and i don`t know how to run them.
@drub0y @daltskin
Closes #124 and i believe #137 as well.
=> Extracted QnAMaker logic from corresponding middleware

libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConstants.cs, libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/ICredentialProvider.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs
Fixes:
- Comments
- Removes v3.x token checks, since they don't exist as token versions
- Moves constants into AuthenticationConstants.cs. We already had some emulator- and channel-specific constants there and I figured people would rather go toward centralizing than splitting.
=> Auth cleanup

libraries/Microsoft.Bot.Builder.Ai/QnAMaker.cs
Updated QnAMaker to use v3 API (http://bit.ly/2EA7syR) which brings optional support for metadata to filter / boost answers returned. I can't see any downsides to implementing v3, given that it works exactly like v2, but with optional metadata properties on the request and in the response. If the user does not specify any metadata on the QnAMakerOptions.
@cleemullins As mentioned on the previous pull request to split out the QnAMaker from the middleware, I tried running the QnAMaker tests, but they are commented out at the moment.  I have however ran the QnA sample against my own QnA service (which has metadata against some of the items in the KB) and all seems to be working well.
@daltskin
=> Updated QnAMaker to use v3 API

libraries/Microsoft.Bot.Builder.Ai/QnAMaker.cs, libraries/Microsoft.Bot.Builder.Ai/QnAMakerMiddleware.cs, libraries/Microsoft.Bot.Builder/Bot.cs, libraries/Microsoft.Bot.Builder/Middleware/MiddlewareSet.cs, libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConstants.cs, libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/ICredentialProvider.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs, tests/Microsoft.Bot.Builder.Ai.Tests/QnAMakerMiddlewareTests.cs, tests/Microsoft.Bot.Builder.Ai.Tests/QnAMakerTests.cs, tests/Microsoft.Bot.Builder.Tests/Adapter_TestAdapterTests.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_EchoTests.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_ReceiveActivityTests.cs
#130 
This alters the behavior of the Bot, so that OnReceive is ONLY called if all relevant Middleware completes. If any middleware fails to call next, or throws, the the OnReceive handler will not be called. Based on consenus in #130, this is the desired behavior. 
The only "edge" case is a Pipeline with no relevant Middleware. I've defined this as "Run OnReceive if there is no Middleware". This seems the correct behavior. 
Relevant tests around this have been added testing the various conditions.
=> OnReceive is only run if all relevant Middleware Complete

libraries/Microsoft.Bot.Builder.BotFramework/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/Adapters/ConsoleAdapter.cs, libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs, libraries/Microsoft.Bot.Builder/ContextExtensions/ContextExtensionMethods.cs, libraries/Microsoft.Bot.Schema/ActivityTypes.cs, libraries/Microsoft.Bot.Schema/ActivityTypesEx.cs
We have an context extension method which was using an activity type of "delay".  Given that this is part of the core SDK, I have brought this in line with other activity types and added it to the ActivityTypes class to prevent the need to use a magic string for comparison and hopefully avoid typo mistakes.
=> Added Delay to ActivityTypes to prevent need to use magic string

libraries/Microsoft.Bot.Builder/Bot.cs, tests/Microsoft.Bot.Builder.Tests/BotContext_Tests.cs, tests/Microsoft.Bot.Builder.Tests/Bot_FunctionalTests.cs
The SendPipeline needs to run even when there is nothing in the queue to send. This allows any registered "Cleanup" or "Post Processing" middleware to run. BotState.Save being a good example. 
We should (discussed in various issues) at least Rename this pipeline to more accurately reflect that it's a post-processing step. 
**The Node SDK already works this way. **
@RyanDawkins
=> Always run the SendPipeline, even if there's nothing to send.

libraries/Microsoft.Bot.Builder.Ai/QnAMakerMiddleware.cs, libraries/Microsoft.Bot.Builder.Ai/QnAMakerMiddlewareOptions.cs, samples/Microsoft.Bot.Samples.Ai.QnA/Controllers/MessagesController.cs, tests/Microsoft.Bot.Builder.Ai.Tests/QnAMakerMiddlewareTests.cs
@cleemullins Included a new QnAMakerMiddlewareOptions class which can be passed to the QnAMakerMiddleware constructor.  This allows the user to specify that the routing should be short circuited on a successful answer.  This seems like a sensible option to provide in the case that the middleware is being used in a chain.
Another option is available to define a default message to be output before a top answer is returned. e.g. "I found this answer that might help...".
I have updated the sample to include comments to show how this can be used.  **I am not sure how to update the wiki to include this information, but if you tell me how then I am happy to do this.**
If the PR looks good then I am happy to implement something similar for the LUIS Middleware (certainly the option the short …
=> QnAMakerMiddleware options

libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
Removed not-needed keyword that was causing a warning
=> Fix minor build warnings in the Test Adapter`

libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs, libraries/Microsoft.Bot.Builder.Core/Middleware/MiddlewareSet.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_BracketingTest.cs, tests/Microsoft.Bot.Builder.Tests/Middleware_ReceiveActivityTests.cs
#184 
Updated MiddlewearSet and relevant dependencies + tests to support the "Bracketed" Middleware. That issue says code like this should work:
```
context.Reply("{"); // Leading Edge
await next();
context.Reply("}"); // Trailing Edge
```
I've included an explicit test for this, as well as one validating that Exceptions that are thrown can be properly handled. The new tests around this are very explicit in the ordering. For example:
```
await new TestFlow(adapter, Echo)
.Send("test")
.AssertReply("BEFORE")
.AssertReply("ECHO:test")
.AssertReply("AFTER")
.StartTest();
```
At a technical level, we want (per this example) the user supplied delegate to be run here:
1. All Leading edge middleware calls made.
2. Delegate called.
3. All trailing edge middleware code is run.  
All previous tests …
=> Addresses Issue #184, which is that bracketing should work correctly

samples/AlarmBot-Cards/AlarmBot-Cards.csproj, samples/AlarmBot/AlarmBot.csproj
Addresses #127 
Updated to the latest recognizer-text package. This package supports .NetStandard2.0 which makes a number of build warnings go away.
=> Updated to latest Recognizer packages, which support NetStandard2.0

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs
Fixes #226 
* Intro'd a static set of empty credentials on `MicrosoftAppCredentials` to minimize allocations/garbage being created for that scenario
* Updated `BotFrameworkAdapter` to detect `null` application identity and use `Microsoft.AppCredentials.Empty` in that case
=> Fix BotFrameworkAdapter::GetAppCredentials assuming configured credentials

libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs, samples/Microsoft.Bot.Samples.Connector.EchoBot/Controllers/MessagesController.cs, tests/Microsoft.Bot.Connector.Tests/JwtTokenValidationTests.cs
* Fixes #226 (for real this time) by updating `JwTTokenValidation::AuthenticateRequest` to properly account for disabled authentication scenarios.
* Draws clearer line btwn responsibilities of `JwtTokenValidation`'s `AuthenticationRequest` method and `ValidateAuthHeader` method
* Adds unit tests for both methods to cover these scenarios going forward and fixes a test that wasn't really asserting correctly in the first place.
=> Support disabled authentication scenario correctly

libraries/Microsoft.Bot.Builder.Azure/AzureTableStorage.cs, libraries/Microsoft.Bot.Builder.Core/IStorage.cs, libraries/Microsoft.Bot.Builder.Core/Storage/FileStorage.cs, libraries/Microsoft.Bot.Builder.Core/Storage/MemoryStorage.cs, tests/Microsoft.Bot.Builder.Azure.Tests/TableStorageTests.cs, tests/Microsoft.Bot.Builder.Tests/Storage_BaseTests.cs, tests/Microsoft.Bot.Builder.Tests/Storage_FileTests.cs, tests/Microsoft.Bot.Builder.Tests/Storage_MemoryTests.cs
If IStoreItem interface is implemented then eTag semantics will apply.  This allows truly POCO objects to be stored under a key in storage
=> changed to allow pure POCO objects to be stored

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotActivitiesHandler.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
This PR fixes #246 by utilizing `MediaTypeHeaderValue::TryParse` which handles the many nuances of media type header values and then simply validation it's `application/json`  against that.
Additional work:
* Breakes the handler out into its own class for better SRP (fixes
#240)
* Explicitly aligns JSON.NET serializer settings with the NetFx version
=> Better handling of Content-Type header in .NET Core Framework

libraries/Microsoft.Bot.Builder.Core/IStorage.cs, libraries/Microsoft.Bot.Builder.Core/Middleware/BotState.cs, tests/Microsoft.Bot.Builder.Tests/State_BasicTests.cs
Now that support was added to state management for POCOs they are no
longer _required_ `IStoreItem`, so we can/should remove the subtype
restriction on `StateT` from `BotState<StateT>` et. al.
This was raised as an issue in #248, though the discussion there spiraled 
into something broader.
=> Remove restriction of IStoreItem from StateT

libraries/Microsoft.Bot.Builder.Core/BotContext.cs, libraries/Microsoft.Bot.Builder.Core/BotContextWrapper.cs, libraries/Microsoft.Bot.Builder.Core/IBotContext.cs, libraries/Microsoft.Bot.Builder.Prompts/BasePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/Microsoft.Bot.Builder.Prompts.csproj, tests/Microsoft.Bot.Builder.Core.Tests/BotContextTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/AgePromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/ConfirmPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/CurrencyPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/DimensionPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/NumberPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/OrdinalPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/PercentagePromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/PhoneNumberPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/RangePromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/TemperaturePromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/TextPromptTests.cs
Removes the batch processing from prompts. This also means the Core.Extensions assembly is no longer needed as a reference, and the BatchMiddleware is not needed in any way. 
Discussed yesterday with Tom & Steve, and Node will update to also removing batching. 
Also tracked in #293
=> Remove Batch processing from prompts and update tests

tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj
Details: warning NU1608: Detected package version outside of dependency constraint: Microsoft.Azure.Test.HttpRecorder 1.7.0 requires Newtonsoft.Json (>= 9.0.1 && < 10.0.0) but version Newtonsoft.Json 10.0.3 was resolved.
=> Suppress build warning NU1608 for Microsoft.Bot.Connector.Tests

libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/ConnectorEx/BotToUser.cs, libraries/Microsoft.Bot.Builder.Core.Extensions/BatchOutput.cs, libraries/Microsoft.Bot.Builder.Core/Adapters/ConsoleAdapter.cs, libraries/Microsoft.Bot.Builder.Core/Adapters/TestAdapter.cs, libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs, libraries/Microsoft.Bot.Builder.Core/BotContext.cs, libraries/Microsoft.Bot.Builder.Core/BotContextWrapper.cs, libraries/Microsoft.Bot.Builder.Core/IBotContext.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, tests/Microsoft.Bot.Builder.Core.Extensions.Tests/BatchOutputTests.cs, tests/Microsoft.Bot.Builder.Core.Tests/BotAdapterTests.cs, tests/Microsoft.Bot.Builder.Core.Tests/BotContextTests.cs, tests/Microsoft.Bot.Builder.Core.Tests/SimpleAdapter.cs, tests/Microsoft.Bot.Builder.Core.Tests/TestMessage.cs, tests/Microsoft.Bot.Builder.TemplateManager/TemplateManagerTests.cs
When activities are sent, a server-generated ID is returned. In some cases the developer needs this Id in order to later Update or Delete an activity. 
The plumbing of the Resource Response from the Connector up through the BotContext on all the relevant Send/Update methods is needed to enable this scenario. 
While in here, I've also refactored the SendActivity() method to only take a single activity. Created a new SendActivities( Activity[] ) method to accept a batch of activities. This aligns with discussions with Tom and Steve for how this should be - optimized for the simple case ("Send 1 Activity") while still keeping the ability to send multiple.
=> Wire ResourceResponses through from the Connector through the BotContext

samples/AlarmBot-Cards/Startup.cs, samples/AlarmBot/Startup.cs
Added CatchException and ShowTyping middleare to Alarm Bot example to demonstrate usage with an appropriate comment for each. cc/ @cleemullins
=> Add CatchException and ShowTyping middleware to Alarm bot sample

libraries/Microsoft.Bot.Builder.Core/ITurnContext.cs, libraries/Microsoft.Bot.Builder.Core/TurnContext.cs, libraries/Microsoft.Bot.Builder.Core/TurnContextWrapper.cs, tests/Microsoft.Bot.Builder.Core.Tests/TurnContextTests.cs
As per comments from @Stevenic in #361 I have added the ability to pass a conversation reference to context.DeleteActivity, bringing this SDK in line with JS.
=> Added overload to context.DeleteActivity to accept a reference

libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
- Update the Bot.Builder library to generate document file
- Tweak BotAdapter doc XML.
**Open question** re [BotFramewrokAdapter.CreateConversation](https://github.com/Microsoft/botbuilder-dotnet/blob/c46107cb25ba385446fc5c98ddab4f7440966b8e/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L274):
- Does this call always complete?
- Should any part of this be in a try-catch block?
- How should a bot developer check for success?
=> Add doc XML to BotFrameworkAdapter

libraries/Microsoft.Bot.Builder.Core/Adapters/ConsoleAdapter.cs, libraries/Microsoft.Bot.Builder.Core/Adapters/TestAdapter.cs, libraries/Microsoft.Bot.Builder.Core/TurnContext.cs, libraries/Microsoft.Bot.Builder.Core/TurnContextServiceCollection.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, tests/Microsoft.Bot.Builder.Core.Tests/SimpleAdapter.cs
* Make the `TurnContext` class `IDisposable`
* Make the `TurnContextServiceCollection` class `IDisposable`
* `TurnContext`'s implementation of `Dispose` disposes of its
`TurnContextServiceCollection` which in turn disposes of any services
inside of it that implement `IDisposable`
* All `XXXAdapter` classes updated to dispose of the `TurnContext`
instances they create
=> Make TurnContext IDisposable

tests/Microsoft.Bot.Builder.Azure.Tests/BlobTranscriptTests.cs
The new transcript tests would fail on initialize if the container was not there. This meant anytime they're run on a new machine, they would fail. 
Switched to a DeleteIfExists, and also made the init wait for the delete to complete.
=> Make Transcript tests pass on a "First time run" scenario

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandler.cs
This PR fixes an issue where bot framework authentication was not working with the ASP.NET Web API integration libraries. When calling processActivity on the BF activity, only the parameter for the auth header was being passed through, but the authenitcation libraries in the connector expect the whole header, i.e. scheme and param. cc @drub0y
=> Fix for authenitcation issue when using bot framework web api integration

tests/Microsoft.Bot.Builder.Ai.LUIS.Tests/LuisRecognizerMiddlewareTests.cs, tests/Microsoft.Bot.Builder.Ai.LUIS.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.Ai.QnA.Tests/QnAMakerMiddlewareTests.cs, tests/Microsoft.Bot.Builder.Ai.QnA.Tests/QnAMakerTests.cs, tests/Microsoft.Bot.Builder.Ai.Translation.Tests/TranslatorMiddlewareTests.cs, tests/Microsoft.Bot.Builder.Ai.Translation.Tests/TranslatorTests.cs, tests/Microsoft.Bot.Builder.Core.Extensions.Tests/TestUtilities.cs
We use the same approach found in the [Luis Recognizer Middleware tests](https://github.com/Microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.Ai.LUIS.Tests/LuisRecognizerMiddlewareTests.cs#L33) for all the tests that need specifics keys (environment variables):
1.  Validate the required environment variables with an EnvironmentVariablesDefined() method.
2. If any variable is not defined, terminate the test as a valid test.
This pull-request fixes #429
=> Fail safe tests with missing credentials

tests/Microsoft.Bot.Builder.Ai.QnA.Tests/QnAMakerMiddlewareTests.cs
We added missing environment variable check to QnaMaker_TestMiddleware_OneResult test.
=> Fail safe tests - Add missing Environment Variables check

libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic.csproj, libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/packages.config, tests/FormTest/FormTest.csproj, tests/FormTest/packages.config, tests/Microsoft.Bot.Builder.Classic.Tests/BotTests.cs, tests/Microsoft.Bot.Builder.Classic.Tests/ChainTests.cs, tests/Microsoft.Bot.Builder.Classic.Tests/DialogModuleTests.cs, tests/Microsoft.Bot.Builder.Classic.Tests/DisableTests.cs, tests/Microsoft.Bot.Builder.Classic.Tests/DispatchDialogTests .cs, tests/Microsoft.Bot.Builder.Classic.Tests/EndConversationTests.cs, tests/Microsoft.Bot.Builder.Classic.Tests/ExceptionTests.cs, tests/Microsoft.Bot.Builder.Classic.Tests/LuisTests.cs, tests/Microsoft.Bot.Builder.Classic.Tests/Microsoft.Bot.Builder.Classic.Tests.csproj, tests/Microsoft.Bot.Builder.Classic.Tests/ScorableDialogTests.cs, tests/Microsoft.Bot.Builder.Classic.Tests/Script.cs
This PR updates and consolidates the Autofac NuGet to version [4.7.1](https://www.nuget.org/packages/Autofac/)
Since version [4.2.1](https://github.com/autofac/Autofac/releases/tag/v4.2.1) [ContainerBuilder.Update Marked Obsolete](https://github.com/autofac/Autofac/issues/811)
The `ContainerBuilder.Update` method was used in the BotBuilder project in tests projects to replace dependencies with mock/stub version of services. All this references to `ContainerBuilder.Update` method resulted in build warnings.
In this PR, we replace those references with the a new ILifetimeScope and registered the new dependencies.
=> Update Autofac to version 4.7.1

tests/FormTest/FormTest.csproj
This PR fixes several build warnings when building the tests\FormTest project. e.g.: `Could not resolve this reference. Could not locate the assembly "System.Reflection.Metadata, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.`
We removed these missing dependencies since the project is actually not using them.
This is a simple console project used as a RView tool example: `Example: RView -g Formtest.exe Microsoft.Bot.Sample.AnnotatedSandwichBot.SandwichOrder.BuildForm`
=> Fix build warnings - Removed unnecessary references in Tests\FormTest

AspNetCore-EchoBot-With-State/AspNetCore-EchoBot-With-State.csproj, AspNetCore-EchoBot-With-State/EchoBot.cs, AspNetCore-EchoBot-With-State/EchoState.cs, AspNetCore-EchoBot-With-State/Program.cs, AspNetCore-EchoBot-With-State/Startup.cs, AspNetCore-EchoBot-With-State/appsettings.json, AspNetCore-EchoBot-With-State/readme.md, AspNetCore-EchoBot-With-State/wwwroot/default.htm, Microsoft.Bot.Builder.Samples.sln, samples-final/Console-EchoBot-With-State/Console-EchoBot-With-State.csproj, samples-final/Console-EchoBot-With-State/Program.cs
C# implementation of the Console Adapter Echo Bot with State Counter. 
Note: 
All code in a single file (Main + Bot + State) to make it easier to read / share / and so on. If we want to change this, we should decide on the standard(s) we want to use moving forward. 
For the console based bots, this seems a reasonable choice. For the ASP.Net Core (and WebAPI samples) following the standard patterns of those platforms will be the right choice.
=> Console Adapter Echo Bot with State Counter

libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
This fixes #314 which is an issue that is constantly biting people who are attempting to do proactive conversations using the base overload of `BotAdapter::ContinueConversation(ConversationReference, Func<ITurnContext, Task>)`.
More details on the fix is available in the individual commit messages.
=> Fix NullReferenceException when calling BotFrameworkAdapter::ContinueConversation

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
This code is to fix a known issue with Skype and Teams.  When sending a typing event in these channels they do not return a RequestResponse which causes the bot to blow up #460 #465
=> Support typing activities in skype and teams

Microsoft.Bot.Builder.sln, libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
#466 
The overload that was there is (was) using the incorrect bot id. That overload is now removed, forcing the developer to explicitly pass in the BotId. 
This is different than the Node SDK, as the BotFrameworkAdapter in .Net allows multiple Bots to be serviced by a single Adapter. This has been confirmed with @Stevenic
=> Removed incorrect overload.

libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
Tracked in #471 
The Headers now show the protocol version as 3.1. 
(Cut/Pasted from Emulator)
"headers": {
"connection": "Keep-Alive",
"content-length": "467",
"content-type": "application/json; charset=utf-8",
"host": "localhost:51427",
"request-id": "|17c88eac-44c94c8f62bf8585.1.1.",
**"user-agent": "Microsoft-BotFramework/3.1 (BotBuilder .Net/4.0.0.0)"**
},
=> Fix incorrect Header to show the protocol version

tests/Microsoft.Bot.Builder.Ai.LUIS.Tests/LuisRecognizerMiddlewareTests.cs
to make test inconclusive (instead of *Failed*). This seemed like a git merge that removed the check at some point.
=> Added missing check of EnvironmentVariablesDefined() 

libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs, tests/Microsoft.Bot.Builder.Azure.Tests/BlobStorageTests.cs, tests/Microsoft.Bot.Builder.Core.Extensions.Tests/StorageBaseTests.cs
Based on the discussion around PR #547 (this PR is based on these changes), we created another alternative implementation leveraging the [`MultiBufferMemoryStream`](https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/Core/MultiBufferMemoryStream.cs) and the [`CloudBlobClient.BufferManager`](https://github.com/Azure/azure-storage-net/blob/3331c605fb2e07de5759da46b8f7086deb78a5a4/Lib/Common/Blob/CloudBlobClient.Common.cs#L90) for pooling resources improving GC caused by in-memory serializing object to be written to Blob storage.
We found this approach broadly used within the [Microsoft.WindowsAzure.Storage library](https://github.com/Azure/azure-storage-net/search?utf8=%E2%9C%93&q=%22new+MultiBufferMemoryStream%22)
Also, reusing the same `BufferManager` to perform requests to …
=> Leverage Azure's MultiBufferMemoryStream and Blob client BufferManager for pooling resources

libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs, tests/Microsoft.Bot.Builder.Azure.Tests/BlobStorageTests.cs, tests/Microsoft.Bot.Builder.Core.Extensions.Tests/StorageBaseTests.cs
This PR included a new storage _batchCreateObjectTest() to create multiple instances of the same object (same key) in parallel (async).
This probes the current implementation of AzureBlobStorag.Write() has Blobk Blob concurrency issues when using ClocuBlockBlob.OpenWriteAsync() to serialize objects using JsonStreamWriter(). It is our assumption that this implementation has conflicts uploading different blocks of the same blob in parallel as it occurs during the initial ConversationUpdate between the first User and the Bot. (We spotted the issue using the AzureBlobStorage in the Echo Bot with State sample)
The AzureBlobStorage.Write() implementation in this PR uses CloudBlockBlob.UploadTextAsync() instead to workaround this issue.
=> Troubleshooting AzureBlobStorage issues

libraries/Microsoft.Bot.Builder.Core/Adapters/ConsoleAdapter.cs
The logic is there to support pluralization, and adds a special case for one, but still adds the extraneous "s" at the end of the word "attachment"
=> Fix logic typo for pluralization of "1"

libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs, libraries/Microsoft.Bot.Builder.Azure/AzureTableStorage.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
The Build has been failing on the CosmosDB tests, which should not be running on the build server(s). The check for the emulator was only looking for the existance of the Cosmosdb emulator file, which is apparently now present on the build servers. 
This PR brings back the "Is the emulator actually running?" code that @tomlm removed in pr #493 
I've verified on my local machine that this works correctly:
1. emulator not installed = Tests not run, reporting "Inconclusive".
2. Emulator installed but not running. Tests not run, reporting "Inconclusive".
3. Emulator running, tests run and passing.
=> Add Check for CosmosDB emulator actually running.

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandler.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotProactiveMessageHandler.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
The build that signed the assemblies was broken due to the use of
`InternalsVisibleTo` for ASP.NET integration libs.
* ASP.NET Core integration didn't actually need it right now, removed
from build
* ASP.NET WebAPI integration only needed it for some `string` fields
which we made public instead and removed from build
=> Remove InternalsVisibleTo from integration libs

libraries/Microsoft.Bot.Builder.Ai.LUIS/LuisRecognizerMiddleware.cs, tests/Microsoft.Bot.Builder.Ai.LUIS.Tests/LuisRecognizerMiddlewareTests.cs
=> Luis recognizer middleware shouldn't invoke the luis recognizer on null/empty utterances

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkOptions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ServiceCollectionExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkOptions.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/ApplicationBuilderExtensionsTests.cs
Exposes the `BotFrameworkPaths` as a property `Paths`, of type
`BotFrameworkPaths`, to the `BotFrameworkOptions` class.
* Makes it a subset of the options that can be configured (via
configuration APIs) in one fell swoop
* Unifies the design between Core and WebAPI (because it was already
this way in WebAPI)
* Makes it possible for runtime code to detect where the endpoints are
actually exposed via `IOptions<BotFrameworkOptions>` (helps with
discussion in #587)
**NOTE:** this also removes an overload from `UseBotFramework` which is
where it was previously configurable in Core (which, in retrospect, was
not a the proper design anyway)
=> Move endpoint path config to BotFrameworkOptions

BuildPackages.cmd
This builds .nupkg files locally, putting them in a single centralized folder.
Proposed resolution for Issue #391 https://github.com/Microsoft/botbuilder-dotnet/issues/391
=> Add BuildPackages.cmd 

libraries/Microsoft.Bot.Builder.Azure/AzureTableStorage.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs
Provides a more performant implementation of the `SanitizeKey` method
for both `AzureTableStorage` and `CosmosDbStorage`. The new
implementation is faster in all cases and, perhaps more importantly,
the new implementation allocates zero bytes in the case that there are
no illegal characters in the key and guarantees only a single
allocation in the case when there are bad characters.
Benchmarks:
``` ini
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.17134
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
[Host]     : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3101.0
DefaultJob : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3101.0
```
|                Method | …
=> Improve perf of SanitizeKey

libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs, libraries/Microsoft.Bot.Builder.Azure/AzureTableStorage.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs, libraries/Microsoft.Bot.Builder.Core.Extensions/BotState.cs, libraries/Microsoft.Bot.Builder.Core.Extensions/FileStorage.cs, libraries/Microsoft.Bot.Builder.Core.Extensions/IStorage.cs, libraries/Microsoft.Bot.Builder.Core.Extensions/MemoryStorage.cs, samples/AlarmBot-Cards/AlarmBot-Cards.csproj, samples/AlarmBot/AlarmBot.csproj, tests/Microsoft.Bot.Builder.Core.Extensions.Tests/StorageBaseTests.cs
Closes #428 
IEnumerable<KeyValuePair<string,Object>
... becomes
IDictionary<string,Object>
=> Removing IEnumerable<KVP> code in favor of a dictionary

libraries/Microsoft.Bot.Builder.Ai.LUIS/Microsoft.Bot.Builder.Ai.LUIS.csproj, libraries/Microsoft.Bot.Builder.Ai.QnA/Microsoft.Bot.Builder.Ai.QnA.csproj, libraries/Microsoft.Bot.Builder.Ai.Translation/Microsoft.Bot.Builder.Ai.Translation.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic.csproj, libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/packages.config, libraries/Microsoft.Bot.Builder.Classic/RView/RView.csproj, libraries/Microsoft.Bot.Builder.Classic/RView/packages.config, libraries/Microsoft.Bot.Builder.Core.Extensions/Microsoft.Bot.Builder.Core.Extensions.csproj, libraries/Microsoft.Bot.Builder.Core/Microsoft.Bot.Builder.Core.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.Prompts/Microsoft.Bot.Builder.Prompts.csproj, libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
This sets up links to GitHub source in the symbols files. Devs can then step through source in debug sessions. Source code is downloaded on the fly as needed.
Issue #474
=> Set up GitHub source links for debug support

libraries/Microsoft.Bot.Schema/ActivityEx.cs
This method is at the base of all of the `AsXXXActivity` conversion
methods which are called frequently. It was using a `string::Split`
100% of the time causing an unnecessary allocation. The focus was
removing that allocation which also came with a massive ~9x performance
boost as well.
``` ini
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.17134
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
[Host]     : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3101.0
Job-HXPPJN : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3101.0
Jit=LegacyJit  Platform=X86  Runtime=Clr  
```
|                 Method |              Type |  activity |       Mean |     Error |     StdDev |     Median | Scaled |  Gen 0 | Allocated | …
=> Optimize Activity::IsActivity helper method

libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/packit.cmd
This makes Bot.Builder.Classic consistent with the other projects that all write their .nupkg files (via Directory.Build.props) to the same folder.
=> Update packit.cmd to use outputpackages folder

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Choice.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs, libraries/Microsoft.Bot.Builder.Dialogs/Internal/BasePromptInternal.cs, libraries/Microsoft.Bot.Builder.Dialogs/Internal/ChoicePromptInternal.cs, libraries/Microsoft.Bot.Builder.Dialogs/Internal/ConfirmPromptInternal.cs, libraries/Microsoft.Bot.Builder.Dialogs/Internal/OAuthPromptInternal.cs, libraries/Microsoft.Bot.Builder.Dialogs/Internal/PromptMessageFactory.cs, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/AttachmentPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/BasicPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoiceResult.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmResult.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberResult.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/TextPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoiceFactoryTests.cs
- significant clean up across prompts
- next phase of clean up (not this check in) will be to consolidate Choice and Confirm
- at which point we should be consistent across all prompts and then (perhaps) remove the internal classes
- note a better name for the "internal" prompts would simply be "RecognizeAndValidate" because that is what they do - they simply add a user provided validate function to a recognizer
=> first level of cleanup across prompts

libraries/Microsoft.Bot.Builder.Core.Extensions/BotState.cs
StateSettings state in the constructor is currently (incorrectly) unused. It is intended to be passed on to the base class.
=> Pass state settings to base class from constructor

libraries/Microsoft.Bot.Connector/Authentication/EndorsementsRetriever.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/EndorsementsRetrieverTests.cs, tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj
Per request from @cleemullins, this PR focuses on the `EndorsementsRetriever` class which is responsible for fetching and parsing keys out of OpenID Connect metadata documents to be used while validating JWT tokens.
Hardening wise I added better exception handling and propagation around HTTP level failures. NOTE: network level failures will still result in a raw `Exception` being propagated.
Test Coverage was initiated in this PR which brings coverage for the `EndorsementsRetriever` class from 0% to 100% coverage.
Performance wise the new implementation brings gains of ~35%-52% in CPU and more modest allocation gains of ~10-20% depending on the scenarios.
----
``` ini
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.17134
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 …
```
=> EndorsementsRetriever perf, hardening and unit test coverage

libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ConfigurationCredentialProvider.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/ConfigurationCredentialProvider.cs
Fixes #255 by moving the `ConfigurationCredentialProvider` class out of
`Microsoft.Bot.Builder` and into the `AspNet.Core` integration library.
Also adds a specific `ConfigurationCredentialProvider` implementation
for WebAPI which loads settings from `AppSettings` instead.
=> Move ConfigurationCredentialProvider out of core

samples/Microsoft.Bot.Samples.EchoBot-AspNetWebApi/Microsoft.Bot.Samples.EchoBot-AspNetWebApi.csproj
The ASP.NET WebAPI EchoBot sample project still had a reference to the
`Microsoft.Bot.Builder.Core` assembly which has now been removed.
Removing that refrerence to eliminate the build warning (and any
confusion that might have ensued).
=> Remove reference to removed assembly from sample

libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/Extensions.cs, libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/LuisModel.cs, libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/LuisOptions.cs, libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/LuisService.cs, libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/Resolution.cs, libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/SetField.cs, libraries/Microsoft.Bot.Builder.Ai.LUIS/LuisModel.cs, libraries/Microsoft.Bot.Builder.Ai.LUIS/LuisRecognizer.cs, libraries/Microsoft.Bot.Builder.Ai.LUIS/LuisRecognizerMiddleware.cs, libraries/Microsoft.Bot.Builder.Ai.LUIS/LuisTraceInfo.cs
- fixed the namespace on all the non-generated code
- consistent with other files removed the license from the header (its in the repo)
=> fixed up namespace and file headers in Ai.LUIS

libraries/Microsoft.Bot.Builder.Ai.LUIS/Microsoft.Bot.Builder.Ai.LUIS.csproj, libraries/Microsoft.Bot.Builder.Ai.QnA/Microsoft.Bot.Builder.Ai.QnA.csproj, libraries/Microsoft.Bot.Builder.Ai.Translation/Microsoft.Bot.Builder.Ai.Translation.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
This fixes file versioning for the Bot.Builder libraries. Current file version value for .dlls in package version 4.0.0.35928 on the MyGet feed is 35928.0.0.0. Now it will match the package version.
=> Fix versioning for 11 projects

.editorconfig, .editorconfig.txt
Adding in the .editorConfig uses by the roslyn team. 
This seems to align well with all the analysis rules. 
https://github.com/dotnet/roslyn/blob/master/.editorconfig
=> Clone .editorConfig from the Rosyln team

.editorconfig
Literally after we checked in a version from the Roslyn team, the
official .NET sample was updated by the editor team with all the newer
language feature settings. This reflects those latest settings.
https://twitter.com/kuhlenhuth/status/1012791199244042240?s=20
=> Patching .editorconfig w/latest feature support

specs/BotBuilderOpenSourcePlans.md
Draft doc describing how the team should be engaging with the open source community. This doc represents how *I* believe we should be engaging with our community and is very much subject to review. 
This doc lays out:
1. Repo Design
2. Contribution Guidelines
3. Build Best Practices
4. Issue and Tag management
... and other related issues. 
I'm sure there's much that I've missed and feedback is welcome.
=> Draft document describing our open-source engagement policies

libraries/Microsoft.Bot.Builder/IRecognizer.cs, libraries/Microsoft.Bot.Builder/IRecognizerConvert.cs
Move the multiple interfaces in a single file to a "1 file per class" approach so the warnings go away.
=> Fix Build Warnings by moving to a single file per class

libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
Fix compare between DateTimeOffset and DateTime.  In +<hour> timezones will have issues because time become out of range.
=> Fix TestAdapter - throws exception in timezone +01

libraries/Microsoft.Bot.Builder/BotState.cs, libraries/Microsoft.Bot.Builder/BotStateSet.cs, libraries/Microsoft.Bot.Builder/ConversationState.cs, libraries/Microsoft.Bot.Builder/IStatePropertyAccessor.cs, libraries/Microsoft.Bot.Builder/IStatePropertyInfo.cs, libraries/Microsoft.Bot.Builder/UserState.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs, tests/Microsoft.Bot.Builder.Tests/BotStateSetTests.cs, tests/Microsoft.Bot.Builder.Tests/BotStateTests.cs, tests/Microsoft.Bot.Builder.Tests/MemoryStorageTests.cs, tests/Microsoft.Bot.Builder.Tests/MemoryTranscriptTests.cs, tests/Microsoft.Bot.Builder.Tests/MessageFactoryTests.cs, tests/Microsoft.Bot.Builder.Tests/OnTurnErrorTests.cs, tests/Microsoft.Bot.Builder.Tests/ShowTyping_MiddlewareTests.cs, tests/Microsoft.Bot.Builder.Tests/StorageBaseTests.cs, tests/Microsoft.Bot.Builder.Tests/TestUtilities.cs, tests/Microsoft.Bot.Builder.Tests/TranscriptBaseTests.cs, tests/Microsoft.Bot.Builder.Transcripts.Tests/CoreExtensionsTests.cs
This is just a basic clean up of the storage. Copyright headers, namespaces, naming, dead code etc.
NOT included here the simplifications to the model: remove the the accessor interface(s), remove the async, the associated force flag etc.
=> basic cleanup copyright headers etc

tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptLocTests.cs
Localization test for confirm prompt: includes Dutch, Spanish, English, Japanese, Portuguese but German, French and Chinese disabled.
=> added localization tests for Confirm Prompt

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
This change enables the OAuth prompt to be used with teams without the magic code.  Teams sends an invoke activity as opposed to a message activity when the user enters a magic code.  This will handle that.  
**Note**:  This will also need to be handled by developers in their bot code.
**See**: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-oauth-card#getting-started-with-oauthcard-in-teams
**Manifest Schema Here**: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema
=> Fix OAuth Prompt for Teams

tests/Microsoft.Bot.Builder.TestBot/TestBot.cs, tests/Microsoft.Bot.Builder.TestBot/TestBotAccessors.cs
see comments in code.
- added a globally scoped SemaphoreSlim to protect from concurrent activities breaking the shared (global) state
- note clarification on use of Responded. You can decide whether you want to start over or begin a fresh waterfall. It depends on how you want your waterfall to behave. It depends on where you want the initial activity to land. It probably makes most sense to check responded.
=> fix race and added Responded check

libraries/Microsoft.Bot.Builder/MiddlewareSet.cs, tests/Microsoft.Bot.Builder.Tests/MiddlewareSetTests.cs
this removes a redundant Receive Activity call on the MiddlewareSet
=> clean up dead code

libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs, tests/Microsoft.Bot.Builder.TestBot/Startup.cs, tests/Microsoft.Bot.Builder.Tests/ShowTyping_MiddlewareTests.cs
By sending the Activity directly through the Adapter rather than using the TurnContext the Responded flag is not set.
=> show typing activity doesn't set Responded

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConstants.cs, libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/OAuthApiClient.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/HttpConfigurationExtensions.cs
This change brings the two settings properties from the V3 SDK into the V4 SDK:
1. "BotOpenIdMetadata" - to customize the Open ID Metadata endpoint
2. "OAuthApiEndpoint" - to customize the OAuth API endpoint
=> Enable bots to use alternative endpoints for Open ID metadata documents and OAuth APIs

libraries/Microsoft.Bot.Builder/TurnContextStateCollection.cs, tests/Microsoft.Bot.Builder.Tests/TurnContextTests.cs
The second turn for a client will fail to Send responses from bot back to user. 
Here's the conditions which sets up the problem:
- ConnectorClient is placed in TurnContextStateCollection.
- ConnectorClient is cached in the Adapter (singleton).
- ConnectorClient implements IDisposable.
- TurnContextStateCollection disposes all elements after turn.
- ConnectorClient Dispose() cleans up HttpClient.
On a second turn, we attempt to use the Adapter's cached ConnectorClient which is now invalid.
Notes:
ConnectorClient has a "ignore the Dispose call" constructor.  @cleemullins and I looked at fixing in ConnectorClient, but decided this may be more durable fix as there are currently many constructors, and a new one could easily circumvent.
=> Fix Adapter ConnectorClient cache

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConstants.cs, libraries/Microsoft.Bot.Connector/OAuthApiClient.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/HttpConfigurationExtensions.cs, tests/Microsoft.Bot.Connector.Tests/OAuthConnectorTests.cs
Work to enable:
1. EmulateOAuthCards for when you are connecting to the emulator and you don't want to actually retrieve remote tokens
2. Ability to use OAuthCards when you haven't specified an appid and password (uses the EmulateOAuthCards path)
=> Fixes to get EmulateOAuthCards working

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Connector/OAuthApiClient.cs, libraries/Microsoft.Bot.Schema/AadResourceUrls.cs, tests/Microsoft.Bot.Connector.Tests/OAuthConnectorTests.cs
Added the GetAadToken APIs to the OAuth client
This API allows users of OAuth Connection Settings using an Azure Active Directory connection to exchange the AAD token for a token that can be used with outher AAD resource URLs.
=> Adding GetAadTokens API

libraries/Microsoft.Bot.Configuration/EncryptUtilities.cs, tests/Microsoft.Bot.Configuration.Tests/EncryptionTests.cs
recipes can have empty values which cause the encrypt routines to blow up on last phase
https://github.com/Microsoft/botbuilder-tools/issues/510
=> make encrypt pass through for empy and null values

README.md
The previous readme shows the LAST build status as the project build state. That means if a PR had a build fail, our overall status would show as failed. 
This is misleading, as only a failure of the *master* branch should relfect in the readme build status badge.
=> The Readme now shows the last build status for master, not the last overall build status

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs, libraries/Microsoft.Bot.Connector/Channels.cs
=> added channels to connector

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs
- Change Dutch translation in confirmPrompt (‘niet’ to ‘nee’). 
Niet could be an option, but isn't the correct translation in this 'yes / no' context.
The .NET `BooleanRecognizer` in Recognizers-Text already supports Dutch and also supports 'niet'.
Related PR in JS repo: https://github.com/Microsoft/botbuilder-js/pull/528
=> Change Dutch translation in confirmPrompt (‘niet’ to ‘nee’) 

tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptLocTests.cs
If PR #1017, I took the change even though the build hadn't run. The build didn't run because Azure Devops isn't setup to run builds for external pull requests. 
I looked at the change, confirmed the translation, and merged it it.... thinking, "This looks good. Nothing will break". 
Sigh. 
Tests should be passing now.
=> Broken tests due to merge of PR #1017

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptTests.cs
2 fixes:
- repeated failed attempts - fix is to add a deep copy
- accepting numbers on confirm prompt
=> confirm prompt fixes

README.md
Updated the Readme to show a build badge for the 4.0 branch. 
[![Build status](https://fuselabs.visualstudio.com/SDK_v4/_apis/build/status/Bot.Builder-DotNet-4.0%20Branch?branchName=4.0)](https://fuselabs.visualstudio.com/SDK_v4/_build/latest?definitionId=341)
Also, update the 4.0 branch build *only* build against master. CI builds should now run the 4.0-branch build only when the 4.0 branch is actually updates. You can see in #1014 that the 4.0 build incorrectly runs even though the PR was against master. 
**To fix this, the build triggers were changed:**
**Pull Requests against this branch should also trigger a 4.0 branch build:**
Note that some features - such as code coverage -  are not available in our 4.0 branch build.
=> Add build status for 4.0 branch build.

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs
- this adds a value type constraint on the NumberPrompt type argument
- and other minor clean up in Dialogs - Channels deprecated was causing compiler warnings
fixes #1029
=> add constraint to NumberPrompt

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ServiceCollectionExtensions.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/ServiceCollectionExtensionsTests.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/ServiceResolutionTests.cs
Add a few simple traces to the BotFrameworkAdapter for *very simple* diagnostics so new developers can verify messages getting through/being sent.
=> Add simple trace messages to BotFrameworkAdapter

Microsoft.Bot.Builder.sln, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/Integration/IAdapterIntegration.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandler.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandlerBase.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ServiceCollectionExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandler.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandlerBase.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/HttpConfigurationExtensions.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/App_Start/BotConfig.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/App_Start/UnityConfig.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/App_Start/UnityWebApiActivator.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Global.asax, tests/Microsoft.Bot.Builder.TestBot.WebApi/Global.asax.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/InteceptorAdapter.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Microsoft.Bot.Builder.TestBot.WebApi.csproj, tests/Microsoft.Bot.Builder.TestBot.WebApi/Properties/AssemblyInfo.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/TestBot.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Web.Debug.config, tests/Microsoft.Bot.Builder.TestBot.WebApi/Web.Release.config, tests/Microsoft.Bot.Builder.TestBot.WebApi/Web.config, tests/Microsoft.Bot.Builder.TestBot.WebApi/packages.config, tests/Microsoft.Bot.Builder.TestBot/InteceptorAdapter.cs, tests/Microsoft.Bot.Builder.TestBot/Startup.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/ServiceCollectionExtensionsTests.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/ServiceResolutionTests.cs
- add interface to capture contract between integration pieces and adapter
- make integration add BotFrameworkAdapter as a default rather than hardcoded
- fix InvokeResponse bugs:
1. should return 501
1. should allow null body
- add new debugging and testing Project for WebApi
- further fix up mocks for IServiceCollection collection behavior (necessary because TryAdd style methods uses Linq Any)
We should now add samples for how to provide your own adapter using the out of the box integration pieces (see test projects), in addition to updating the new sample of traditional MVC integration.
=> Johtaylo/missing adapter integration interface and InvokeResponse bugs

README.md
The tag was merged into a single one.
https://meta.stackoverflow.com/q/374974
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/botbuilder-dotnet/1051)
=> Remove Stack Overflow link to v4 tag

libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDBKeyEscapeTests.cs
And some minor "CosmosDB" comment fixes.
=> rename CosmosDBKeyEscape to CosmosDbKeyEscape

libraries/Microsoft.Bot.Configuration/Services/EndpointService.cs, tests/Microsoft.Bot.Configuration.Tests/ConfigurationLoadAndSaveTests.cs, tests/Microsoft.Bot.Configuration.Tests/Microsoft.Bot.Configuration.Tests.csproj, tests/Microsoft.Bot.Configuration.Tests/govTest.bot
This property 'channelService' is used to drive decisions in the Bot Builder SDK about whether to use public Azure or US Government Azure authentication constants. I am adding this property to the .bot file.
=> Adding 'channelService' property to the bot file's endpoint service type

libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/GovernmentAuthenticationConstants.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs
When the emulator is configured (via the channelService property in the .bot file) to use the US Government Azure AAD endpoint, this causes a different set of issuers and a different open id metadata URL to be needed to validate the emulator's JWT token.
Because this involves testing JWT tokens which I cannot check-in, I validated with:
1. Emulator configured to use Gov talking connecting to a local .NET core bot configured to use Gov running locally 
2. Emulator configured to use Gov talking connecting to an Azure hosted .NET core bot configured to use Gov running locally 
3. DirectLine talking to the same bot (via US Gov)
You can go here to play with the test bot:
https://helloworldgov.azurewebsites.net/
=> Updating to validate JWT tokens from the emulator

libraries/Microsoft.Bot.Builder/BotState.cs, tests/Microsoft.Bot.Builder.TestBot/Startup.cs, tests/Microsoft.Bot.Builder.TestBot/TestBot.cs, tests/Microsoft.Bot.Builder.Tests/BotStateTests.cs
This is a bug fix.
If you clear the state you currently have to include the force flag on an subsequent save operation. This is a fix for that - essentially clear always invalidates the hidden internal cache and so the save will actually work as expected even skipping the force flag.
=> fixed force flag on save following clear

libraries/Microsoft.Bot.Schema/ActivityEx.cs, tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs, tests/Microsoft.Bot.Schema.Tests/EntitySchemaValidationTest.cs
This fixes https://github.com/Microsoft/BotBuilder/issues/5128
And brings parity with the JavaScript. However note the implementation has slightly different factoring because the C# makes use of partial classes and adds these methods to Activity rather than TurnContext. This checkin builds on what's there already in the C#.
=> add reply conversation ref method to activity

libraries/Microsoft.Bot.Builder.Dialogs/WaterfallDialog.cs, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/TelemetryWaterfallTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryInitializerTests.cs
Enables WaterfallDialog to emit an InstanceId.  
This makes it possible to distinguish between two instances of the same dialog firing.
This is a requirement for VA metrics.  
This is added to the WaterfallStep, WaterfallCancel and WaterfallEnd events.
For more context see [spec](https://github.com/daveta/analytics/blob/master/va_reports.md#customevent-waterfallstep-botflowstatus)
=> Telemetry: Add instanceId to WaterfallDialog logging

libraries/Microsoft.Bot.Builder.Dialogs/WaterfallDialog.cs, libraries/integration/Microsoft.Bot.Builder.ApplicationInsights.Core/ServiceCollectionExtensions.cs, libraries/integration/Microsoft.Bot.Builder.ApplicationInsights.Core/TelemetrySaveBodyASPMiddleware.cs, libraries/integration/Microsoft.Bot.Builder.ApplicationInsights.WebApi/TelemetryBotIdInitializer.cs, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/BotTelemetryClientTests.cs, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/TelemetryWaterfallTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/ServiceResolutionTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupInvalidInstance.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupMultipleAppInsights.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupVerifyNullTelemetry.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryOverrideTelemClient.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/testbot.bot.default, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/testbot.bot.multiple_app_insights
Add support for WaterfallStart event.
Also:
- Support multiple Application Insights configs within BotConfig
- Include BotTelemetryClient tests
=> Add WaterfallDialog StartEvent for VA

libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/InterceptRequestHandler.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
This is basically the code from @adiazcan (much appreciated, thanks!)
- rebased
- dropped "ref" from ValidateOptions (C# is by-ref by default for classes)
- tightened up test case a little to validate the sent JSON contains the options we want to see
=> add options to individual QnAMaker calls

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/TelemetryWaterfallTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ComponentDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogSetTests.cs
This enables ComponentDialog to set the TelemetryClient and updates all the underlying dialog's TelemetryClient
- Add `DialogSet.TelemetryClient` which will set the telemetryClient on all contained dialogs.
- Modify DialogSet.Add to set the `TelemetryClient` property on the dialog being added.
- Modify setter on `ComponentDialog.TelemetryClient` to set contained dialogs.
- Modify `ComponentDialog.Add` to set `TelemetryClient` property on the dialog being added.
=> Add DialogSet.SetTelemetryClient(), and modify ComponentDialog

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs, libraries/integration/Microsoft.Bot.Builder.ApplicationInsights.Core/TelemetryBotIdInitializer.cs, libraries/integration/Microsoft.Bot.Builder.ApplicationInsights.WebApi/TelemetryBotIdInitializer.cs, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/TelemetryWaterfallTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ComponentDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogSetTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryInitializerTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/TelemetryInitializerTests.cs
This is related to bot Troubleshooting.  The Bot Services team would like a way to enable all customers to have an audit of all distinct ConversationID's.  This enable trace messages to have the standard Bot headers (most/all of the samples are currently using ILogger to log events).
This change is not needed on the .js side, as currently it attempts to place the Bot ID's on all telemetry.
=> Log TraceTelemetry with Application Insights telemetry

libraries/Microsoft.Bot.Builder/BotState.cs, tests/Microsoft.Bot.Builder.Tests/BotStateTests.cs
This brings the C# implementation in line with the JavaScript.
This is the corresponding JavaScript PR. https://github.com/Microsoft/botbuilder-js/pull/679
=> add Delete function to BotState for parity with JavaScript

libraries/integration/Microsoft.Bot.Builder.ApplicationInsights.Core/Microsoft.Bot.Builder.ApplicationInsights.Core.csproj
Added in all of the PropertyGroups needed for building / packaging / signing the .Net Core 2 assembly for AppInsights integration. 
Note: Not yet tested, but as this was copied nearly 100% from the ASP.Net Core integration library everything should be good. Testing (Which I'll done once this PR is reviewed) will require cutting packages to the daily build server and validating signing steps.
=> Update AppInsights .Net Core 2 project for packaging

libraries/Microsoft.Bot.Builder.ApplicationInsights/BotTelemetryClient.cs, libraries/Microsoft.Bot.Builder.ApplicationInsights/Microsoft.Bot.Builder.ApplicationInsights.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ApplicationBuilderExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ServiceCollectionExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetrySaveBodyASPMiddleware.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/TelemetryBotIdInitializer.cs, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/BotTelemetryClientTests.cs, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/Microsoft.Bot.Builder.ApplicationInsights.Tests.csproj, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/TelemetryWaterfallTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/ServiceResolutionTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Startup.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupInvalidInstance.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupMultipleAppInsights.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupVerifyNullTelemetry.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupVerifyTelemetryClient.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryInitializerTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryOverrideTelemClient.cs, tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/ServiceResolutionTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/TelemetryInitializerTests.cs
- Add Microsoft.Bot.Builder.ApplicationInsights assembly.
- Fix unused references.
- Fix the namespaces.
=> cleemullins:Application Insights build fixes

libraries/Swagger/package-lock.json, libraries/Swagger/package.json
Fixes #1207 
- Update `"@microsoft.azure/autorest.csharp"` dependency in Swagger/package.json to 2.3.82
- Latest generated code had no differences from currently checked in code, hence this PR only contains the package.json and package-lock.json.
=> update autorest.csharp dependency to 2.3.82

libraries/Microsoft.Bot.Builder.ApplicationInsights/BotTelemetryClient.cs, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/BotTelemetryClientTests.cs
https://github.com/Microsoft/BotBuilder/issues/5194
Make BotTelemetryClient methods virtual.
>I would like to be able to extend the OOTB client with additional business logic and obfuscate or augment the data being logged without having to write an IBotTelemetryClient from the scratch. For example, users will be able to opt-in/opt-out from logging and have different privacy preferences, I would like to override the TrackEvent method so I can manipulate the data based on the user that is using the bot.
=> Make BotTelemetryClient methods virtual

libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs
Fixing a NullReferenceException bug which is thrown if the incoming Activity's From property is null in `TranscriptLoggerMiddleware`. Eg. if `BotFrameworkAdapter.CreateConversationAsync()` is triggering an 'event' Activity and for some reason does not sets the From property.
=> TranscriptLoggerMiddleware bugfix

libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobTranscriptStoreTests.cs
- Update `WindowsAzure.Storage` reference from `9.3.2` to `9.4.2`. The package was split into 4 different packages, so the reference is replaced with the necessary ones (`Microsoft.Azure.Storage.Blob` and `Microsoft.Azure.Storage.Common`)
- Modify `LongIdAdd` test due to exception thrown being modified in `Microsoft.Azure.Storage.Blob`, from `AggregateException` to `StorageException`
=> Update WindowsAzure.Storage package reference

CodeCoverage.runsettings
Currently, code coverage results are being adversely affected by the new Azure Storage libraries - this new exclusion correction should fix that.
=> Added new Azure Storage Exclusions

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
Fixing a ArgumentNullException bug which is triggered if I call the `Dialogs.OAuthPrompt.GetUserTokenAsync` after a non-text message (ex. button click), and `context.Activity.Text` is not set.
=> Dialogs.OAuthPrompt.GetUserTokenAsync bugfix

libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs
transcript queue should not be a member variable.
Moved inside turn to make it's scope for the turn.
C# fix for https://github.com/Microsoft/botbuilder-js/issues/700
=> fix transcript logger queue scope

libraries/Microsoft.Bot.Builder/Integration/IAdapterIntegration.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/InteceptorAdapter.cs, tests/Microsoft.Bot.Builder.TestBot/InteceptorAdapter.cs
=> Add ContinueConversationAsync to IAdapterIntegration

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs, libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConstants.cs, libraries/Microsoft.Bot.Connector/Authentication/GovernmentAuthenticationConstants.cs, libraries/Microsoft.Bot.Connector/Authentication/IOAuthConfiguration.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftGovernmentAppCredentials.cs, libraries/Microsoft.Bot.Connector/Authentication/OAuthConfiguration.cs, libraries/Microsoft.Bot.Connector/Authentication/Retry.cs, libraries/Microsoft.Bot.Connector/Authentication/RetryParams.cs, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, tests/Microsoft.Bot.Connector.Tests/GetTokenRefreshTests.cs, tests/Microsoft.Bot.Connector.Tests/MicrosoftGovernmentAppCredentialsTests.cs, tests/Microsoft.Bot.Connector.Tests/RetryParamsTests.cs, tests/Microsoft.Bot.Connector.Tests/RetryTests.cs, tests/Microsoft.Bot.Connector.Tests/SessionRecords/Connector.Tests.ConversationsTest/CreateDirectConversationAsyncWithValidData.json, tests/Microsoft.Bot.Connector.Tests/SessionRecords/Connector.Tests.ConversationsTest/CreateDirectConversationSyncWithValidData.json
Revamping the token acquisition code that obtains a token given the bot App id and password. This is an effective execution of the OAuth client credentials flow, which is supported by the ADAL dotnet library.
Some implementation details and considerations below to complement the source changes:
Token cache: We use ADAL built-in token cache. Given that Adal handles much of the token caching nowadays, we consider it better to leverage ADAL library implementation, leaving less responsibilities in our code. However, after working with the ADAL team we are still responsible for maintaining low concurrency (done through semaphores in this case) and retrying, using the retry after headers received from AAD when we get HttpStatusCode 429.
Testing: We ran long haul load test, in addition to …
=> Token refresh revamping: rewriting client credential flow using ADAL.

specs/BotBuilderOpenSourcePlans.md, tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobTranscriptStoreTests.cs
Fixes #1297
The Transcript Tests that were failing were doing so when tests were ran in parallel or in a different order. The relevant tests had state dependencies as they were doing "counting" validation. 
If a different test ran first and stored data, that data would cause a subsequent test to fail. 
Note: The only machine we've seen this on is my home machine (latest VS, latest emulator).
=> Fixed state-dependant / order dependant bug in transcript tests

Directory.Build.props, libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.LUIS.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.ApplicationInsights/Microsoft.Bot.Builder.ApplicationInsights.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
1. Normalize all of the properties for NuGet File generation (for the .Net Core projects) into a standard location. 
2. Disable the build warning around the LicenceUrl. Per [this thread](https://github.com/NuGet/Home/issues/7509), we cannot fix that at this time. The "Disable" solution is the same thing the Asp.Net team has done, as found in [this PR](https://github.com/aspnet/AspNetCore/blob/46a16831282bb9d958eeb1e15a056a14f464a397/Directory.Build.props#L16).
=> Cleanup of NuGet properties across all projects

Directory.Build.props
Debug builds - which are the norm - don't build docs. This is done to make the builds go faster. 
The PR suppresses those warnings.
=> Don't warn about docs during standard debug builds

CodeCoverage.runsettings
Update the runsettings file to be explicit about only including certain DLL's. 
Note that the auto-generated project (.schema) is NOT in this list. 
It's my belief that we're testing quite a few DLLs now that we don't mean to, and moving to an include model should provide more accurate results.
=> Move Code Coverage to an explicit include model

tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
The signature on the WaterfallWithStepsNull was incorrect and resulting in a warning.
=> Fix method signature to eliminate warning

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
This pull request changes the default timeout in OAuthPrompt.cs from 54000000 (15 hours in milliseconds)  to 900000 (15 minutes in milliseconds).
Fixes https://github.com/Microsoft/botbuilder-dotnet/issues/1307
=> Change 15-hour timeout to 15 minutes (#1307)

libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.LUIS.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.ApplicationInsights/Microsoft.Bot.Builder.ApplicationInsights.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Microsoft.Bot.Builder.AI.Luis.Tests.csproj, tests/Microsoft.Bot.Builder.AI.QnA.Tests/Microsoft.Bot.Builder.AI.QnA.Tests.csproj, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/Microsoft.Bot.Builder.ApplicationInsights.Tests.csproj, tests/Microsoft.Bot.Builder.Azure.Tests/Microsoft.Bot.Builder.Azure.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Tests/Microsoft.Bot.Builder.Dialogs.Tests.csproj, tests/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.Tests.csproj, tests/Microsoft.Bot.Builder.TestBot.WebApi/Microsoft.Bot.Builder.TestBot.WebApi.csproj, tests/Microsoft.Bot.Builder.TestBot.WebApi/Web.config, tests/Microsoft.Bot.Builder.TestBot.WebApi/packages.config, tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj, tests/Microsoft.Bot.Builder.Transcripts.Tests/Microsoft.Bot.Builder.Transcripts.Tests.csproj, tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj, tests/Microsoft.Bot.Schema.Tests/Microsoft.Bot.Schema.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/packages.config
Fixes #1310
This PR consolidates conflicting / mismatched versions of dependencies across the SDK. Specifically:
1. Microsoft.AspNet.WebAPI has been set to 5.2.6
2. Microsoft.Net.Test.Sdk has been set to 15.9.0
3. Microsoft.Rest.ClientRuntime has been standardized to 2.3.13
4. Newtonsoft.Json has been standardized to 10.0.3
5. Moq has been standardized to 4.10.0
Also, the latest version of SourceLink has been picked up which sets the Development Dependency to true so our runtime dependency goes away.
=> Consolidated packages across versions.

libraries/Microsoft.Bot.Schema/CardActionEx.cs, tests/Microsoft.Bot.Schema.Tests/CardActionTest.cs
=> add implicit constructor to CardAction

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Connector/Channels.cs
Fix for #1255 - Added Skype for Business to channels list and updated oAuthPrompt to not use hardcoded strings.
=> Fix for #1255 - Added Skype for Business to channels list

libraries/Microsoft.Bot.Builder/BotState.cs, tests/Microsoft.Bot.Builder.Tests/BotStateTests.cs
fixes #1191 
Note this is actually a change of behavior - but it is closer to the JavaScript.
Not exactly the same because JavaScript has the notion of undefined - and null is not the same. This is particularly evident if the accessor model is being used to access raw properties - as is done in the unit tests.
As the conversation in the issue suggests, its very hard to imagine this being used in this way out side of the immediate context of the dialog system where currently it must be passed in. And as other issues have covered, even in that context it is only ever used in a one particular way (as a ref and so only Get is called.)
And the change is safe for the usage in the Dialog system.
=> change accessor to return null not throw with no factory

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
Address these two issues:
https://github.com/Microsoft/botbuilder-dotnet/issues/1236
...Use OpenUrl for'msteams' SignIn card instead of SignIn CardAction
https://github.com/Microsoft/botbuilder-dotnet/issues/1273
...Properly run the task in the background
=> Bug fixes for OAuthCard & Teams, and Task.Run

libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
The KeyVault.Core package ( [GitHub Repo here](https://github.com/Azure/azure-sdk-for-net/tree/master/src/SDKs/KeyVault/data-plane) ), picked up as a transitive dependency of the Azure Storage libraries doesn't yet support NetStandard20. I confirmed with the Azure Storage team that this warning is fine, and can be supressed. 
> [12:20 PM] Keith Farmer
> So, our only dependency on that is the definitions of two interfaces, which are stable.  Not the implementation.  The warning should be ignorable in that case.
It does appear the Azure SDK team is "in-process" of supporting NetStandard20 as seen in [this Commit](https://github.com/Azure/azure-sdk-for-net/commit/b0d42d14bfe92a24996826b2487ba592e644f581).
We cannot apply the no-warn suppression directly to the package links below as they're …
=> Supress NU1701 for the Azure Project

libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceRecognizers.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/Find.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicesRecognizersTests.cs
=> allow choice recognizer to accept null and empty string

libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder/Integration/BotFrameworkOptions.cs, libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Microsoft.Bot.Builder.AI.Luis.Tests.csproj, tests/Microsoft.Bot.Builder.AI.QnA.Tests/Microsoft.Bot.Builder.AI.QnA.Tests.csproj, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/Microsoft.Bot.Builder.ApplicationInsights.Tests.csproj, tests/Microsoft.Bot.Builder.Azure.Tests/Microsoft.Bot.Builder.Azure.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Tests/Microsoft.Bot.Builder.Dialogs.Tests.csproj, tests/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.Tests.csproj, tests/Microsoft.Bot.Builder.TestBot/Microsoft.Bot.Builder.TestBot.csproj, tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj, tests/Microsoft.Bot.Builder.Transcripts.Tests/Microsoft.Bot.Builder.Transcripts.Tests.csproj, tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj, tests/Microsoft.Bot.Schema.Tests/Microsoft.Bot.Schema.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests.csproj
Upgrade all Test Projects (along with TestBot) to netcoreapp2.1
This was done as the AppInsights projects(s) require it, and having mismatched versions (some requiring netcoreapp20, others 21) will lead to problems. 
Minor other changes around warnings to produce a cleaner build.
=> Upgrade to NetCore21 for test projects.

README.md, libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.LUIS.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.ApplicationInsights/Microsoft.Bot.Builder.ApplicationInsights.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
This PR, against the 4.2 branch, updates the "Author" attribute of every nuget package. 
Per [the rules](https://aka.ms/Microsoft-NuGet-Compliance), which recently seem to have changed, our author attribute is incorrect. This is causing Nuget to reject all of our package pushes:
```
Pushing Microsoft.Bot.Builder.4.2.1.nupkg to 'https://www.nuget.org/api/v2/package'...
PUT https://www.nuget.org/api/v2/package/
BadRequest https://www.nuget.org/api/v2/package/ 1591ms
Response status code does not indicate success: 400 (The package is not compliant with metadata requirements for Microsoft packages on NuGet.org. Go to https://aka.ms/Microsoft-NuGet-Compliance for more information. Policy violations: The package metadata is missing required author 'Microsoft'.).
```
This PR cleans up the 4.2 …
=> Update NuGet Package authoring attribute

libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs
Makes usage more clear, especially when trying to use functions that need ITurnContext within waterfall dialog steps (was not immediately obvious I could access ITurnContext through WaterfallStepContext).
=> Added summary for WaterfallStepContext

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Choice.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoiceFactoryTests.cs
- Modify ChoiceFactory.HeroCard to incorporate each choice's Action property the way ChoiceFactory.SuggestedAction does
- Centralize that functionality in a shared method
- Update the Choice.Action doc comment to reflect that
- Add tests in ChoiceFactoryTests to account for actions in hero cards and suggested actions
- Add basic test for ChoiceFactory.HeroCard that was missing
This is meant to piggyback on garypretty's recent PR since I noticed `Choice.Action` wasn't incorporated into `ChoiceFactory.HeroCard`: https://github.com/Microsoft/botbuilder-dotnet/pull/1339
=> Fix a few things regarding choices and actions

libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDBKeyEscapeTests.cs
Fixes #1197
This code updates the CosmosDB key scrubbing class to enforce the 255 character length defiened by CosmosDB.
=> Apply limits to the CosmosDB Key Length

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandler.cs, tests/Microsoft.Bot.Builder.TestBot/Startup.cs
Fixes #1371
A regression was introduced when support was added in #1352 for a scenario where body stream buffering was enabled. Unfortunately, during that PR, non-buffered streaming scenarios were not regression tested leading to a bug in that (the default) scenario.
The bug was caused by setting `Position = 0` on the body stream when non-buffered because, non-buffered streams are not seekable and thus throw a `NotSupportedException` if you attempt to change their position.
=> Fixing bug around request buffering

libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs, tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobStorageTests.cs
fixes #1292 
- removed caching of container handle
- removed concurrency from Delete, Read and Write calls
- simplified code it use straight forward loops instead of Linq and Lambdas
- fixed conditional creation of AccessCondition (the original code was non sense but probably harmless) 
- removed calls to IfExists for container on Delete and Read (which are coded to be conditional anyhow)
- added unit tests
This should most likely fix the non-nonsensical ETag exception because this code was incorrect. _At least this code is now correct_ and that should presumably make the exception go away, at least it's a start. Anyhow I could not reproduce this exact problem either way.
I also made a good start on adding unit tests, I'm sure we could always add more.
=> fixed concurrency and added unit tests

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisApplication.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisApplicationTests.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs
This is the C# implementation for https://github.com/Microsoft/BotBuilder/issues/5255
The only thing to note here is that the JavaScript is slightly different because the C# has this additional LuisApplication class. Because the C# has that class I added the extra constructor on that. (Making sure to wire all the constructir overloads through the same code path.)
@stevengum is planning to do the JavaScript.
=> additional constructor that takes raw LUIS endpoint

libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.LUIS.csproj, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/TestData/Typed.json, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/TestData/TypedPrebuilt.json
- Update to new revision of Azure SDK
- New Azure SDK enables downstream feature for Dispatch
- "connectedServiceResult" is a new property that will land in the existing (marshaled) luisResult that lives in properties.
- ConnectedServiceResult is the underlying service-specific Luis result 
- This was requested by Darren for Enterprise and Virtual Assistant features.
In conjunction with nodejs: https://github.com/Microsoft/botbuilder-js/pull/766
=> Update LUIS to new (Azure) C# SDK

libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
- added optimization so CreateIfNotExists for the container only ever happens once per object - this assumes we have a singleton which is a good assumption
- added retry policy to blob open call - this handles 500 and 408
- added retry for 412 on blob open
Note that this code only uses a single client/container on a single thread. This makes this code safe to edits as there are scenarios where the client/container is not thread safe.
The concurrent handling of a list of objects is not include here as the caller of this code only ever handles a single key at a time. In other words the untested concurrent was actually never used.
The way to understand this module is to see it as a storage plug-in to the BotState class and not as an attempt at a generic wrapper to an otherwise widely used …
=> Added optimization around CreateIfNotExists and additional error handling

libraries/Microsoft.Bot.Builder/ActivityHandler.cs, tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
- use Linq Any() not Count() > and so avoid bug
- additional unit tests that can distinguish between Any and Count
=> fix linq error in ActivityHandler conversationUpdate

libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/Analyzer.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/TemplateEngine.cs, tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/Examples/analyzer.lg, tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/TemplateEngineTest.cs
API exposed on top of the TemplateEngine object which would return the dependencies of a templateId.
For Example: 
example.lg file:
```
#wPhrase
- Hi {userName}
#pizzaOrderConfirmation
- Your pizza order of  {base} with toppings {join(topping, ',', 'and')} is confirmed.
#sandwichOrderConfirmation
- Your {bread} sandwich with {meat} is on its way. Thanks.
#orderReadOut
- CASE: {orderType == 'pizza'}
- [wPhrase] [pizzaOrderConfirmation] 
- CASE: {orderType == 'sandwich'}
- [sandwichOrderConfirmation] 
```
Get Result:
```
var engine = TemplateEngine.FromFile(GetExampleFilePath("example.lg"));
engine.Dependencies("orderReadOut") = ["orderType","userName","base","topping","bread","meat"]
engine.Dependencies("sandwichOrderConfirmation") = ["bread", "meat"]
```
=> add lg file analyzer

libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkHttpAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/packages.config
This add an extra couple of arguments to the BotFrameworkHttpAdapter to be passed through to the base class. The essential one here is the ChannelProvider which is required for gov scenarios.
=> gov fix for adapter

tests/Microsoft.Bot.Connector.Tests/GetTokenRefreshTests.cs
This PR disables the Token Refresh tests, as they're all failing with what looks like a recent configuration error on the AAD side. 
Related to #1480
=> Disable the "Live" token refresh tests

libraries/Microsoft.Bot.Builder.AI.LUIS/ITelemetryRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisTelemetryConstants.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisUtil.cs, libraries/Microsoft.Bot.Builder/TelemetryConstants.cs, libraries/Microsoft.Bot.Builder/TelemetryLoggerConstants.cs, libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.Tests/TelemetryMiddlewareTests.cs
Adds support for IBotTelemetryClient (no new dependencies) within the Luis Recognizer.
https://github.com/daveta/analytics/blob/master/telemetry_enhancements/TelemetryEnhancements.md#telemetry-support-luis
- Properties can be added to the telemetry event per invocation 
- Class can be derived to override default behavior
- Exposed methods to help populate events when deriving
=> New Telemetry Support for Luis Recognizer

libraries/Microsoft.Bot.Builder/TelemetryConstants.cs, libraries/Microsoft.Bot.Builder/TelemetryLoggerConstants.cs, libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/TelemetryMiddlewareTests.cs
Middlware component that uses IBotTelemetryClient to log events when messages are received/sent/updated or deleted in the bot.
Additional Details
https://github.com/daveta/analytics/blob/master/telemetry_enhancements/TelemetryEnhancements.md
js: https://github.com/Microsoft/botbuilder-js/pull/812
=> TelemetryLoggerMiddleware 

libraries/Microsoft.Bot.Builder.AI.QnA/ITelemetryQnAMaker.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnATelemetryConstants.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
Adds Telemetry support to QnAMaker
Shares same pattern as Luis and TelemetryMiddleware.
- Enables setting properties during GetAnswersAsync
- Enables deriving from class and adding properties
https://github.com/daveta/analytics/blob/master/telemetry_enhancements/TelemetryEnhancements.md#telemetry-qna-recognizer
=> QnA Telemetry Support

libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ServiceCollectionExtensions.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/ServiceResolutionTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupAppSettingsOnly.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/appsettings.json.default, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/appsettings.json.invalid_instrumentation_key
John, here's a stab at "no botfile" override.  
Would logically change:
`public void ConfigureServices(IServiceCollection services)`
`{`
`       var botConfig = BotConfiguration.Load("testbot.bot", null);`
`      services.AddBotApplicationInsights(botConfig);`
To something like:
`public IConfiguration Configuration { get; }`
`public void ConfigureServices(IServiceCollection services)`
`{`
`        services.AddBotApplicationInsights(Configuration);`
=> Application Insights config from appsettings.json

tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpAdapterTests.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/ServiceCollectionExtensionsTests.cs
- Reorder methods and fields
- Remove trailing whitespace
- Rename local variable
=> [StyleCop] Fix all the warning in Integration.AspNet.Core.Tests

tests/Microsoft.Bot.Configuration.Tests/ConfigurationLoadAndSaveTests.cs, tests/Microsoft.Bot.Configuration.Tests/ConnectionTests.cs, tests/Microsoft.Bot.Configuration.Tests/EncryptionTests.cs, tests/Microsoft.Bot.Configuration.Tests/ServiceTests.cs
- Reorder using directives
- Remove empty blank lines
- Add trailing comma in multi-line initializers
- Fix typo in a class name
=> [StyleCop] Fix all warnings in BotBuilder.Configuration.Test

tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs, tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs, tests/Microsoft.Bot.Builder.Tests/AutoSaveStateMiddlewareTests.cs, tests/Microsoft.Bot.Builder.Tests/BotAdapterBracketingTest.cs, tests/Microsoft.Bot.Builder.Tests/BotAdapterTests.cs, tests/Microsoft.Bot.Builder.Tests/BotFrameworkOptionsTests.cs, tests/Microsoft.Bot.Builder.Tests/BotStateSetTests.cs, tests/Microsoft.Bot.Builder.Tests/BotStateTests.cs, tests/Microsoft.Bot.Builder.Tests/CallCountingMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/ConnectorClientThrowExceptionOnDispose.cs, tests/Microsoft.Bot.Builder.Tests/MemoryStorageTests.cs, tests/Microsoft.Bot.Builder.Tests/MemoryTranscriptTests.cs, tests/Microsoft.Bot.Builder.Tests/MessageFactoryTests.cs, tests/Microsoft.Bot.Builder.Tests/MiddlewareSetTests.cs, tests/Microsoft.Bot.Builder.Tests/PocoItem.cs, tests/Microsoft.Bot.Builder.Tests/PocoStoreItem.cs, tests/Microsoft.Bot.Builder.Tests/ShowTyping_MiddlewareTests.cs, tests/Microsoft.Bot.Builder.Tests/SimpleAdapter.cs, tests/Microsoft.Bot.Builder.Tests/StorageBaseTests.cs, tests/Microsoft.Bot.Builder.Tests/TestAdapterTests.cs, tests/Microsoft.Bot.Builder.Tests/TestMessage.cs, tests/Microsoft.Bot.Builder.Tests/TestPocoState.cs, tests/Microsoft.Bot.Builder.Tests/TestState.cs, tests/Microsoft.Bot.Builder.Tests/TestUtilities.cs, tests/Microsoft.Bot.Builder.Tests/TrackDisposed.cs, tests/Microsoft.Bot.Builder.Tests/TranscriptBaseTests.cs, tests/Microsoft.Bot.Builder.Tests/TranscriptUtilities.cs, tests/Microsoft.Bot.Builder.Tests/Transcript_MiddlewareTests.cs, tests/Microsoft.Bot.Builder.Tests/TurnContextTests.cs, tests/Microsoft.Bot.Builder.Tests/TypedObject.cs
- Add/remove spacing
- Add element's documentation
- Fix upper/lowercase letters
- Remove prefix calls with base
- Fix constructors initializer
- Remove unused variables
- Rename variable's name
=> [StyleCop] Fix all the warnings on Bot.Builder.Tests

tests/Microsoft.Bot.Connector.Tests/AttachmentsTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/EndorsementsRetrieverTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/EndorsementsValidatorTests.cs, tests/Microsoft.Bot.Connector.Tests/BaseTest.cs, tests/Microsoft.Bot.Connector.Tests/BotAccessTokenStub.cs, tests/Microsoft.Bot.Connector.Tests/ConnectorClientTest.cs, tests/Microsoft.Bot.Connector.Tests/ConversationsTest.cs, tests/Microsoft.Bot.Connector.Tests/FaultyClass.cs, tests/Microsoft.Bot.Connector.Tests/GetTokenRefreshTests.cs, tests/Microsoft.Bot.Connector.Tests/JwtTokenValidationTests.cs, tests/Microsoft.Bot.Connector.Tests/MicrosoftGovernmentAppCredentialsTests.cs, tests/Microsoft.Bot.Connector.Tests/OAuthConnectorTests.cs, tests/Microsoft.Bot.Connector.Tests/RetryParamsTests.cs, tests/Microsoft.Bot.Connector.Tests/RetryTests.cs
- Reorder using directives
- Remove empty blank lines
- Add trailing comma in multi-line initializers
- Remove trailing white spaces
- Update protected const fields to be protected property with private set.
- Update private const field to be private read-only to avoid unreachable code in BaseTest class.
=> [StyleCop] Fix warnings in Bot.Connetor.Test project

tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/BotTelemetryClientTests.cs, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/MyBotTelemetryClient.cs, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/TelemetryWaterfallTests.cs
- Rename variable to avoid Hungarian notation
- Fix spacing
- Fix parameters
=> [StyleCop] Fix all the warnings on ApplicationInsights.Tests

BotBuilder-DotNet.ruleset, Directory.Build.props
Remove the Property used to suppress the rule [SA0001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md). This was applied to the projects that didn't support ruleset files, but now all the projects use an unique ruleset file. 
Also, the rules [SA0001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md) and [SA1652](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1652.md) about the `XML documentation` were moved into the ruleset file.
Finally, we updated the StyleCop version to 1.1.0-beta008, to properly support the C# version used by the projects of the solution.
Currently, all the projects are configured to set the latest major version of C#. and uses some features of c# 7.0 …
=> [StyleCop] Update XML documentation suppress rule

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisPredictionOptions.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.TestBot/LuisHelper.cs
Change construction of the LUIS recognizer to maintain binary compatibility.  This effectively reverts back to original constructor and pushes new options in the `LuisPredictionOptions` class.
Also add a few more tests.
I'll update nodejs side if we're good with this..
@Zerryth : We can follow this pattern for timeout.
=> Retain binary compatibility for LUIS recognizer

libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs
Fixes #1485 
Per issue, if a Choice uses something like:
```
new Choice()
{
Action = new CardAction()
{
Type = "messageBack",
Value = "myValue",
Title = "myTitle,
}
}
```
instead of simply:
```
new Choice()
{
Value = "myValue"
}
```
...it creates a `Object reference not set to an instance of an object` exception.
This is because if `choice.Action.Title` is `null`, this line:
```
var l = choice.Action != null && string.IsNullOrEmpty(choice.Action.Title) ? choice.Action.Title.Length : choice.Value.Length;
```
evaluates to:
```
var l = true && true = choice.Action.Title.Length
```
...so it checks for `choice.Action.Title.Length` when `choice.Action.Title` is `null`
=> Fix null Action.Title check in ChoiceFactory

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ReplaceDialogTest.cs
=> replace dialogs calls end dialog

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
In `DialogContext.EndDialogAsync` just call `EndActiveDialogAsync` to pop the active dialog off the stack.
=> DialogContext.EndDialogAsync - remove code duplication.

libraries/Microsoft.Bot.Builder.TemplateManager/DictionaryRenderer.cs, libraries/Microsoft.Bot.Builder.TemplateManager/ITemplateRenderer.cs, libraries/Microsoft.Bot.Builder.TemplateManager/LanguageTemplateDictionary.cs, libraries/Microsoft.Bot.Builder.TemplateManager/TemplateIdMap.cs, libraries/Microsoft.Bot.Builder.TemplateManager/TemplateManager.cs
- Add documentation for methods
- Move classes to new file
- Fix spacing
=> [StyleCop] Fix all the warnings on TemplateManager

tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/ServiceResolutionTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Startup.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupInvalidInstance.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupMultipleAppInsights.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupOverideTelemClient.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupVerifyNullTelemetry.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupVerifyTelemetryClient.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryInitializerTests.cs
- Remove Trailing white space
- Rename file to match with the class name
=> [StyleCop] Fix all the warnings in the ApplicationInsights.Core.Tests

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs, libraries/Microsoft.Bot.Connector/Channels.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicesChannelTests.cs
Fixes https://github.com/Microsoft/BotBuilder/issues/5316
and
https://github.com/Microsoft/BotBuilder/issues/5313
OAuthPrompt (tested and works)
Dialogs Channel: added LIne 
- SupportsSuggestedActions: 13
- SupportsCardActions: 99
Channel Constant: added Line
Add ChoicesChannelTests
=> Line channel updates

libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
Addresses [binary compatibility issue with QnA](https://github.com/Microsoft/botbuilder-dotnet/issues/1560).
Refactor constructors to preserve binary compat, Cleanup warnings on QnA tests.
=> Fix binary compat for QnAMaker

libraries/Microsoft.Bot.Schema/ActivityEx.cs, tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs
Fixes https://github.com/Microsoft/botbuilder-dotnet/issues/1580
Seems odd that Recipient and From are flipped in CreateTrace.
=> Allow null Recipient field for CreateTrace and CreateReply

tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
WriteAsync and ReadAsync CosmosDbStorage.cs implementations throw ArgumentNullException when passing null as object to store or keys to look for.
Test were broken since both were asserting a different behavior.
=> Fix Cosmos DB tests

libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryInitializerTests.cs
Fix issue that VA encountered.
Allow users to override telemetry that's logged from the initializer.
=> Allow TelemetryInitializer properties to be overridden by user

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs
Fixes #1349
With this change, `LuisRecognizer.RecognizeAsync` will no longer throw an exception when the turn context's activity has no text. Instead it will bypass the LUIS endpoint (saving the expense of an API call) and create a fake `RecognizerResult` with a `string.Empty` intent. This will allow bots to handle textless messages gracefully when they're not designed to explicitly check if the text is null or empty before calling `RecognizeAsync`. If the bot has a `switch` statement with a `default` clause then that will be triggered, probably responding the same as a None intent. Otherwise, nothing will happen.
=> Allow `LuisRecognizer` to handle textless messages

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputWrapper.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 10 - ChoiceInput/ChoiceInput.main.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 12 - GithubIssueBot/show.lg, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
Add Choice Input and related sample.
Supported Type in ChoicePrompt:
public enum ListStyle
{
/// <summary>
/// Don't include any choices for prompt.
/// </summary>
None,
/// <summary>
/// Automatically select the appropriate style for the current channel.
/// </summary>
Auto,
/// <summary>
/// Add choices to prompt as an inline list.
/// </summary>
Inline,
/// <summary>
/// Add choices to prompt as a numbered list.
/// </summary>
List,
/// <summary>
/// Add choices to prompt as suggested actions.
/// </summary>
SuggestedAction,
/// <summary>
/// Add choices to prompt as a HeroCard with buttons.
/// </summary>
HeroCard,
}
=> Add ChoiceInput

tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/LGGeneratorTests.cs
Fixed tests to correctly point resource explorer to fallback folder
=> LG Tests were broken by recent refactoring of ResourceExplorer

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisApplication.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisApplicationTests.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs
Fixes https://github.com/Microsoft/botbuilder-dotnet/issues/1387
Enable empty endpoint (just like nodejs)!
=> [nodejs parity] Allow LUIS endpoint to be null or empty 

tests/Microsoft.Bot.Builder.TestBot.WebApi/App_Start/WebApiConfig.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/BookingDetails.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Bots/DialogAndWelcomeBot.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Bots/DialogBot.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Dialogs/BookingDialog.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Dialogs/DateResolverDialog.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Dialogs/MainDialog.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Global.asax.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/LuisHelper.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Microsoft.Bot.Builder.TestBot.WebApi.csproj, tests/Microsoft.Bot.Builder.TestBot.WebApi/Properties/AssemblyInfo.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Web.config
Resolve stylecop issues on Bot.Builder.TestBot.WebApi
- Formatting and spacing
- Resolve version of the dependent assembly
- Ignore SA issue maintaining the protectedness
=> [StyleCop] Fix stylecop warnings on Bot.Builder.TestBot.WebApi

tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/OverrideFillRecognizer.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/TelemetryConvertResult.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/TelemetryOverrideRecognizer.cs
•	'public' members before 'private' members
•	A closing brace not preceded by a blank line
•	Add trailing comma in multi-line initializers
•	The 'protected' before 'override'
•	Single-line comment preceded by a blank line
•	Element '_result' declare an access modifier
•	Files only contain a single type
=> [StyleCop] Fix all the warnings on Bot.Builder.AI.LUIS.Tests

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ServiceCollectionExtensions.cs, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/TelemetryWaterfallTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ReplaceDialogTest.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/ServiceResolutionTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupAppSettingsOnly.cs
**Libraries**: 
•	Bot.Builder.AppInsights.Tests
•	Bot.Builder.Integration.AppInsights.Core
•	Bot.Builder.Dialogs.Tests
•	Bot.Builder.AI.LUIS
•	Bot.Builder
•	Bot.ApplicationInsights.core.Tests
•	Remove trailing whitespace
•	Remove multiple blank lines in a row
•	Add documentation for type parameter <T>
=> [StyleCop] Fix all the warnings on several libraries

libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs
if used some serializer setup which are honoured by the dialogs and saved with the accessors they might not be read back if not same settings/converters are set. using f.i. Iso8601TimeSpanConverter this is not globally accessible. the change uses same global JsonConvert.DefaultSettings (AND the additional setting which was set in thie original code) as the rest of the bot.
=> fix for using other serializing formats and converters. 

libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs
The `HttpClient` was not being shared with the `ConfigurationManager<OpenIdConnectConfiguration>`. Needed to pass the instance into the constructor overload so that it is used by the `OpenIdConnectConfiguration` when fetching the document.
Fixes #1595.
=> Share HttpClient to OIDC metadata document retriever

libraries/Microsoft.Bot.Builder.AI.LUIS/ITelemetryRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisPredictionOptions.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerOptions.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
Part 2 of 2 PRs to fix https://github.com/Microsoft/BotBuilder/issues/5196
* Added timeout option (in milliseconds) in `LuisRecognizer` and `QnAMaker` - **dotnet**
* As in C# `HttpClient`, set timeout default to 100000 milliseconds
* fixed missing `"` in docs of `IBotTelemetryClient`
**LuisRecognizer**
- added `Timeout` property to `LuisPredictionOptions`
- `LuisRecognizer` now exposes a `DefaultHttpClient` property to set a default HttpClient for requests, as well as to expose for testing
- in order to pass `ServiceClientCredentials`, `HttpClient`, `HttpClientHandler`, and `LuisDelegatingHandler` changes to `LUISRuntimeClient`, used MsRest's `CreateRootHandler()` and `CreateHttpHandlerPipeline()` to create `HttpClient` to send to `LUISRuntimeClient` constructor inside `LuisRecognizer` …
=> added timeout options for qna & luis for dotnet

tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests.csproj
Removed unnecessary & duplicated references from `Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests` library
=> Remove unnecessary & duplicated references

libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorageOptions.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
This PR will fix the Issue #1407.
- Add `PartitionKey` field to the `CosmosDbStorageOptions`
- Modify the `DeleteAsync` method to generate the `RequestOptions `with the `PartitionKey `provided by the `CosmosDbStorageOptions`
- Pass the `options` optional parameter to the `DeleteDocumentAsync` method.
1. [ Connect your bot to a CosmosDB](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
1.  Add the following on the main bot class:
```
private const string CosmosServiceEndpoint = "Endpoint";
private const string CosmosDBKey = "YourDBKey";
private const string CosmosDBDatabaseName = "bot-cosmos-sql-db";
private const string CosmosDBCollectionName = "bot-storage";
private const string CosmosDBPartitionKey = …
```
=> [Azure] Fix 'PartitionKey value must be supplied for this operation' error

libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs, libraries/Microsoft.Bot.Connector/Authentication/TimeSpanExtensions.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/TestUtilities.cs, tests/Microsoft.Bot.Builder.Tests/TestUtilities.cs, tests/Microsoft.Bot.Builder.Tests/TranscriptUtilities.cs
Unit Tests had references to Fusebox cmd files. With the migration to Functional tests, and a dedicated functional test build with proper secret management, these references need to be removed. 
Cleaned up some stylecop warnings while I was in there.
=> Remove references to FuseBox keys from Unit Tests

tests/Microsoft.Bot.Builder.TestBot.WebApi/Bots/DialogBot.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Dialogs/BookingDialog.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Dialogs/DateResolverDialog.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/DisableAllRuleSet-DotNet.ruleset, tests/Microsoft.Bot.Builder.TestBot.WebApi/Microsoft.Bot.Builder.TestBot.WebApi.csproj
- Revert fixes made on PR #1642
- Create a new ruleset file on Bot.Builder.TestBot.WebApi & customize it for ignoring rules (Action="None")
- Edit the .csproj file on Bot.Builder.TestBot.WebApi and add the CodeAnalysisRuleSet
=> Ignore Stylecop warnings in TestBot.WebApi project

libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Originally we support such format: A[0]
Modify this to support string format index: A['name'], in this way developper can access an element by dynamic variable, such an example:
we have such scope:
```
'weather' : {
'today' : 'sunny',
'tomorrow' : 'cloudy'
}
```
The variable string 'day' is obtained from user‘s input, may be 'today' or maybe 'tomorrow'.
Original we can use such functions: `weather.(Accessor(day))`, but it looks unfriendly.
In PR #1658 a new function was added: `Property`,  now `property(weather, day)` works well.
In this PR, developper can also access the weather in such way -> `weather[day]`
=> Expression: Add string index support in access element function

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputWrapper.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/04 - TextInput/TextInput.WithoutProperty.main.dialog, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
…
Fixes #1701 + tests + sample
=> InputWrapper: If no property is provided we simply don't bind to memory but let the prompt go through.

libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
support such expression:
'a' || 'b' -> true
'a'&& 'b' -> true
not('hi') -> false
if('a', 1, 2) -> 1
In logical comparison functions(or, and, not, if) and operators(||, &&, !) , to support non boolean type.
for below case, false will return:
original value for boolean
0 for number,
null or empty for string,
0 count for list,
0 property for other format(JObject, dynamic)
=> Expression: add truthiness feature

samples/Microsoft.Bot.Builder.TestBot.Json/Samples/12 - GithubIssueBot/show.lg
Handle escape characters from LG directly.
LG doesn't handle escape characters in JSON
=> Fix github issue sample

libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugAdapter.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggingAdapterExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/DeclarativeAdapterExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs/LGAdapterExtensions.cs, libraries/Microsoft.Bot.Builder/AdapterExtensions.cs, libraries/Microsoft.Bot.Builder/BotAdapter.cs, libraries/Microsoft.Bot.Builder/MiddlewareSet.cs, libraries/Microsoft.Bot.Builder/RegisterClassMiddleware.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Controllers/BotController.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj, samples/Microsoft.Bot.Builder.TestBot.Json/Startup.cs, samples/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
- moved off 4.2 pattern to new MVC controller pattern
- Cleaned up startup.cs 
- added extensions to BotAdapter so we could reduce the amount of "magic" middleware that need to be added.
- Removed the amount of dependency injected stuff (people can easily refactor to use more dependency injection if they want)
startup.cs basically looks like this now:
```c#
IStorage storage = new MemoryStorage();
var userState = new UserState(storage);
var conversationState = new ConversationState(storage);
var resourceExplorer = ResourceExplorer
.LoadProject(HostingEnvironment.ContentRootPath);
// TODO get rid of this dependency
TypeFactory.Configuration = this.Configuration;
// set up bot framework runtime environment (Aka the adapter)
services.AddSingleton<IBotFrameworkHttpAdapter, …
```
=> cleanup startup.cs

libraries/Microsoft.Bot.Builder.AI.TriggerTrees/Trigger.cs, libraries/Microsoft.Bot.Builder.AI.TriggerTrees/TriggerTree.cs, libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, libraries/Microsoft.Bot.Builder.Expressions/Constant.cs, libraries/Microsoft.Bot.Builder.Expressions/ExpressionEvaluator.cs, libraries/Microsoft.Bot.Builder.Expressions/ExtensionsRewriters.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/RewriteTests.cs
This simplifies the apis by getting through a wonky parameter and maintains that the knowledge about expressions is defined when the expression is created rather than needing to be passed in later.
Also did a little code cleanup.
=> Move negation into ExpressionEvaluator

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs
This is the C# version of [this Javascript PR](https://github.com/Microsoft/botbuilder-js/pull/886)
This change handles the in-transition location of the tenant ID field for MS Teams.
Load a middleware in the constructor for BotFrameworkAdapter that will look for channelData.tenant.id and copy the value to conversation.tenantId for use in createConversation.
* Connect a bot to MS Teams, then use `adapter.createConversation` to create a DM with a user.
=> Add middleware to address transitional location of tenantId field

libraries/Microsoft.Bot.Builder/BotState.cs
This commit makes LoadAsync, SaveChangesAsync, ClearStateAsync and ClearStateAsync virtual so they can be mocked in unit tests.
=> Made BotState CRUD operations virtual so they can be mocked for testing.

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptOptions.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptValidatorContext.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/PromptValidatorContextTests.cs
@johnataylor / @cleemullins:  these changes address #1748. Please revuew and let me know what you think..
Changes include:
- Removed NumberOfAttempts from PromptOptions
- Added NumberOfAttempts getter to PromptValidatorContext
- Implemented logic to keep internal count of number of attempts in the prompt state.
- Updated unit test to compile and pass (this counter is 1 based)
- Added missing cancellationTokens where needed
=> Modifications to number of attempts property behavior

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.TraceActivity.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/TraceActivity.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
- if you don't give value, value will be State
- changed property name to value instead of valueProperty
- Jobject convert it so that consumers get dynamic version of object
=> misc traceactivity cleanup

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EmitEvent.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.IfCondition.schema, samples/Microsoft.Bot.Builder.TestBot.Json/app.schema
The schema required a property "expression" which did not exist rather than "condition".
=> Fix a bug in the schema definition for IfCondition 

libraries/Microsoft.Bot.Builder/Inspection/InspectionActivityExtensions.cs, libraries/Microsoft.Bot.Builder/Inspection/InspectionMiddleware.cs
Emulator when in sidecar debugging mode would like to see the following:
- a single state object containing properties for each bot state.
- a trace activity as the response to the initial /INSPECT open
(This is the same change as the JavaScript.)
=> state changes for sidecar

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/PlanningContext.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/Rule.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugAdapter.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Events.cs, libraries/Microsoft.Bot.Builder.Dialogs/ActivityTemplate.cs, libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogInstance.cs, libraries/Microsoft.Bot.Builder.Dialogs/TextTemplate.cs, libraries/Microsoft.Bot.Schema/ActivityEx.cs, samples/Microsoft.Bot.Builder.TestBot.Json/TestBotHttpAdapter.cs
- debugger now displays friendly descriptions for
- dialog
- activity
- templates
- dialoginstance
- Plumb through adaptive events so that we get full events in debugger
=> add debug annotations and plumb through AdaptiveEvents

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
Fixes: https://github.com/Microsoft/botbuilder-dotnet/issues/1859
=> Fix cosmos casting issue

build/PublishToCoveralls.ps1
The current Archive module that ships with PowerShell has an issue where it uses the backslash for directory path separator which creates archives that don't expand correctly on non-Windows machines as the backslash is a valid path character.
Until the PowerShell images (AzDevOps in this case for this build) gets updated to the (yet to be published) fixed version, this is a temporary workaround to pull down the latest version from master branch of Archive repo which has the fix.
Once the AzDevOps image is updated, this workaround should be removed.
=> Add workaround to temporarily use fixed version of Archive module

build/PublishToCoveralls.ps1
Lets us set the "Via" column at coveralls.io.
This lets us distinguish between BotBuilder-DotNet master CI-PR and BotBuilder-DotNet master Functional Tests, both of which are publishing to coveralls.io.
=> Add -serviceName parameter

FunctionalTests/ExportedTemplate/DeploymentHelper.cs, FunctionalTests/ExportedTemplate/deploy.ps1, FunctionalTests/ExportedTemplate/deploy.sh, FunctionalTests/ExportedTemplate/deployer.rb, FunctionalTests/ExportedTemplate/parameters.json, FunctionalTests/ExportedTemplate/template.json, FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/DirectLineClientTests.cs, FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/Microsoft.Bot.Builder.FunctionalTests.csproj, tests/Microsoft.Bot.Builder.TestBot/Startup.cs
- Enable echo controller in **_Microsoft.Bot.Builder.TestBot_** project by adding an environment variable with the name of the bot we want to use.
- Add new **DirectLineClientTests** to _FunctionalTests_ project to test sending a message to the **_TestBot_** deployed in Azure with ARM Templates and check its response.
1- Define five environment variables: **AppId**, **AppSecret**, **BotName**, **BotGroup** and **CHOSENBOT** and mark the first two as Secrets.
2- Add a **_Dotnet Task_** to publish the Test Bot project and leave it as a zip in a folder named PublishedBot.
In _Arguments_ we need to set:
```powershell
--output $(System.DefaultWorkingDirectory)\tests\Microsoft.Bot.Builder.TestBot\PublishedBot
```
3- Configure one **_Azure CLI Task_** to:
- Run _az deployment create_ command to …
=> Add test for TestBot in Functional Tests project

build/ExtractCompressNuGet.ps1
Fixed #1871 
Adds the powershell hack in while we wait for the powershell team to merge/deploy the fix.
=> Update master with the powershell hack

libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerOptions.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
Fixes #1718
* `QnAMaker.HydrateOptions` originally tried to make a copy of the options passed into `QnAMaker`'s constructor
* But because passed by reference, assigning local variable `hydrateOptions = _options` would actually have `hydrateOptions` pointing to `_options`'s reference types members' location
* creating "deep clone" of values passed into `QnAMaker`'s constructor (`_options`) via serialization/deserialization
=> hydratedOptions now clones qna options via serialization/deserializations

tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
=> Include test for #1859

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ActivityPrompt.cs
The class summary had previously been copied from Prompt.cs which was misleading. The comment made it sound like `ActivityPrompt` was the base class of all prompts.
=> Fix ActivityPrompt documentation comments

libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs
As discussed with @daveta - adding virtual to OnTurn method to allow override. This can then be used to enable logging of information from the context, such as TurnState.
=> Made OnTurn method on TelemetryLoggerMiddleware virtual

libraries/Microsoft.Bot.Builder.LanguageGeneration/Diagnostic.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/ErrorListener.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGParser.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGTemplate.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs
Refer to the diagnostics specification of vscode Extension to add more information to the error handling, including starting rows/columns, stopping rows and columns.
=> Refactoring LG error handler

FunctionalTests/ExportedTemplate/template.json, tests/Microsoft.Bot.Builder.TestBot/Controllers/BotController.cs, tests/Microsoft.Bot.Builder.TestBot/Startup.cs
Closes #1924 
- Remove the _switch_-based bot assignation and its variable, and replace it with a `Func<string, IBot>` service.
- Add a different endpoint for each bot to the controller.
With these changes we can remove the `CHOSENBOT` variable from the Pipelines build and the line where we set that `CHOSENBOT` into Azure's WebApp.
=> [TestBot] Configure an endpoint for each bot

FunctionalTests/ExportedTemplate/LinuxDotNet/template.json, tests/Microsoft.Bot.Builder.TestBot/DeploymentScripts/Linux/.deployment, tests/Microsoft.Bot.Builder.TestBot/DeploymentScripts/Linux/deploy.sh
We created a deployment script for deploying the TestBot on an Azure Linux Host using Azure Pipelines. This should be configured after #1946 is merged.
We will be using the Windows Nightly build as a starting point for our build. 
1. Make a clone of the Windows      Nightly build Pipeline.
2. Create new Application Credentials(AppId and AppPassword) and replace the pipeline variables.
3. Create a [deployment user on Azure](https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-dotnetcore#configure-a-deployment-user) and add the credentials as      build variables.
4. Disable Zip publish project on the *dotnet Publish task.
5. Add an *Azure Resource group deployment* task with the following settings:
6. Modify the *Azure CLI* task "Create resources" and place the …
=> [TestBot][Linux] Deploy on Azure using Azure Pipelines

libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs
Previously Expression support such format: `'hello'.length()`, which is same as `length('hello')`, but in the future, this kind of Expression will be deprecated.
=> [Expression] Obsolete special format

build/PublishToCoveralls.ps1
Updated BotBuilder-DotNet-master-CI-PR to use the Windows 2019 VS 2019 hosted agent and the solution build task to use VS 2019
=> Updateing build pipelines to use VS2019

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/Microsoft.Bot.Builder.FunctionalTests.csproj, libraries/Microsoft.Bot.Builder.AI.LUIS/ITelemetryRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisPredictionOptions.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/EmptyLuisResponseClientHandler.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Microsoft.Bot.Builder.AI.Luis.Tests.csproj
Added overrides to LuisRecognizer.RecognizeAsync that take LuisPredictionOptions.
Added unit tests for the different use case.
Removed IRecognizer from LuisRecognizer (it is implicit through the implementation of ITelemetryRecognizer)
Updated EmptyLuisResponseClientHandler to be able to use it with the recognizer tests.
=> Adds overrides to LuisRecognizer.RecognizeAsync that take luis LuisPredictionOptions

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ComponentDialogTests.cs
Right now, if a component dialog is cancelled, the status returned is Completed, this is inconsistent with the behavior for Dialogs
This PR updates the ComponentDialog class to return Cancelled if the dialog is cancelled. It will still return the results object in case the dev wants to use this value to return information regarding the cancellation.
=> Updated ComponentDialog so it returns DialogTurnStatus.Cancelled when the dialog is cancelled

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpAdapterTests.cs
The constructor we added in 4.4.4 introduced ambiguity in the DI system in some usage patterns.
The implication is any project being updated to 4.4.4 from anything after 4.3.* can hit this ambiguity if they have included the BotFrameworkHttpAdapter directly in the DI setup. The ambiguity is only hit when you attempt to use the constructor directly, the ideal pattern in the application code is to subclass (and we follow this in the majority of the samples.) However we managed to break this code:
services.AddSingletone<IBotFrameworkHttpAdapter, BotFrameworkHttpAdapter>();
This is not strictly recommended however it is real a shame to have broken this. We like the new constructor (it also abstracted the gov initialization) and we think subclassing is the nicest pattern. A fix that avoids the …
=> make new constructor protected to avoid potential ambiguity in DI

libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs
Re: Issue https://github.com/microsoft/botbuilder-dotnet/issues/1903
When the question property was renamed to matchedQuestion the no answer found case wasn't updated.  This causes an exception in the case where personal information is being logged because the question property was already created.
Related Issue:
https://github.com/microsoft/botframework-solutions/issues/1358
=> Fix telemetry for QnA no answer found case

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs
Fixes #1596 
Also related: https://stackoverflow.com/questions/55970661/ms-bot-framework-doesnt-remember-authentication/55975228#55975228 - this seems like a pretty easy issue to run into.
`OAuthPrompt` has to be called to for certain messages. If that message contains a string that has a 6-digit number, `OAuthPrompt` used that number as the magic code, which was invalid, so it re-prompted for Login. The JS SDK doesn't have this issue because [it doesn't check for the magic code in `beginDialog()`](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts#L198)
.
* Removes attempt to detect magic code in `BeginDialogAsync()`
* Removes some other checks in `GetUserTokenAsync()` that are unnecessary because of the above change that are …
=> Take magic code detection out of OAuth BeginDialog

build/PublishToCoveralls.ps1, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConfiguration.cs, libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EndorsementsValidator.cs, libraries/Microsoft.Bot.Connector/Authentication/EnterpriseChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
- Support for enforcing required endorsements in the auth layer
- Created AuthConfiguration abstraction received by the BotAdapter. It is a class and not an interface since interfaces cannot be added fields to after first release, so it is quite inconvenient.
- Changed JwtTokenValidator and JwtToken extractor to support testing of endorsements, including mocking the endorsement retriever, which can now optionally be received as a constructor parameter.
- Added JwtTokenExtractor tests to verify the change and further allow future coverage increases in this code area
=> Auth: Support required endorsements

README.md
Following the advice posted here: https://github.com/lemurheavy/coveralls-public/issues/971
Append " &service=github " to the first URL for the badge.
=> Fix coveralls badge not updating

libraries/Microsoft.Bot.Schema/ActivityExtensions.cs
This changes the logic to strip mentions out to cater for the specific way mentions are sent from a Skype bot. @EricDahlvang would be great to get your eyes on this and see if it meets your requirements.
=> Fix for #1934 skype channel not stripping mentions

libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetrySaveBodyASPMiddleware.cs
Fix for #1902 - added check to ensure null ref exception not thrown.
=> Added null check for content type

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/HttpHelper.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpAdapterTests.cs
#2005 #2010 and #1979 into master
=> cherry pick of 4.4 changes into master

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ActivityPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptValidatorContext.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ActivityPromptTests.cs
=> add AttemptCount to Activity and OAuth prompts

libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs
We have a typo in the [DocumentStoreItem](https://github.com/microsoft/botbuilder-dotnet/blob/091f96915f94ea4d0cb28b2840d9d4ae11ab93f9/libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs#L381) Class. The serialized property is correct, so things work. 
This is a private classe used (only) by the CosmosDB class. It could *probably* be changed, but I'm super-paranoid about this as breaking it invalidates stored state for everyone using this provider. We should just continue to live with the typo.
=> Add a comment telling folks not to fix the typo due to Back Compat

libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
refer to #1965
Origin PR is raised by @vicentegnz but he does not have permission to merge it. So I recommit his update here.
```
I think it is a good option to put the scope nullable, 
with this we don't force to pass a null by parameter.
I have also added a new test case to verify that everything 
is correct without passing the scope by parameter.
Thanks,
```
=> Modify EvaluateTemplate to use scope nullable

libraries/Microsoft.Bot.Configuration/BotConfiguration.cs, tests/Microsoft.Bot.Configuration.Tests/ConnectionTests.cs
Fixes #1910 
* only assign if id is null or empty
* only check for duplicate if user is giving their own unique id
* using random() is inefficient, switch to just identifying the next available slot with single scan.
=> remove random from auto assigned ids

libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/analyzer.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/lgTemplate.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
origin issue: #2093 
Originally analyzeTemplate(templateName: string) would return a list of variables.
From now , this function will reture a structure dat, including a list of variables and list of templateref names.
=> [LG] refactor analyzer

build/ExtractCompressNuGet.ps1
https://github.com/microsoft/botbuilder-dotnet/issues/1872
This is pending someone from support verifying the generated NuGet package installs on a Mac.
Example: Microsoft.Bot.Builder 4.5.0-preview-190620-16
=> The next path separator fix hack for Linux NuGet installs

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder/ActivityHandler.cs
- make DialogContext constructor public (it was internal) this was a customer ask from two independent sources
- make DelegatingTurnContext protected rather than private in ActivityHandler - this allows derived classes to also get the benefit of slightly stronger typing (this was really a bug as ActivityHandler was intended for extensibility through inheritance)
=> issue 1960 private to public

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SwitchCondition.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/03 - IfCondition/SwitchCondition.main.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/ShowEmail/DisplayEmailList.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
=> SwitchCondition: support numeric and boolean types, and do not require quotes for string literals

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ActivityPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ActivityPromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/EventActivityPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/EventActivityWithoutRetryPrompt.cs
Fixes #2004 
* `ActivityPrompt` class [in other repos include the `isRetry` parameter](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/prompts/activityPrompt.ts#L101) in the `OnPrompt` method
* Additionally, other prompt classes in the dotnet repo itself also include this parameter ([`AttachmentPrompt`](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/AttachmentPrompt.cs#L19), [`ChoicePrompt`](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs#L43), [`Prompt.cs`](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs#L137), etc.)
* To remain consistent across …
=> Add OnPromptAsync overload with isRetry parameter

build/PublishToCoveralls.ps1
Add a space in the --commitEmail argument. That prevents an empty email argument from killing the coveralls upload as happened in BotBuilder-DotNet-master-CI-PR build # 66992.
=> Fix publishtocoveralls.ps1

libraries/Microsoft.Bot.Builder/Inspection/InspectionMiddleware.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/GetBookingDetailsDialogTestsDataGenerator.cs, tests/Microsoft.Bot.Builder.TestBot/AdapterWithErrorHandler.cs, tests/Microsoft.Bot.Builder.TestBot/Startup.cs, tests/Microsoft.Bot.Builder.Tests/InspectionTests.cs
=> remove at mention for INSPECT

libraries/Microsoft.Bot.Builder.Testing/DialogTestClient.cs, libraries/Microsoft.Bot.Builder.Testing/XUnit/XUnitDialogTestLogger.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/BookingDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/CancelAndHelpDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/DateResolverDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/GetBookingDetailsDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/MainDialogTests.cs, tests/Microsoft.Bot.Builder.Testing.Tests/DialogTestClientTests.cs, tests/Microsoft.Bot.Builder.Testing.Tests/XUnit/XUnitOutputMiddlewareTests.cs
Renamed XUnitOutputMiddleware to XUnitDialogTestLogger (so its name is closer to js).
Added some spaces to the XUnitDialogTestLogger  output so it reads better.
Removed callback constructor parameter from DialogTestClient (it relies on an internal DialogTurnResult and that's fishy, we will need to find a better solution in the future to support this).
Added optional ConversationState parameter to the DialogTestClient constructor and exposed a property to allow people to inspect it or access it.
=> DialogTestClient constructor updates and XUnitOutputMiddleware renames

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/Rule.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/SelectorTests.cs
=> fix bug: Empty or invalid constraint in Rule will break the dialog

libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs
The US Gov endpoint should be .azure.us instead of .us
=> Updating trusted URLs for US Gov

Directory.Build.props
Fixes #2261
Points Nuget packages at the icon stored in our master github repo.
=> Point Nuget packages to a valid icon file.

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ComponentDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/CancelAndHelpDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/GetBookingDetailsDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/BookingDialogTestsDataGenerator.cs
This PR reverts changed made in https://github.com/microsoft/botbuilder-dotnet/pull/1993.
At this moment, is not possible to return cancelled from a component dialog.
=> Reverts PR 1993

libraries/Microsoft.Bot.Builder.StreamingExtensions/BotFrameworkApplicationBuilderExtensions.cs, libraries/Microsoft.Bot.Builder.StreamingExtensions/StreamingRequestHandler.cs
Two fixes:
1) Unblocks users designing transient bots with scoped dependencies, by creating a new scope for each request in the same manner an MVC controller would.
2) Allows for passing in of OnTurnError logic via the application extension for bots using named pipes.
=> Add support for transient services depending on scoped services.

BotBuilder-DotNet.ruleset, tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
Code fixed to eliminate Stylecop warnings. Stylecop warnings set as errors. Ref: https://github.com/microsoft/botbuilder-dotnet/pull/2171
=> Stylecop fixes

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/SequenceContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
This allows us to explicitly ask that inputs inherit state as well. 
The scenario that this enables is the following:
```
var rootDialog = new AdaptiveDialog(nameof(AdaptiveDialog))
{
Generator = new TemplateEngineLanguageGenerator(),
Rules = new List<IRule>()
{
new UnknownIntentRule()
{
Steps = new List<IDialog>()
{
new TextInput()
{
Property = "$name",
Prompt = new ActivityTemplate("What is your name?")
},
new NumberInput()
{
Property = "$age",
Prompt = new ActivityTemplate("Hello {$name}, how old are you?")
},
new SendActivity()
{
Activity = new ActivityTemplate("Hello {$name}, I have your age as {$age}")
}
}
}
}
};
await CreateFlow(rootDialog)
.Send("Hi")
.AssertReply("What is your name?")
.Send("zoidberg")
.AssertReply("Hello zoidberg, how old are you?")
.Send("22") …
```
=> Dialog and Sequence Context: make decisions about inherited state more flexible

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/NumberPromptMock.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/NumberPromptTests.cs
Fixes #2288 
* `NumberPrompt` now takes into account culture while parsing value from `Recognizers.Text.ModelResult`
* Wrote more tests for NumberPrompt to reach 100% code coverage for `NumberPrompt.cs` file
* Uses C#'s `TryParse()` overload that accepts culture
* Added tests that test culture different from default (`en-us`)
* Added tests that checked that expected errors were thrown when expected params were missing
* Removed redundant type check from `NumberPrompt.OnPromptAsync()`, which was already covered in ctor's logic
=> NumberPrompt considers culture when parsing

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BaseInvokeDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BeginDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/ReplaceDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
Fix a bug where options are not passed from adaptive dialog to steps, plus enable basic option databinding to enable calls such as the following:
```csharp
new BeginDialog("ageDialog")
{
Options = new
{
userAge = "$age"
}
}
```
See the tests for more variations on enabled scenarios by this PR. 
TBD whether we want to do recursive databinding of multilevel properties in options but wanted to get this piece out for designer.
=> Adaptive: Options are passed to child steps + BeginDialog databinds options

libraries/Microsoft.Bot.StreamingExtensions/ReceiveRequestExtensions.cs
This PR reverts changes to how we handle requests containing activities without bodies to match the behavior expected by the channel SDK. This also creates consistency between requests and responses for handling empty-body activities.
=> Handle empty bodies the way the channel expects.

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
- Fixes #2258 
- Fixes an issue introduced by #2334 where `allowInterruption = NotRecognized` was incorrectly bubbling up when the input step recognized an invalid input. 
- Added 10+ new tests to cover both 'turn.processInput' addition as well as test the `allowInterruption` enum across possible conditions.
=> Added turn.processInput as a way for input step to re-process user utterance

libraries/Microsoft.Bot.Builder.StreamingExtensions/Microsoft.Bot.Builder.StreamingExtensions.csproj, libraries/Microsoft.Bot.Builder.StreamingExtensions/StreamingRequestHandler.cs, libraries/Microsoft.Bot.Builder.StreamingExtensions/VersionInfo.cs, libraries/Microsoft.Bot.StreamingExtensions/AssemblyInfo.cs, libraries/Microsoft.Bot.StreamingExtensions/Microsoft.Bot.StreamingExtensions.csproj, libraries/Microsoft.Bot.StreamingExtensions/Payloads/Assemblers/IAssembler.cs, libraries/Microsoft.Bot.StreamingExtensions/Payloads/Models/Header.cs, libraries/Microsoft.Bot.StreamingExtensions/Transport/ITransport.cs, libraries/Microsoft.Bot.StreamingExtensions/Transport/ITransportReceiver.cs, libraries/Microsoft.Bot.StreamingExtensions/Transport/ITransportSender.cs, tests/Microsoft.Bot.StreamingExtensions.Test/Microsoft.Bot.StreamingExtensions.Tests.csproj
Fixes "inaccessible due to its protection level" errors. Also supports the (new) multi-configuration CI builds. Passed in this build: https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=73079&view=results
ITransportSender was made public to be visible to the proxy generator used by Moq. It probably doesn't need the #if SIGNASSEMBLY directive any longer.
=> Add InternalsVisibleTo to fix CS0122

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/GetMethodExtensions.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Renderer.Tests/Fallback/test.en-US.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Renderer.Tests/LGGeneratorTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/TemplateRef.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/TemplateParamsNotMatchArgsNum.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/2344
We have a validation function in static checker period which is validating whether the parameters number from template definition is same with the number from the actual template call function. This PR is to make the validation always pass if the actual parameter number is zero. This is by design that no parameters mean parameters are inherited from caller's the scope.
=> [LG] Fix lg reference parameter issue

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.BeginDialog.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.DeleteProperty.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EditArray.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EndDialog.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.Foreach.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.ForeachPage.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.HttpRequest.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.InitProperty.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.ReplaceDialog.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.SetProperty.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.TraceActivity.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BaseInvokeDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BeginDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/ReplaceDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs, schemas/baseComponent.schema, schemas/component.schema, schemas/sdk.schema, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/DialogContextStateTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs, tests/Microsoft.Bot.Builder.TestBot.Json/Samples/BugRepo/BugRepo.main.dialog, tests/Microsoft.Bot.Builder.TestBot.Json/app.schema
#2012 
* Add Databinding Options for BeginDialog and ReplaceDialog
* Removed memoryPath $role (everything is an expression now)
* changed BeingDialog/ReplaceDialog to use DialogId instead of Dialog so that we can treat it as an expression.
=>  Changes to BeginDialog, ReplaceDialog, and RepeatDialog steps

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/DialogContextStateTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/RegexRecognizerTests.cs
Fixes #2330 
to support @ and @@ via capture groups
This makes regexrecognizer align with luisrecognizer to be able to recognizer named entities via multiple capture groups
=> change regexrecognizer to return multiple entities 

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/IfCondition.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
ifCondition does not handle missing memory references which return null which should be treated as false.
=> Fix bug in ifCondition 

libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
C# ToString on true produces "True" which parses as a memory path.  This normalizes true/false/null to ignore case.
=> Parse true/false independent of case

libraries/Microsoft.Bot.Builder.Expressions.Parser/Expression.g4, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/DialogContextStateTests.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs, tests/Microsoft.Bot.Builder.TestBot.Json/Samples/12 - GithubIssueBot/show.lg
1. Expression such as 'user.lists.{dialog.listName}' didn't throw exceptions from errorListener. 
2. Line number in error message should start from one instead of zero as line number of most editors starts from one
=> [Expression&LG] fix error listener bug in expression and line number issue in LG

libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs
Expose the lookup function in ExpressionEngine, so that the upper layer can further customized based on it.
The direction, is ExpressionEngine is the single extension point for functions. Next step would be let LG accept a customized ExpressionEngine.
=> Expose evaluator lookup

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/TwilioAdapterTests.cs
Fix ISSUE #2415 
Replaced bare _Exception_ with `ArgumentException` and `ArgumentNullException` in the `TwilioAdapter.cs` file. Also updated the related test methods.
Replaced _TwilioAdapter_'s constructor bare `Exception` with `ArgumentException` and `ArgumentNullException` respectively.
Also, updated _SendActivitiesAsync_ method for replacing an `Exception` an `ArgumentException`:
All the test methods successfully passed:
=> [TwilioAdapter] Replace TwilioAdapter bare Exceptions

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/ITwilioClient.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioApi.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/TwilioAdapterTests.cs
This fixes ISSUE #2413 
Change the parameter type in _GetResourceIdentifier_ from object to **CreateMessageOptions**.
Also, improved the name of the method _GetResourceIdentifier_ to **SendMessage**, since it creates and sends a message, and returns its resource identifier once sent.
**Modified classes:**
- ITwilioClient
- TwilioAdapter
- TwilioApi
Test methods updated accordingly and all of them passing.
=> [TwilioAdapter] Change GetResourceIdentifier method signature

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioMessage.cs
Added support for handling the message format when using Twilio's [Conversation API](https://www.twilio.com/docs/conversations).
Also added an **EventType** property to the _TwilioMessage_ class, to handle event types when using Twilio's [Conversations API](https://www.twilio.com/docs/conversations).
When using the Conversation API the received payload differs from the format used for [standard SMS sending and receiving](https://www.twilio.com/docs/sms/api/message-resource#message-properties), with the structure of the message varying between the different events ([link](https://www.twilio.com/docs/conversations/conversations-webhooks)). 
Among other changes, the sender's phone number is stored in the **Author** field instead of **From**. This change adds support for both properties. …
=> [TwilioAdapter] Add support for Twilio Conversations API

libraries/Microsoft.Bot.Builder.Expressions.Parser/Expression.g4, libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
=> remove ^ and ~ shortcuts

BotBuilder-DotNet.ruleset, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BaseInvokeDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.BeginDialog.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.ReplaceDialog.schema, schemas/sdk.schema, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.TestBot.Json/app.schema
From bug report:
I am trying to bring the latest 4.Future to Composer, but I found a bug about BeginDialog.
In this commit, https://github.com/microsoft/botbuilder-dotnet/commit/c2e078f25cf6a793320df4c4bbd2934bd0ad11b7
You have disabled Begin a dialog by dialog: “dialogname”, it works well for code but not in declarative format.
In declarative, first we did not assign a id (“d2”, “d3”) to the constructor. Second, we did not call d2.AddDialog(d3) in the loader.
So in declarative, when Begin a dialog, it can’t find the dialog and throw a null reference exception.
What would you suggest on this? fix from the Adaptive side or Declarative side?
Thanks,
Lu
=> Revert dialog id as expression

libraries/Microsoft.Bot.Builder/BotState.cs, tests/Microsoft.Bot.Builder.Tests/BotStateTests.cs
Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/2457
If there is no CachedBotState, there is nothing to force.
=> Forcing BotState.SaveChangesAsync should not Throw NullReferenceException without CachedBotState

tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
The TestMemberRemoved* tests appeared to be copies of the TestMemberAdded* tests, and they were still setup to test the members added.  Fixed to populate the Activity.MembersRemoved and expected method assertions.
=> Corrected ActivityHandlerTests RemoveMember tests.

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs
Fixes: #2480
`BotframeworkAdapter.CreateConversation` [strips out the ChannelData of the message here](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L782). As you can see per linked issue, this can cause problems when using `CreateConversation` with Teams since Teams requires `TenantId` on the `ChannelData`.
I also fixed up an issue where `MockAdapter.CreateConversation` wasn't mimicking our actual code, which would have caught this issue earlier.
**BotFrameworkAdapter.cs**
```diff
- eventActivity.Conversation = new ConversationAccount(id: result.Id);
+ eventActivity.Conversation = new ConversationAccount(id: result.Id, tenantId: conversationParameters.TenantId);
+ eventActivity.ChannelData = …
```
=> Fixed Teams TenantId/ChannelData issue

libraries/Microsoft.Bot.Builder.AI.QnA/Models/QueryResults.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/TestData/QnaMaker_ReturnsAnswer.json
Added Active learning enabled flag support 
Tests added for that.
=> [QnAMaker] GetAnswerRaw added

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/DebugBreak.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/Constants/TurnPath.cs
Fix for #2425 
Added a new `turn.interrupted` flag that set anytime an "ActivityReceived" event is handled within an `AdaptiveDialog`.  The `InputDialog` now checks for this flag instead of using `turn.stepCount`.
Removed `turn.stepCount` all together.
=> Dropped turn.stepCount in favor of turn.interrupted

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
Fix for #2392 
We weren't incrementing maxTurnCount when an interruption occured and we weren't checking that maxTurnCount was exceeded during an interruption.  Interruptions now count as a turn from the prompts perspective.
=> Check maxTurnCount for interruptions

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProvider.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/IResourceProvider.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration.Templates/LGAdapterExtensions.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Templates.Tests/LGGeneratorTests.cs
Fix for #2525  
- Create empty ResourceExplorer
- Change to TryGetResource() semantics for IResourceProvider (we actually don't want a provider to throw)
- Create unit test around no ResourceExplorer
=> Fix LanguageGeneration initialization with no resourceExplorer

libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceRecognizers.cs, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/NumberPromptTests.cs
This PR adds the `NumberWithUnit` recognizer to catch cases where `Number` fails to recognize.
- Refactor of the `RecognizeNumber` and `RecognizeOrdinal` to avoid repeted logic.
- Add the method `RecognizeNumberWithUnit` to `NumberPrompt`
- Modify the `OnRecognizeAsync` method to call `RecognizeNumberWithUnit`
- Add the recognition of _age_, _currency_, _temperature_ and _dimension_
=> [Dialogs] Add numberWithUnit recognizer to NumberPrompt

Microsoft.Bot.Builder(Preview).sln, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/ExpressionPropertyConverter.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/ExpressionProperty.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ExpressionPropertyTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ObjectPathTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Templates.Tests/LGGeneratorTests.cs
Rewrote ObjectPath to not rely on expression library.
Add unit tests to verify all functionality
=> Remove Expressions library dependency from .dialogs assembly 

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/HttpHelper.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkHttpAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/HttpHelper.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpAdapterTests.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/BotFrameworkHttpAdapterTests.cs
Both integration implementations return BadRequest when called with something other than an Activity.
An Activity being something that can be serialized into an Activity with a Type. All fields other than Type are optional. Technically at any one release, Type is restricted in what values it can take, however, this is not practical to constrain at this level (it is handled in the ActivityHandler layer.)
=> fix http adapter errors

libraries/Microsoft.Bot.Builder.Teams/TeamsActivityHandler.cs
(testing infrastructure needs updating to more easily test varied responses to event handlers ... no additional unit tests for this right now)
=> [Teams] Allow null response from OnTeamsTaskModuleSubmitAsync

libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/DialogMemoryScope.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs
DialogStateManager implements IDictionary<string, object> but the implementation of the methods were sometimes returning the MemoryScope object instead of the object behind the MemoryScope, preventing the debugger inspector from looking at the value of the memory scope.
This fixes that.
=> Fix DialogStateManager to property return the object in the debugger

libraries/Microsoft.Bot.Builder.AI.LuisV3/Microsoft.Bot.Builder.AI.LuisV3.csproj, libraries/Microsoft.Bot.Builder.ApplicationInsights/Microsoft.Bot.Builder.ApplicationInsights.csproj, libraries/Microsoft.Bot.Builder.Teams/Microsoft.Bot.Builder.Teams.csproj, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, libraries/Microsoft.Bot.Connector.Teams/Microsoft.Bot.Connector.Teams.csproj, libraries/Microsoft.Bot.Schema.Teams/Microsoft.Bot.Schema.Teams.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj
Noticed a few projects were not generating local NuGet packages on build - this PR fixes that.
=> Ensure all projects generate local NuGet package on build

libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ApplicationBuilderExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryInitializerMiddleware.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetrySaveBodyASPMiddleware.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/TelemetryBotIdInitializer.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/TelemetryInitializerMiddleware.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryInitializerTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/TelemetryInitializerTests.cs
Fixes: #2477 
Fixes: #2474 
This change introduces TelemetryInitializerMiddleware, as a replacement for the current TelemetrySaveBodyASPMiddleware.  Marking this PR as review for now until a few people have their chance to review, given a few conversations last week with @munozemilio @daveta among others. 
This existing method stores the incoming http request body in the HttpContext.Items collection.  This is later used by the TelemetryBotIdInitializer classes within the integration libraries to parse the request and set conversation / user / activity channel IDs on outgoing Application Insights requests. The current problem is that the current method assumes an incoming request is a Bot Framework Activity, but if a custom adapter is used, the incoming http request may be something …
=> Fix telemetry for custom adapters

libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorageOptions.cs, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionStorageTests.cs, tests/Microsoft.Bot.Builder.Tests/StorageBaseTests.cs
Addresses DCR #5467 https://github.com/microsoft/botframework-sdk/issues/5467 
@cleemullins @mdrichardson This is the initial version of the new CosmosDbPartitionedStorage class - I would appreciate your review before I move any further forward.
- The new implementation no longer handles database creation.  We only handle container creation.
- Uses the new v3 SDK
- Implements partitioning for the user, with the option to pass in a key now gone.  We utilize the ID of the item as the partition key.
Tests still need adding following initial review.
=> CosmosDbPartitionedStorage using v3 SDK.

libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/CustomizedMemoryScope.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/MemoryScope.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
Fix https://github.com/microsoft/botbuilder-dotnet/issues/2612
A few notes:
1. It's implemented in similar approach like how DialogStateManager today injecting shortcuts into expression, by creating a "customized IDictionary<string, object>". 
Those two cases are actually assuming the interface for a customized memory access pattern is IDictionary<string, object>. Which is too implicit, and maybe be true in the future because 
a. we actually don't need a full IDictionary interface for a memory scope interface. you can see most interface methods are not implemented
b. a IDictionary don't allow us to include the abstraction of memory stack which might be useful, it we really want a "cacading" memory expose. 
we might want to reconsider to take …
=> Allow sub-template access to global memory scope

libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/MemoryScope.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs
Update state manager to allow simple computed paths via using curly braces.  Eventually this can be connected to the expression engine.
=> Allow simple computed paths

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandlerBase.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/HttpHelper.cs
Serializing http request and response bodies async from memorystream, to avoid .netcore3 sync IO restrictions.
This PR does not address similar issues in Twilio, WebEx and ApplicationInsights projects.
An alternative option would be to use System.Text.Json with superior performance (memory and CPU), but serialization settings would need to be regression tested + it would introduce a new dependency to this package.
=> Sync read of request body throws on .netcore 3.0

tests/Teams/ActionBasedMessagingExtension-FetchTask/Bots/ActionBasedMessagingExtensionFetchTaskBot.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/2666
Fix `OnTeamsMessagingExtensionBotMessagePreviewSendAsync` to send the card to:
-  Teams "General" channel (Roster call to retrieve team).
-  Channel the messaging extension was started on.
-  Compose box for the user.
-  Cleanup send activities for other handlers.
Handles if user is in a group chat or personal scope..
=> Fix OnTeamsMessagingExtensionBotMessagePreviewSendAsync to match js

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandler.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/TwilioHelperTests.cs
Update Twilio / Webex and Invoke handlers to use async when reading request / writing to response for compatibility with .NET Core 3 in line with #2614
=> Twilio / Webex / Invoke use Async for .NET Core 3 compat

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/6.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
In normal case, use templateName(args) is more straightforward, but when you want to call a template without hard-coding the name, lgTemplate function comes in handy.  It works like reflection. 
So bring it back.
=> Bring back lgTemplate function

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
Ensure dialog dependencies have been installed when handling events.
A NullReferenceException can occur at L497 of AdaptiveDialog.cs, when the default Selector has not been set.
We run into this scenario because we are hydrating the dialogs each turn.
=> Ensure Dialog Dependencies have been installed when processing event

libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/MemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/SettingsMemoryScope.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs
As was Settings scope.
Since these are immutable values I don't think it makes sense for them to be sent as part of the memory snapshot, as that would push settings secrets into transcript logs as well as attempt to serialize objects that aren't designed to be serialized. 
* changed GetSnapshotMemory() to not take snapshot of readonly memory
* Made settings an explicit implemented memoryscope.  Old code was "filling" the settings in external location, now it's internal to SettingsMemoryScope
=> Class Scope was being returned in Memory Snapshot

libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineThrowExceptionTest.cs
Change empty template body from error severity to warning severity.
Original:
```
```
Currently:
```
```
=> Change empty template body from error severity to warning severity

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/StructuredTemplate.lg
=> Fix structured-lg don't work when the last line contains space

libraries/Microsoft.Bot.Expressions/parser/ExpressionEngine.cs, tests/Microsoft.Bot.Expressions.Tests/ExpressionEngineTests.cs
=> [Expression] fix empty string as expression issue

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerBadRequestTests.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerNotImplementedTests.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs, tests/Teams/ActionBasedMessagingExtensionFetchTask/Bots/ActionBasedMessagingExtensionFetchTaskBot.cs, tests/Teams/AdaptiveCards/Bots/AdaptiveCardsBot.cs, tests/Teams/MessagingExtensionAuth/Bots/MessagingExtensionAuthBot.cs, tests/Teams/Roster/AdapterWithErrorHandler.cs, tests/Teams/Roster/TeamsTenantFilteringMiddleware.cs, tests/Teams/Roster/appsettings.json, tests/Teams/TaskModule/Bots/TaskModuleBot.cs
Fixes: 
https://github.com/microsoft/botbuilder-dotnet/issues/2737
and
https://github.com/microsoft/botbuilder-dotnet/issues/2718
•	Remove the tenant filtering middleware from the product, and add to samples
-Removed TeamsTenantFilteringMiddleware from the product and added it to Roster bot as an example.
•	Bot message preview edit/send return value should be bad request if malformed
-now returning BadRequest
•	File consent should be bad request if malformed
-now returning BadRequest
•	OnTeamsMessagingExtensionFetchTaskAsync should take a MessagingExtensionAction and not MessagingExtensionQuery 
-Changed parameter type
•	In TeamACtivityHandler we should check whether there is an InvokeResponse activity on the turnstate and if there is don’t overwrite it.
- added check of TurnState for …
=> [Teams] Hackathon feedback

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
Fixes #2727 
Now the only time we recursively execute steps is when an parent above the currently executing dialog has changed their plan. This is typically in response to an emitted event and very rare.  Loops and such should require no recursion.
=> Updated AdaptiveDialog to execute steps without using recursion

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs
@EricDahlvang stylecop was complaining about the exception class - while i was in there I added the message as we discussed and also made the SafeCast throw this exception.
arguable a null Action or BotMessagePreviewAction should be a bad request? currently it would be a NotImplemented i'm tempted to  just leave this at this point...
=> fix stylecop issue and add message to exception

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/CancelAllDialogs.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
Fixes #2531 
The default is "false" which preserves the current 4.5 behavior.
=> Added a flag to control the bubbling of cancellation events

libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs, libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs, libraries/Microsoft.Bot.Connector/Authentication/OAuthConfiguration.cs, libraries/Microsoft.Bot.Connector/Authentication/Retry.cs, libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/TimeSpanExtensions.cs, libraries/Microsoft.Bot.Connector/Internals.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/AppCredentialsTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenValidationTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/MicrosoftAppCredentialsTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/SkillValidationTests.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Mocks/MockAppCredentials.cs
Relates to #2743 
Added constructor overload to AppCredentials and MicrosoftAppCredentals that allow the developer to set a custom OAuthScope (this helps with skill authentication where the audience will be the calling bot).
Added code to validate skill request tokens
Adds missing (c) to OAuthConfiguration, Retry and TimeSpanaExtensios.
Added InternalsVisibleTo to facilitate unit testing.
=> Implements auth changes required to handle skills

libraries/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
The Skills package should be shipped with a preview tag. This updates to the correct Azure Devops variable that drives those versions.
=> Update Skills Package to use Preview semver tag.

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandler.cs
Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/2762
=> Ensure memory stream is at position 0 after Body is copied into it

libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ObjectPathTests.cs
Example:  "dialog[user.name].Age"
fix for #2757
=> fix ObjectPath.GetValue to handle nested property paths

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggerSourceMap.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DialogDebugAdapter.cs
* Debugger requires camelcase serialization when communicating with vscode debugger
* VSCode sends different case drive letter then IIS has.  
** Added support to only use file name for resources, (.dialog, .lg, etc.) 
** made path case insensitive on windows platform.
=> Fix regressions in Debugger support

libraries/Microsoft.Bot.Builder.Skills/Adapters/BotFrameworkSkillHostAdapter.cs, libraries/Microsoft.Bot.Builder.Skills/Integration.AspNet.Core/BotFrameworkHttpSkillsServer.cs, libraries/Microsoft.Bot.Builder.Skills/SkillHostAdapter.cs, tests/Microsoft.Bot.Builder.Skills.Tests/Microsoft.Bot.Builder.Skills.Tests.csproj, tests/Microsoft.Bot.Builder.Skills.Tests/SkillAdapterTests.cs, tests/Microsoft.Bot.Builder.Skills.Tests/SkillConversationTests.cs
Removed IBot from the BotFrameworkSkillHostAdapter/SkillHostAdapter constructos (and the related property) and updated the code to use the IBot instance passed in the BotFrameworkHttpSkillsServer.ProcessAsync()
Updated unit tests project to use XUnit.
Relates to #2774
=> SkillHostAdapter Constructor updates

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandlerBase.cs
Fixed issue where the body of invokes with no response was 'null' rather than an empty body. This was causing all the `TeamsActivityHandler` delegates that didn't have a payload response to an invoke to fail in-flight on returning to Teams as one of the intermediaries attempts to parse the body as JSON if present.
=> Fix for #2776: 'null' response to Invoke when using AspNetCore integration package

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs
We need to maintain the Generator properly to the dialog scope.
* Changed to cache and restore the generator as adaptive dialogs come in and out of scope on BeginDialog(), ContinueDialog(), And REsumDialog() boundaries
* changed EndDialog to restore the parent, in case the parent doesn't cache correctly.
* Added unit test to verify that nested dialogs with local generators have the correct generator for the dialog scope.
=> LG local scoped generators get clobbered with nested dialogs

libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs, libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs
to handle cross memory scope references and nested bracket syntax across Get/Set/RemovePath() calls
=> Fix objectPath array syntax 

libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs, libraries/Microsoft.Bot.Builder/AdapterExtensions.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/SettingsStateTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs
Fixes #2823 
Current code was doing it's own custom storage
* removed custom storage, replaced to use PropertyAccessors
* removed RunAsync() (can add in the future)
* added unit tests
** OnError works to clear conversationState
** Expiration works to clear conversationState
* Cleaned up UseState()
=> DM should be using ConversationState/UserState directly 

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Builder.Skills/Adapters/BotFrameworkSkillHostAdapter.cs, libraries/Microsoft.Bot.Builder.Skills/SkillHostAdapter.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs
Implements #2775 
Updated OAuthPrompt to add a sign in link for the emulator and webchat.
Updated logic in BotFrameworkAdapter to use AppCredentials directly instead of grabbing them from the connect client so it can use the skill credentials if need and update the logic to create the signing link to unpack the proper server URL and conversation ID from the skill conversation ID
Added null check for channelData for teams TenentId middleware
=> Adds support for OAuthCards for skills

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/BotStateMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/ClassMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/ConversationMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/MemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/SettingsMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/TurnMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/UserMemoryScope.cs, libraries/Microsoft.Bot.Builder/TurnContextStateCollection.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/SettingsStateTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/LamdaDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/2842
MemoryScopes were being initialized by external DM, which is not optimal
* it makes it harder to add new scopes
* it adds a hard dependency on the implementation of User and Converation scopes
This delta adds unit test for the issue, but implements BotStateMemoryScope with User and Conversation versions of it which are self contained.
User and Conversation state were being copied into the TurnState, but there was no real reason to do this.
Turn memory scope was always being intialized even if it was already there.
This cleanup allows for
* more BotState based scopes to be easily added (such as Tenant, etc)
* Better encapsulation
* Ability for customers to replace memory scopes (such as User and Conversation) with their own …
=> Refactor MemoryScopes to be self-contained 

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/DirectLineSpeechTests.cs
We don't currently have a way to automate adding the DirectLine Speech channel to a bot, which means the functional tests aren't able to add it to the bot created to run tests against. The tests run and pass if the bot is setup correctly, but need to be ignored until the test setup is able to add Speech to the the test bot.
Also the OS check was pointless, the tests are not run from the same environment the bot is deployed to.
=> Ignore DirectLine Speech tests until tooling is updated to support them

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/MessageGeneratorTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/NormalStructuredLG.lg
Trim the whitespace of structured-lg. For example:
```
[     Activity       -> type will be parsed as 'Activity', but not '    Activity    ';       
text = 'hi'
]
```
=> Trim the whitespace of structured-lg

libraries/Microsoft.Bot.Builder.Skills/Adapters/BotFrameworkSkillHostAdapter.cs, libraries/Microsoft.Bot.Builder.Skills/Integration.AspNet.Core/BotFrameworkHttpSkillsServer.cs, tests/Microsoft.Bot.Builder.Skills.Tests/Integration.AspNet.Core/BotFrameworkHttpSkillsServerTests.cs, tests/Microsoft.Bot.Builder.Skills.Tests/Microsoft.Bot.Builder.Skills.Tests.csproj
Removed unused code from BotFrameworkSkillHostAdapter.
Added overload for BotFrameworkSkillHostAdapter.ForwardActivityAsync that takes SkllOptions and callback URL.
Updated BotFrameworkHttpSkillsServer to handle relative paths and refactored code to use delegates.
Added unit tests for BotFrameworkHttpSkillsServer.
Relates to #2774
=> Skill updates for CCI integration

libraries/Microsoft.Bot.Builder.Skills/Adapters/BotFrameworkSkillHostAdapter.cs, libraries/Microsoft.Bot.Builder.Skills/SkillHostAdapter.cs, tests/Microsoft.Bot.Builder.Skills.Tests/SkillAdapterTests.cs
Relates to #2774 
Fixes issue handling InvokeActivities
Added code to create a deep clone of the Activity in ForwardToSkill in order to avoid issues related to manipulating the activity during the forward operation
Removes functionality to load Skills information from config in BotFramworkSkillHostAdapter and ForwardToSkill overload that was using it.
Updated ForwardToSkill abstract method in SkillHostAdapter.
Fixed several compilation warnings by removing unused parameters (we can add them back later).
FYI @lzc850612
=> Skill bug fixes

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptCultureModels.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs
Per standup this morning, this is a PR against 4.6, replacing [this PR](https://github.com/microsoft/botbuilder-dotnet/pull/2943)
---
Fixes: #2942 
* `ChoicePrompt`: Ensures that locale defaults to English and handles mapping to the nearest locale more gracefully
* `PromptCultureModels`: Implements our own version of [Recognizers-Text's `MapToNearestLanguage`](https://github.com/microsoft/Recognizers-Text/blob/7b20c1bbbfdebc3a801fbc61b094706ceebd7acf/.NET/Microsoft.Recognizers.Text/Culture.cs#L66) -- They added a bunch of other supported languages that will break this without doing this.
* `ChoicePromptTests`: Added a test to specifically set the Locale to null
* ConfirmPrompt already handled this fine and had tests for it
* I'll also work on some tests for PromptCultureModels, but I …
=> ChoicePrompt handles null locales [4.6 cherry-pick]

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs, libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConfiguration.cs, libraries/Microsoft.Bot.Connector/Authentication/ClaimsValidator.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs, tests/Microsoft.Bot.Builder.TestBot.Json/TestBotHttpAdapter.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenValidationTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/SkillValidationTests.cs
Relates to: https://github.com/microsoft/botbuilder-dotnet/issues/2970
Added ClaimsValidator to AuthtentcationConfiguration and updated validation sequence in JwtokenValidation to use it.
Updated BotFrameworkHttpAdapter and BotFrameworkHttpAdapterBase to surface constructor parameters from BotFrameworkAdapter so they can be used.
Refactored BotFrameworkHttpAdapter and BotFrameworkHttpAdapterBase to have only one constructor call base and the other ones to use this. to make it easier to maintain and have consistent execution paths.
=> Adds ClaimValidator to AuthtentcationConfiguration

tests/Microsoft.Bot.Builder.Dialogs.Tests/ObjectPathTests.cs
However, ObjectPath can't get null out. Is it a bug or expected behavior? Thanks
Related https://github.com/microsoft/botbuilder-dotnet/issues/2891
=> Add null, enum tests for ObjectPath

libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/Microsoft.Bot.Builder.ApplicationInsights.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Tests/Microsoft.Bot.Builder.Dialogs.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.TestBot.Tests/Microsoft.Bot.Builder.TestBot.Tests.csproj, tests/Microsoft.Bot.Builder.TestBot/Microsoft.Bot.Builder.TestBot.csproj, tests/Microsoft.Bot.Expressions.Tests/Microsoft.Bot.Expressions.Tests.csproj, tests/Microsoft.Bot.Streaming.Tests/Microsoft.Bot.Streaming.Tests.csproj, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests.csproj
For more info see: 
https://github.com/microsoft/BotBuilder-Samples/issues/1524
and
https://github.com/aspnet/Universe/issues/1180
Without this change, I cannot build some of the test projects from a clean repo pull.
`dotnet --info`
Note this recommendation: 
> When referencing the Microsoft.AspNetCore.App or Microsoft.AspNetCore.All packages, do not specify their version.
has a known issue on 2.1:
> Known issue: the .NET Core 2.1 SDK only supported this syntax when the project also uses Microsoft.NET.Sdk.Web. This is resolved in the .NET Core 2.2 SDK.
from:
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#recommendation
=> Fix library compat issues.

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/StructuredTemplate.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
in LG, expression should be described as @{expression}
but now, if you just want to escape it, use a \ in front of expression, like  \\@{expression}, 
so it will be evaluated as string '@{expression}'
=> fix expression escape issue

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/TemplateEngineLanguageGenerator.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/b.en-us.lg, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/c.en.lg
Currently, to support flexible multi-language support. We try to enumerate every entry lg + every locale found, which is too wide. 
If the entry is "foo.en_us.lg" and refers to "bar.lg", we should only looking for "bar.en_us.lg" or other language fallback. We should not try to create other locales found, because the file id already tells the locale
=> Fix multi-lang resource generator enumerate locale blindly

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/2690
and partly
https://github.com/microsoft/botbuilder-dotnet/issues/2689
=> Clear activity.id before sending in BotFrameworkAdapter.OnSendActivities

libraries/Microsoft.Bot.Builder/ChannelServiceHandler.cs
From `Microsoft.Bot.Builder.Integration.AspNet.Core` to `Microsoft.Bot.Builder`.
=> Fix namespace on ChannelServiceHandler

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MiscTests.cs
Adaptive Dialog needs to have dialog set initialized before dialogcontext is created.  When dialogs are static this is a small issue, but when you create the dialog tree on each this will cause inconsistent dialogset collections.
Fix for #3031
=> DialogSet dependencies not initialized correctly when created each turn

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs
`ILogger logger` parameter was made optional in the Webex and Twilio adapter's constructors, to match with the rest of the adapters.
Logger parameter was made optional in Webex and Twilio adapters' constructors. This is consistent with the other two adapters ([Facebook ](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs#L46)and [Slack](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs#L36)), and also fixes an exception that occurred when targeting **NETCore 3.0** with any of those two adapters:
=> [BotBuilder-DotNet] Add optional logger parameter to Webex and Twilio Adapters

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
Relates to https://github.com/microsoft/botframework-sdk/issues/5654
Removes special handling for sign in link generation for skills and adds code to force magic code in OAuthPrompt for skills
In R7 skills that use the OAuthPrompt will still require a magic code, we will look into removing the need for magic code in R8.
=> OAuthPrompt Updates for Skills

libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorageOptions.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDBKeyEscapeTests.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionStorageTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/2766 CosmosDbPartitionedStorage should support a custom user provided suffix for id
and
https://github.com/microsoft/botbuilder-dotnet/issues/2765 CosmosDbPartitionedStorage should work with existing collections created by CosmosDbStorage
=> Add KeySuffix and CompatibilityMode to CosmosDbPartitionedStorage

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/DialogStateManager.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs
Fix for bug #3074 
Added ResolveMemoryScope() call
Added unit tests.
=> SetPathValue needs to use ResolveMemoryScope() like GetPathValue does

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
AppCredentials construction: Enable extension of credential construction by sublcassing of adapter and http client. Side effect: promoting 4 private members to protected.
Instead of building new functionality for custom credentials in the adapter (and adding more constructors to the problem), we allow subclasses to customize how credentials are created. This enables scenarios like multitenant bots with custom creds, etc.
All the lines changed only boil down to 1) refactoring the creation of the AppCredentials to a protected virtual method, 2) promoting 4 private members to protected for subclasses to be able to access them. We make them properties since our policy does not allow protected members :)
=> AppCredentials construction: Enable extension of credential construction

libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs
The overload is private and has no references.
=> remove unused overload in JwtTokenExtractor

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/DirectLineClientTests.cs, FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/DirectLineSpeechTests.cs, FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/GetTokenRefreshTests.cs, FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/JwtTokenExtractorTests.cs, build/yaml/ci-test-steps.yml
Added attribute [TestCategory("FunctionalTests")] to functional tests. Builds then reference that attribute for running tests instead of compiling different versions.
=> Change Functional tests to use attribute instead of compiler directive

build/yaml/botbuilder-dotnet-functional-tests-setup.yml
Delete no-longer-used compiler directive from the functional tests YAML build. Specifically, delete msbuild argument  -p:DefineConstants="FUNCTIONALTESTS"
This is build cleanup from PR #3124.
=> Delete compiler directive from functional tests YAML build

libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj
The other NuGet packages from the botbuilder-dotnet signing build contain their .pdb files, just not this one. Adding this property to the .csproj file fixed it.
=> Force Bot.Streaming .nupkg file to contain symbols

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/RandomSelector.cs, libraries/Microsoft.Bot.Expressions/BuiltInFunctions.cs
They are not thread-safe when multiple users call these functions.
Also we must use `services.AddSingleton<IBot, TestBot>()` for the state of RandomSelector._rand
=> fix for multi user scenario

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs, libraries/Microsoft.Bot.Builder/BotAdapter.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
#3147  - Added additional ContinueConversationAsync overload for custom adapters for skills compatibility.
#3146 - Move 'BotIdentityKey' const to BotAdapter and made it public.
=> Update adapters for Skills compatibility

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/NumberInput.cs
Number input treat any inputs as float, if pass the following validation, the number input will convert the integer number to float, "22" -> "22.0" with length 4 which is nonintuitive.
```
{
"$kind": "Microsoft.NumberInput",
"property": "user.age",
"alwaysPrompt": true,
"prompt": "What is your age?",
"invalidPrompt": "Please input a number.",
"validations": [
"length(string(this.value)) == 2"
]
},
```
=> [Adaptive] Fix Number Input

build/yaml/functional-test-setup-steps.yml
Fixes "error : The 'Publish' target is not supported without specifying a target framework"
(I picked 3.0 instead of 2.1 or 2.2. It seems to work in my test build, but this ought to tell for sure.)
=> Add argument "--framework netcoreapp3.0" to Create PublishedBot.zip

build/yaml/functional-test-setup-steps.yml, build/yaml/functional-test-setup2-steps.yml
Turns out netcoreapp3.0 creates a test bot that does not work. Specifying 2.1 does work.
=> Change to "--framework netcoreapp2.1"

libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceRecognizers.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/FindChoicesOptions.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicesRecognizersTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/2956
and
https://github.com/microsoft/botbuilder-dotnet/issues/3039
=> Add RecognizeOrdinals and RecognizeNumbers flags to FindChoicesOptions

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/Ask.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.Ask.schema, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/ExpressionProperty.cs, schemas/sdk.schema, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/GeneratorTests/sandwich/sandwich-BreadAsk.dialog
This allows computing expected properties with an expression or using an explicit list of property names.
=> Make Ask.ExpectedProperties support expressions

build/yaml/botbuilder-dotnet-sign.yml, build/yaml/ci-post-to-github-steps.yml
Also add publish-to-Github verification. 
This PR adds to the yaml CI build the same things that are already in effect in build BotBuilder-DotNet-master-CI-PR running here: https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=457&_a=summary
Examples: The added conditionals in the PR build #98101 let the publish to GitHub steps execute. In the non-PR build #98147 they skip execution. 
The verification step reads the build log searching for the result status "201 Created".
The verification compensates for the fact that the GitHub publish step always indicates "succeeded" regardless of whether the publish succeeded or failed. (Build #97889 shows that problem.)
=> Add PR conditionals for publish to Github PR

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptCultureModels.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptLocTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/PromptCultureModelsTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/TestLocale.cs
Recognizers-Text [added support for a few additional languages](https://github.com/microsoft/Recognizers-Text/blob/7b20c1bbbfdebc3a801fbc61b094706ceebd7acf/.NET/Microsoft.Recognizers.Text/Culture.cs#L25) that we don't currently support in our Confirm and Choice prompts:
* Bulgarian
* Hindi
* Italian
* Korean
* Swedish
* Turkish
This PR adds support for those, ensures they get test coverage, and also adds test coverage for `PromptCultureModels`.
*Notes:* 
* I skipped adding Arabic support because it is read Right to Left, which makes prompt support tricker.
* Recognizers-Text JS SDK currently has only added Italian, but I don't believe there's a reason our C#/Node SDKs need to have matching language support
* I'm also far from a polyglot, so most of the translations were provided by …
=> Additional Language Support for Confirm/Choice Prompts

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
Relates to #3245
Adds code to initialize _appCredentialMap and _connectorClients cache with default instances during  ContinueConversationAsync calls.
This PR also adds the serviceUrl of the reference activity to the AppCredentials.TrustServiceUrl list.
This is needed because these in memory objects are not initialized unless the channel invokes the bot first. In some proactive scenarios and skills, the server may not have been initialized and this cases a 401 when the bot tries to respond to the channel.
=> Initialize security context for Skill ContinueConversationAsync calls

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexHelper.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.TestBot/Bots/EchoBot.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexAdapterTests.cs
Add support for messages sent from a room and reply to them in the room instead of in a private conversation.
- Update **WebexAdapter** class to handle the roomId and the new method's signature on _CreateMessageAsync_ method
- Update **WebexClientWrapper** class to call the _CreateMessageAsync_ instead of the _CreateDirectMessageAsync_ method.
- Update **WebexHelper** class to get the SpaceId from the message.
- Update the **WebexTestBot** to handle the membership event and send a message when the bot is added to a room.
- Update unit tests for the new method signature.
=> [Webex adapter] Add support for room messages

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj, libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.ApplicationInsights/Microsoft.Bot.Builder.ApplicationInsights.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj, libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj, libraries/Microsoft.Bot.Builder.Testing/Microsoft.Bot.Builder.Testing.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Expressions/Microsoft.Bot.Expressions.csproj, libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj, tests/Microsoft.Bot.Expressions.Tests/Microsoft.Bot.Expressions.Tests.csproj
Added <PrivateAssets>all</PrivateAssets> to all project references to SourceLink.Create.CommandLine.
Addresses Issue #3211 , the "immediate fix" part.
=> Add PrivateAssets metadata to SourceLink.Create.CommandLine references

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LGAdapterExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Testing/TestActions/AssertReplyActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Testing/TestActions/UserActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Testing/TestActions/UserConversationUpdate.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Testing/TestActions/UserDelay.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Testing/TestActions/UserSays.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Testing/TestActions/UserTyping.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Testing/TestScript.cs, libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs, libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/TestUtils.cs
* adding **testAdapter.GetNextReplyAsync()** in **TestAdapter** and used proper Task semantics without polling
* Changed TestFlow and TEstScript to use the **GetNextReplyAsync()**. This gets rid of all polling in the test adapter/test script.
* cached the **LanguageGeneratorManger** per resourceExplorer as we were creating a new one EVERY test, which took 1 sec each test.
* Cleaned up output to show timings and actual rule which is executing
* Added timings for turns so we can see the amount of time it took to execute a turn when running unit tests.
**All of the unit tests compute in <3 minutes now** (where it was 10 minutes without these changes.
Adaptive Dialog tests now complete in < 2 seconds
=> Make Unit Tests run 3-10x faster.

README.md
Fixes #3271 
The main README has:
[# Click here to find out what's new with Bot Framework](https://github.com/Microsoft/botframework/blob/master/whats-new.md#whats-new) which points to an archived Repo. 
It was updated for Ignite in November. If we're still going to use it, feel free to disregard this PR.
I also considered linking to the Releases page of this repo, but felt it was better to just remove the link.
=> Update stale link

CodeCoverage.runsettings, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, tests/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests.csproj
Fixes #3213 
Updated Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj to target .netCore3.0 and standard.
Updated references to Microsoft.ApplicationInsights.AspNetCore 2.12 (has to be 2.8 or higher to support .netcore 3.0 as shown here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core)
Updated output path for cross compiled projects to use the $(TargetFramework) variable in the path.
Readded removed AsyncUsageAnalyzers to Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
=> .NetCore 3.0 support updates

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ChannelServiceController.cs
Fixes #3256
Made ChannelServiceController abstract and its constructor protected to prevent the ASP.Net runtime from registering it as a controller.
Important, this is a breaking change but ChannelServiceController is really intended to be derived.
=> Made ChannelServiceController abstract

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs
Fixes #3251.  
When a dialog is added to a ComponentDialog the TelemetryClient setter sets the TelemetryClient on any child dialogs as well, as per this line https://github.com/microsoft/botbuilder-dotnet/blob/8d8b2b594f578c0a1d3bf9f23e0217d73e79075b/libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs#L51 
However, when nesting ComponentDialogs, such as myComponentDialog.AddDialog(anotherComponentDialog), this breaks and the TelemetryClient is not set on any child dialogs of 'anotherComponentDialog'.  This is because the TelemetryClient on the ComponentDialog is using ***new*** instead of ***override***, meaning that when using the Add method on a DialogSet, the TelemetryClient (https://github.com/microsoft/botbuilder-dotnet/blob/8d8b2b594f578c0a1d3bf9f23e0217d73e79075b/libraries/Mi …
=> Change TelemetryClient property on ComponentDialog to override

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookMessage.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot/Bots/PrimaryBot.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Bots/SecondaryBot.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookHelperTests.cs
The changes address the issue raised in bug [#3071](https://github.com/microsoft/botbuilder-dotnet/issues/3071) where the typing indicator is not supported in the .NET version of the adapter yet.
To display a `typing_on` [sender_action](https://developers.facebook.com/docs/messenger-platform/send-messages/sender-actions/) every time the bot prepares a message, we added the _SendMessage_ method in **FacebookHelper** which creates an extra activity with the required format for the Sender Action (note that `FacebookMessage.Message` needs to be null when Sender Actions are present) and then sends it along with the actual message activity using TurnContext [SendActivitiesAsync](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/TurnContext.cs#L218) …
=> [Facebook Adapter] Add typing indicator support

build/yaml/botbuilder-dotnet-ci-slacktest.yml
NOTE: This PR depends on #3108 to be merged.
This pull request adds a YAML file to set up a build pipeline for Slack Functional Test.
We added the file `botbuilder-dotnet-ci-slacktest.yml` inside the `build/yaml` folder, this file can be used to set up a pipeline to run functional tests for slack.
By default, the file is configured to run the pipeline for each commit or pull request in the master branch. This can be changed in the file or in the UI when setting the pipeline. 
The next steps will guide you through the configuration of a Build pipeline based on the YAML files.
- Azure DevOps organization.
- Azure subscription. Required to create and delete Azure resources.
- One app registration in Azure. [More info](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart- …
=> Add YAML file to set up pipeline for functional test with Slack

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/SlackClientTest.cs, build/yaml/botbuilder-dotnet-ci-slacktest.yml, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/Bots/EchoBot.cs
This PR contains the fix to correctly determine if a message comes from a user or a bot. Also, the updated functional test to work with the changes made in the adapter and the yaml file to run the test.
With the [changes](https://api.slack.com/messaging/retrieving) in the Slack API, the field subtype that we used to filter bot messages, is no longer part of the event's body. 
In the _EventToActivityAsync_ method of the **_SlackHelper_** class, we now filter the messages using the _bot_id_ field of the slack event.
In the **_SlackClientTest_** we updated the _SendMessageAsync_ method to create and send the message directly to the bot instead of using the API, because there's no way to impersonate a user to send the message and the bot could respond to it.
We updated the …
=> [Slack Adapter] Fix to filter bot messages

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/FacebookChatTests.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot/DeploymentTemplates/template-with-new-rg.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot/DeploymentTemplates/template-with-preexisting-rg.json
NOTE: YAML file to set up a pipeline with this functional test in PR #3262
This pull request adds a functional test for the Facebook Adapter.
We added the class `FacebookChatTests.cs` with the functional test for Facebook.
Also we edited the templates `template-with-new-rg.json` and `template-with-preexisting-rg.json` from the PrimaryTestBot to include the required variables to deploy it to Azure.
=> [Facebook Adapters] Add Facebook functional test

libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/TelemetryBotIdInitializer.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryInitializerTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/TelemetryInitializerTests.cs
Addresses this issue reported in JS https://github.com/microsoft/botbuilder-js/issues/1512
App Insights has a maximum session ID of 64 characters, but in some instances for some channels (such as reported with Teams) this may be exceeded due to conversation ID currently being used for session ID.  This PR hashes the conversation ID and sets this as the session ID.  It also adds an additional telemetry property to ensure we retain the original conversation ID within the telemetry.
The hashed ID is only used for Application Insights and the original conversation ID and activity are left untouched.
=> Implement hash for App Insights session ID

build/yaml/botbuilder-dotnet-ci-facebook-test.yml, build/yaml/botbuilder-dotnet-ci-slacktest.yml, build/yaml/botbuilder-dotnet-ci-twilio-test.yml, build/yaml/botbuilder-dotnet-ci-webextest.yml, build/yaml/nightly-build-functional-test-unix.yml, build/yaml/nightly-build-functional-test-windows.yml
This PR updates the functional tests YAML files to work with the Net Framework 3.1 version and to keep consistency betweem them.
- Twilio YAML: Change the set environment variables step to use uppercase: The use of lowercase can conflict with the use of pipeline variables set to hidden.
- Twilio, Slack, Webex, Nightly Build YAMLs: 
- Change the target for the publish bot step: This is required when the project is multi-target and requires to specify which one to use, now we are using only 3.1.
- Remove the build steps to replace them with the _ci-build-steps_ template.
=> Update Functional Tests YAML files

libraries/Microsoft.Bot.Expressions/BuiltInFunctions.cs, tests/Microsoft.Bot.Expressions.Tests/BadExpressionTests.cs, tests/Microsoft.Bot.Expressions.Tests/ExpressionEngineTests.cs
closes #3279
Now split function can take a single parameter:
split('hello'), new string[] { "h", "e", "l", "l", "o" }
Also if the seperator is a null, it will return same result as the seperator is string.Empty. If both input string and seperator are string.Empty or null, it will return a empty string array.
split('hello',''), new string[] { "h", "e", "l", "l", "o" }
split('',''), new string[] {  }
split('hello',nullObj), new string[] { "h", "e", "l", "l", "o" }
If the input string is null, it will return string.Empty regardless the content of the non-empty seperator.
split(nullObj,'e')", new string[] { string.Empty }
=> Supporting iterate string by split function

libraries/Microsoft.Bot.Builder.LanguageGeneration/CustomizedMemory.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFile.cs, libraries/Microsoft.Bot.Expressions.Properties/Extensions.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/MessageGeneratorTests.cs
close: #3297
Today, every time a free LG text like "@{welcome}" is evaluated by creating a new "anonymous template" to wrap this free text, and create a temporary LG file with the new content = original content + new anonymous template, for evaluation.
This is not performance friendly. In this pr, we just parse the additional part, so that there is no need to reparse the original content.
=> Optimize performance of LG evaluation

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
The existing overload of GetOauthSignInLinkAsync function with a userId as argument isn't working. It was hardcoding directline, passing empty conversations etc. This PR is to fix that.
=> [OAuth] small oauth fix

FunctionalTests/Skills/SimpleBotToBot/EchoSkillBot/Authentication/AllowedCallersClaimsValidator.cs, FunctionalTests/Skills/SimpleBotToBot/EchoSkillBot/Bots/EchoBot.cs, FunctionalTests/Skills/SimpleBotToBot/EchoSkillBot/Controllers/BotController.cs, FunctionalTests/Skills/SimpleBotToBot/EchoSkillBot/EchoSkillBot.csproj, FunctionalTests/Skills/SimpleBotToBot/EchoSkillBot/Program.cs, FunctionalTests/Skills/SimpleBotToBot/EchoSkillBot/Properties/launchSettings.json, FunctionalTests/Skills/SimpleBotToBot/EchoSkillBot/SkillAdapterWithErrorHandler.cs, FunctionalTests/Skills/SimpleBotToBot/EchoSkillBot/Startup.cs, FunctionalTests/Skills/SimpleBotToBot/EchoSkillBot/appsettings.json, FunctionalTests/Skills/SimpleBotToBot/EchoSkillBot/wwwroot/default.htm, FunctionalTests/Skills/SimpleBotToBot/EchoSkillBot/wwwroot/manifest/echoskillbot-manifest-1.0.json, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/AdapterWithErrorHandler.cs, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/Authentication/AllowedSkillsClaimsValidator.cs, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/Bots/RootBot.cs, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/Controllers/BotController.cs, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/Controllers/SkillController.cs, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/Program.cs, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/Properties/launchSettings.json, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/SimpleRootBot.csproj, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/SkillConversationIdFactory.cs, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/SkillsConfiguration.cs, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/Startup.cs, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/appsettings.json, FunctionalTests/Skills/SimpleBotToBot/SimpleRootBot/wwwroot/default.htm, Microsoft.Bot.Builder.Skills.sln, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftGovernmentAppCredentials.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/MicrosoftGovernmentAppCredentialsTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3233
Added constructor to MicrosoftGovernmentAppCredentials that takes OAuthScope to support skills in gov.
Updated BotFrameworkHttpClient and BotFrameworkAdapter to pass the OAuthScope to MicrosoftGovernmentAppCredentials
Added SimpleBotToBot functional test for testing.
Added Microsoft.Bot.Framework.Skills.sln to load skills test projects.
=> Updated MicrosoftGovernmentAppCredentials to support Skills in Azure Gov

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookEntry.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioClientWrapper.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookAdapterTests.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookWrapperTests.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/TwilioAdapterTests.cs
Fixes #3370 
Also updates use of cancellation tokens in adapters for consistency.
=> Added cancellation token to ContinueConversationAsync on Facebook adapter

libraries/Microsoft.Bot.Builder/EventFactory.cs, libraries/Microsoft.Bot.Builder/HandoffEventNames.cs, tests/Microsoft.Bot.Builder.Tests/EventFactoryTests.cs
From https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library with minor changes
=> Event factory for handoff protocol

libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFile.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGParser.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/LGFileTest.cs
Originally, we do parse the additional inline text directly.
In this pr, we will add a new text parser, that accepts the text and original LGFile both.
So, there will be no intermediate error messages appearing in parse directly. 
At the same time, no impact on parse performance.
close: #3352
=> [LG] optimize inline text evaluation

libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorageOptions.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
Fixes: https://github.com/microsoft/botframework-sdk/issues/5634
Deprecate CosmosDbStorage and CosmosDbStorageOptions with recommendation to use CosmosDbPartitionedStorage, and fix compiler warnings in CosmosDbStorageTests
=> Add Obsolete attribute to CosmosDbStorage 

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/DialogStateManager.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs
Fix for #3165 
Issue was with Type confusion when resolving .first(). Added unit tests
=> Fix @ resolver to deal with complex objects correctly

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
as per DCR #3089 
if there is not activity.text, or it's empty, AND there is a activity.Value then activity.Value will be used as the value.
=> fallback to .value property if there is no text.

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
ref to this issue: #3344
At first, LG `ActivityFactory` use `MessageFactory.Text()` to generate message activity result from LG output, but `MessageFactory.Text()` would inject `inputhint = expectingInput ` into activity, and the prompt of input relies on this feature.
Then we found there is no reason to add `inputhint` into pure text activity, so we removed it in this pr: #3382. 
At the same time, we should update adaptive inputs to set `inputHint = expectingInput` whenever we are issuing a prompt or reprompt (unrecognized/ invalid prompt).
=> update adaptive inputs to set inputHint = expectingInput 

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/DialogManager.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/DialogStateManager.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/BotStateMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/ConversationMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/UserMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs, libraries/Microsoft.Bot.Builder/BotState.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogManagerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs
* ChangeBotStateMemoryScope to return full BotState object instead of property Fix #3392 
* Change DialogManager to allow alternate dialogStateProperty (for backward compat with custom property names) Fix #3393 
* Removed internal throw for property access lookup (perf enhancement.)
=> Fix BotStateScope to show full botState and give control for dialogState Property name

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
Small change in code, revert behavior for using scope in `CreateOAuthApiClientAsync` per discussions with @lzc850612.
The code this PR is reverting does not exist in the other languages afaik.
=> use standard OAuthScopes in CreateOAuthApiClientAsync

libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryInitializerMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/TelemetryMiddlewareTests.cs
Fixes: #3395 
If `TelemetryLoggerMiddleware` is used and then `CreateConversationAsync()` is called, there are cases where `Activity.From` will be null, which causes things like this to throw:
```csharp
{ TelemetryConstants.FromIdProperty, activity.From.Id },
```
**Changes**:
Adds a few null-conditional operators, where appropriate.
**Testing**:
Added one test which calls `CreateConversationAsync()` while ensuring the `Activity.From` is null.
=> Fix errors when From is null in telemetry

libraries/Microsoft.Bot.Builder.LanguageGeneration/LGParser.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/CustomFunction.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/LGFileTest.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj
support custom function in LG
ref: https://github.com/microsoft/botbuilder-js/pull/1784
=> [LG] support custom function

libraries/Microsoft.Bot.Builder/BotState.cs, tests/Microsoft.Bot.Builder.Tests/BotStateSetTests.cs
=> Added null check and code to return default(T) in GetPropertyValueAsync<T>

libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryInitializerMiddleware.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryInitializerTests.cs
Fixes: #3442 
Similar to [this PR](https://github.com/microsoft/botbuilder-dotnet/pull/3436), but adds a null check I missed (plus an additional test).
From
```csharp
if (items.ContainsKey(TelemetryBotIdInitializer.BotActivityKey))
```
To
```csharp
if (items != null && items.ContainsKey(TelemetryBotIdInitializer.BotActivityKey))
```
=> Add additional null check in Telemetry

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/DialogStateManager.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_NestedMemoryAccess.test.dialog
close #3391 
When we evaluate such expression like "dialog[a].b" with the scope implement by `DialogStateManager`,
The steps to get the result:
1. call DialogStateManager.TryGetValue
2.TransformPath path to get the right format path
3.ResolveMemoryScope to get the memory scope and remaining path
...
The issue occurs in step3, when `dialog['a'].b` comes in, `ResolveMemoryScope`  would separate the path into two parts, first part is `dialog['a']`, and the second part is `b`, but `dialog['a']` is not a valid scope, `dialog` is. 
How to reproduce:
build the below dialog structure:
```
"actions": 
[
{
"$kind": "Microsoft.SetProperty",
"property": "user.name.firstname",
"value": "dialog.jack"
},
{
"$kind": "Microsoft.SetProperty",
"property": "turn.nameproperty",
"value": "name"
},
{
"$kind": …
```
=> fix Dynamic properties do not work

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/ActionContext.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/DebugBreak.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/DeleteProperties.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/DeleteProperty.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EditActions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/IfCondition.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SwitchCondition.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/EntityEvents.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/ITriggerSelector.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/ConditionalSelector.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/FirstSelector.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/MostSpecificSelector.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/RandomSelector.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/TrueSelector.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCondition.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnError.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnIntent.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
- Renamed class and file.
- Cleaned up various variable names.
- Made the context passed into actions a standard DC.
- Updated actions to work against their parent ActionContext for things like sequence manipulation.
=> Renamed SequenceContext to ActionContext

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_AttachmentInput.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_TextInputWithInvalidPrompt - Copy.test.dialog
Fixes #3298
Added logic to `InputAction` that ensures an empty array is provided if `context.activity.attachments` is null.  Also added a unit test to cover `AttachmentInput`.
=> Fixed issue with null attachment arrays in AttachmentInput

build/yaml/botbuilder-dotnet-functional-test-linux.yml
This pull requests fix the YAML for the functional test in unix. The pipeline was failing when running the test `SendDirectLineMessage` because the bot deployed was not working on Azure after the change of the test bot using net core 2.1 to net core 3.1.
We added an argument to the publish step of the file `botbuilder-dotnet-functional-test-linux.yml` so the bot used in the functional test can be deployed properly and be used by direct line.
Below you can see the test failing in previous runs and the test passing in a new one after the change.
=> Fix YAML file for functional-test-unix

FunctionalTests/Skills/DialogToDialog/DialogRootBot/Dialogs/MainDialog.cs, FunctionalTests/Skills/DialogToDialog/DialogRootBot/SkillConversationIdFactory.cs, libraries/Microsoft.Bot.Builder.Dialogs/BeginSkillDialogOptions.cs, libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/SkillDialogOptions.cs, libraries/Microsoft.Bot.Builder/BotAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/SkillDialogTests.cs
=> Adds support for buffered replies to skill dialog

libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFile.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGTemplate.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/2.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/LGFileTest.cs
Originally, the Body of LGTemplate presents the first line except for comments, to the last line except for comments. 
for example:
```
> comment1
> comment2
- hi
> comment3
- hi
```
originally Body of template  t1 is 
```
- hi
```
After this pr, the body of the template presents from the first of template content to the last line before the next template (or end of file). 
So, the body of tempale t1 is
```
> comment2
- hi
> comment3
```
Additionally, allow empty comments.
=> Update LG template content range

libraries/AdaptiveExpressions/Constant.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Close #3498
The Expression ToString result should be re-parsed correct and have the same evaluate result as original expression.
For some reason, the expression ToString result may not be exactly the same as the original one. because:
1. float/double format data.  for example, 1.0 is a float/double, the stringify result is "1" or other formats, not the same with 1.0 maybe
2. for the sequence operator, for example, add(1, 2, 3), the expression ToString result is :
"1 && 2 && 3", if we construct with this string, we could get the new expression: 
"(1 && 2) && 3", because "&&" in the expression is a Binary operator. The two string results are not literally equal, but the meaning is the same.
=> Update Constant Expression ToString method

FunctionalTests/Skills/DialogToDialog/DialogRootBot/Dialogs/MainDialog.cs, FunctionalTests/Skills/DialogToDialog/DialogRootBot/Dialogs/TangentDialog.cs, FunctionalTests/Skills/DialogToDialog/DialogSkillBot/Bots/SkillBot.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
Fixes #3506 
Added RepromptDialogAsync and ResumeDialogAsync to SkillDialog.
Moved skill request handling logic into Dialog.RunAsync
Updated sample DialogToDialog sample to handle interruptions
=> Added interruptions support to SkillDialog

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/LogAction.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/UpdateActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/QnAMaker/QnAMakerDialog2.cs
ref： #2783
add LG telemetry client.
=> Add LG telemetry

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
There is code in the OAuthPrompt to change the sign in action of an OAuthCard to "openUrl" instead of "signin" for skills. This really only should be done for the emulator, as it impacts how WebChat handles the card.
=> Skill OAuth only change card action for emulator

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/CancelAllDialogs.cs, libraries/Microsoft.Bot.Builder.Dialogs/Recognizer.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_CancelAllDialogs.test.dialog
#3534 
Fixes CancelAllDialogs.eventName and eventValue is valid to be null
=> Add unit test for CancelAllDialogs and fix eventName and eventValue null

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Skills/SkillHttpClient.cs
fix lack of a generic typed method for posting activities to skills
=> fix lack of a generic typed method for posting activities to skills

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Skills/SkillHttpClient.cs
Cherry-picks https://github.com/microsoft/botbuilder-dotnet/pull/3539 to the `4.8` branch.
* fix lack of a generic typed method for posting activities to skills
* remove duplicated code
Co-authored-by: Swagat Mishra <swagatm@microsoft.com>
=> [4.8 cherry-pick] fix lack of a generic typed method for posting activities to skills 

libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
Fixes #3541 
Added check to only cancel dialogs in RunAsync when EoC comes from a parent bot (root or skill).
The issue was that this affected part of the code was being triggered when a skill responds with an EoC to a caller (EoCs are routed back to the pipeline in SkillHandler). 
This PR also applies the urn format to CallerId as per [OBI Spec](https://github.com/microsoft/botframework-obi/blob/master/protocols/botframework-activity/botframework-activity.md#bot-calling-skill)
=> EoC should only be handled when coming from parent in RunAsync

libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
* Added check to only cancel dialogs in RunAsync when EoC comes from a parent bot (root or skill).
* Applied URI prefix to caller ID as per OBI spec
https://github.com/microsoft/botframework-obi/blob/master/protocols/botframework-activity/botframework-activity.md#bot-calling-skill
(cherry picked from commit 373096310de1272ac1f26f2045448b3f40f4ff68)
=> EoC should only be handled when coming from parent in RunAsync (#3540)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/PathResolvers/AliasPathResolver.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_SetProperty.test.dialog
Fix #3545 . 
Our property assignment action, SetProperty, SetProperties, and EditArray are not working when the property contains dynamic values to evaluate, and the dynamic value is reference using a shortcut, for example
user[$mylist].todo // not working 
user[dialog.mylist].todo // working
The root cause is our path resolver assuming alias (#, $) assume this alias at beginning, and do a full replace at the beginning, which cause broken path if alias is in middle. 
The tranforming behavior is broken
`user[$mylist].todo => dialog.mylist].todo` // user[ is dropped
`turn.recongized["$instance"] => dialog.instance"]` // what's before $ is totally dropped
the fix is to enforce the transform only deals the alias at beginning.
=> Fix path resolver not working when alias in middle

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
When OAuthAppCredentials is passed in as part OAuthPromptSettings, do not set SignInLink to be empty as Emulator/other first party channels will ignore this and get a SignInLink without the additional OAuthAppCredentials setting.
=> [OAuth]do not set signInLink to empty when OAuthAppCredentials is set

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
[OAuth]do not set signInLink to empty when OAuthAppCredentials is set
=> [Cherry-pick from master][OAuth]do not set signInLink to empty when OAuthAppCredentials is set

libraries/AdaptiveExpressions/ExpressionFunctions.cs, libraries/AdaptiveExpressions/ExpressionType.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4, tests/AdaptiveExpressions.Tests/BadExpressionTests.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
1. Remove Array prebuilt-function. You can use createArray funtions.
2. Type Checking prebuilt functions:
isString, isInteger (*), isFloat, isArray, isObject, isDateTime (**), isBoolean
Notes:
* In JavaScript, when you call isInteger(1.0), it will true, so isFloat(1.0) will be false.
** isDateTime can will only return true when a ISO TimeStamp string is parsed
=> Improve Expression with adding type checking functions

libraries/Microsoft.Bot.Builder/ActivityFactory.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs
close: #3383
Remove the type checking and return the actual object if no type was found or type definition does not map to a supported activity type
So, if the LG output is `{"key": "value"}`, and no LG type(`lgType`) in the properties, string Activity would be returned. 
if LG output contains `lgType` property, but it does not map to any supported types (activity, xxxCard, cardaction, adaptivecard, attachment. etc.), a warning would be throw shows that the current type is not supported. And finally, the text activity would be the result.
=> [activityfactory] Improve missing type error

libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/MultiLineExpr.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/MultiLineExprError.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
fixes: #3466
Now user can write there expressions in multiple lines, like:
\# definition2
\- this is book list: ${join(createArray("Ender's Game",
"Dune")
, ", ")}
LG will treat all the content after ${ as an expression until reaches a }.
=> Add support of multi line definition of expression in LG

libraries/AdaptiveExpressions/Memory/SimpleObjectMemory.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Loose a restriction on path introduced in https://github.com/microsoft/botbuilder-dotnet/pull/3226. 
To support variable path like "$index"
=> Remove unnecessary restrication on memory path

libraries/AdaptiveExpressions/Expression.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/CustomFunction2.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Make customized function in LG and expression easier by accepting just a lambda. 
At the cost of expose FunctionTable instead of a generic IDictionary.
Now you can do
```C#
Expression.Functions.Add("contoso.sqrt", (args) =>
{
object retValue = null;
if (args[0] != null)
{
double dblValue;
if (double.TryParse(args[0], out dblValue))
{
retValue = Math.Sqrt(dblValue);
}
}
return retValue;
});
```
to add a new function
=> make custom function easier

libraries/Microsoft.Bot.Builder/AdapterExtensions.cs
Related to Issue #3527.
The warning on Recognizer.cs was fixed in PR #3536.
=> Fix AdapterExtensions' ambiguous references

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ChoiceInput.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ConfirmInput.schema
The Composer UI will use the title if present when presenting options to the user. Currently, for choices the options are `array`, `array`, and `expression` which is hard to disambiguate.
=> add title to choices and confirmChoices schema

libraries/Microsoft.Bot.Builder.LanguageGeneration/Template.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Originally, we treat LG file as the combination of templates and use empty string as the separator.
From now on separator "\r\n" would be used.
So, if we update a template with the body "- A", we would always get the body "- A" but not "-A\r\n" in any case. This idempotent relationship will greatly increase robustness and consistency
=> Make the CRUD of the template consistent

libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplatesParser.cs
The import chain of LG file is like a graph, there may be various reference logic.
Antlr's parse takes a lot of time in it, If LG SDK can cache the results of Antlr parse(single call life cycle), the performance will be greatly improved.
After experiments, it can save more than half of time for complex lg call chain.
issue link: https://github.com/microsoft/BotFramework-Composer/issues/2374
=> cache Antlr parse result

libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FileResource.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProvider.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProviderExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceTests.cs
#3641 DCR
* Add fallback for string reference binding "foo.xxx" => looks for "foo.xxx.dialog" and if not found attempts to bind to "foo.xxx",
The point of these changes is that it allows new extensions to be added to the resource explorer, and if there are object bindings for those extensions they will be used.  If a file is valid json but NOT a dialog file (Such as .schema files) then they can be used directly without having to have .dialog extension.
For example, this captures the 2 scenarios:
1. **"recognizer":"foo.lu"** => will bind to attempt to bind to "foo.lu.dialog", and if lubuild has run find it. if there is no .dialog it will attempt to load the foo.lu file and appropriately fail.
2. **"schema":"foo.schema"** => will attempt to bind to foo.schema.dialog, and then fall back to …
=> DCR: Change .dialog file string resource lookup to fallback to non-dialog files.

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
Interface looks like it changed name but the name in the error message didn't.
=> Fix the interface name in the error message.

libraries/Microsoft.Bot.Builder.LanguageGeneration/Extensions.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Template.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
In C#, LG use `StringReader.ReadLine` to read the content line from LG file, but there may exist some points that do not match the LG's requirements.
In C# doc: https://docs.microsoft.com/en-us/dotnet/api/system.io.stringreader.readline?view=netframework-4.8#remarks
> The string that is returned does not contain the terminating carriage return or line feed. The returned value is null if the end-of-stream marker has been reached. That is to say, if there is nothing between the last line read and the end-of-stream marker, the method returns null.
So, the trailing newlines would be dropped when parsing the text with `ReadLine` method.
if the template is:
```
- hi
```
and do some CRUD operation on this template, finally, we would get the template body:
```
- hi
```
the tailing newlines are …
=> [LG] Fix missing trailing line break with String.Readline()

libraries/AdaptiveExpressions/Constant.cs, libraries/AdaptiveExpressions/Expression.cs, libraries/AdaptiveExpressions/ExpressionFunctions.cs, libraries/AdaptiveExpressions/parser/ExpressionParser.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
fixes #3598 
use CultureInfo.InvariantCuture to make sure the cultureInfo of user's local machine won't affect the outcome of expresssion functions.
For example, in de-DE 
1.0 will be parsed to 10. 
03/12/2012 will be parsed to03,12,2012
=> Fix local culture info changes the result of parsing number and datetime

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/DialogManager.cs
Before, Bot State will be the state of the out-most dialog, which will be inconvenient:
For example, in this dialog
Trace will be
While Bot State will be 
After this, Bot State will be same as trace
=> use inner most dc for sending Bot State

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateErrors.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs
1. Originally LG use the end white space of error message to separate the error layer to make it more readable.
But it is strange to have such message. So, we concat the error stack at runtime with white space.
2. There are many duplicate code to build the stack error message,  extract them make the code clean and pure.
=> [LG] Refine Error message and remove duplicate code

libraries/AdaptiveExpressions/Constant.cs, libraries/AdaptiveExpressions/Expression.cs, libraries/AdaptiveExpressions/ExpressionFunctions.cs, libraries/AdaptiveExpressions/Extensions.cs
close: #3615
Add `Array` return type to make array type errors be discovered during the static check period.
For example, before :
```
var expr = Expression.Parse("skip(1, 1)"); // it's ok
var result = expr.TryEvaluate(null); // throw runtime exception, skip can not applied on int
```
After:
```
var expr = Expression.Parse("skip(1, 1)"); // 1 is not a valid array
```
why does `Expression.Parse("skip(1, 1)")` not throw exception before.
If the method accepts `Object` type, e.g. `count` method accepts one parameter, which could be string or array. If the param is a string, return string length, and if the param is an array, return the array size.
So, we can only mark the param `object`, any return type here is ok during the static checker period.
Same logic with `skip(1, 1)`, `skip` accepts …
=> [Expression] Add array return type

libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/Expand.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
fix #3523.
For issue: Achieve the correct result for foreach expansion. ref: #3238. It is R10 item and will be fixed in another PR.
=> refactor expander

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEach.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachPage.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.EditArray.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.Foreach.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.ForeachPage.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.DateTimeInput.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.InputDialog.json, schemas/sdk.schema, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_ForeachPage_Nested.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_Foreach_Nested.test.dialog
=> Fix foreach issue and update some schema examples

libraries/Microsoft.Bot.Builder/TelemetryConstants.cs, libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs
Addresses #1574 in JS repo (https://github.com/microsoft/botbuilder-js/issues/1574)
Telemetry logger will now include the collection of any attachments sent with the activity, if the LogPersonalInformation flag is set to true.
=> Update telemetry logger to include attachments

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
This fixes issue #3590, by returning MicrosoftAppCredentials.Empty when AppId is set to null or empty spaces.
=> Replace null check with string.IsNullOrWhiteSpace()

libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs, libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentials.cs
This parameter enables application developers to achieve easy certificates roll-over in Azure AD: setting this parameter to true will send the public certificate to Azure AD along with the token request, so that Azure AD can use it to validate the subject name based on a trusted issuer policy. This saves the application admin from the need to explicitly manage the certificate rollover (either via portal or powershell/CLI operation)
=> [Certificate Authentication] Expose sendX5c parameter

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/DialogManager.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/Skills/SkillHandler.cs, libraries/Microsoft.Bot.Schema/CallerIdConstants.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogManagerTests.cs, tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs, tests/Microsoft.Bot.Builder.Tests/Skills/SkillHandlerTests.cs
Updated callerId assignment to be taken from claims after auth rather than from the activity.
Updated related tests.
Applied temporary fix for the new callerId log for DialogManager (final fix will be done after refactoring to match DialogExtensions.RunAsync logic).
=> Updates for CallerId

libraries/AdaptiveExpressions/ExpressionFunctions.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
closes: #3768 
In this PR,
setProperty({}, 'name', user.name).name will return null when user.name is null. It won't throws exception.
Also, create object with {} syntax,
{name: user.name}.name will have the same behavior as setProperty function.
=> [Expression] Enable setProperty function creating object handling null correctly

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/TemplateAsFunction.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
close: #3755 
Originally, we use exact match of returntype to validate the correctness of function parameters.
But, then Expression achieved then ability to support composite types. So, LG/Expression should change the return type comparison, as long as they have the intersection of the same return type, it is correct in the static checker stage.
=> Change Comparisons to ReturnType of 'template' function use bit operators

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpClientTests.cs
Fixes: #3684
If Activity.Recipient is null, this can cause skills to throw errors as the Recipient field is expected. This PR sets Recipient to an empty ChannelAccount if the value is null.
https://github.com/microsoft/botframework-sdk/issues/5785
Added positive and negative tests for `BotFrameworkHttpClient.PostActivityAsync()` changes
=> add recipient in BotFrameworkHttpClient.PostActivityAsync if value is null

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
=> set recognized properties even if interruption is off

libraries/Microsoft.Bot.Builder.LanguageGeneration/MultiLanguageLG.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/MultilanguageLGTest.cs
close: #3551 
- add a `defaultLanguages` param format list which can replace "" as default
- sync with latest SDK how language policy is updated, "de-de" => "de-de", "de"
- replace `EvaluateText` with `Evaluate`
- support passed in parsed Templates instead of just file paths, `Dict<string, Templates>`
=> [LG] re-do multiLingualLg

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs, tests/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj, tests/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3769 TestBot.Json broken in master
https://github.com/microsoft/botbuilder-dotnet/pull/3711 introduced a cache for json converters, in which json converters are created once when converting first json, and reused in later json conversion. 
The issue is, those json converters are stateful, in which SourceContext captured the state (the call stack).  In order to make it work as expected, the call stacked must be initialized with a SourceRange pushed to bottom of the stack, and this initialization only happens when creating those converters. 
So reusing the converters will not re-initializing the state, in this specific case, will not push a SourceRange into stack.  Then all the following source range registering will not get a path …
=> Revert the reusing of json converters

build/yaml/ci-test-steps.yml, tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobStorageTests.cs, tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobTranscriptStoreTests.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionStorageTests.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs, tests/Microsoft.Bot.Builder.Azure.Tests/StorageEmulatorHelper.cs
Running storage in cloud is not being reliable.  This consolidates the code in the unit tests so we can disable if running on build server.
=> make running storage emulators disabled on build server

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCondition.cs, libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogEvents.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogInstance.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs, libraries/Microsoft.Bot.Builder.Dialogs/WaterfallDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogContainerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogSetTests.cs
* Add **dialoginstance.version** property for saving version string between turns.
* Add **dialog.GetVersion()** which allows a dialog to return unique string for a configuration
* Add **DialogSet.GetVersion()** which will be different if collection of dialogs and the GetVersion() have changed.
* Add **DialogContainer.GetInternalVersion()** - which detects at the container level internal changes for children.
Add **DialogContainer.CheckForVersionChange()** - which is called on BeginDialog/ContinueDialog/ResumeDialog() to detect that a dialogContainer has changed
* Add DialogEvents.VersionChanged event which is fired when change is detected
* Implement AdaptiveDialog.GetInternalVersion() to detect triggers changes, schema changes as well as dialog changes
Unit tests, etc.
=> [PORT] Bot Change Detection

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/CodeAction.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EditActions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/IfCondition.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperties.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/UpdateActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DialogDebugAdapter.cs, libraries/Microsoft.Bot.Builder.Dialogs/Debugging/NullDialogDebugger.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs, libraries/Microsoft.Bot.Builder/PathUtils.cs, libraries/Microsoft.Bot.Builder/StringUtils.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/TelemetryBotIdInitializer.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogContainerTests.cs, tests/Microsoft.Bot.Builder.TestBot.Json/CustomSteps/JavascriptAction.cs, tests/Microsoft.Bot.Builder.Tests/StringUtilsTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryInitializerTests.cs, tests/tests.schema
* Replace random copies of code with StringUtils.
* truncate long computed ids
* unit tests.
=> Add StringUtils class to BotBuilder

libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs
Fixes #3814 - null reference exception when logging telemetry and [From] property is null.
=> Check for null on Activity.From when logging telemetry

libraries/Microsoft.Bot.Builder/StringUtils.cs
close: #3825
Support `null` string in `Ellipsis` and `Hash` method
=> add null string support in StringUtils

libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
Added code to ensure that InvokeResponse values are deserialized as InvokeResponse (they come as JObject in C# by default)
=> Adds serialization fix for #3833

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs
fixes #3854 
* cleaned up CreateInnerDC so it is applied consistently
* changed WaterfallStepContext ctor to pass in parent dc.
=> Fix WaterfallStepContext to use parent dc properly

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/MultiLanguageGeneratorBase.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/TemplateEngineLanguageGenerator.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguageGenerator.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguageGeneratorExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/TextTemplate.cs, libraries/Microsoft.Bot.Builder/ActivityFactory.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs
fixes #3558
LG returns an object when binding to herocards/activity.
object was being serialized to JSON, then run through code to detect if it's JSON and convert it to an object.  
This was all because LanguageGenerator.Generate() had signature of string for the return type.
Changes
* Changed Generate() to return an object
* Removed goofy code with double-deserialization
* Updated unit tests to not do goofy double-deserialization
* also made LGExtensions class name match other classes in system.
=> Fix signature of LanguageGenerator base class

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/CrossTrainedRecognizerSet.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/MultiLanguageRecognizer.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RecognizerSet.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/ValueRecognizer.cs, libraries/Microsoft.Bot.Builder.Dialogs/Recognizer.cs
fixes #3557
recognizers were not capturing file location when instantiated via code, updated constructors to do appropriate goo.
=> added debug signature to recognizers

tests/Microsoft.Bot.Streaming.Tests/NamedPipeTests.cs
Closes #3861 
Tested using VSTest under netcore 2.1 and 3.1, now passes 100% of the time, vs around 50% of the time previously. Also now asserts the connection has been established and then torn down, to be sure the state has changed.
=> Improve disconnect test so it actually tests disconnect.

libraries/AdaptiveExpressions/ExpressionProperties/ArrayExpression.cs, libraries/AdaptiveExpressions/ExpressionProperties/StringExpression.cs, tests/AdaptiveExpressions.Tests/ExpressionPropertyTests.cs
Fixes #3868 
* If someone passes in null array, implicit assignment was attempting to .ToList() it.  Changed use IEnumerable and not try to use .ToList() which means null flows through correctly.
* Add more unit tests to verify default(T) behavior around implicit assignment.
=> Allow default(array) implicit assignment

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.SkillDialog.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Skills/AdaptiveSkillDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/BeginSkillDialogOptions.cs, libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/SkillDialogOptions.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/SkillDialogTests.cs
Moved OAuth ConnectionName from BeginSkillDialogOptions to SkillDialogOptions.
Updated AdaptiveSkillDIalog to expose a connectionName and use it.
Updated tests and schema.
=> SkillDialogUpdates for ConnectionName.

libraries/AdaptiveExpressions/ExpressionFunctions.cs, libraries/AdaptiveExpressions/ExpressionType.cs, tests/AdaptiveExpressions.Tests/BadExpressionTests.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Refers to the first question in https://github.com/microsoft/botbuilder-dotnet/issues/3873
formatNumber(num1, num2), takes two arguments, the first one should be a numeric value, and the second one should be an integer. The returned value is a string
Examples
formatNumber(12.123, 2) =  "12.12"
formatNumber(20, 2) =  "20.00"
formatNumber(1.555, 2) = "1.56"
formatNumber(12.123, 4) = "12.1230"
Added formatEpoch and formatTicks. 
formatEpoch(1521118800) -> 2018-03-15T13:00:00.000Z
formatTicks(637243624200000000) -> 2020-05-06T11:47:00.000Z
Removed ticks functionality from formatDateTime.
Fixed an issue where JSON conversion would truncate 64 bit values and doubles.
=> [Expression] Add formatNumber, formatEpoch and  formatTicks as prebuilt functions

libraries/AdaptiveExpressions/ExpressionFunctions.cs, libraries/AdaptiveExpressions/ExpressionType.cs, tests/AdaptiveExpressions.Tests/BadExpressionTests.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
cherry pick  formatNumber, formatEpoch and  formatTicks related commits
=> [Cherry-pick] formatNumber, formatEpoch and  formatTicks as prebuilt fumctions

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Skills/AdaptiveSkillDialog.cs
Override AdaptiveSkillDialog.OnComputeId as per https://github.com/microsoft/botbuilder-js/pull/2196 (with minor changes to mirror other OnComputeId overrides in C#)
=> override OnComputeId in AdaptiveSkillDialog

.gitignore, libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserActivity.cs, libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs, libraries/Microsoft.Bot.Schema/ActivityEx.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/DebugComposer.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Startup.cs
fixes #3908 
* Add PreBubbleEvent handler to decide whether to allow interruptions or not
* added ContinueDialog override to detect we have been interrupted and end the dialog if we have
* refactored some code to cache results computed in PreBubbleEvent and capture suggested questions.
* Added general purpose unit test for debugging a composer bot with all of the QnA/LUIS assets in place.
=> Fix QnAMakerDialog to handle interuption scenarios

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Observers/CycleDetectionObserver.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_CancelAllDialogs_DoubleCancel.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs, tests/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj, tests/Microsoft.Bot.Builder.TestBot.Json/Samples/DoubleReference/DoubleReference.dialog, tests/Microsoft.Bot.Builder.TestBot.Json/Samples/DoubleReference/sub0.dialog, tests/Microsoft.Bot.Builder.TestBot.Json/Samples/DoubleReference/sub2.dialog, tests/Microsoft.Bot.Builder.TestBot.Json/Samples/DoubleReference/sub3.dialog
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3913
The `Add()` method of `DialogSet` has a mechanism for supporting multiple dialogs with the same id, which is adding a unique suffix for internal book keeping. 
There is a bug however, if the same exact dialog is added multiple times because it is referenced by multiple dialogs. In this scenario, this is not a name collision, we are just adding the same dialog. But still we are assigning a different Id and treating it as different which brings downstream incorrect behaviors.
The fix here is to more precisely detect whether this is a name collision, by checking whether the dialog that is being added, was already added. If that is the case, we don't assign a new id and just leave things as they are.
Note that this is not a …
=> DialogSet.Add: Unique dialog ids for name collisions but not for reference collisions

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
* Do NOT call TeamsInfo.getMember for the bot
* Add TestConversationUpdateBotTeamsMemberAdded
=> Do NOT call TeamsInfo.getMember for the bot cherry-pick from 4.9 (#3923)

build/yaml/botbuilder-dotnet-sign.yml
The signed build is no longer used for running functional tests.
=> Remove functional test setup from the signed build.

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj, tests/Microsoft.Bot.Builder.TestBot.Json/Samples/DoubleReference/sub2.dialog, tests/Microsoft.Bot.Builder.TestBot.Json/testbot.schema, tests/tests.schema
They stopped updating nuget.client in 2017...it was replaced with **nuget.packaging** which is many versions past the one we were using.
Worse, **nuget.client** had a bad prerelease package pushed in 2017 that breaks installation of adaptive into linqpad because it has a circular dependency chain.
* also fixed .dialog files which were not compliant to schema (missing actions node)
=> nuget.client package reference is obselete, replaced with nuget.packaging

build/yaml/botbuilder-dotnet-ci-mac.yml, build/yaml/botbuilder-dotnet-ci.yml
These builds are specified in our github required status checks. Github status checks do not support path-based includes or excludes, so we cannot use them in the yaml.
=> Remove path excludes from triggers

libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogManagerTests.cs
Fixes #3956
- Added check to ensure we don't send EoC when a skill is done and we are at the root bot.
- Updated tests to handle this case and removed duplicated test after refactoring.
- Fixed some typos and trace message names.
=> Fixes BadRequest message in Teams

libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogManagerTests.cs
* Added check to ensure we don't send EoC when a skill is done and we are at the root bot.
Updated tests to handle this case and removed duplicated test after refactoring.
Fixed some typos and trace message names.
=> Fixes BadRequest message in Teams (#3966)

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs
See parent PR: https://github.com/microsoft/botbuilder-js/pull/2246
Some of the prompts break if user uploads an attachment instead of responding with text because of some of the `string` methods that get called on `activity.text` (which doesn't exist if an attachment is sent).
Add some variation of
```csharp
if (string.isNullOrEmpty(turnContext.Activity.Text)) {
return Task.FromResult(result);
}
```
to:
1. ChoicePrompt
2. DatetimePrompt
3. NumberPrompt
4. ConfirmPrompt
I also renamed `message` to `utterance` to be more in line with other prompts.
The original issue was only for DatetimePrompt, but I added the other two. Other prompts didn't seem relevant for this.
=> Hardened prompts

build/yaml/botbuilder-dotnet-ci-mac.yml, libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EnterpriseChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3961
=> Auth: Tighten JWT validation of channel-issued tokens with certificate signature

build/yaml/botbuilder-dotnet-ci-mac.yml, tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
This means test runs can uniformly use "TestCategory" for filtering both xUnit and MSTest tests.
=> Change xUnit test attribute to fit "TestCategory" filtering

build/yaml/botbuilder-dotnet-ci-mac.yml, libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EnterpriseChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3982
=> [Cherry pick from 4.9] Auth: Tighten JWT validation of channel-issued tokens with certificate signature

README.md
Now pointing to blob storage in Bot Connector Internal subscription.
=> Fix broken dependency graph link

libraries/AdaptiveExpressions/ExpressionFunctions.cs, libraries/AdaptiveExpressions/ExpressionType.cs, tests/AdaptiveExpressions.Tests/BadExpressionTests.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
close: #3787 
Add `EOL()` builtin function which supplies the line ending for the current OS.
=> Add EOL builtin function

build/yaml/botbuilder-dotnet-ci-mac.yml, tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
This merges to master. The previous PR of the same name was for merging to 4.9.
This means test runs can uniformly use "TestCategory" for filtering both xUnit and MSTest tests.
=> Change xUnit test attribute to fit "TestCategory" filtering 

libraries/AdaptiveExpressions/ExpressionFunctions.cs
fixes: #3955 
replace $"{expr} can't evaluate." with more detailed messages based on the context of some pre-built functions
=> Change error messages in pre-built functions to make the descriptions more accurate

libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs
* disable throwing exception if dialog change not handled
* remove trace from versionChanged
Fix #4013
=> Don't throw exception on unhandled VersionChangeDetected event (#4000)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
Calling an event driven dialog did not work because passed in options would override the initial setup of dialog memory.
=> Allow calling an event driven dialog

libraries/AdaptiveExpressions/Memory/ReflectionMemory.cs, libraries/AdaptiveExpressions/Memory/SimpleObjectMemory.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/CustomizedMemory.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/EvaluationTarget.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/RecursiveTemplate.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/LoopDetected.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
close: #4004
Modify the template loop detection to enable the recursive functions.
The loop exception will only be triggered if both the template name and the parameters are same.
=> Refine template loop detection to enable recursive functions

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/SlackClientTest.cs
If the server validates that the timestamp is recent to prevent replay attacks, then it would fail.
This PR changes the integration test to simulate what Slack would do.
=> Slack sets timestamp as unix time in seconds

libraries/Microsoft.Bot.Builder.LanguageGeneration/Diagnostic.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/ErrorListener.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateErrors.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplatesParser.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs
close: #3906
- Add more context info into some diagnostic errors.
- Add file path info into diagnostic errors.
|Item | Before | After|
|-- | -- | --|
|Invalid template name | Invalid template name. Template names can only contain letter... | Invalid template name: '{invalidName}'. Template names can only contain letter...|
|Invalid structure body | Invalid structure body. Body can include... | Invalid structure body: '{invalidBody}'. Body can include...|
|Syntax Error | Unexpected Content. Expecting a comment, template def... | {unexpectedContent}. Expecting a comment, template def...|
|Invalid Parameter | Invalid parameter name. Parameter names can ... | Invalid parameter name: '{invalidParameter}'. Parameter names can|
|Diagnostics | [Error] line 3:0 - line 3:8: [template]Invalid …
=> Enrich LG error message

libraries/Microsoft.Bot.Builder.Dialogs.Debugging/CodeModels/CodePoint.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DialogDebugAdapter.cs
Following changes:
* support expression in debug evaluate
* output error for expression grammar
* output error for evaluation process
* treat null as normal output instead of error (since value could be null)
Blockers:
* https://github.com/microsoft/botbuilder-dotnet/issues/3970 fixes debugging
* https://github.com/microsoft/botbuilder-dotnet/issues/3969 then we could tell if it is a null value or non-exist value
=> support expression in debug evaluate

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendActivity.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_SendActivity.test.dialog
close: #4001
```
{
"$kind": "Microsoft.SendActivity",
"activity": {
"$kind": "Microsoft.StaticActivityTemplate",
"activity": {
"type": "message",
// only channel data property, no text and speak.
// This one should be valid and be sent to the channel.
"channelData": {xxxx}
}
}
}
```
=> Allow the activity only with channelData property in sendActivity action

libraries/Microsoft.Bot.Connector/AttachmentsEx.cs, libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs, libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs, libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConfiguration.cs, libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EndorsementsRetriever.cs, libraries/Microsoft.Bot.Connector/Authentication/EnterpriseChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/Retry.cs, libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/ThrottleException.cs, libraries/Microsoft.Bot.Connector/Authentication/TimeSpanExtensions.cs, libraries/Microsoft.Bot.Connector/Channels.cs, libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Connector/OAuthClientConfig.cs, libraries/Microsoft.Bot.Connector/OAuthClientOld.cs
Addresses part of #2367 
- Enables FxCop Analyzer for the Connector library and addressed violations.
- Marked OAuthClientOld as obsolete.
- Marked a lot of private methods in AdalAuthenticator as statics (that's the big diff here)
=> Enables FxCop Analyzer for the Connector library

tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj, tests/Microsoft.Bot.Builder.Tests/Skills/SkillHandlerTests.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityExtensionsTests.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerBadRequestTests.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerHidingTests.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerNotImplementedTests.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
Migrating teams test to Xunit. Let me know if this all looks correct before I start the mass replication.
=> Migrates Tests tests to Xunit

build/yaml/botbuilder-dotnet-ci.yml
Partially addresses: #4055
Build [137843](https://fuselabs.visualstudio.com/SDK_Public/_build/results?buildId=137843&view=results) for these changes has a total duration of 21min and 16s:
The last successful build ([137707](https://fuselabs.visualstudio.com/SDK_Public/_build/results?buildId=137707&view=results)) took 27min 12s to complete:
___
This PR speeds up the build by disabling the auto-injected "Run Codesign Validation" task, which was running at the end of our stages.  This task automaically fetches an internal tool for the codesign validation step and applicable .NET Core SDKs before eventually skipping the workflow, a process that takes around one minute.
Searching for the variable name, there were other Microsoft projects that also disabled this task as it was N/A. …
=> disable unused codeSignValidationInjection task in main CI

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisExtensions.cs
User would like to publish the luis to mooncake.
eg. chinaeast2 region is targeting https://chinaeast2.api.cognitive.azure.cn instead of https://${region}.api.cognitive.microsoft.com.
https://github.com/microsoft/BotFramework-Composer/issues/2986
=> Support luis customized endpoint

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
Fixes #4124 
Ensures content type check within the adapter doesn't fail if encoding info is included in the header.
=> Make content type check more robust

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV2.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV3.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisOracleTests.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisV3OracleTests.cs
Fixes #4117 
Luis Recognizer returns an intent of string.empty with a perfect score of 1.0.  This messes up logic downstream in RecognizerSet because it thinks it has a perfect intent.
* Changed LuisRecognizer to return empy RecognizerResult (no intents or entities) when there is no utterance.
Changed RegexRecognizer to behave just like LuisRecognizer so that ValueRecognizer tests are valid check.
=> Fix LuisRecognizer to not return intents if there is no utterance

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/ExpandText.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
small fix. Fix `expandText` returntype error.
=> fix expandText return type error

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapterOptions.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/AttachmentPayload.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookAttachment.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookBotUser.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookEntry.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookPostback.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookQuickReply.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookRecipient.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookResponseEvent.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookResponseOk.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/FacebookPassThreadControl.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/FacebookTakeThreadControl.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/FacebookThreadControl.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/HandoverConstants.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Templates/Button.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Templates/DefaultAction.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Message.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookAdapterTests.cs
Contributes towards #3388 
- Update the Facebook Adapter to take adapter options by default, with an optional param for overriding the client used.
- Updated code docs and removed error / warning supression.
- Updated unit tests.
=> Updates to Facebook Adapter

specs/DailyBuildProposal.md
Part of #4114. 
Spec / document detailing changes around how daily builds, weekly builds, and final versions are created, versioned, and pushed to package repositories. 
The summary:
1. Copy with the ASP.Net Core team is doing where possible
2. Push daily builds to Azure Devops
3. Push a weekly build to exercise our release pipeline
4. Clearly define use of tags (-preview, -rc)
=> Added initial cut at daily build spec

libraries/Microsoft.Bot.Schema/CardEx.cs, tests/Microsoft.Bot.Schema.Tests/CardExTest.cs, tests/Microsoft.Bot.Schema.Tests/Microsoft.Bot.Schema.Tests.csproj
Fixes #4040
- Add the **_ToAttachment_** method for OAuthCard in _CardEx_ class.
- Add unit tests for all the ToAttachment methods.
In the image below we can see the [CardsBot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/06.using-cards) sample using an OAuthCard as an attachment.
=> Add ToAttachment method for OAuthCard

FunctionalTests/ExportedTemplate/template-with-preexisting-rg.json, FunctionalTests/ExportedTemplate/template.json
This fixes the Windows functional test error "Assert.AreEqual failed. Expected:<Echo: Testing Azure Bot GUID: d882954f-e6dc-4c84-b370-60d146e4ebdc>. Actual:<Where would you like to travel to?>.".
=> Change deployment template endpoint to .../api/mybot from .../api/messages

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/CrossTrainedRecognizerSet.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/CrossTrainedRecognizerSetTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/CrossTrainedRecognizerSetTests/CrossTrainedRecognizerSetTests_Empty.test.dialog
Fixes #
We plan to set default recognizer in composer as Luis+QnA CrosstrainedRecognizer. 
And it will fit into different recognizer types by the .lu/.qna content.
Recognizer: "dialogname.lu.qna"
dialogname.lu.qna,dialog will be generated as the following rule:
.lu and .qna both not empty =>
```
{ 
"$kind": "Microsoft.CrossTrainedRecognizerSet" 
recongizers:[ 
"dialogname.lu", 
"dialogname.qna” 
] 
} 
```
.lu and .qna both empty =>
```
{ 
"$kind": "Microsoft.CrossTrainedRecognizerSet" 
recongizers:[ 
] 
} 
```
.lu empty =>
```
{ 
"$kind": "Microsoft.CrossTrainedRecognizerSet" 
recongizers:[ 
"dialogname.qna” 
] 
} 
```
.qna empty =>
```
{ 
"$kind": "Microsoft.CrossTrainedRecognizerSet" 
recongizers:[ 
"dialogname.lu"
] 
} 
```
This change is to support the empty recognizer scenario in …
=> Add empty recognizer support for CrosstrainedRecognizer (composer scenario)

libraries/AdaptiveExpressions/ExpressionProperties/StringExpression.cs, libraries/AdaptiveExpressions/ExpressionProperties/ValueExpression.cs, tests/AdaptiveExpressions.Tests/ExpressionPropertyTests.cs
Fixes #4192 
When encoding a string as an expression we need to properly handle slash.
* tests updated to validate round-trip slashes
=> properly escape slashes in constant strings with StringExpression/ValueExpression

libraries/Microsoft.Bot.Configuration/BotConfigurationExtensions.cs, libraries/Microsoft.Bot.Configuration/EncryptUtilities.cs, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, libraries/Microsoft.Bot.Configuration/ServiceTypes.cs, libraries/Microsoft.Bot.Configuration/Services/AppInsightsService.cs, libraries/Microsoft.Bot.Configuration/Services/AzureService.cs, libraries/Microsoft.Bot.Configuration/Services/BlobStorageService.cs, libraries/Microsoft.Bot.Configuration/Services/BotService.cs, libraries/Microsoft.Bot.Configuration/Services/ConnectedService.cs, libraries/Microsoft.Bot.Configuration/Services/CosmosDbService.cs, libraries/Microsoft.Bot.Configuration/Services/DispatchService.cs, libraries/Microsoft.Bot.Configuration/Services/EndpointService.cs, libraries/Microsoft.Bot.Configuration/Services/FileService.cs, libraries/Microsoft.Bot.Configuration/Services/GenericService.cs, libraries/Microsoft.Bot.Configuration/Services/LuisService.cs, libraries/Microsoft.Bot.Configuration/Services/QnAMakerService.cs
Towards #4052.
Adds missing code docs for configuration library.
Also removes the suppression of CS1309 as part of microsoft/botframework-sdk#5933
=> Add missing code docs for Configuration lib

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/AttachmentActionData.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexMessageRequest.cs
Towards #4052 
Adds missing code docs and removes the error suppression for code docs in the webex adapter project.
=> Add missing code docs for the webex adapter

libraries/AdaptiveExpressions/ExpressionFunctions.cs, tests/AdaptiveExpressions.Tests/BadExpressionTests.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Fixes #4029
Originally, `getProperty` accepts two parameters, the first parameter is an instance, and the second parameter is the property name which user wants to access the value from. In this mode, the user can not access the top-level memory from dynamic/special string property.
After this change, `getProperty` accepts only one parameter, that presents the root property from the memory.
Example: 
Scope is :
```
{
"a:b": "value"
}
```
`getProperty('a:b')` would get string "value",
=> Extend 'getProperty' builtin function to support accessing top memory.

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs
Fixes #2291 
Removing Slack from the list of channels that do not support suggested actions.
=> Remove Slack from the list of channels that support Suggested Actions

libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Azure/Queues/ContinueConversationLater.cs
Towards #4052.
Adds missing code docs for Azure librariy.
Also removes the suppression of CS1309 as part of https://github.com/microsoft/botframework-sdk/issues/5933
=> Update missing code docs for the Azure library

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs
Fixes #2638 
Move TelemetryClient onto DialogContainer (implementation the same in AdaptiveDialog and ComponentDialog).
=> Move TelemetryClient property to DialogContainer

libraries/Microsoft.Bot.Schema/CardAction.cs
Fixes #4041
This does not add the field to the constructor, since we are moving away from the huge constructor pattern.
Verified the new field is passed through to WebChat:
=> Add ImageAltText to CardAction

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
Addresses #4079
This PR adds the Teams' **Channel Restored** event in [TeamsActivityHandler](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs) class.
- Updated [TeamsActivityHandler](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs) class to add the new _OnTeamsChannelRestoredAsync_ method.
- Add unit test for the new method in [TeamsActivityHandlerTests](https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs) class.
The following image shows the new event being handled by a test bot.
The next image shows the new test passing.
=> Add Teams Channel Restored event

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SwitchCondition.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_Switch.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_Switch_Bool.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_Switch_Number.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/SwitchBool.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/SwitchNumber.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/SwitchString.dialog, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
Fixes #4071 
SwitchCondition treated errors as exceptions when all that was happening was an comparison which was false. In addition, it was always assuming that a quoted number should be compared as a number. 
* Fix switch to not treat expression errors as exceptions but instead as false condition
* Fix switch to treat ambiguity in string case definition more robustly by comparing for both value type and string of value type. (23 OR "23")
updated unit test cases to cover this.
=> SwitchCondition with number throws an exception when compared against a string

libraries/AdaptiveExpressions/ExpressionFunctions.cs, libraries/AdaptiveExpressions/ExpressionType.cs, tests/AdaptiveExpressions.Tests/BadExpressionTests.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
issue link: #4014
merge function can take JSON object as input.
merge(jobject1, jobject2, ...)
for example:
```
json1 = @"{
'FirstName': 'John',
'LastName': 'Smith',
'Enabled': false,
'Roles': [ 'User' ]
}"
```
```
json2 =@"{
'Enabled': true,
'Roles': [ 'User', 'Admin' ]
}"
```
`string(merge(json(json1), json(json2)))` will return
```
{"FirstName":"John","LastName":"Smith","Enabled":true,"Roles":["User","Admin"]}
```
=> [Expression] Add merge prebuilt function for merging JSON object

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/MultiLanguageRecognizer.cs
Fixes #4219 
Adds null check for activity.Locale before calling LanguagePolicy.TryGetValue to avoid an exception being thrown.
=> Add null check for locale into MultiLanguageRecognizer

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicesChannelTests.cs
Fixes in dotnet: microsoft/botframework-sdk#5950
Adds directlinespeech to Channel.cs which determines the SuggestedAction and CardAction support in the prompts.
The buttonCount limits follow Web Chat and Direct Line because this is in the context of Direct Line Speech via Web Chat.
- Adds directlinespeech to Channel.cs helper functions
- Add tests for Channel.cs changes
Tested using Direct Line Speech and Web Chat via the repository's Microsoft.Bot.Builder.TestBot project.
Modified the Startup.cs to `UseWebSockets()` and used some of the [MainDialog code](https://github.com/microsoft/BotBuilder-Samples/blob/3738ec761d4e169d8ce31d28256e9e861d1bf634/samples/csharp_dotnetcore/06.using-cards/Dialogs/MainDialog.cs#L42-L52) from [06.using-cards](https://github.com/microsoft/BotBuilder-Samples/tr …
=> add directlinespeech support to prompts

.github/CODEOWNERS
Adds @chrimc62 & @tomlm as code owners for `/**/*.schema` at the **end** of the `CODEOWNERS` file to override all other code owners.
This change is to prevent the requiring of many code owners for the semi-ubiquitous `.schema` files as in https://github.com/microsoft/botbuilder-dotnet/pull/4243.
=> Add code owners for /**/*.schema

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/TelemetryTrackEventAction.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.TelemetryTrackEvent.schema, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
Fixes #4234 
This adds an action, which will be surfaced within Composer, to allow a user to track a custom event using the telemetry client, along side the existing passive event tracking already present.
=> Added new Telemetry Track Event action

libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/TelemetryMiddlewareTests.cs
Add Teams specific telemetry properties when activity received via the Teams channel.
Fixes #4255
=> Add Teams specific telemetry properties 

BotBuilder-DotNet.ruleset, libraries/Microsoft.Bot.Builder.AI.LUIS/AssemblyInfo.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/DynamicList.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/Generator/GeographyV2.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/Generator/InstanceData.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/Generator/OrdinalV2.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisAdaptiveRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisApplication.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisDelegatingHandler.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisExtensions.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV2.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV3.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisUtil.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj, libraries/Microsoft.Bot.Builder.AI.LUIS/V3/DynamicList.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/V3/ListElement.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/V3/LuisApplication.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/V3/LuisPredictionOptions.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/V3/LuisRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/V3/LuisRecognizerOptions.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisOracleTests.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisV3OracleTests.cs
- Added FxCop and Async analyzers to the LUIS project.
- I suppressed some Dispose warnings for now, we will address those once we start using HttpClientFactory in a future release.
- Deprecated the DefaultHttpClient static property in LuisRecognizeer and crated an internal HttpClient instance property that can be seen for testing (that's the only reason why is there).
- Added AssemblyInfo to make internal methods visible to tests.
- Added exclude for rule CA1822 (Mark members as static) as requested by Tom.
=> Added FxCop and Async analyzers to the LUIS project.

libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Models/FeedbackRecords.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Models/Metadata.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Models/QnAMakerTraceInfo.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Models/QnAResponseContext.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Models/QueryResult.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Models/QueryResults.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Models/RankerTypes.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerOptions.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Utils/HttpRequestUtils.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
=> Added FxCop and Async analyzers to the QnAMaker project.

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpRequestSequenceMock.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpResponseMock.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/SequenceResponseManager.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisLoader.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisRecognizer.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/PropertiesMock.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReply.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyOneOf.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserConversationUpdate.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestScript.cs
- Added CultureInfo and StringComparison parameters to some string operations.
- Removed unused fields from TestScript
- Removed several setters from List properties that wheren't set to address CA2227 (Collection properties should be read only).
- Renamed ContentTypes enum in HttpResponseMock to ResponseContentType in order to address CA1717 (Only FlagsAttribute enums should have plural names) and updated usages (had to use ResponseContentType because ContentType was causing collisions with the property name in that class).
=> Adds FxCop to Adaptive.Testing

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.csproj
- Enabled warning as errors
- Added project level exclude for CS1591 (this should be addressed as part of another issue).
=> Added FxCop to Adaptive.Teams

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisDelegatingHandler.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Utils/HttpRequestUtils.cs, libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4275
=> Use RuntimeInformation.FrameworkDescription if TargetFrameworkAttribute.FrameworkName is null

libraries/Microsoft.Bot.Builder.LanguageGeneration/AnalyzerResult.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/EvaluationOptions.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Extensions.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj, libraries/Microsoft.Bot.Builder.LanguageGeneration/MultiLanguageLG.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Template.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateErrors.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateException.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplatesParser.cs
- Added several #pragma warning disable for CA2227 (Collection properties should be read only) that we can't change because of binary compat.
- Added several ToLowerInvariant, CultureInfo and StringComparison parameters to string operations.
- Replaced some LINQ Count() and Length() operations by .Any() or Count and Length properties.
- Added CA1032 and CA2229 for TemplateException (we can implement these later if needed.
=> Added FxCop to LanguageGenreation.

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookRead.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookMessage.cs
See https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/message-reads
Add support for Facebook Read Message.
It may not be used by the Bot yet but it helps to better support the Facebook events and allow better reusability of the library outside of the "Bot" context in another project for example.
- added FacebookRead.cs class for deserialisation of Facebook Event message_reads
- added new property Reads on FacebookMessage
=> Add support for Facebook Message Read event

libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/SemaphoreSlimExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ICoercion.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugTransport.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggerSourceMap.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggingBotAdapterExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DialogDebugAdapter.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Events/IEvents.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Protocol.cs
- Made DebugTransport IDisposable and implemented dispose pattern on it and the derived DialogDebugAdapter.
- Added CulturInfo and StringComparison parameters to some string operations.
- Added several #pragma warning disable for [CA1034 (Nested types should not be visible)](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1034?view=vs-2019)
- Added several #pragma warning disable for [CA1819 (Properties should not return arrays)](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1819?view=vs-2019)
- Added several #pragma warning disable for [CA1716 (Identifiers should not match keywords)](https://docs.microsoft.com/en-us/visualstudio/code-quality/CA1716?view=vs-2019). Not sure if this can be fixed or if it is by design.
**Note to reviewers and …
=> Added FxCop to Dialogs.Debugging.
