microsoft/botbuilder-dotnet

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ActivityPrompt.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/ActivityPromptTests.cs

Fixes #2449
replaces: https://github.com/microsoft/botbuilder-dotnet/pull/4172
note: isRetry is false when OnPromptAsync is called from RepromptDialogAsync for other prompts:
https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs#L210

ActivityPrompt.RepromptDialogAsync call OnPromptAsync with isRetry false

---

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ActivityPrompt.cs

Parity with JS: https://github.com/microsoft/botbuilder-js/pull/744
Replaces https://github.com/microsoft/botbuilder-dotnet/pull/4263

Make ActivityPrompt a normal class - remove abstract

---

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/resources/test2.dialog
tests/tests.schema

Fixes #4250 
only apply resource.id as default .id if there is no id in the incoming json payload.
Change conditional for auto assigning dialog.id
added unit test to verify.

Only use resource.id as the default dialog id if the dialog doesn't have an id.

---

libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs

Fixes #4328
Currently, LG uses `__temp__` as the template id when evaluating inline text with `EvaluateText` method.
Later, the `expandText` function was introduced,  which would use the `evaluateText` to achieve the result. So, there would exist two `__temp__` templates.
Assign a random ID for template name when evaluating an inline text to support the nested inline text evaluation.

Fix anonymous template name conflict

---

libraries/Microsoft.Bot.Builder.TemplateManager/DictionaryRenderer.cs
libraries/Microsoft.Bot.Builder.TemplateManager/ITemplateRenderer.cs
libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj
libraries/Microsoft.Bot.Builder.TemplateManager/TemplateManager.cs

- Added several #pragma disable to violations where we can't change things withouth breaking compat.

Added FxCop fot TemplateManager

---

libraries/Microsoft.Bot.Configuration/BotConfiguration.cs
libraries/Microsoft.Bot.Configuration/EncryptUtilities.cs
libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj
libraries/Microsoft.Bot.Configuration/ServiceTypes.cs
libraries/Microsoft.Bot.Configuration/Services/AppInsightsService.cs
libraries/Microsoft.Bot.Configuration/Services/ConnectedService.cs
libraries/Microsoft.Bot.Configuration/Services/DispatchService.cs
libraries/Microsoft.Bot.Configuration/Services/GenericService.cs
libraries/Microsoft.Bot.Configuration/Services/LuisService.cs

- Added several #pragma disable for all the FxCop violations (all the affected classes are obsolete but this will allow us to apply FxCop to all the projects in the libraries folder using dirprops)

Added FxCop analyzers to Configuration

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpRequestSequenceMock.cs
tests/Directory.Build.props

Fixes #4240
Fixes #4239
Opens #4349 for temporarily suppressing xunit warnings.

Temporarily suppressing XUnit warnings

---

libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/ReaderWriterLock.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/ReferenceEquality.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/SemaphoreSlimExtensions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/CodeModels/CodePoint.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/CodeModels/ICodeModel.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/DataModel.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/DataModelBase.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/DictionaryDataModel.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/EnumerableDataModel.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ICoercion.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/JValueDataModel.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ListDataModel.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/NullDataModel.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ReadOnlyDictionaryDataModel.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ReflectionDataModel.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ScalarDataModel.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggerSourceMap.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Events/Events.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/IdentifierCache.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/IdentifierFactory.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/IdentifierMutex.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/Identifier{T}.cs
tests/Microsoft.Bot.Builder.Tests/MessageFactoryTests.cs

To make documentation easier I'm making the majority of the classes in dialog.testing internal.

Changing dialog.testing primarily internal

---

build/yaml/botbuilder-dotnet-ci-facebook-test.yml
build/yaml/botbuilder-dotnet-ci-slack-test.yml
build/yaml/botbuilder-dotnet-ci-twilio-test.yml
build/yaml/botbuilder-dotnet-ci-webex-test.yml
build/yaml/botbuilder-dotnet-functional-test-linux.yml
build/yaml/botbuilder-dotnet-functional-test-windows.yml
build/yaml/botbuilder-dotnet-functional-tests-setup.yml
build/yaml/botbuilder-dotnet-sign.yml

CA is only needed for CI and PR builds. For others, disabling it shortens the build time.
[Issue #4076](https://github.com/microsoft/botbuilder-dotnet/issues/4076).

Disable code analysis for non-CI builds

---

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
libraries/Microsoft.Bot.Connector/AssemblyInfo.cs
libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs
tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs

Fixes #4347
Fixes Unauthorized error when ContinueConversation is called on a bot app service instance that didn't originate the skill request.
- Updated code in BotFrameworkAdapter.ContinueConversation() so it always adds the activity.ServiceUrl to TrustedHostNames if the request has been authorized and it has an app ID (this will work for skills and other proactive messages)
- Made TrustedHostNames in AppCredentials internal and added InternalsVisibleTo directive to Microsoft.BotConnector so we can access it and assert the state of the state in tests.
- Cleaned up some async warnings in BotFrameworkAdapterTests
- Added additional logging to AppCredentials to help troubleshoot this issue in the future.

Fixes Unauthorized error when calling ContinueConversation

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BaseInvokeDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EndDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperties.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperty.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/JsonExtensions.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_SetProperties.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_SetProperty.test.dialog

Fixes #4050
support deep data binding for the following properties:
- `Value` property in `SetProperty`
- `Assignments` (for `SetProperties`)
- `Value` property in `EndDialog`
- `Body` in `HTTPRequest`
- `options` in `BeginDialog` action
For example, `Value` property in `SetProperty` action, 
```
{
"$kind": "Microsoft.SetProperty",
"property": "user.profile",
"value": {
"name": "${sentenceCase('jack')}",
"age": "${10 * 2}"
}
}
```
Before, Object 
```
{
"name": "${sentenceCase('jack')}",
"age": "${10 * 2}"
}
```
would assign to variable `user.profile`, and the result of `user.profile.name` is `${sentenceCase('jack')}`
After, Object
```
{
"name": "Jack",
"age": "20"
}
```
would assign to variable `user.profile`, and the result of `user.profile.name` is `Jack`
The same with other 4 …

Support deep data binding for some properties

---

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/resources/test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/resources/test3.dialog

Fixes #4367
Changed resourceExplorer to Apply resource.id to referenced objects.
Updated unit tests to have referenced objects too to validate.

Use Resource.Id as default Id for referenced objects 

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LGResourceLoader.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs

Fixes #4309
Original language policy:
en-us -> en-us, en, ''
fr-fr -> fr-fr, fr, ''
'' -> ''
Current default language policy:
en-us -> en-us, en
fr-fr -> fr-fr, fr
'' -> ''
So, it is necessary to update the `GroupByLocale` in `LGResourceLoader` to apply the lastest language policy.
Append all other resources those locale not match current entry locale to current locale.
For example：
there exist `a.en-us.lg`, `a.lg`, `b.lg`
At first, we should group all LG resources to make them locale awareness.
Suppose there exists the language policy:
en-us: en-us, en
'' : ''
The final grouped resources should like:
en-us -> a.en-us.lg, b.lg
'' -> a.lg, b.lg

Make Language fallback consistent with current LanguagePolicy

---

tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs

Temporary only. To unblock other PRs until this gets investigated and fixed.

Ignore failing test: JsonDialogLoad_CycleDetection

---

libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs
libraries/Microsoft.Bot.Builder.AI.QnA/Utils/ActiveLearningUtils.cs

Fixes the C# Portion of #3706 
Clean start from master from chris earlier PR: https://github.com/microsoft/botbuilder-dotnet/pull/4251

Fixes the C# portion of #3706

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Actions/AssertCondition.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/AdaptiveTestingComponentRegistration.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpRequestMock.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpRequestSequenceMock.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockHttpRequestMiddleware.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisExtensions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisLoader.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisRecognizer.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockedHttpClientHandler.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/MockSettingsMiddleware.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/PropertiesMock.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/PropertyMock.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReply.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyOneOf.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/TestAction.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserConversationUpdate.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserDelay.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserSays.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserTyping.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/UserTokenMocks/UserTokenBasicMock.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/UserTokenMocks/UserTokenMock.cs

Some classes were missing ctor doc comments and class doc comments.
Added missing doc comments.
none, it's just comments.

Flush out missing doc comments in Adaptive.Testing assembly

---

libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs

Fixes #4269
Sends a trace activity and tracks a trace event, via the telemetry client, for unhandled versionChanged and error events.

Send trace for unhandled dialog events

---

libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/SkillDialogTests.cs

Refactored SkillDialog to call the factory only during begin and store the generated conversationId in state to be used in subsequent calls to the skill.
Needs parity for python and JS
Fixes #4374

Refactored SkillDialog to call ConversationFacotry.CreateConversationId only once 

---

build/yaml/botbuilder-dotnet-ci.yml

Fixes #4320
This PR updates the [botbuilder-dotnet-ci](https://github.com/microsoft/botbuilder-dotnet/blob/master/build/yaml/botbuilder-dotnet-ci.yml) yaml file adding a script that evaluates which compatibility checks are needed, depending on what libraries have been modified.
If the pipeline is scheduled (Nightly Build) all the API compatibility validations will run.
- Updated the **_API_Compatibility_Validation_** stage in _botbuilder-dotnet-ci_ yaml to add a validation in the PowerShell step that gets the updated files si it only runs the API compat validation on those libraries. 
- Added a condition to the **_check_api_for_** and **_post_results_to_gitHub_** jobs to run if one or more libraries were updated.
- Converted the **_Post_Results_to_GitHub_** stage into a job so it can be …

Update dotnet-ci yaml to condition the API compat execution

---

libraries/Microsoft.Bot.Schema/Activity.cs
libraries/Microsoft.Bot.Schema/CardAction.cs
libraries/Microsoft.Bot.Schema/ConversationReference.cs

With this PR and after conversation with @EricDahlvang the code base will be up to date with the swagger spec json [v3.1.12](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-protocol/botframework-channel.json)
After merging this, it would be safe to delete current ConnectorAPI.json under swagger folder.

Fixed diff in descriptions against SDK swagger

---

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPromptSettings.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4395

Add EndOnInvalidMessage to OAuthPromptSettings

---

build/yaml/ci-build-steps.yml

Fixes #4047
This pull request updates the yaml for the CI pipeline setting the _logProjectEvents_ option to false, reducing the pipeline's build time.
_Note: According to the [MSBuild task documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops) the default value for logProjectEvents is false, but we noticed in our pipeline that this is not the case, and the log lines were actually reduced after setting the option to false._ 
- Added variable `logProjectEvents: false`. When true, this option records timeline details for each project.
The following images show the improvement made in the pipeline's build time after setting logProjectEvents to false.
The following images show the logs for Release_3.1 build before and after the change.

Set logProjectEvents to false in MSBuild task

---

libraries/AdaptiveExpressions/BuiltinFunctions/Json.cs

closes: #4397 
Now the error message of json pre-built function is:
$"Unexpected character at Path {err.Path}, line {err.LineNumber}, position {err.LinePosition} when parsing {originalContent}."
which can provide more details of where the error occured in LG or Expressions.

change the error message of Json pre-built function to provide more context infomation.

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BeginSkill.cs
libraries/Microsoft.Bot.Builder.Dialogs/SkillDialogOptions.cs
libraries/Microsoft.Bot.Builder/Skills/BotFrameworkSkill.cs

Fixes #4372
- Added code to `BeginSkill.BeginDialog()` that stores `DialogOptions` in state.
- Added overrides for `ContinueDialogAsync`, `RepromptDialogAsync`, `ResumeDialogAsync` and `EndDialogAsync` that pull the stored DialogOptions from the dialog state and regenerate the property .
- Added json serialization attributes to `SkillDialogOptions` and `BotFrameworkSkill` classes.
Notes:
- Unit tests will be added as part of #3879, I am just trying to fix the P0 issue for R10 right now. 
- This PR requires parity on JS and Python

BeginSkill fixes for ContinueDialog

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3627
This PR also prioritizes the timeout check before RecognizeTokenAsync, since RecognizeTokenAsync has side affects.

OAuthPrompt timeout applies to all auth related events and invokes.

---

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/AssemblyInfo.cs
libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs
libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Debugging/ResourceSourceContext.cs
libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Observers/CycleDetectionObserver.cs
libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/resources/testWithId.dialog

The AutoAssignId function was adding an entry with `'id': '<id>'`, but since it was adding a line, the token ranges computed by `SourceRange` were off. 
Here we 
- Recompute the range after assigning id
- Remove double assignment that was happening before
- Improve stack manipulation logic for corner cases (remove bottom of the call stack since it is a duplicate entry always)
- Re-enable cycle detection test

[Declarative] Resource IDs: Update resource ID best-effort assignment to be consistent for debugging experience

---

build/yaml/botbuilder-dotnet-ci.yml
build/yaml/ci-test-steps.yml

This PR updates the [ci-test-steps](https://github.com/microsoft/botbuilder-dotnet/blob/master/build/yaml/ci-test-steps.yml) yaml file to skip the test and coverage steps in the Debug builds.
Also, it fixes an issue found on the API Compat job matrix that caused that the _Microsoft.Bot.Builder.Integration.ApplicationInsights.Core_ library wasn't getting compared.
- **ci-test-steps yaml**:
- Removed the test steps for Debug 2.1 and Debug 3.1 jobs
- Added a condition to execute the coverage steps only for Release builds.
- **botbuilder-dotnet-ci.yml**:
- Updated the PowerShell script to create the matrix for the API Compat job including all the libraries. 
- Updated the Powershell script to run all API Compat validation on Manual builds fixing an error.
The following image shows the test …

[CI-PR Pipelines] Skip tests in Debug builds

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.Ask.schema
tests/tests.schema

The Microsoft.Ask schema had two errors that did not match the Microsoft.Ask implementation.
1) expectedProperties was missing the items specification.
2) defaultOperation was an objectExpression rather than a stringExpression.

Fix schema bugs in Microsoft.Ask.

---

tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs

Test failing in Microsoft.Bot.Builder.Dialogs.Declarative.Tests. 
Name: TestDialogResourcesAreValidForSchema
Error message: `Assert.Fail failed. D:\a\1\s\tests\Microsoft.Bot.Builder.TestBot.Json\Samples\80 - AdaptiveSkillDialog\AdaptiveSkillDialog.main.dialog JSON is valid against no schemas from 'oneOf'. Path ''.`
The last build against master, commit c6ff4a4, run #157298, failed, and passed running against the same commit last Wednesday, #156538. That indicates no source code change of ours is responsible for the break.
Ignoring temporarily until the root cause is found. 
Opened issue #4460 to track the fix.

Temporarily ignore failing Adaptive test

---

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/Fallback/inject.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/inject.lg
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/InjectionTest/inject.lg
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs

Issue reported by @chrimc62 that the injected LG function don't have access to global state (DSM state).
This PR enable injected LG template functions to access global memories. 
Suppose we have a template, with a global variable {user: {name: "user1", date: "2001-01-01"}, }
```
> !# @strict = false
> !# @namespace = Adaptive
> !# @Exports = UserDataConcat
#UserDataConcat()
- ${user.name} : ${user.date}
```
The result of evaluating the expression `Expression.parse("Adaptive.UserDataConcat()")` is `user1 : 2001-01-01`

Support accessing global memories in injecting LG templates as Expressions

---

libraries/AdaptiveExpressions/BuiltinFunctions/GetNextViableTime.cs
libraries/AdaptiveExpressions/BuiltinFunctions/GetPreviousViableDate.cs
libraries/AdaptiveExpressions/BuiltinFunctions/GetPreviousViableTime.cs

fixes: #4465
After checking these bugs and tested with freezing DateTime.UtcNow in BotBuilder-JS. 
The bugs in getNextViableTime, getPreviousViableDate, getPreviousViableTime are now fixed.
However we lack of a test framework in C# to mock DateTime.UtcNow so that the tests related to that will be more meaningful.

fix bugs in getNextViableTime, getPreviousViableDate, getPreviousViableTime

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BeginSkill.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.BeginSkill.schema

Similar as InputDialog, Support AllowInterruptions in BeginSkill action. 
Fixes https://github.com/microsoft/BotFramework-Composer/issues/3848

Support AllowInterruptions in BeginSkill

---

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs

Fixes #4487
The cycle detection uses sourcemap.path for cycle detection, but we were only optionally setting sourcemap.path if it's a FileResource. PVA has a custom resourceProvider.  
We promoted fullname to resource base class to support resource providers ability to provide "fullname" information., we can rely on that as the value for sourcemap.path.  It's possible that someone might not set FullName, so we fall back to .id
*   removed conditional check for fileResource type
*   use resource.fullname, and if it's not there fall back to resource.id
all tests pass.

always assign sourcemap.path

---

libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs

* Set WaterfallStepContext.Parent correctly
* Add test verifying the waterfall step parent is the waterfall dialogs parent
* Remove uneeded test class

4.10 cherry-pick of Set WaterfallStepContext.Parent correctly (#4480) also including 'Enable schema tests' cherry pick

---

libraries/AdaptiveExpressions/BuiltinFunctions/String.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

Fixes #4502
Originally, If the string function accepts a string parameter, `string` function would use `JsonConvert.SerializeObject` to convert the string result.
This PR would directly output the string content if the original parameter type is string.

Make "string" function return the original content if the parameter is a string type

---

libraries/AdaptiveExpressions/BuiltinFunctions/Merge.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

Fixes #4417
Originally, "merge" just support JObject parameters. 
It is necessary for it to support different kinds of nested objects. Like: Anonymous object, Dictionary,  JObject .etc.

Make "merge" support any kind of object  type

---

.github/CODEOWNERS

First pass at https://github.com/microsoft/botbuilder-dotnet/issues/4540 in the `4.10` branch
Adds appropriate code owners for Test projects

add specific owners for TestBot.Json & TestProtocol

---

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs

The current implementation of ResourceExplorer requires declarative types to be defined statically. Power Virtual Agents has different implementations of certain extended declarative assets for design time vs runtime, and we expect possible variation in declarative types by Bot in the future. 
A multi-bot process that allows variable declarative type configuration would need to specify a set of declarative types in an instance-bound manner as opposed to a static manner. 
- Add a new constructor overload to `ResourceExplorer` that accepts an `IEnumerable<IComponentDeclarativeTypes>`. This field can be null, which is the default value when using other constructors. 
- When resolving declarative types, use the local field when available instead of the static …

Allow resource explorer to accept the set of declarative type registrations

---

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs

Fixes #4556
Added a catch for JsonExeption in GetBodyContent (this catch was in 4.7 but was removed in 4.8 when BotFrameworkHttpClient was refactored).
This catch allows the user to check the status code of the response (but the content won't be returned because its type us unknown).

Add catch for JsonException in GetBodyContent.

---

tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenValidationTests.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4578

Add SkillValidation Claims tests

---

tests/AdaptiveExpressions.Tests/ExpressionPropertyTests.cs
tests/AdaptiveExpressions.Tests/LRUCacheTest.cs

This PR fixes the xUnit1013 issue in **[AdaptiveExpression.Tests](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/AdaptiveExpressions.Tests)** project.
- **_ExpressionPropertyTests_**
- Fixed xUnit1013 issue by changing the access modifier to private in _TestWithData_ and _TestExpressionPropertyWithValue_ methods.
- Remove unused method _TestErrorExpression_.  
- **_LRUCacheTest_**
- Fixed xUnit1013 issue by changing the access modifier to private in _StoreElement_ method.
- Changed var for const when corresponded.
- Use var instead of int.
The next image shows the tests passing after the changes made:

[xUnit] Fix issues on AdaptiveExpressions.Tests

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperty.cs

Retries track how many times an Ask prompt has been done and is reset when a property is set.  Rather than setting it to 0, this removes it which more clearly indicates that there is no current Ask outstanding.

Remove retries

---

tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests.csproj
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/identifierTests.cs

Fixes #4094
This PR migrates all [Microsoft.Bot.Builder.Dialogs.Debugging](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests) tests from **MSTest** to **xUnit**.
- Changed `[DataTestMethod]` to `[Theory]`.
- Changed `[DynamicData(nameof(Data))]` to `[MemberData(nameof(Data), DisableDiscoveryEnumeration = true)]`.

Migrate Microsoft.Bot.Builder.Dialogs.Debugging.Tests to xUnit

---

tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs

This PR fixes the xUnit1013, xUnit2000, xUnit2004, xUnit2009, xUnit2013, and xUnit2017 issues in [_TemplatesTest_](https://github.com/microsoft/botbuilder-dotnet/blob/main/tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs) file of **_Microsoft.Bot.Builder.LanguageGeneration.Tests_** project.
- **_TemplatesTest_**
- Fixed xUnit1013 by marking the _TestMemoryAccessPath_ method as _fact_ (this test was ignored and it's now executed).
- Fixed xUnit2000 by swapping the arguments of the _Assert.Equal_ statements. 
- Fixed xUnit2004 by replacing _Assert.Equal_ with _Assert.True_ to check for boolean conditions.
- Fixed xUnit2009 by replacing the _Assert.True_ with _Assert.Contains_ when checking for substrings.
- Fixed xUnit2013 by changing the _Assert.Equal_ …

[xUnit] Fix issues on TemplatesTest file

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookWrapperTests.cs

When Facebook rejects an http request through the Facebook adapter, that response is swallowed, making it hard to discover what happened.
This throws an exception containing the Facebook rejection message. That exception is discoverable in Azure via Application Insights/Failures.
An example Facebook rejection:
StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
x-app-usage: {"call_count":0,"total_cputime":0,"total_time":0}
WWW-Authenticate: OAuth "Facebook Platform" "invalid_request" "(#10) This message is sent outside of allowed window. Learn more about the new policy here: https://developers.facebook.com/docs/messenger-platform/policy-overview"
facebook-api-version: v6.0
Strict-Transport-Security: …

Improve Facebook adapter diagnostics

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/MultiLanguageRecognizer.cs

Fixes https://github.com/microsoft/BotFramework-Composer/issues/3729
Minor fix, activity from facebook channel take 'null' locale, this line would throw exception:
Object reference not set to an instance of an object.
Since the activity.Locale could be null.

fix null object reference

---

libraries/Microsoft.Bot.Connector/ConnectorClient.cs

Fixes #4462
Change JSON serialization formatting from `Formatting.Indented` to `Formatting.None` .
Remove the indention from the JSON body to shrink the size of HTTP request.
Local test result: With code:
```
var serializerSettings = new JsonSerializerSettings
{
DateFormatHandling = DateFormatHandling.IsoDateFormat,
DateTimeZoneHandling = DateTimeZoneHandling.Utc,
NullValueHandling = NullValueHandling.Ignore,
ReferenceLoopHandling = ReferenceLoopHandling.Serialize
};
var jObj = new JObject
{
["key1"] = "value1",
["key2"] = "value2"
};
serializerSettings.Formatting = Formatting.None;
Console.WriteLine("Serialization result with None formatting:");
Console.WriteLine(JsonConvert.SerializeObject(jObj, serializerSettings));
serializerSettings.Formatting = Formatting.Indented; …
```

Change JSON serialization formatting of ConnectorClient

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/MultiLanguageRecognizer.cs

Fixes:
https://github.com/microsoft/BotFramework-Composer/issues/4073
and
https://github.com/microsoft/botbuilder-dotnet/issues/4599

Cherry-pick to 4.10 MultiLanguageRecognizer: Remove activity locale check while adding default policy

---

tests/Microsoft.Bot.Configuration.Tests/ConfigurationLoadAndSaveTests.cs
tests/Microsoft.Bot.Configuration.Tests/ConnectionTests.cs
tests/Microsoft.Bot.Configuration.Tests/EncryptionTests.cs
tests/Microsoft.Bot.Configuration.Tests/Microsoft.Bot.Configuration.Tests.csproj
tests/Microsoft.Bot.Configuration.Tests/ServiceTests.cs

Fixes #4103
This PR migrates all [Microsoft.Bot.Configuration](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Configuration.Tests) tests from **MSTest** to **xUnit**.
- Changed `Assert.IsNotNull` to `Assert.NotNull`.
- Changed `Assert.IsNull` to `Assert.Null`.
- Changed `Assert.Fail` to `throw new XunitException`.
- Changed `[ExpectedException]` to `Assert.ThrowsAsync`.
- Improved tests Assertions.

[#4103] Migrate Microsoft.Bot.Configuration.Tests to xUnit

---

tests/Microsoft.Bot.Streaming.Tests/Payloads/HeaderSerializerTests.cs
tests/Microsoft.Bot.Streaming.Tests/Payloads/PayloadAssemblerTests.cs
tests/Microsoft.Bot.Streaming.Tests/Payloads/PayloadReceiverTests.cs
tests/Microsoft.Bot.Streaming.Tests/Payloads/PayloadSenderTests.cs
tests/Microsoft.Bot.Streaming.Tests/Payloads/RequestManagerTests.cs
tests/Microsoft.Bot.Streaming.Tests/Payloads/StreamManagerTests.cs

Addresses #4106
This PR migrates all [Microsoft.Bot.Streaming.Tests/Payloads](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Streaming.Tests/Payloads) tests from **MSTest** to **xUnit**.
- Replaced `[TestMethod]` with `[Fact]`.
- Changed Asserts.
- Replaced `Assert.Fail()` with `throw new XunitException("Should have failed")`.
- Used constants instead of variables where applicable.
- Used `var` instead of the specific type.
- Removed redundant parenthesis.
The following image shows the tests passing after the changes.

Migrate Microsoft.Bot.Streaming.Tests/Payloads folder to xUnit

---

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs

Fixes warnings that appear in the generated ref doc build
- Disambiguate class reference. 
- Update comments for LuisRecognizer.DefaultHttpClient.
- Not sure how to test this. However, the change did not generate any new build warnings in VS, and the link in IntelliSense links to the correct class.

Update doc XML

---

tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/Microsoft.Bot.ApplicationInsights.WebApi.Tests.csproj
tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/ServiceResolutionTests.cs
tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/TelemetryInitializerTests.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests.csproj

Fixes #4108
This PR migrates all [Microsoft.Bot.ApplicationInsights.WebApi](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests) tests from **MSTest** to **xUnit**.
- Changed `[TestCategory]` to `[Trait]`.
- Improved tests Assertions.

Migrate Microsoft.Bot.ApplicationInsights.WebApi.Tests to xUnit

---

tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogManagerTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogSetTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/Microsoft.Bot.Builder.Dialogs.Tests.csproj
tests/Microsoft.Bot.Builder.Dialogs.Tests/NumberPromptTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/Startup.cs

Fixes #4096
This PR migrates **the following test files** inside the [Microsoft.Bot.Builder.Dialogs.Tests](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.Dialogs.Tests) folder from **MSTest** to **xUnit**.
- DialogManagerTests.cs
- DialogSetTests.cs
- DialogStateManagerTests.cs
- MemoryScopeTests.cs
- NumberPromptTests.cs
- OAuthPromptTests.cs
- Startup.cs
- Added `xUnit` packages to `.csproj`.
- Changed `[ExpectedException]` to `Assert.Throws`/`Assert.ThrowsAsync`.
- Changed `Assert.IsNotNull` to `Assert.NotNull`.
- Changed `Assert.IsNull` to `Assert.Null`.
- Changed `Assert.IsTrue` to `Assert.True`.
- Added `[assembly: TestFramework("Microsoft.Bot.Builder.Startup", …

[#4096] Migrate Microsoft.Bot.Builder.Dialogs.Tests to xUnit

---

build/yaml/botbuilder-dotnet-sign.yml

The old version format: "4.11.0-daily.<date>.<build_id>" 
The new version format: "4.11.0-daily.<date>.<build_id>.<commit_hash>"

Add commit hash to package versions

---

tests/Microsoft.Bot.Builder.Tests/EventFactoryTests.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerNotImplementedTests.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
tests/Microsoft.Bot.Builder.Tests/TelemetryMiddlewareTests.cs
tests/Microsoft.Bot.Builder.Tests/Transcript_MiddlewareTests.cs
tests/Microsoft.Bot.Builder.Tests/TurnContextTests.cs

This PR fixes xUnit1013, xUnit2000 and xUnit2003 issues in **[Microsoft.Bot.Builder.Tests](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.Tests)** project.
- **_EventFactoryTests_**
- Fixed xUnit2003 issue by changing `Assert.Equal` to `Assert.Null`.
- **_TeamsActivityHandlerNotImplementedTests_**
- Fixed xUnit1013 issue by adding `[Fact]` to a test.
- **_TeamsInfoTests_**
- Fixed xUnit2000 issue by changing the **expected** and **actual** values.
- **_TelemetryMiddlewareTests_**
- Fixed xUnit1013 issue by adding `[Fact]` to a test.
- **_Transcript_MiddlewareTests_**
- Fixed xUnit1013 issue by changing the access modifier to `private` in multiple methods.
- Fixed xUnit2000 issue by changing the **expected** and **actual** values.
- …

[xUnit] Fix issues on Microsoft.Bot.Builder.Tests

---

tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesParseTreeTest.cs

This PR fixes the xUnit2009 issues in [_TemplateDiagnosticTest_](https://github.com/microsoft/botbuilder-dotnet/blob/main/tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs) file of **_Microsoft.Bot.Builder.LanguageGeneration.Tests_** project.
Also fixes the xUnit2013 issues in [_TemplatesParseTreeTest_](https://github.com/microsoft/botbuilder-dotnet/blob/main/tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesParseTreeTest.cs) file of **_Microsoft.Bot.Builder.LanguageGeneration.Tests_** project.
- **_TemplateDiagnosticTest_**
- Fixed xUnit2009 issue by replacing the Assert.True with Assert.Contains when comparing strings.
- **_TemplatesParseTreeTest_**
- Fixed xUnit2013 issue by changing the Assert.Equal with Assert.Single when …

[xUnit] Fix issues on TemplateDiagnosticTest & TemplatesParseTreeTest files

---

tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/LuisV3OracleTests.cs

This PR fixes the xUnit1013 issue in **[Microsoft.Bot.Builder.Ai.LuisV3.Tests](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.Ai.LUISV3.tests)** project.
- **_LuisV3OracleTests_**
- Fixed xUnit1013 issue by changing the access modifier to `private` in the `TestJson` method.
- Disabled xUnit1013 warning in `MinimalWithGeo` method.  
The next image shows the tests passing after the changes made:

[xUnit] Fix issues on Microsoft.Bot.Builder.Ai.LuisV3.Tests

---

build/yaml/botbuilder-dotnet-ci-facebook-test.yml
build/yaml/botbuilder-dotnet-ci-slack-test.yml
build/yaml/botbuilder-dotnet-ci-twilio-test.yml
build/yaml/botbuilder-dotnet-ci-webex-test.yml
build/yaml/botbuilder-dotnet-functional-test-linux.yml
build/yaml/botbuilder-dotnet-functional-test-windows.yml

Fixes #4081
To execute their respective tests, all functional test pipelines test projects must be built and a bot needs to be published as a target. To do so, the pipelines follow a restore, build, publish, and test pattern. 
The **bot to be deployed project is being built twice**, since the *build* step builds the whole solution, including both the bot to be deployed and the tests projects, and the *publish* step builds the bot to be deployed as well.
The changes introduced in this branch remove the build steps (including _NuGet_ steps) from all functional test pipelines and reassign building to the publish and test steps for their specific projects, saving approximately **3 minutes** on each pipeline execution.
This implementation works best for tests involving a relatively small …

[#4081] Stop building twice in the dotnet functional test pipelines

---

tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj
tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/ServiceResolutionTests.cs
tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Startup.cs
tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupAppSettingsOnly.cs
tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupInvalidInstance.cs
tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupMultipleAppInsights.cs
tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupNoParameters.cs
tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupOverideTelemClient.cs
tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupVerifyNullTelemetry.cs
tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupVerifyTelemetryClient.cs
tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryInitializerTests.cs

Fixes #4108
This PR migrates all [Microsoft.Bot.Builder.Integration.ApplicationInsights.Core](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests) tests from **MSTest** to **xUnit**.
- Changed `[TestCategory]` to `[Trait]`.
- Improved tests Assertions.

Migrate Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.Tests to xUnit

---

tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/BotTelemetryClientTests.cs
tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/Microsoft.Bot.Builder.ApplicationInsights.Tests.csproj
tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/TelemetryWaterfallTests.cs

Fixes #4089
This PR migrates all [Microsoft.Bot.Builder.ApplicationInsights](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.ApplicationInsights.Tests) tests from **MSTest** to **xUnit**.
- Changed `Assert.Fail` to `throw new XunitException`.
- Changed `Assert.IsTrue` to `Assert.True`.
- Changed `[ExpectedException(typeof(ArgumentNullException))]` to `Assert.Throws<ArgumentNullException>`.
- Changed `TestContext.TestName` to include directly the name of the test.

[#4089] Migrate Microsoft.Bot.Builder.ApplicationInsights.Tests to xUnit

---

libraries/Microsoft.Bot.Builder.AI.QnA/JoinOperator.cs
libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerOptions.cs
libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs
libraries/Microsoft.Bot.Builder.AI.QnA/Schemas/Microsoft.QnAMakerDialog.schema
libraries/Microsoft.Bot.Builder.AI.QnA/Schemas/Microsoft.QnAMakerRecognizer.schema
libraries/Microsoft.Bot.Builder.AI.QnA/StrictFiltersCompoundOperationType.cs
libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs
tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerRecognizerTests.cs
tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
tests/Microsoft.Bot.Builder.TestBot.Json/testbot.schema
tests/tests.schema

Fixes #4454
QnAMaker GenerateAnswer API has been enhanced to provide choice to user for join condition. User can choose the Compound Operation for joining strictfilters a.k.a metadata. The values for the Compound Operation Type are 'AND' and 'OR'. The default behaviour is 'AND', to support  backward compatibility. 
The changes implementation needs change in QnAMakerOptions, QnAMakerDialog.schema, testbot.schema and tests.schema. Changes implemented in QnARecognizer and QnAMakerDialog. Test has been created for testing the functionality.
-
QnaMaker_StrictFilters_Compound_OperationType() added for testing.

QnAMaker GenerateAnswer StrictFiltersCompoundOperationType  for Metadata Join Operation

---

libraries/AdaptiveExpressions/BuiltinFunctions/Split.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

closes: #4639 
Fix the split function results when the separator is whitespace.
```
split('token1 token2 token3', ' ') 
``` 
returns `["token1", "token2", "token3"]`
```
split('token1 token2 token3', '  ') 
``` 
returns `["token1 token2 token3"]`
```
split('token one', '') 
``` 
returns `["t", "o", "k", "e", "n", " ", "o", "n", "e"]`
The changed is introduced in this PR:
https://github.com/microsoft/botbuilder-dotnet/pull/4278/files?file-filters%5B%5D=.cs#diff-91d35031c5cb26ad523273c98506f94f

Fix split function results with whitespace separator

---

build/yaml/botbuilder-dotnet-sign.yml
build/yaml/ci-build-steps.yml
build/yaml/sign-steps.yml

This removes version display from CI and PR builds. It is not relevant there, and it generates OAuth warnings in forked builds.
Also improves displayed tags.

Move version tagging to parent signing yaml

---

libraries/AdaptiveExpressions/Memory/StackedMemory.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

- `StackMemory` would always return true. It is not correct.
- `StackMemory` would ignore `null` result. This would cause the memory breakdown.
For example:  There is such a stack memory:
-- IMemory1: a = null
-- IMemory2: b = "b"
If `a` is called, the step is: firstly achieve value from memory1, the result is `null`, originally, the Adaptive-expression would drop this result and find the result in memory2. After this change, the `null` result would return directly.

[Expression] Support return null result in stack memory

---

tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobTranscriptStoreTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/AzureQueueTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/BlobStorageBaseTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/BlobsStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/BlobsTranscriptStoreTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDBKeyEscapeTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionStorageFixture.cs
tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/IgnoreOnHasNoEmulatorFact.cs
tests/Microsoft.Bot.Builder.Azure.Tests/IgnoreOnNoEmulatorFact.cs
tests/Microsoft.Bot.Builder.Azure.Tests/Microsoft.Bot.Builder.Azure.Tests.csproj
tests/Microsoft.Bot.Builder.Azure.Tests/StorageEmulatorHelper.cs
tests/Microsoft.Bot.Builder.Azure.Tests/TranscriptStoreBaseTests.cs

Fixes #4090
This PR migrates all of the [Microsoft.Bot.Builder.Azure.Tests](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.Azure.Tests) tests from **MSTest** to **xUnit**.
- Replaced the MSTest packages with xUnit in the .csproj.
- Replaced `[TestMethod]` with `[Fact]`.
- Replaced `[TestCategory]` with `[Trait]`
- Changed Asserts.
- Replaced `[TestInitialize]` moving the code to the class constructor.
- Replaced `[TestCleanup]` implementing `IDisposable` `Dispose` method in the class.
- Replaced `TestContext.TestName` in test initialization using `TestOutputHelper` and reflection.
- Added `CosmosDbPartitionStorageFixture` class to have `CosmosDbPartitionStorage` class initialization code. 
- In `CosmosDbPartitionStorageTests` and …

[#4090] Migrate Microsoft.Bot.Builder.Azure.Tests project to xUnit

---

tests/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.Tests.csproj
tests/Microsoft.Bot.Builder.TemplateManager/TemplateFixture.cs
tests/Microsoft.Bot.Builder.TemplateManager/TemplateManagerTests.cs

Fixes #4098
This PR migrates all [Microsoft.Bot.Builder.TemplateManager](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.TemplateManager) tests from **MSTest** to **xUnit**.
- Changed `[TestCategory("Template")]` to `[Trait("TestCategory", "Template")]`.
- Changed `TestContext.TestName` to include directly the name of the test.
- Implemented `TemplateFixture` class to share data context among tests.

[#4098] Migrate Microsoft.Bot.Builder.TemplateManager.Tests to xUnit

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnConversationUpdateActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnEndOfConversationActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnEventActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnHandoffActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnInvokeActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnMessageActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnMessageDeleteActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnMessageReactionActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnMessageUpdateActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnTypingActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Extensions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnAssignEntity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnBeginDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCancelDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnChooseEntity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnChooseIntent.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnChooseProperty.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCondition.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnContinueConversation.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnDialogEvent.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnEndOfActions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnError.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnIntent.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnQnAMatch.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnRepromptDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnUnknownIntent.cs

Address #4321
This PR adds the missing XML documentation to all visible classes, methods, properties, and parameters in [Bot.Builder.Dialogs.Adaptive/TriggerConditions](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions), removing 75 errors.
**Note**: the NoWarn-CS1591 property is removed in the last PR of the series adding the documentation, to avoid build failures.
- Adds all missing documentation instances to all *.cs* files found within [*Microsoft.Bot.Builder.Dialogs.Adaptive* TriggerConditions directory](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions).
Below you can see the number of errors shown before and after the changes when de …

[#4321] Add missing XML documentation to Bot.Builder.Dialogs.Adaptive/TriggerConditions

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Functions/HasPendingActionsFunction.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Functions/IsDialogActiveFunction.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/MultiLanguageGenerator.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/MultiLanguageGeneratorBase.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ResourceMultiLanguageGenerator.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/TemplateEngineLanguageGenerator.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/Ask.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/AttachmentInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInputOptions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceSet.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/DateTimeInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialogOptions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/NumberInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/TextInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/Converters/ChoiceSetConverter.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/Converters/DialogExpressionConverter.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/DialogExpression.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/ConditionalSelector.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/FirstSelector.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/MostSpecificSelector.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/RandomSelector.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/TrueSelector.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/ActivityTemplate.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/StaticActivityTemplate.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/TextTemplate.cs

Address #4321
This PR adds the missing XML documentation to all visible classes, methods, properties, and parameters in the *Bot.Builder.Dialogs.Adaptive* [Functions](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Functions), [Generators](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators), [Input](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input), [Memory](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory), [Selectors](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors), and …

[#4321] Add missing XML documentation to Bot.Builder.Dialogs.Adaptive Functions, Generators, Input, Memory, Selectors and Templates folders

---

tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs

This PR fixes xUnit2004 and xUnit2009 issues in **[Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests)** project.
- **_ActivityFactoryTests_**
- Fixed xUnit2004 issue by changing `Assert.Equal` to `Assert.True`.
- **_LGGeneratorTests_**
- Fixed xUnit2009 issue by changing `Assert.True` to `Assert.Contains`.
The next image shows the tests passing after the changes made:

[xUnit] Fix issues on Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests

---

libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs

Fixes #4510
Make DisplayQnAResultAsync method protected so that user has flexibility of changing the display of answer.
Example: Via adaptive cards
DisplayQnAResultAsync access modifier change
Refactor to bring it before private methods
Added comments
Not a new feature

Make DisplayQnAResultAsync protected

---

libraries/Microsoft.Bot.Builder/BotState.cs

In order to properly manage internal variable state in memory, we override some of the data access in derived versions of memory scopes. Since parts of the memory management system have a strict dependency on CachedBotState, we would like to instantiate CachedBotState from our extensions.
Make the CachedBotState constructor **public**

Make Bot Cache state public

---

libraries/Microsoft.Bot.Builder/TokenResolver.cs

Fixes #4673 in `4.10` branch (will not close issue)
- Change from `Task.WaitAll()` to `Task.WhenAll()` to not block background polling operations
- This is spiritual a "reversion" of some code factoring in the 4.10.0 release
- Add comments/documentation explaining what the code is doing to prevent future breaks
- Fix minor typo
Manually tested these changes along with a fix for https://github.com/microsoft/BotFramework-WebChat/issues/3439 and the workaround mentioned in https://github.com/microsoft/botbuilder-dotnet/issues/4674 with Direct Line ASE and Direct Line Speech. The OAuth flow works as expected.
Note: No magic-code OAuth flows are not supported outside of regular Direct Line with Enhanced Authentication.

undo blocking on token polling ops; add docs & comments

---

libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs

* don't wait on logging
* Move the loop that iterates over the transcript into the async method to avoid triggering multiple async tasks that could cause concurrency issues.
Co-authored-by: Gabo Gilabert <ggilaber@microsoft.com>
Fixes #4642

Revert TranscriptMiddleware to not wait on logging (#4644)

---

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Find.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicesRecognizersTests.cs

Fixes #4619
Because the default tokenizer ignores special characters, choices that only differ in their special characters are seen as identical and our choice recognizers had no way of taking special characters into account when resolving a tie between two choices. Our choice recognition system was designed for natural language processing, but choice prompts usually allow users to click on buttons rather than typing their choices and so it makes sense to expect exact matches much of the time. This PR resolves the special character problem by checking for exact matches before any tokenization occurs.
Note that since special characters still aren't tokenized, they still aren't taken into account if an exact match isn't found. So if the choices are ":) face" and ":-( face" and the user …

Fix special character problem by making FindValues prefer exact matches

---

tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs

Fixes xUnit2000 error. The first parameter in Assert.Equal, should be the expected value.

Remove xUnit2000 error from templates test in Microsoft.Bot.Builder.LanguageGeneration.Tests

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/IfCondition.cs

Add exception to missing predicate condition.

---

libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/SkillDialogTests.cs

Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/4567

Delete Conversation Reference from ConversationIdFactory when SkillDialog receives EndOfConversation while using ExpectReplies

---

libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs
tests/Microsoft.Bot.Builder.Tests/ShowTyping_MiddlewareTests.cs

Fixes #4478
Adds an additional check to make sure the bot isn't running as a skill before starting to send typing activities.
- Adds a method to check if a bot isn't running as a skill
- Adds an additional condition on line 67 to make sure the bot isn't running as a skill
- Modifies the existing ShowTypingMiddleware tests to use a mock bot identity that identifies it as a root bot
- Adds a test to verify no typing activities are sent if the mock bot identity identifies it as a skill
This PR adds a MockBotIdentityMiddleware class for use in the tests to inject a mock bot identity before running the ShowTypingMiddleware. There may be a better solution, but I couldn't find any. I've tried adding the identity in the callback, but that's too late in the pipeline.

Avoid sending typing activity when bot is invoked as skill

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.BeginDialog.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.BeginSkill.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.DeleteProperties.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.DeleteProperty.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.EditArray.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.Foreach.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.ForeachPage.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.HttpRequest.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SetProperties.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SetProperty.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SwitchCondition.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.AttachmentInput.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ChoiceInput.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ConfirmInput.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.DateTimeInput.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.NumberInput.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.TextInput.uischema

Fixes 
https://github.com/microsoft/BotFramework-Composer/issues/4187
https://github.com/microsoft/BotFramework-Composer/issues/4189
Mappings between components and Intellisense options were previously hardcoded in Composer.
This PR aims at leveraging the uiSchema instead for the mappings, while bringing in Intellisense to remaining components.

Adding mappings between components and Intellisense options

---

libraries/AdaptiveExpressions/BuiltinFunctions/Split.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

closes: #4639 
Fix the split function results when the separator is whitespace.
```
split('token1 token2 token3', ' ') 
``` 
returns `["token1", "token2", "token3"]`
```
split('token1 token2 token3', '  ') 
``` 
returns `["token1 token2 token3"]`
```
split('token one', '') 
``` 
returns `["t", "o", "k", "e", "n", " ", "o", "n", "e"]`
The changed is introduced in this PR:
https://github.com/microsoft/botbuilder-dotnet/pull/4278/files?file-filters%5B%5D=.cs#diff-91d35031c5cb26ad523273c98506f94f

Cherry pick: Fix split function results with whitespace separator

---

FunctionalTests/Directory.Build.props

The following third party libraries that do not have strong names:
- NAudio
- Twilio
- Thrzn41.WebexTeams
This change disables the warning in the FunctionalTests project.
Fixes #4458

Disable build warning CS8002 in Microsoft.Bot.Builder.FunctionalTests

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/ActivityTemplate.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/TextTemplate.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests.csproj
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_NumberInputWithDefaultResponse.test.dialog

closes: #4409 
I have an E2E test for this fix: Here is the dialog file
```JSON
{
"$schema": "../../testbot.schema",
"$kind": "Microsoft.AdaptiveDialog",
"triggers": [
{
"$kind": "Microsoft.OnBeginDialog",
"actions": [
{
"$kind": "Microsoft.SendActivity",
"$designer": {
"id": "859266",
"name": "Send a response"
},
"activity": "Welcome User!"
},
{
"$kind": "Microsoft.NumberInput",
"defaultLocale": "en-us",
"disabled": false,
"maxTurnCount": 2,
"alwaysPrompt": true,
"allowInterruptions": false,
"prompt": "Give me your favorite number (1-10)",
"unrecognizedPrompt": "Sorry, ${turn.activity.text} did not include a valid number.",
"invalidPrompt": "Sorry, ${this.value} does not work. Can you give me a different number that is between 1-10?",
"defaultValueResponse": "Sorry, we have tried for …
```

fix DefaultValueResponce can't access DialogContext.State 

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs

closes: #4524 
Only if user didn't give a specified user-agent in the header. The default value is "Mozilla/5.0"

Add a default user-agent in  the header of HttpRequest action

---

libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs

Fixes #4511
Adds ObsoleteAttribute to [AzureBlobTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs) and [AzureBlobStorage](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs) classes, pointing to use [BlobsTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs) and [BlobsStorage](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs) instead, which are in the new package [Microsoft.Bot.Builder.Azure.Blobs](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure.Blobs)
Added …

[#4511] Add ObsoleteAttribute to AzureBlobTranscriptStore and AzureBlobStorage pointing to new 'blobs' classes

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs

This fixes a bug where a custom dialog inheriting from AttachmentInput will currently fail.  
(Comparing class names does not cover inheritance.)

Enable overriding AttachmentInput dialog

---

Directory.Build.props
FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/DirectLineClientTests.cs
FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/DirectLineSpeechTests.cs
FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/FacebookChatTests.cs
FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/Microsoft.Bot.Builder.FunctionalTests.csproj
FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/SlackClientTest.cs
FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/TwilioNumberTests.cs
FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/WebexClientTest.cs
build/yaml/botbuilder-dotnet-ci-slack-test.yml
build/yaml/botbuilder-dotnet-ci-twilio-test.yml
build/yaml/botbuilder-dotnet-functional-test-linux.yml
build/yaml/botbuilder-dotnet-functional-test-windows.yml

This PR sets up functional tests to:
(1) Be skipped in local test runs and only run in automated builds. The tests fail when run locally, creating a headache for devs. 
Using the AUTOMATEDBUILD preprocessor constant accomplishes this.
(2) Make an automated build fail if an essential environment variable for a test is missing.
Using Assert.Fail() accomplishes this. Assert.Inconclusive() causes the test to be skipped and lets a build pass.
Issue #4716

Make missing test environment vars cause a functional test build to fail

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BeginSkill.cs

This fixes a bug which occurs if an Activity is not provided to BeginSkill.  This fix ensures we send turnContext.Activity, rather than throw Null Reference Exception.

Send context.Activity if none provided in BeginSkill

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot/FacebookAdapterWithTag.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot/Startup.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs

Fixes #4743
Refactored FacebookAdapter to add a virtual method for FB message creation that allows the devs to manipulate the FB message instance before it gets sent to Facebook.
Added FacebookAdapterWithTag adapter to FB test bot so we can add the "ACCOUNT_UPDATE" tag as defined in https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags#sending

Adds CreateMessageFromActivity method to facebook adapter. 

---

libraries/AdaptiveExpressions/Expression.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/InjectionTest/injectWithoutNamespace.lg
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs

Issue: https://github.com/microsoft/BotFramework-Composer/issues/3982
Originally, the injection of LG function into Expression require a namespace option. If there is no namespace option, a absolute path is require. It is too strict.
Loose the namespace fallback policy. The priority order is:
1. If there is a namespace option, use it
2. If there is an un-empty id, parse the file name from the id, and get the namespace
3. If the Id is empty, just drop the namespace and use the template name as the expression name directly.
For example:
If there is an option in LG file, like:
```
> !# @Namespace = general
```
`general` is the namespace, the export function could be presented as `general.xxx`
If there does not exist a namespace option, use the name of Id by default, for example:
If the id …

[LG] Redo the default fallback of namespace

---

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs

Fixes #4710 
Avoid cast exception System.InvalidCastException - Unable to cast object of type ‘System.Int64’ to type ‘System.Int32
Using Convert.Int32 instead of (int) in Line 533

Update BotFrameworkAdapter, Fixes : #4710

---

build/yaml/botbuilder-dotnet-ci.yml

To disable, set var DisableApiCompatibityValidation to true in ADO.

Allow API Compatibility Validation to be disabled

---

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/Configuration/EnvironmentConfig.cs
FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/GetTokenRefreshTests.cs
build/yaml/botbuilder-dotnet-functional-test-linux.yml
build/yaml/botbuilder-dotnet-functional-test-windows.yml

These 7 tests were being skipped in BotBuilder-DotNet-Functional-Tests-Windows-yaml:
√ SendDirectLineMessage [13s 651ms]
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.2+2d84eb3141 (64-bit .NET Core 4.6.29220.03)
! SendDirectLineSpeechVoiceMessage
! TokenTests_GetCredentialsWorks [384ms]
! TokenTests_RefreshTokenWorks [4ms]
! TokenTests_RefreshTestLoad [6ms]
! Connector_TokenExtractor_NullRequiredEndorsements_ShouldFail [18ms]
! Connector_TokenExtractor_EmptyRequireEndorsements_ShouldValidate [3ms]
! Connector_TokenExtractor_RequiredEndorsementsPresent_ShouldValidate [3ms]
[xUnit.net 00:00:02.96]   Discovering: Microsoft.Bot.Builder.FunctionalTests
[xUnit.net 00:00:02.99]   Discovered:  Microsoft.Bot.Builder.FunctionalTests
Results File: …

Change Assert.Inconclusive() to Assert.Fail() in tests

---

libraries/Microsoft.Bot.Builder.Azure.Queues/AzureQueueStorage.cs
libraries/Microsoft.Bot.Builder.Azure.Queues/Microsoft.Bot.Builder.Azure.Queues.csproj
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ContinueConversationLater.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.ContinueConversationLater.schema
libraries/Microsoft.Bot.Builder/QueueStorage.cs
tests/Microsoft.Bot.Builder.Azure.Tests/AzureQueueTests.cs

Refactor of Microsoft.Bot.Builder.Azure.Queues.

---

libraries/Microsoft.Bot.Connector/Authentication/BotFrameworkAuthenticationFactory.cs
libraries/Microsoft.Bot.Connector/Authentication/ParameterizedBotFrameworkAuthentication.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs

Change the behavior for configured cloud environments.
If there is any configuration for a cloud environment fall into the parameterized code path.
Otherwise, the default is the public cloud with no configuration and the gov cloud if the (legacy) ChannelService property indicates that.

fix the default behavior when cloud environments are configured

---

tests/tests.schema
tests/tests.uischema

This update is generated.
This update should have been included in [4692](https://github.com/microsoft/botbuilder-dotnet/pull/4692).
Also includes other updates, probably missed in other PRs.

Update tests.schema with changes to Microsoft.ContinueConversationLater.

---

build/yaml/-experimentalDummy.yml
build/yaml/botbuilder-dotnet-ci-facebook-test.yml
build/yaml/botbuilder-dotnet-ci-slack-test.yml
build/yaml/botbuilder-dotnet-ci-twilio-test.yml
build/yaml/botbuilder-dotnet-ci-webex-test.yml
build/yaml/botbuilder-dotnet-ci.yml
build/yaml/botbuilder-dotnet-functional-test-linux.yml
build/yaml/botbuilder-dotnet-functional-test-windows.yml
build/yaml/botbuilder-dotnet-functional-tests-setup.yml
build/yaml/botbuilder-dotnet-sign.yml
build/yaml/botbuilder-dotnet-simple-build-test.yml

Lets the build agent VM image for pipelines be settable at queue time. 
Issue #4765

Check for var VMImage to override the default build agent VM image

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestScript.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/MultiLanguageRecognizer.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MultiLanguageRecognizerTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/TestUtils.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/MultiLanguageRecognizerTests/MultiLanguageRecognizerTest_LanguagePolicy.test.dialog

Fixes #4143
Make language policy in MultiLanguageRecognizer follow the LG UseLanguagePolicy convention 
Change the default policy assignment with composite value achievement.
The step is: 
- Get value from the property  `LanguagePolicy` directly
- Get value from the value from `UseLanguagePolicy`
- Use default languagePolicy `new LanguagePolicy()`

Make language policy in MultiLanguageRecognizer align with the policy in UseLanguagePolicy

---

build/yaml/botbuilder-dotnet-ci-facebook-test.yml
build/yaml/botbuilder-dotnet-ci-slack-test.yml
build/yaml/botbuilder-dotnet-ci-twilio-test.yml
build/yaml/botbuilder-dotnet-ci-webex-test.yml
build/yaml/botbuilder-dotnet-functional-test-linux.yml
build/yaml/botbuilder-dotnet-functional-test-windows.yml
build/yaml/botbuilder-dotnet-functional-tests-setup.yml

For triggering functional test builds.
Currently PR triggers do not fire for functional test builds. Now they would fire if the host build was changed.

Set PR filters to include the host .yml file

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs

Fixes #4467
This share some of the significant implementation across the two dialog classes.
There is more consolidation to do here. But that bigger exercise and involves migrating off the current IUserTokenProvider, IExtendedUserTokenProvider and IConnectorClientBuilder. All of which are implemented on the BotFrameworkAdapter.

consolidate some implementation

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/TextInput.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_TextInput.test.dialog

Fixes #4758
If someone assigns an empty string or `null` value or whitespace string to property `OutputFormat`, would trigger the unrecognized prompt error.
Ignore the `null` or whitespace string in `OutputFormat`.
Such action:
```
{
"$kind": "Microsoft.TextInput",
"property": "user.name",
"alwaysPrompt": true,
"prompt": "Hello, what is your name?",
"unrecognizedPrompt": "How should I call you?",
"validations": [
"this.value.Length > 3"
],
"outputFormat": "" // would ignore this property
}
```

Ignore the null or empty result of the OutputFormat in TextInput

---

FunctionalTests/Skills/Adaptive/AdaptiveRootBot/Middleware/LoggerMiddleware.cs
FunctionalTests/Skills/DialogToDialog/DialogRootBot/Middleware/LoggerMiddleware.cs
libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs
libraries/Microsoft.Bot.Connector/Conversations.cs
libraries/Microsoft.Bot.Schema/ActivityEventNames.cs
libraries/Microsoft.Bot.Schema/ConversationReferenceEx.cs
libraries/Microsoft.Bot.Schema/EventActivityNames.cs
tests/Microsoft.Bot.Builder.Azure.Tests/AzureQueueTests.cs
tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs
tests/Microsoft.Bot.Builder.Tests/TranscriptLoggerMiddlewareTests.cs

Fixes #4733 
Changes include:
- Added check in TranscriptLoggerMiddleware to filter incoming ContinueConversation events.
- Introduced ActivityEventNames class with constant strings for ContinueConversation so we don't have those strings hardcoded.
- Added also CreateConversation to the EventActivityNames helper (not related to this issue but saw it and decided to add it since it is better to have constants).
- Refactored ConversationReferenceEx to use the new constant (and use more straightforward code to create the event).
- Added tests for new logic in TranscriptLoggerMiddleware.
- Updated Skills testing projects to use the new constant
Add TranscriptLoggerMiddleware to the simple skill sample and verify that ContinueConversation events are not logged in the transcript.

Adds check to TranscriptLoggerMiddleware doesn't log continue conversation event activities

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.Ask.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnAssignEntity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnEndOfActions.uischema

This assists form dialogs in Composer - https://github.com/microsoft/BotFramework-Composer/issues/4360
This adds missing UI schema for Microsoft.Ask, Microsoft.OnAssignEntity, and Microsoft.OnEndOfActions necessary to have them render property in composers flow designer and property pane.
- Add UI schemas
N/A

Adding UI schema to handle form dialogs

---

libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs
libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs
libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4645
This reduces tracing, but does not address the other issues raised in 4645:
> I would expect to be able to have a setting or configuration or something which controls the traceactivities.

Remove extra skill dialog trace activities

---

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
libraries/Microsoft.Bot.Builder/Inspection/InspectionSession.cs

One more round of improvements around disposable patterns that should have a substantial impact in bots that have medium to large scale, in terms of resource utilization, including connections (clients), memory (dead references) and CPU (because of the GC having to do heavy passes in large size chunks)

Perf + Resource Utilization: Ensure proper dispose of disposable members

---

libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggerSourceMap.cs
libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs
libraries/Microsoft.Bot.Builder.Dialogs/Debugging/DebugSupport.cs

Debugging improvements:
- Fix debugging of declarative assets
- Move from first wins to last wins. When we reload an object, we always retain the latest instance for a given range
- Declarative perf: Interface converter has a non-concurrent dictionary since the process does not reqiure concurrency control
- Remove cloning from interface converter due to bug in json.net: https://github.com/JamesNK/Newtonsoft.Json/issues/2410

Declarative Debugging: Breakpoint to instance mapping from 'first wins' to 'last wins'

---

libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs
tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenValidationTests.cs

This PR removed the check on Trusted Service Url in the custom AppCredentials class.
Some of the internal implementation has been removed and the public methods obsoleted.
Tests have been updated and removed. (Also note the odd behavior in the TeamsInfo test. It seems there is a subtle distinction between null and empty string in no-auth scenarios.)
This check is redundant as all the logic does is add to a collection and then a couple of stack frames later check for the presence of the value in that same collection.
This was never a security feature exactly. It was a feature added in V3 to stop accidental deployment of code to production that didn't contain the ASP MVC auth attribute. In v4 the inbound / outbound nature of the protocol is fully encapsulated with the adapter and it does …

remove trusted service url check in appcredentials

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Model/EventType.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Files/ReactionAddedEvent.json
tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft.Bot.Builder.Adapters.Slack.Tests.csproj
tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackAdapterTests.cs

Fixes #4594
User reported. The Slack adapter does not know how to deserialize EventType.Item as it was set as a string.
I changed the type of `Item` from `string` to `JObject`. I was not able to find anywhere in the Slack Events API documentation an instance of EventType.Item used as a string. See [Event Type](https://api.slack.com/types/event) and [Event Wrapper](https://github.com/slackapi/slack-api-specs/blob/master/events-api/slack_common_event_wrapper_schema.json)
- Added unit test `ProcessAsyncShouldSucceedWithReactionAddedEventType` that verifies the payload is processed as expected.
- Refactored common code to methods for reuse. 
- All unit tests passed.

Change type of property EventType.Item from string to JObject in Slack Adapter

---

libraries/Microsoft.Bot.Builder/NormalizeMentionsMiddleware.cs
libraries/Microsoft.Bot.Builder/SkypeMentionNormalizeMiddleware.cs
tests/Microsoft.Bot.Builder.Tests/NormalizeMentionsMiddlewareTests.cs

Fixes #4842 
Skype and teams both annotate raw text with <at>user</at> tags.  The current middleware that attempts to solve this only removes the markup from the text, but not from the mention object.  And it is named "SkypeNormalize" when it is also needed for teams (or for that matter, any channel which is passing <at> markup ).
* marked SkypeMentionNormalizeMiddleware as obsolete
* Created new NormalizeMentionsMiddleware class
* removes <at> tags from text and mention entities.
* has option to remove Recipient from text and mention entities for recipient (aka bot).
* works for any channel (it's not just skype)
* added unit tests

Add new NormalizeMentionsMiddleware class

---

libraries/AdaptiveExpressions/ExpressionProperties/StringExpression.cs
libraries/AdaptiveExpressions/ExpressionProperties/ValueExpression.cs
tests/AdaptiveExpressions.Tests/ExpressionPropertyTests.cs

closes: #4823 
```
str = new StringExpression("test `name");
str.TryGetValue(data).Value
```
The result is ```"test `name"```
```
str = new StringExpression("test //`name");
str.TryGetValue(data).Value
```
The result is ```"test //`name"```
```
val = new ValueExpression("test `name");
val.TryGetValue(data).Value
```
The result is ```"test `name"```
```
val = new ValueExpression("test //`name");
val.TryGetValue(data).Value
```
The result is ```"test //`name"```

fix error caused by backtick in stringExpression and valueExpression

---

libraries/Microsoft.Bot.Connector/Authentication/ParameterizedBotFrameworkAuthentication.cs
libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs

The SkillsValidation class also contains the list of issuers and should be the same as the EmulatorValidators array.
And as a separate issue - these should surely share some code - however that can be addressed in the internals of the CloudAdapter auth implementation.

additional values in the issuers list

---

libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4837
Since this field is private and not injected for tests, I don't think there is any advantage to using IDictionary vs ConcurrentDictionary.

IDictionary to ConcurrentDictionary in StreamingRequestHandler

---

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
libraries/Microsoft.Bot.Builder/TurnContext.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4657
Unfortunately we broke developers who implemented their own `ITurnContext` when adding a cast to `TurnContext` in `DialogContext.GetLocale()`. Furthermore, the `GetLocale()` method is quite useless considering that whenever the `DialogContext` is available, a `ITurnContext` instance is available as well and we could get the locale from there.
I have some broader locale changes in another incoming PR (in which I mark `DialogContext.GetLocale()` as deprecated among other things), but this is the minimum bar, which is to un-break developers that have been broken because of this change.

DialogContext: tactical change to decouple from TurnContext to remediate breaking changes

---

tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaTestsFixture.cs
tests/tests.schema

test.schema has been having unnecessary churn and this fixes the issue so that it should only change when people change component schems.  This was for two reasons:
1) A bug in dialog:merge where oneOf clauses were not being sorted. (Which has been fixed and checked in.)
2) Developers running an older version of bf.  This is fixed by auto-installing the latest version if there is a change in test.schema.  
This PR also contains a refactoring of the tests so BF is only executed when the test is run and not when we open Test Explorer (addressses part of #4802)

Automatically install bf for schema merge.

---

build/ExtractCompressNuGet.ps1

The patch install on line 19 gets a "not found" error, likely because it is no longer needed. It dates from June 2019 
This build shows this fix works: https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=180307&view=results

Remove the patch install from ExtractCompressNuGet.ps1

---

build/ExtractCompressNuGet.ps1

This reverts PR "Remove the patch install from ExtractCompressNuGet.ps1 (4.11)" #4898.
Also, updated to install the current version of Microsoft.PowerShell.Archive, 1.2.5.
Turns out ExtractCompressNuGet.ps1 was likely broken by a module repository outage that was later resolved.
It may be desirable to make ExtractCompressNuGet.ps1 less vulnerable to this kind of outage.

Revert PR 4898 for ExtractCompressNuGet.ps1 (4.11)

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.LogAction.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.TraceActivity.uischema

Fixing https://github.com/microsoft/BotFramework-Composer/issues/4623
Fix the broken link: https://aka.ms/bfc-debugging-bots in `Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.LogAction.uischema` and `Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.TraceActivity.uischema`files are broken.
Pointing to this article: https://aka.ms/composer-telemetry

Fix broken help links in uischema files

---

tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionStorageFixture.cs

Prior to this fix, there were some issues when running Cosmos tests individually.
- change the fixture from IDisposable to [IAsyncLifetime](https://github.com/xunit/xunit/blob/master/src/xunit.core/IAsyncLifetime.cs)
Tests were failing when run individually. Now:

await async methods in Cosmos test fixture

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SendActivity.schema

Fixes https://github.com/microsoft/BotFramework-Composer/issues/4651
Composer is assuming disable property to be booleanExpression across all the kinds.
But currently in sdk, in SendActivity and Ask action, the disable property is defined as a StringExpression which breaks composer's assumption and the disable feature for SendActivity and Ask action is not working now.
Disabling the two actions will get an validation error.  
- Update disable property in SendActivity from StringExpression to booleanExpression.
Tested in composer UX, update the schema will fix this issue.

Update disabled property to booleanExpression in Microsoft.SendActivity.schema

---

README.md

Here is the permalink: https://botbuildersdkblobstorage.blob.core.windows.net/sdk-dotnet-dependency-reports/latest/InterdependencyGraph.html
The pipeline updating the dependency graph pushes to that permalink. Once this PR is merged, the readme never needs further updating.
Issue #4854

Trying again: Readme updated with a "permalink" to the latest dependency graph

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/MultiLanguageGeneratorBase.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/TemplateEngineLanguageGenerator.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/DateTimeInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/NumberInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/TextInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LGResourceLoader.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCondition.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs

This PR replaces all the generic expressions in `Dialogs.Adaptive` root, Generators, Input, and TriggerConditions folders.
Replaced generic exceptions in:
- `Dialogs.Adaptive` library.
- Root folder.
- Input folder.
- Generators folder.
- TriggersConditions folder.
No tests required updates.

[#4022] Throwing Generic Exceptions - Dialogs Adaptive Inputs

---

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj

Update the orchestrator-core native dependencies in 4.11 branch to pick up a linux-related fix (native icu dependencies cannot be found due to naming error), all other OSes unaffected.
- Update `Microsoft.BotFramework.Orchestrator` version to `4.11.0-rc2.preview`

Update Microsoft.BotFramework.Orchestrator to 4.11.0-rc2.preview

---

libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs
libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs
libraries/Microsoft.Bot.Streaming/ReceiveRequestExtensions.cs
tests/Microsoft.Bot.Streaming.Tests/StreamingRequestHandlerTests.cs

Fixes: Return BadRequest if an Activity is not present https://github.com/microsoft/botbuilder-dotnet/issues/4958
Do not throw if callerid is null
await ReadToEndAsync within ReadBotyAsStringAsync

Streaming fixes

---

libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs
libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs
libraries/Microsoft.Bot.Streaming/ReceiveRequestExtensions.cs
tests/Microsoft.Bot.Streaming.Tests/StreamingRequestHandlerTests.cs

* Streaming: Return BadRequest if an Activity is not present
* Nullcheck callerid in GetAudienceFromCallerId
* Await the ReadToEndAsync within ReadBodyAsStringAsync

Cherry-Pick to 4.11: Streaming fixes (#4959)

---

libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConfiguration.cs
libraries/Microsoft.Bot.Connector/Authentication/ClaimsValidator.cs
libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenValidationTests.cs

Backporting changes from:
* https://github.com/microsoft/botbuilder-dotnet/pull/4570
* https://github.com/microsoft/botbuilder-dotnet/pull/4598

Throw err if IsSkillClaim & ClaimsValidator is null

---

build/yaml/sign-steps.yml

SHA was not updated for this legacy branch a few months ago when ESRP required it for all signing.
This updated file is merely a copy of the one from the main branch.

Update branch 4.8 ESRP signing with new SHA 

---

build/yaml/ci-api-validation-steps.yml

Fixes #4894
The issue states that the report is not uploaded when the comparer fails, but we couldn't reproduce this issue.
Instead, we found that the report is not uploaded when any of the previous steps of the job fails.
The comparer is skipped when any previous step job fails, and no report is created.
The most likely step to fail is _NuGet install_, which downloads the library to be compared and can fail if it doesn't find it.
This PR introduces a default report file creation.
If the report file is not found, it will be created with the following text:
> The binary compatibility report for library LibraryName wasn't generated. This may have happened because the NuGet library LibraryName for version VersionNumber was unavailable or a connectivity issue.
- Updates _Insert nuget link …

[#4894] Binary compatibility checks need updating

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Actions/GetMeetingParticipant.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Actions/AssertCondition.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BaseInvokeDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EditActions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EditArray.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EndDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/GetActivityMembers.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/GetConversationMembers.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperties.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperty.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ThrowException.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/TraceActivity.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_ThrowException.test.dialog

This PR replaces all 17 generic exceptions found within the _Actions_ directory for `Dialogs.Adaptive`, `Dialogs.Adaptive.Teams`, and `Dialogs.Adaptive.Testing` libraries with proper exceptions according to the [Standard Exception Types](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/using-standard-exception-types).
- Replaces all 17 generic exceptions within:
- libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\Actions
- libraries\Microsoft.Bot.Builder.Dialogs.Adaptive.Teams\Actions\
- libraries\Microsoft.Bot.Builder.Dialogs.Adaptive.Testing\Actions\
- Updates test `Action_ThrowException.test.dialog` to comply with the changes
Here's a screenshot of the tests for these files working correctly with the changes applied:

[#4022] Throwing Generic Exceptions - Adaptive Actions

---

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/TwilioNumberTests.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioClientWrapper.cs
libraries/AdaptiveExpressions/BuiltinFunctions/Accessor.cs
libraries/AdaptiveExpressions/Memory/StackedMemory.cs
libraries/AdaptiveExpressions/RegexErrorListener.cs
libraries/AdaptiveExpressions/parser/ExpressionParser.cs
libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs
libraries/Microsoft.Bot.Builder/MemoryStorage.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandlerBase.cs
tests/Microsoft.Bot.Builder.Tests/Adapters/TestFlowTests.cs

This PR replaces all the generic expressions in `AdaptiveExpressions`, `Adapters`, `integration`, `FunctionalTests`, and part of `BotBuilder` libraries. Also, updates the affected tests to assert the proper exception.
Replaced generic exceptions in:
- FunctionalTests
- libraries\Adapters
- libraries\AdaptiveExpressions
- libraries\integration
- libraries\Microsoft.Bot.Builder\Adapters
Updated tests to assert proper exception:
- tests\Microsoft.Bot.Builder.Tests\Adapters\TestFlowTests.cs

[#4022] Throwing Generic Exceptions - Adaptive Expressions

---

libraries/Microsoft.Bot.Builder.Dialogs.Debugging/CodeModels/CodePoint.cs
libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Events/ExpressionRef.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/MultiLanguageLG.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs
libraries/Microsoft.Bot.Configuration/BotConfiguration.cs
libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/EndorsementsRetriever.cs
libraries/Parsers/Microsoft.Bot.Builder.Parsers.LU/LUResource.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
tests/Microsoft.Bot.Configuration.Tests/ConfigurationLoadAndSaveTests.cs

This PR replaces all 39 generic exceptions found within the libraries `Dialogs.Debugging`, `Dialogs.Declarative`, `LanguageGeneration`, `Configuration`, `Connector`, and `Parsers.LU` with proper exceptions according to the [Standard Exception Types](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/using-standard-exception-types).
- Replaces all 39 generic exceptions within:
- libraries\Microsoft.Bot.Builder.Dialogs.Debugging\
- libraries\Microsoft.Bot.Builder.Dialogs.Declarative\
- libraries\Microsoft.Bot.Builder.LanguageGeneration\
- libraries\Microsoft.Bot.Configuration\
- libraries\Microsoft.Bot.Connector\
- libraries\Parsers\Microsoft.Bot.Builder.Parsers.LU\
- Updates test `ConfigurationLoadAndSaveTests`, `TemplatesTest`, `TemplateDiagnosticTest`, and …

[#4022] Throwing Generic Exceptions - LanguageGeneration

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/TextInput.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_TextInputWithNonStringInput.test.dialog

Fixes #4948 
In adaptive dialog, TextInput action only accept string values, but in some cases, non-string values such as objects will be passed into TextInput action, in such cases, it will throw exceptions instead of throw invalid prompt to users for a valid input. This is not friendly. In this fix, we added the validation of string format for all values and if it's value is not string, it will go into invalid state instead of throwing exceptions. 
- TextInput.cs
Test cases added

Return unrecognized state instead of throwing exceptions for non-string input of TextInput action

---

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorAdaptiveRecognizer.cs
libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs
libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs
libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs
libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs
libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/DialogMemoryScope.cs
libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs
libraries/Microsoft.Bot.Builder/Streaming/StreamingHttpClient.cs
libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs

This PR replaces all 15 generic exceptions found within the _Streaming_ directory of `Bot.Builder` and the libraries `AI.Orchestrator`, `Azure`, and `Dialogs` with proper exceptions according to the [Standard Exception Types](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/using-standard-exception-types).
- Replaces all 15 generic exceptions within:
- libraries\Microsoft.Bot.Builder\Streaming\
- libraries\Microsoft.Bot.Builder.AI.Orchestrator\
- libraries\Microsoft.Bot.Builder.Azure\
- libraries\Microsoft.Bot.Builder.Dialogs\
Here's a screenshot of the tests for these files working correctly with the changes applied:

[#4022] Throwing Generic Exceptions - Azure

---

.github/CODEOWNERS

Testing out simplified codeowners.
The global rule now requests reviews from the **microsoft/botframework-sdk** team.
Select glob patterns also trigger reviews from other teams or individuals in addition to the **microsoft/botframework-sdk**.

simplify CODEOWNERS

---

build/yaml/botbuilder-dotnet-ci-mac.yml
build/yaml/ci-build-steps.yml

Nuget being used was 4.9.1. Now it's 5.8.0.
This fixes the many errors: 
##[error]C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): Error NETSDK1005: Assets file 'D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\obj\project.assets.json' doesn't have a target for 'netstandard2.0'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project.
Apparently brought on by a new version of msbuild being used.

Install later NuGet version for build pipelines

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertNoActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReply.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyOneOf.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/CustomEvent.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/MemoryAssertions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/SetProperties.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserSays.cs

Fixes #4022
This PR replaces all generic exceptions found within `Dialogs.Adaptive.Testing\TestActions`.
- Replaces all generic exceptions within:
- libraries\Microsoft.Bot.Builder.Dialogs.Adaptive.Testing\TestActions
No test coverage for these files.

[#4022] Throwing Generic Exceptions - Dialogs Adaptive Testing

---

build/yaml/ci-api-validation-steps.yml

This PR fixes an issue that was causing the pipelines to fail in the "Insert nuget link into ApiCompat results file." task for the Api Compatibility check.
- Add missing double quotes in the "Insert nuget link into ApiCompat results file." task for the `ci-api-validation-steps.yml` file.

Fix ApiCompat issue causing pipeline failures

---

libraries/Microsoft.Bot.Builder/ActivityHandler.cs
libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs
tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenValidationTests.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpAdapterTests.cs

Fixes #4992 
Allow `AuthenticationConfiguration` as a parameter in `BotFrameworkHttpAdapter` and `BotFrameworkHttpAdapterBase`, as currently only `BotFrameworkAdapter` allows it.

Add constructor that allows AuthenticationConfiguration to BotFrameworkHttpAdapter and BotFrameworkHttpAdapterAdapterBase

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4918

Fix InvalidOperationException text in oauth input and oauth prompt

---

libraries/Microsoft.Bot.Builder/ActivityFactory.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/NormalStructuredLG.lg

Fixes #4991 
To create invoke response using composer and LG requires that the untyped activity.Value has a typed object InvokeResponse in in it.
- Changed ActivityFactory to coerce value to InvokeResponse when the activity Type is a InvokeResponse
- Added unit test to verify coercion.

Fix creating InvokeResponse activities in LG

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptCultureModels.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/PromptCultureModelsTests.cs

Fixes #4981
This is a port of https://github.com/microsoft/botbuilder-js/pull/2534, and it should help adaptive dialogs handle unexpected locales better in Composer
- Implement `PromptCultureModelsTests.ShouldNotThrowWhenLocaleIsNull`
- Fix `MapToNearestLanguage` so that it doesn't throw when the locale is null and so it's more efficient and easier to read and closer to the TypeScript implementation
- Rename `GetCulture` to `DetermineCulture` in `ConfirmInput` and `ChoiceInput` to align with other classes
- Fix `DetermineCulture` in `ConfirmInput` and `ChoiceInput` so that it uses `MapToNearestLanguage`
- Have `DetermineCulture` accept a second parameter in `ChoiceInput` to align with `ChoicePrompt`
- Rework `ConfirmPrompt` and `ChoicePrompt` constructors so that the default choice …

Fix locale determination in confirm/choice inputs

---

libraries/AdaptiveExpressions/BuiltinFunctions/ConvertFromUtc.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

closes: #5003 
Now the default format of ConvertFromUtc are the same as it in WDL, which compiles "yyyy-MM-ddTHH:mm:ss.fffffffK".
See Ref:
https://docs.microsoft.com/en-us/azure/logic-apps/workflow-definition-language-functions-reference#convertFromUtc

Remove offset in default format in ConvertFromUtc pre-built function

---

.github/workflows/create-botbuilder-js-parity-issue.yml

This will remotely trigger the workflow introduced via https://github.com/microsoft/botbuilder-js/pull/3080
This will reintroduce the "Tom Bot" functionality of creating parity issues automatically when pull requests are merged in this repo.
We could certainly add globs to limit the sets of things that trigger parity issues, but I think this will be a good start.
The full source code for the action is available via [joshgummersall/dispatch-workflow](https://github.com/joshgummersall/dispatch-workflow).

feat: create parity issues via github workflow

---

.github/workflows/create-botbuilder-js-parity-issue.yml

Github actions don't have a lot of rich operators or functions to, for
example, construct JSON.
The `dispatch-workflow` action expects a JSON string that includes some
PR metadata (which may include single or double quotes).
In order to make this as simple as possible, but also as flexible as
possible, base64 encode all JSON values before jamming them in the JSON
string.
The `dispatch-workflow` action, then, knows how to decode these values.

fix: use base64 encoded JSON values

---

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorAdaptiveRecognizer.cs
libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs
libraries/Microsoft.Bot.Builder.AI.Orchestrator/Schemas/Microsoft.OrchestratorRecognizer.schema
tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorTests.cs

In 4.11 we deprecated the specific EntityRecognizer concept and instead only have Recognizer (EntityRecognizer base class is now Recognizer).  LuisRecognizer has property **ExternalEntityRecognizer** which is of type Recognizer.  This delta aligns with LUIS, so that you can a recognizer which is run and the results passed into orchestrator for orchestrator to use.
- Replaced **List<EntityRecognizer> EntityRecognizers** property with **Recognizer ExternalEntityRecognizer**
- updated schema
- updated unit tests

Align OrchestratorRecognizer with LuisRecognizer ExternalEntityRecognizer

---

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj

Update the orchestrator-core native dependencies to pick up a linux-related fix (native icu dependencies cannot be found due to naming error), all other OSes unaffected.
- Update `Microsoft.BotFramework.Orchestrator` version to `4.11.0-rc2.preview`

Update Orchestrator Native deps to 4.12 daily builds

---

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs

`Channel.SupportsCardActions` returns false for Telegram when it should return true. This makes no difference when you call `ChoiceFactory.ForChannel` because that prefers suggested actions anyway, but it's important to have `Channel.SupportsCardActions` contain accurate information anyway.

Update Channel.cs to make it clear that Telegram supports card actions

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/EntityAssignment.cs
tests/tests.schema

Fix bug where an operation without properties would get dropped as an assignment.
Preserve expectedEntities for assignments without a property.
Preserve operation when choosing an entity.
Both of these were to support skip as an entity in generation.

Support Skip() as an operation for form generation

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/EntityAssignment.cs

Tom asked for this to be changed from a readonly collection to a list to be consistent with the API.

Switch to list to be consistent with other properties.

---

build/yaml/botbuilder-dotnet-ci-facebook-test.yml
tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot/DeploymentTemplates/template-with-new-rg.json

Adds tags to the provisioned Azure Resource Group for automated management of RGs for the **Facebook adapter tests**.
These tags indicate when and why the Resource Group was created. They also provide pointers to the repository, the source branch and name of the pipeline that was run to better assist other team members with figuring out who to contact.
- Add tags to `az group create` step
- Create `$DateTimeTag` runtime variable in Azure DevOps
- A REST call is required to get the actual pipeline queue time, which didn't seem necessary for the goals of this PR.
- Creating an RG via ARM template also sets the appropriate tags
___

add resource tags to FB adapter CI

---

.github/workflows/create-botbuilder-js-parity-issue.yml

Also supports various parity automation labels in the following ways:
- If a PR does not have any automation labels, a parity issue will be created
- If a PR is marked with just "Automation: No parity", no parity issue will be created
- If a PR is marked with "Automation: No parity" and "Automation: Parity js", a parity issue on the JS repo will be created, and nothing else
With these combinations, we control over what parity issues get created. Also, the default behavior continues to be that a parity issue is created for every "downstream" repo.

feat: parity issues for js, python, and java

---

libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/ActiveObject.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggingBotAdapterExtensions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DialogDebugAdapter.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Events/Events.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Protocol/HasRest.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Protocol/ProtocolMessage.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Transport/DebugTransport.cs
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Transport/IDebugTransport.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/TraceOracle.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/TraceOracles/ProtocolMessages_AreConsistent.json
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/TraceTests.cs

This PR allows the debugger transport to be injectable to
1. simplify the debug adapter code
2. remove implementation inheritance
3. allow unit tests (with mocked transports) for the debug adapter code
- create new IDebugTransport interface
- move code to use IDebugTransport interface
- add first substantial unit test for debug adapter
Yep.

[Debugger] add injectable transport, with unit tests

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.LogAction.schema

Fixes #4988 
The schema definition of field Text is in conflict with the field type in LogAction.cs
Updating the schema definition to IActivityTemplate.

Change LogAction.Text from stringExpression to IActivityTemplate

---

libraries/Microsoft.Bot.Builder.Runtime/Authentication/AllowedCallersClaimsValidator.cs
libraries/Microsoft.Bot.Builder.Runtime/CoreBot.cs
libraries/Microsoft.Bot.Builder.Runtime/Providers/RuntimeConfigurationProvider.cs
tests/Microsoft.Bot.Builder.Runtime.Tests/Authentication/AllowedCallersClaimsValidationTests.cs

Fixes microsoft/botframework-core#24
Fixes microsoft/botframework-core#31
Fixes microsoft/botframework-core#44
- Remove autoEndDialog enforcement for skill bots.
- Instantiate allowed callers claims validation for all bots (host and skill), this is used to validate identity [Claim](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claim?view=net-5.0).
The current implementation enforces the runtime to auto end the root dialog when it is consumed as a skill, but this restricts the bot author from making that decision themselves (setting the autoEndDialog property in the root dialog using Composer). There are two scenarios where the skill dialog needs to end.
1. The skill dialog ends automatically when there are no more actions available in the stack. This will be supported …

Enable skill authentication and default behaviors on core runtime

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5060

Throw a meaningful exception if InputDialog.Prompt is missing

---

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV3.cs

Modifying the `httpClient` default request headers seems a bit more prone to errors and/or side effects than simply constructing a scoped request with its own headers.

fix: request scoped headers for LUIS v3 api calls

---

libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
tests/Microsoft.Bot.Connector.Tests/ConnectorClientTest.cs

Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/4867
Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/5042
Fixes: https://github.com/microsoft/BotFramework-Composer/issues/4828
Fixes: 
https://github.com/microsoft/botbuilder-dotnet/issues/5026
UserAgent:
Currently WITH comment only (web api):
Microsoft-BotFramework/3.1 
BotBuilder/4.0.0.0 
(.NET Framework 4.8.4250.0; Microsoft Windows 10.0.19042 ; X64)
Currently WITH comment ONLY (netcore):
Microsoft-BotFramework/3.1 
BotBuilder/4.0.0.0 
(.NETCoreApp,Version=v3.1; Microsoft Windows 10.0.19042; X64)
Currently WITHOUT comment only (netcore):
Microsoft-BotFramework/3.1 
BotBuilder/4.0.0.0 
FxVersion/4.700.20.41105 
OSName/Windows 
OSVersion/Microsoft.Windows.10.0.19042 …

Remove comment only ProductInfoHeaderValue

---

libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs
libraries/Microsoft.Bot.Builder.Azure/CosmosDbCustomClientOptions.cs
libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorageOptions.cs
libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobTranscriptStoreTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/BlobsStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/BlobsTranscriptStoreTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/TranscriptStoreBaseTests.cs

Fixes an issue brought up by @mrivera-ms and @dandriscoll, similar to #4909 
`Microsoft.Azure.Cosmos` could not be used alongside `Microsoft.Bot.Builder.Azure` without updating the `...Cosmos` package. In fixing this, I also found few other issues, noted below.
- Update `Microsoft.Azure.Cosmos` package used in `Microsoft.Bot.Builder.Azure` library from 3.14.0 (has since been de-listed) to 3.15.1
- Update `Microsoft.Azure.DocumentDB` from 2.1.2 to 2.13.1 since there were no breaking changes and [the changelog](https://github.com/Azure/azure-cosmos-dotnet-v2/blob/master/changelog.md) noted quite a few performance improvements.
- Change from `cref:<packageReference>` to `href:<urlReference>`
- This was a weird one that I couldn't seem to fix. The `cref` correctly addressed the appropriate …

Update Cosmos, fix Azure tests

---

build/yaml/botbuilder-dotnet-ci-webex-test.yml

Webex Functional Tests fail intermittently during the restore stage of `dotnet publish`. This change modifies the verbosity of the command to aid in investigations.

Add verbosity for diagnosis of Webex Functional tests failures

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs

Using `expectingInput` while `inputHint` property is not assigned of prompt property in InputDialog. Otherwise, keep it as it is.
Original issue links:
https://github.com/microsoft/botbuilder-js/issues/3195
https://github.com/microsoft/botbuilder-js/issues/1776#issuecomment-733418246
Original j pr:https://github.com/microsoft/botbuilder-js/pull/3196

Allow customize inputHint via prompt property

---

FunctionalTests/ExportedTemplate/template-with-new-rg.json
build/yaml/botbuilder-dotnet-ci-slack-test.yml
build/yaml/botbuilder-dotnet-ci-webex-test.yml
build/yaml/botbuilder-dotnet-functional-test-windows.yml
tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/DeploymentTemplates/template-with-new-rg.json
tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.TestBot/DeploymentTemplates/template-with-new-rg.json

Fixes #5032 
Add tags to Azure resource groups with metadata that's handy for debugging.
*Azure Portal View of Resource Group with Tags*
<details>
<summary>AZ CLI View</summary>
```json
{
"id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/NightlyWinTestBotRG",
"location": "westus",
"managedBy": null,
"name": "NightlyWinTestBotRG",
"properties": {
"provisioningState": "Succeeded"
},
"tags": {
"buildName": "BotBuilder-DotNet-Functional-Tests-Windows-yaml",
"cause": "automation",
"date": "2021-01-12T07:19:18Z",
"product": "microsoft/botbuilder-dotnet",
"sourceBranch": "refs/heads/Zerryth/azg-tagging"
},
"type": "Microsoft.Resources/resourceGroups"
}
```
</details>
Added to following dotnet functional test pipelines:
- Slack 
- Webex 
- Windows

Tag Resource Groups in DevOps Pipelines

---

build/yaml/botbuilder-dotnet-ci-webex-test.yml

Fixes #5123 
Added the nuget restore to the yaml file. It will restore the nuget packages, this change is for intermittent issue to get libraries ( error NU1101: Unable to find package. ).
- Added nuget restore task in the yaml

Add nuget restore to botbuilder-dotnet-ci-webex-test.yml for Azure Pipelines

---

build/yaml/botbuilder-dotnet-ci.yml
build/yaml/ci-api-validation-steps.yml

This PR adds support for excluding classes from the API Compatibility checks.
We introduced a new pipeline variable (`ApiCompatExcludeClasses`) that will let you define a comma separated list of excluded classes. Each class has to be defined as **[Package]+[Class]**, e.g. `Microsoft.Bot.Builder.AdapterExtensions, ...`
Then, the Compare Binaries task has been modified to not fail on issue leaving the pipeline with a **SuccessWithIssues** state when it founds compatibility issues.
Finally, a new PowerShell task will compare the compatibility issues found on the previous step with the list of excluded classes. If all issues have been excluded, the task will set the status as **Success**, otherwise it will be set as **Failed**.
- Updated `Compare Binaries` task on …

[Api Compat] Add support for excluding classes in compatibility check

---

libraries/Microsoft.Bot.Builder.Runtime/Extensions/ConfigurationBuilderExtensions.cs

This change adds support to optionally specify a relative directory path to search for appsettings.json within. It also removes an extraneous call to add environment variables as a configuration provider to the builder, as it is already added by the default host builder.
- Add additional prototype to ConfigurationBuilderExtensions.AddBotRuntimConfiguration() to support specifying relative directory path containing appsettings.json.
- Removing call to builder.AddEnvironmentVariables(), as this is already in the default builder created by Host.CreateDefaultBuilder().
Intend to manually verify with an update to the runtime generator once package is published. No breaking changes are expected.

Runtime ConfigurationBuilderExtensions changes

---

build/yaml/botbuilder-dotnet-ci-facebook-test.yml
build/yaml/botbuilder-dotnet-ci-slack-test.yml
build/yaml/botbuilder-dotnet-functional-test-linux.yml
build/yaml/botbuilder-dotnet-functional-test-windows.yml

Fixes #5123
Added the nuget restore to the yaml file. It will restore the nuget packages, this change is for intermittent issue to get libraries ( error NU1101: Unable to find package. ).
- Added nuget restore task in the yaml to fix the intermittent issue.

Update Functional tests yaml for Azure Pipelines

---

tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/TestScriptTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/TestScriptTests_UserActivity.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/TestScriptTests_UserTyping.test.dialog

There wasn't an existing test for UserActivity. Since I add one [in this JS PR](https://github.com/microsoft/botbuilder-js/pull/3187), I figured I should add it here, as well.

Add UserActivity test

---

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceTests.cs
tests/tests.schema

Fixes #4821
Set resource id as the default dialog id in loaded dialog memory when the id is not specified in dialog definition
- Change AutoAssignId function in ResourceExplorer.cs to assign id to loaded dialog json token
Unit test is added in ResourceTests.cs

Fix dialog id is not default set to resource id issue when LoadType = AdaptiveDialog

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5103

When input is invalid, only send responses to message types in OAuthInput 

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/Converters/DialogExpressionConverter.cs
libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs
libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogManagerTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogSetTests.cs

- **DialogSet:** Telemetry client setter leading to StackOverflowExceptions on any cyclical dialog structure. Affects traditional component dialogs, coded adaptive dialgs and could affect declarative dialogs
- **DialogManager:** Recursive registration of dependencies, on cyclical dialog structures could lead to stackOverflowException
- **Type loading:** Cache DialogExpression instances to improve performance, fix debugger which requires a single instance for an id, and catch special cases that can break type loading of cyclical dialog structures (fixes https://github.com/microsoft/botframework-sdk/issues/6094). In a future change for debugging we'll enforce all instances to be unique during type loading, but that will be part of a larger change to also support richer debugging semantics. …

Cyclical dialog graphs: Bug fixes and improvements in DialogSet, DialogManager and Type Loading

---

libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
libraries/Microsoft.Bot.Builder/TokenResolver.cs
libraries/Microsoft.Bot.Builder/TurnContext.cs
libraries/Microsoft.Bot.Builder/TurnContextStateCollection.cs

turn context and turn state dispose
Rather than relying on turnContext.TurnState.Set(null); to detect later errors, the correct behavior is to to directly detect the later invalid access.

added disposed

---

tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/TestScriptTests_PropertyMock.test.dialog

The MemoryAssertions tests were silently failing. They'll now pass and also elicit errors if they fail. You can see it in the original code if you throw a breakpoint [here](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/MemoryAssertions.cs#L64).
- Removed `new KeyValuePair<string, string>("fileoverwrite", "this is overwritten")`. `settings` is an `ImmutableDictionary` and cannot be overwritten. 
- --->>>>	**This may be an error in ObjectPath.cs**, but I don't know enough about this to say for sure. <<<<----
- Added an `OnError` trigger for the PropertyMock test script. It would otherwise silently swallow errors.
- Adjusted what memory properties get written and overwritten.
**Note: There's a similar issue in JS …

Fix MemoryAssertions test

---

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisUtil.cs
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisUtilTests.cs

Fixes Issue#3568 utterance smaller than entity indexes
This pull request is a follow up on a [previous pull request](https://github.com/microsoft/botbuilder-dotnet/pull/4456) that was closed due to inactivity.
It fixes the [issue #3568](https://github.com/microsoft/botframework-solutions/issues/3568), adding the requested unit tests.
Adds a verification on the utterance length when setting the Entity text in the class LuisUtil. The current behavior is only modified for utterance with a length smaller than the entity. We followed the suggestion made on the previous pull request where the utterance is returned when it is shorter than the entity.
We added tests for both current and new behaviors.

fix Issue#3568 utterance smaller than entity indexes

---

libraries/Microsoft.Bot.Builder/BotAdapter.cs

Abstract class updates for https://github.com/microsoft/botbuilder-dotnet/issues/5087

add continue with activity to BotAdapter abstract class

---

libraries/AdaptiveExpressions/BuiltinFunctions/Abs.cs
libraries/AdaptiveExpressions/BuiltinFunctions/Sqrt.cs
libraries/AdaptiveExpressions/ExpressionFunctions.cs
libraries/AdaptiveExpressions/ExpressionType.cs
tests/AdaptiveExpressions.Tests/BadExpressionTests.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

Fixes #5114
Add `abs` and `sqrt` prebuilt function.
Example:
```
abs(3.12134)  -> 3.12134
abs(-3.12134) -> 3.12134
abs(0) -> 0
sqrt(9) -> 3
sqrt(-1)  -> throw error
sqrt(0) ->  0
```

[Expression]Add abs and sqrt built- in function

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ContinueConversation.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ContinueConversationLater.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/GetConversationReference.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.ContinueConversation.schema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.GetConversationReference.schema
libraries/Microsoft.Bot.Builder/QueueStorage.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ContinuationTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ConversationActionTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MockQueue.cs

We have **ContinueConversationLater** action which allows you to take the current conversation and schedule it for later, but we don't have the ability to continue a specific conversation later.  This delta adds that, and fixes comments and bugs discovered in the process of adding that 
If you want to have the current conversation continue an hour from now you use **ContinueConversationLater**.  This writes to an azure queue a message which will be processed in an hour, and when that happens **OnContinueConversation** trigger will fire.
This PR enables switching conversations.  Say you have 2 conversations, A and B.
A -> **GetConversationReference** captures a **ConversationReference(A)** that you can store in some shared state
B -> wants to continue that conversation, so gets the …

Added GetConversationReference/ContinueConversation actions

---

libraries/Microsoft.Bot.Builder.Runtime/ConfigurationConstants.cs
libraries/Microsoft.Bot.Builder.Runtime/Extensions/ConfigurationBuilderExtensions.cs

As part of the adaptive runtime integration process with Composer, changes are being made to no use the ComposerDialogs folder in non-development environments as the bot root. Additionally, adding Orchestrator generated settings as a configuration source in order to support the Orchestrator recognizer plugin.
- Removal of 'bot' application setting.
- Removal of 'isDevelopment' flag from ConfigurationBuilderExtensions::AddBotRuntimeConfiguration extension methods.
- Use application root in all environments.
- Add Orchestrator generated settings as configuration source.
Pending manual validation through Composer integration testing.

feat: Runtime Configuration Builder Updates

---

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorAdaptiveRecognizer.cs
libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs
libraries/Microsoft.Bot.Builder.AI.Orchestrator/Schemas/Microsoft.OrchestratorRecognizer.schema
tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorTests.cs

Note: This checkin associated with :
- Nodejs Orchestrator recognizer update ([nodejs pr](https://github.com/microsoft/botbuilder-js/pull/3251))
- A samples update that uses Orchestrator recognizer ([samples pr](https://github.com/microsoft/BotBuilder-Samples/pull/3062))
- Composer updates (@taicchoumsft : Will submit once new SDK released)
- bf-cli updated (@tsuwandy checked in updates)
From the first preview, we've received feedback that our parameter names are confusing. 
This performs the following parameter renames:
modelPath => modelFolder
snapshotPath => snapshotFile
Tests have been updated to reflect new parameter names.

Orchestrator Recognizer: Rename misleading parameter names

---

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs
libraries/Microsoft.Bot.Connector/Authentication/ParameterizedBotFrameworkAuthentication.cs
libraries/Microsoft.Bot.Connector/ConversationsEx.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkHttpAdapter.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenValidationTests.cs

Fixes #4833
Remove the references to this code that was made redundant in the last release.

remove references to TrustServiceUrl

---

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpClientTests.cs

When callling /api/messages the return type is always a **InvokeResponse&lt;T&gt;** data structure.
When a skill receives an activity with **deliveryMode=expectReplies**, the **botframeworkAdapter** caches all outbound activities and returns them as a **InvokeReponse&lt;ExpectedReplies&gt;** :
```
{
"status": status code
"body": { // type expectedReplies
"activities": [... ]
}
}
```
This is the correct speced behavior.
The bug is that the **BotFrameworkHttpClient** code is interpreting the body of the response as **ExpectedReplies** instead of **InvokeResponse&lt;ExpectedReplies&gt;**
The properties don't align and hence the activities are dropped on the floor.
The unit tests test both sides independently but with mismatched assumptions, so only when e2e is used it doesn't work. (classic …

Fix deliveryMode.ExpectReplies for skills.

---

libraries/AdaptiveExpressions/BuiltinFunctions/Equal.cs
libraries/AdaptiveExpressions/BuiltinFunctions/Sqrt.cs

Fixes: #5114
Reference: https://github.com/microsoft/botbuilder-dotnet/issues/5114#issuecomment-766661900
- Change the minimal value of float/double to `double.Epsilon`
- Fix typo

Use double.Epsilon for equal check in expression

---

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpClientTests.cs

Reverts microsoft/botbuilder-dotnet#5142
We did some end to end testing on this and I think the assumption of the original PR is incorrect. 
When the callers requests deliveryMode ExpectReplies, the adapter returns an InvokeResponse where the body is of type ExpectReplies, not of type InvokeResponse<ExpectPreplies> see: 
https://github.com/Microsoft/botbuilder-dotnet/blob/a5d63d2df90827718d4af2b897033a10034c38f4/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L457

Revert "Fix deliveryMode.ExpectReplies for skills."

---

libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogManagerTests.cs

Updated DialogManager to return EoC code (as RunAsync does) and updated tests

---

libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs
tests/Microsoft.Bot.Builder.Tests/BotFrameworkHttpAdapterBaseTests.cs

Fixes #5110
Added unit tests for null and non-null StreamingRequestHandler.Audience.

fix: null audiences/OAuthScopes shouldn't break streaming

---

libraries/AdaptiveExpressions/BuiltinFunctions/StringOrValue.cs
libraries/AdaptiveExpressions/ExpressionFunctions.cs
libraries/AdaptiveExpressions/ExpressionType.cs
tests/AdaptiveExpressions.Tests/BadExpressionTests.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

Fixes #5009
Introduce a new built-in function that refers to smart interpolation.
The original requirements are:
- when user input is a simple variable, like `${name}` or `${age}`, it should evaluate as a single variable and the return type is the variable type (int\float\string, it could vary)
- when user input is text + variables, like `${age} is too big`, it should evaluate as a string intepolation, and always return a string type 
Samples:
`stringOrValue('${2+3}')` -> 5
`stringOrValue('woof is ${3+5}')` would produce 'woof is 8'.
Create a new function that can evaluate the value expression smartly.

[Expression]Add stringOrValue built-in function

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnChooseEntity.schema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnChooseProperty.schema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnChooseEntity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnChooseProperty.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ChooseEntityTests/ChooseEntity.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ChooseEntityTests/LuisChooseEntity-bread2.mock.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ChooseEntityTests/LuisChooseEntity-wheat.mock.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ChooseEntityTests/LuisChooseEntity-whole wheat.mock.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ChooseEntityTests/cachedResponses/=`00000000-0000-0000-0000-000000000000`/550341391.json
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ChooseEntityTests/oneProperty.json
tests/tests.schema

Fixes #5177 
In writing the documentation for OnChooseEntity and OnChooseProperty I realized the operation was missing from OnChooseEntity and none of the properties for OnChooseProperty were used or even made sense.  This updated both the class and the schema.  These events are only fired if there is a schema and the only current source of schema is form generation which has not been released or documented yet.
Improved the OnChooseEntity test to make sure filter properties work.

Clean-up OnChooseEntity and OnChooseProperty schemas and classes

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/EntityAssignment.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/EntityAssignmentComparer.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnAssignEntity.schema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnChooseEntity.schema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnAssignEntity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnChooseEntity.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AskTests/AskRetriesAssign.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AskTests/AskRetriesOnChooseEntity.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AskTests/AskRetriesOnChooseProperty.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AskTests/DefaultOp.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AssignEntityTests/AddEntity.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AssignEntityTests/ClearEntity.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AssignEntityTests/RemoveEntity.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ChooseEntityTests/ChooseEntity.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ChoosePropertyTests/ChooseProperty.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/GeneratorTests/sandwich/en-us/library/sandwich-library-Choose.en-us.lg
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/GeneratorTests/sandwich/sandwich.dialog
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaTestsFixture.cs
tests/tests.schema

Both operation and property are also entities so it was strange to have an entity property--renaming it to value makes the intent clearer.

Rename entity to value in form related triggers 

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnActivity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnBeginDialog.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnCancelDialog.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnChooseIntent.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnConversationUpdateActivity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnDialogEvent.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnEndOfConversationActivity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnError.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnEventActivity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnHandoffActivity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnIntent.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnInvokeActivity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnMessageActivity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnMessageDeleteActivity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnMessageReactionActivity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnMessageUpdateActivity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnQnAMatch.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnRepromptDialog.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnTypingActivity.uischema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnUnknownIntent.uischema

Follows #4341 
Follows #5099 
In #4341, we port the ui schema `form` part to runtime in order to support the customization of Composer Form Editor;
In #5099, we port the ui schema `flow` part to support the customization of Action UI;
in this PR, the `trigger` part is added to runtime as well to support the customization of Composer's Trigger creation wizard.
Refs ui.schema definition change in SDK repo: https://github.com/microsoft/botframework-sdk/pull/6178
- OnActivity
- OnBeginDialog
- OnCancelDialog
- OnChooseIntent
- OnConversationUpdateActivity
- OnDialogEvent
- OnEndOfConversationActivity
- OnError
- OnEventActivity
- OnHandoffActivity
- OnIntent
- OnInvokeActivity
- OnMessageActivity
- OnMessageDeleteActivity
- OnMessageReactionActivity
- OnMessageUpdateActivity
- OnQnAMatch
- …

uischema: port uischema 'trigger' part to component schema files

---

libraries/Parsers/Microsoft.Bot.Builder.Parsers.LU/NewEntitySection.cs
tests/Parsers/Microsoft.Bot.Builder.Parsers.LU.Tests/Fixtures/testLU310.json
tests/Parsers/Microsoft.Bot.Builder.Parsers.LU.Tests/Fixtures/testLU310.txt
tests/Parsers/Microsoft.Bot.Builder.Parsers.LU.Tests/Microsoft.Bot.Builder.Parsers.LU.Tests.csproj
tests/Parsers/Microsoft.Bot.Builder.Parsers.LU.Tests/Parser/LuParserTests.cs

PVA reported and issue when parsing list entities with dashes in the synonyms list.
The fix changes the parsing of the synonym String and adds a test to cover this scenario.

Fixing synonym parsing in list entity

---

libraries/AdaptiveExpressions/BuiltinFunctions/TitleCase.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

Fixes #5235
The default [ToTitleCase](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.textinfo.totitlecase?view=netcore-3.1) could not cover all cases. It would convert the first letter following the number to the upper case. It is not correct.
Add additional rules to make `titleCase` more accurate.

fix the bug about built-in function 'titleCase'

---

libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/Extensions/ServiceCollectionExtensions.cs
tests/integration/Microsoft.Bot.Builder.Integration.Runtime.Tests/Extensions/AdapterRegistrationTests.cs

Runtime: Fix bug in CoreAdapter registration. SkillHttpClient needs a BotAdapter registered (#5241)
Fixes #
- 
-
-

cherry-pick to 4.12: Runtime: Fix bug in CoreAdapter registration. SkillHttpClient needs a BotAdapter registered

---

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptCultureModel.cs

Had some extra text in the comments that shouldn't be there. Removed.
Fixes: #5252

Remove bad copy/paste in comments

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/EntityInfo.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnCondition.schema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/FirstSelector.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCondition.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/SelectorTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/SelectorTests/SelectorTests_Float_Priority.test.dialog

closes: #5082 
Now the priority in triggers is float number, where 0 is the highest and less than 0 is ignored.
The `priority` property in OnCondition now is NumberExpression, the default value is 0.

Switch priority in triggers to float type

---

libraries/AdaptiveExpressions/parser/ParserErrorListener.cs
tests/AdaptiveExpressions.Tests/BadExpressionTests.cs

Fixes #5256
The error thrown by `Antlr` is not readable for non-developer users. Change it to the general expression format error.

Make syntax error message more readable in Expression

---

libraries/Microsoft.Bot.Builder.LanguageGeneration/Template.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplatesParser.cs
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs

Fixes #5181
For some requirements from Composer side. Describe here:
Structure LG parsed result should cover the common key/value pairs results.
For example:
```
[Activity
Text=good
Speak=hi
]
```
The parsed Template would contains a property named `properties`, in which would contains:
```
properties: {Text: "good", Speak:"hi", $type:'Activity'}
```
- Pure Expression reference would be ignore
```
[A
key1=value1
${T2()}     -> this one would be ignored
]
```
- would keep the origin list info
```
[A
list = a | b
]
```
the properties would be:
`{list: ['a', 'b'], $type: 'A'}`

[PORT]Add properties property for Template class

---

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj

Update Orchestrator Recognizer to point at 4.12.0-preview instead of 4.12.0-rc1.preview.
(There are no code changes between the two packages - just using the correct version).

Update Orchestrator package to point at correct label version

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioClientWrapper.cs
libraries/AdaptiveExpressions/ExpressionProperties/ExpressionProperty.cs
libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorAdaptiveRecognizer.cs
libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs
libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ContinueConversationLater.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceSet.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ChoiceInput.schema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ConfirmInput.schema
libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/BotStateMemoryScope.cs
libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
libraries/Microsoft.Bot.Builder/MemoryTranscriptStore.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests.csproj
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_ChoiceInput_ComplexTemplate_en.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_ChoiceInput_ComplexTemplate_es.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_ChoiceInput_SimpleTemplate_en.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_ChoiceInput_SimpleTemplate_es.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_ConfirmInput_ComplexTemplate_en.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_ConfirmInput_ComplexTemplate_es.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_ConfirmInput_SimpleTemplate_en.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_ConfirmInput_SimpleTemplate_es.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/test.en.lg
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/test.es.lg
tests/tests.schema

* Make ChoiceSet  implement ITemplate<ChoiceSet>
Fix ExpressionProperty Throw in Try method that shouldn 't throw
Updated ConfirmInput and ChoiceInput to use ITemplate>.BindData() if expression is template reference.
Added unit tests
* update schema
* fix schema definition for choices
Fixes #
- 
-
-

Cherry-Pick to 4.12: Change ChoiceSet to support LG (#5309)

---

libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs
libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs
tests/Microsoft.Bot.Builder.Azure.Tests/TranscriptStoreBaseTests.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5271

Log missing update activity and fix infinite loop

---

tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaTestsFixture.cs
tests/tests.schema

We have tests that merge all schemas and then test dialog files against them.  This only works if people run tests locally before they check-in.  This changes the behavior so the tests will fail on the builder server if the schema changes. This was tested by uploading with a bad schema (which failed) and then uploading the updated schema (which succeeded.)

Enforce that tests.schema must be up to date 

---

libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogExtensionsTests.cs

add TelemetryClient to Dialog used in RunAsync

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/ActivityTemplate.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/TextTemplate.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs

Fixes #5102
Originally, while user wants to apply LG template feature in AdaptiveDialog, he/she should add a specific LG resource in `Generator` property.
It does not align with the current design pattern. It's good to have the data binding work ootb, and by adding a default empty TemplateEngine, AdaptiveDialog can leverage the capability of LG engine to do data binding (though lg file is empty). That's also kind of naturally aligned with current design

Assign a default  TemplateEngineLanguageGenerator to Generator

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs

Fixes #5360 
Adds missing ObjectExpressionConverters to the SDK to support properties on the SendHandoffActivity adaptive action.

Add ObjectExpressionConverters to support Send Handoff Activity action

---

libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
tests/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj

Refs https://github.com/dotnet/runtime/issues/49377#affected-software
Fixes #5356 
System.Text.Encodings.Web has security issues needs to be fixed. 
Most of our libraries don't directly depend on this particular package, in most cases, we depend on it via asp.net core. And after .net core 3.0, the asp.net core is built-into .net core runtime, so usually user just have to update the .net core runtime in their end, we should be OK. 
One exception is in this particular package, we depend on "Microsoft.ApplicationInsights.AspNetCore" and then later depend on this offending package via package reference, which can't be solved by updating runtime. 
So, in this fix, i override the transient dependency directly. 
See also https://github.com/microsoft/BotFramework-Composer/pull/6548
After the fix

Fix CVE-2021-26701

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveBotComponent.cs

Originally added as part of this PR: https://github.com/microsoft/botbuilder-dotnet/pull/5361/files
Now ported these converters to the new model.

Hand-off: add converters to support hand off action

---

libraries/Microsoft.Bot.Builder/Skills/SkillHandlerImpl.cs
tests/Microsoft.Bot.Builder.Tests/Skills/CloudSkillHandlerTests.cs

Fixes #5314
Updated SkillHandleImpl to process Command and CommandResult activities based on the spec.
In this PR, I also refactored the CloudSkillHandlerTests class by moving duplicated code and mocks inside a private CloudSkillHandlerTestMocks class.
I also found out that assertions in Moq based objects don't work (see [this](http://blachniet.com/blog/assertions-in-moq-callbacks/) for more details) so changed the implementation to capture internal state in the mock callback methods and moved the assertions to the main test methods.

Adds skill processing for commands

---

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs
libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptions.cs
libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV2.cs
libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV3.cs
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisOracleTests.cs
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisV3OracleTests.cs

Fixes #4157
In the linked issue, there's some discussion about whether or not this change is wanted, but no resolution. Personally, I think this would be very useful, but I'm not happy with:
* This being the only `RecognizeAsync()` method that doesn't use any telemetry. It *could*, but LUIS telemetry currently requires `TurnContext`, so it would necessitate more changes
* There were quite a few methods/overrides that had to be added to get this to work, whereas it seems like a relatively simple request. I'm not super C# smart and don't work in the AI library much, so maybe there's a better way?
Allows developers to call `<LuisRecognizer>.RecognizeAsync(<utterance>)` without providing `TurnContext`, giving them more flexibility integrating LUIS with their bot.

Allow LuisRecognizer to recognize without turnContext

---

libraries/Microsoft.Bot.Builder/FileTranscriptLogger.cs
tests/Microsoft.Bot.Builder.Tests/FileTranscriptTests.cs
tests/Microsoft.Bot.Builder.Tests/TranscriptBaseTests.cs

The `FileTranscriptLogger` has a bug when it's being used in a bot that is being tested locally from the Bot Framework Emulator.
The problem is that the logger is trying to create a transcript file with the following name format: `<conversationId>.transcript`. But when you are talking to the from the Emulator, the conversation ID is set by the Emulator to strings like this: `8b6e9a80-3c94-11eb-83c4-83172d04969b|livechat`.
I have no idea about Linux/Mac (and a bit lazy right now to check :)), but I am 100% sure that on Windows, the `|` character is not a valid character in a filename (it's before the `livechat` part in the above example), thus the `FileTranscriptLogger` will fail to log any activities to the filesystem. Worst of all, it does this silently, leaving almost zero traces of the …

Fix FileTranscriptLogger

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialogBot.cs
libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/ConfigurationAdaptiveDialogBot.cs
tests/Auth/bot-authentication/Akhenaten.cs
tests/Auth/bot-authentication/AuthenticationBot.csproj
tests/Auth/bot-authentication/Startup.cs
tests/Auth/bot-authentication/hello.dialog

For migration we can easily have the bot pick up any Dialogs from the services collection and add them to the AdaptiveDialog's Dialogs property.
This way a package containing coded dialogs could trivially wrap them in a ComponentDialog and then AddSingleton that to the services collection where it can be invoked with the BeginDialog action. See the Auth test project - it runs a ComponentDialog this way.
This is a small non-breaking change.
Incidentally testing this I found the error handling within the AdaptiveDialog world not particularly friendly but that's a different matter and can be addressed independently.

have AdaptiveDialogBot pick up Dialogs from services collection

---

libraries/AdaptiveExpressions/BuiltinFunctions/Empty.cs
libraries/AdaptiveExpressions/FunctionUtils.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

Fixes #5337
The [doc](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#empty) of `empty` shows that if the input is null, `true` would be given.
Example:
```
empty(null)   -> true
```

Support null for buildin function empty

---

libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerBotComponent.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/AdaptiveTestingBotComponent.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/AdaptiveTestingComponentRegistration.cs

Converted AdaptiveTestComponentRegistration to AdaptiveTestingBotComponent.  Obsoleted AdaptiveTestComponentRegistration  and changed to extend DeclarativeComponentRegistrationBridge.
This could be cherry picked to 4.13.  Required to convert old test cases using AdaptiveTestComponentRegistration and correct QnAMakerBotComponent
For QnAMakerBotComponent, the original code in QnAMakerComponentRegistration was:
```
/// <summary>
/// Gets JsonConverters for DeclarativeTypes for QnAMaker.
/// </summary>
/// <param name="resourceExplorer">resourceExplorer to use for resolving references.</param>
/// <param name="sourceContext">SourceContext to build debugger source map.</param>
/// <returns>enumeration of json converters.</returns>
public IEnumerable<JsonConverter> …
```

Added AdaptiveTestingBotComponent

---

libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs
libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/SettingsMemoryScope.cs
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Startup.cs
tests/Microsoft.Bot.Builder.AI.QnA.Tests/Startup.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Startup.cs
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/Startup.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/Startup.cs

SettingsScope was not working in a backward compatible way because of 3 subtle things happening simultaneously:
- `DialogStateManager` was registering the `DialogcomponentRegistration` by itself
- We removed `IConfiguration` from the turnState, so legacy `SettingsMemoryScope` did not have access to configuration in turn state (so the registration in dialog state manager was not getting any settings)
- `SettingsMemoryScope` only gets evaluated once
Here we remove the `DialogStateManager` call to `DialogComponentRegistration` since this is the last call to `ComponentRegistration` in non-test code. Legacy code will still work because legacy adapters still add `IConfiguration` to the turnState. New code will use the new route.
Also, fixing a breaking change where we would break folks using …

Settings scope: support backward compat setting scope, remove ComponentRegistration in DialogStateManager

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs
libraries/Microsoft.Bot.Builder/SetSpeakMiddleware.cs
libraries/Microsoft.Bot.Connector/Channels.cs
tests/Microsoft.Bot.Builder.Tests/SetSpeakMiddlewareTests.cs

Fixes #5403 
- Removes the lang argument from the SetSpeakMiddleware implementation to align with the current implementation in the Composer runtime (https://github.com/microsoft/BotFramework-Composer/blob/ea04f990e0b675b8ce35f315d5a6c1d6264ae525/runtime/dotnet/core/SetSpeakMiddleware.cs)
- Update adaptive runtime ServiceCollectionExtensions class to ensure middleware is added correctly.
- Also added telephony to the channel constants.
Once this is merged the adaptive runtime implementation will need to be updated to remove the argument when adding the middleware.

SetSpeakMiddleware - remove lang argument

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs
libraries/Microsoft.Bot.Builder/SetSpeakMiddleware.cs
libraries/Microsoft.Bot.Connector/Channels.cs
tests/Microsoft.Bot.Builder.Tests/SetSpeakMiddlewareTests.cs

- Removes the lang argument from the SetSpeakMiddleware implementation to align with the current implementation in the Composer runtime (https://github.com/microsoft/BotFramework-Composer/blob/ea04f990e0b675b8ce35f315d5a6c1d6264ae525/runtime/dotnet/core/SetSpeakMiddleware.cs)
- Update adaptive runtime ServiceCollectionExtensions class to ensure middleware is added correctly.
- Also added telephony to the channel constants.
Once this is merged the adaptive runtime implementation will need to be updated to remove the argument when adding the middleware.

[Cherry Pick 4.13] Update SetSpeakMiddleware to remove lang aligned with existing runtime (#5404)

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
libraries/Microsoft.Bot.Builder/Skills/SkillConversationIdFactory.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_ParentBotInterruption.test.dialog
tests/Microsoft.Bot.Builder.Tests/Skills/SkillConversationIdFactoryTests.cs

Cherry for #5426 into 4.13 branch

ResumeDialog is not called after resumption with adaptivedialog  (#5426)

---

libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs
libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogManagerTests.cs

pass through StateConfiguration in DialogManager

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ConfigurationBuilderExtensions.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests/Extensions/ConfigurationBuilderExtensionsTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests.csproj

Fixes #5438 
Replaced HostBuilderContext parameter in ConfigurationBuilderExtensions.AddBotRuntimeConfiguration() extension method by explicit EnvironmentName (optional) in order to support azure functions and dotnet core apps.
The generatos will need to pass the environment parater as follows: 
``` csharp 
public static IHostBuilder CreateHostBuilder(string[] args) =>
Host.CreateDefaultBuilder(args)
.ConfigureAppConfiguration((hostingContext, builder) =>
{
var applicationRoot = AppDomain.CurrentDomain.BaseDirectory;
var settingsDirectory = "settings";
var environmentName = hostingContext.HostingEnvironment.EnvironmentName;
builder.AddBotRuntimeConfiguration(applicationRoot, settingsDirectory, environmentName);
builder.AddCommandLine(args);
})
.ConfigureWebHostDefaults(webBuilder =>
{ …
```

Remove HostBuilderContext parameter from AddBotRuntimeConfiguration()

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ConfigurationBuilderExtensions.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests/Extensions/ConfigurationBuilderExtensionsTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests.csproj

Replaced HostBuilderContext parameter in ConfigurationBuilderExtensions.AddBotRuntimeConfiguration() extension method by explicit EnvironmentName (optional) in order to support azure functions and dotnet core apps. (#5439)

Cherry pick Remove HostBuilderContext parameter from AddBotRuntimeConfiguration() #5439  Merged

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Settings/TelemetrySettings.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests/Extensions/TelemetryRegistrationTests.cs

Fixes #5455 
Change the RT "telemetry" config to read ApplicationInsightsServiceOptions instead of just InstrumenationKey.  This allows for the full range of ApplicationInsights control.
Alternative would be to change from "instrumentationKey" to "connectionString".  But the former is consistent with how we handle the CosmosDb options.
New appsettings would be:
```
"runtimeSettings": {
"telemetry": {
"options": {
"connectionString":  "imaconnectionstring"
},
"logActivities": true,
"logPersonalInformation": false
}
}
```
Though, this would "work":
```
"runtimeSettings": {
"telemetry": {
"options": {
"instrumentationKey":  "imainstrumentationkey"
},
"logActivities": true,
"logPersonalInformation": false
}
}
```
This is the original config:
```
"runtimeSettings": {
"telemetry": { …
```

Runtime: Using ApplicationInsightsServiceOptions to initialize telemetry.

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Settings/TelemetrySettings.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests/Extensions/TelemetryRegistrationTests.cs

[Cherry Pick 4.13] Runtime uses connectionString for ApplicationInsights

---

libraries/Microsoft.Bot.Schema/OAuthCard.cs

Fixes #5460
This PR adds the missing JsonProperty attribute to the [TokenExchangeResource](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/OAuthCard.cs#L57) property of the OAuthCard class.
- Updated **_OAuthCard_** class to add JsonProperty name to _TokenExchangeResource_ property.
This image shows the test passing after the change.

[#5460][OAuthCard] TokenExchangeResource property is missing JsonProperty attribute name

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj

#minor
This makes csproj files for adapters consistent with the other cs proj by:
- Include schemas and ui schemas the way other csproj do. Example from established project (adaptive dialogs): https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj#L32
- Get all content in a single folder to avoid duplication (which makes schemamerge fail). Example from established project (adaptive dialogs): https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj#L17

SDK Adapters: include schemas guaranteeing no duplicates in package

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Microsoft.AdaptiveDialog.schema
tests/tests.schema

#minor 
bf dialog:merge was updated to always use en sorting to make it more stable across dev boxes.  This caused some order changes in tests.schema that need to be checked-in. 
Fix documentation bug in adaptive dialog schema.

Update test.schema to match normalized sort.

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs

Runtime: Allow components and startup overriding IBot and IBotTelemetryClient

---

libraries/Microsoft.Bot.Connector/Channels.cs

#minor
Alexa its now a channel supported by the Bot Builder. 
This manner we can check Channel Id using this Alexa constant
before:
```csharp
if (activity.ChannelId == "alexa")
```
after:
```csharp
if (activity.ChannelId == Channels.Alexa)
```
Alexa Channel Id added

Alexa Channel Id added

---

libraries/Microsoft.Bot.Builder/CloudAdapterBase.cs

Fixes #5491 
Removes the null argument check when constructing creds for ContinueConversationAsync to ensure it can be called without an AppId.

Update to ensure ContinueConversationAsync works with an empty AppId

---

libraries/Microsoft.Bot.Builder/CloudAdapterBase.cs

Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/5491
* Update to ensure ContinueConversationAsync works with an empty AppId
* Default botAppId to string.Empty

CherryPick to 4.13: Update to ensure ContinueConversationAsync works with an empty AppId(#5515)

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SignOutUser.cs

Fixes #5528
Adds logic to call UserTokenClient if its found on the TurnContext (which it will be if CloudAdapter was used) otherwise falls back to old logic of attempting to cast the adapter to the IExtendedUserTokenProvider interface.

add logic to call UserTokenClient when present

---

libraries/Microsoft.Bot.Schema/ActivityEx.cs
tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs

Fixes #5499 
NullReferenceException being thrown when calling CreateReply method with default/null From property in Activity. Added null check similar to CreateTrace method.
- Null check for From property in CreateReply method

Add null check for From property in CreateReply

---

libraries/AdaptiveExpressions/BuiltinFunctions/Equal.cs
libraries/AdaptiveExpressions/BuiltinFunctions/NotEqual.cs
libraries/AdaptiveExpressions/FunctionUtils.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/switchcase.lg
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs

Fixes #5508
Firstly, let me explain the cause of the bug:
```
{
"$kind": "Microsoft.SetProperty",
"property": "$answer",
"value": {
"score": 1
}
},
```
Here is a `SetProperty` action,  and in the LG template, the customer uses :
`${$answer.score}` to achieve the score.
Actually, In dialog memory manager, if the value is a `JObject`, it would use  `jobj.TryGetValue` to get the result.
https://github.com/microsoft/botbuilder-dotnet/blob/fc5fb14800ce84c8e84a24f8d2e8553d36d51420/libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs#L647
And, the result would be a long int(Int64) format data but not a Int32 format data. So, the result is actually `1L`, but not `1`
Another side, In the comparison of switch expression and case expression, the LG SDK treat they are different.
Original code: …

Apply Expression equal function in LG library

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/ConfigurationAdaptiveDialogBot.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialogBot.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogBotTests.cs

Fixes #5504 
PR to ensure adaptive dialog events are being logged correctly.
- Ensures the IBotTelemetryClient is added to the TurnState, which then ensures adaptive dialog events are correctly captured.
- Amends the value of dialogId captured on the AdaptiveDialogAction event to use the parent dialog Id.
- Adds an Instance Id property to the AdaptiveDialogStart / AdaptiveDialogComplete / AdaptiveDialogAction events to ensure they can be correlated within App Insights queries (this brings parity with waterfall dialog telemetry events).

Update Adaptive Runtime to add telemetry client to the TurnState

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/ConfigurationAdaptiveDialogBot.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialogBot.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogBotTests.cs

* Update Adaptive Runtime to add telemetry client to the TurnState.  Also amend the AdaptiveDialogAction  telemetry event to use correct dialog Id and log dialog instance Id
* Remove instanceId implementation and tracking for adaptive dialogs

CherryPick to 4.13: Update Adaptive Runtime to add telemetry client to the TurnState (#5509)

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5544
and https://github.com/microsoft/botbuilder-dotnet/issues/5516
Modifying OAuthInput to save state prior to sending an OAuthCard. The invoke response for a token exchange from the root bot could come in before the method finishes or could land in another instance in a scale-out scenario. This means that if the state is not saved prior to sending the card, race conditions lead to OAuthInput not being at the top of the stack when the invoke for token exchange comes in, resulting in the token exchange request being discarded.
[Extremely simplified vision of the simplest SSO flow for general understanding. Lots of details missing bug should help understand the situation]
With this change, because we save state prior to sending …

SSO + adaptive runtime: Save state before sending OAuthCard to prevent race conditions

---

libraries/AdaptiveExpressions/BuiltinFunctions/ConvertFromUtc.cs
libraries/AdaptiveExpressions/BuiltinFunctions/GetTimeOfDay.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

closes:  https://github.com/microsoft/botbuilder-dotnet/issues/5552
- The input of datetime functions (like `getTimeOfDay`), only accepts the original datetime format("yyyy-MM-ddTHH:mm:ss.fffZ")
- The output format of `convertFromUTC` was changed from "yyyy-MM-ddTHH:mm:ss.fffZ" to "yyyy-MM-ddTHH:mm:ss.fffffffK" in R12, which is correct because a time converted from UTC should no longer have the "Z" postfix.  This is also aligned with WDL's convention. 
- Then the result of `convertFromUTC` doesn't fit in the input of `getTimeOfDay`, error occurs.
In a summary, the current datetime functions input format is too strict. 
Expand the input of date time functions to cover the case of timestamp without timezone postfix.

Support timestamp without timezone postfix in getTimeOfDay

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs

Fixes #5323 
When the user presses a button in slack, the one sending the payload to the bot is the user not the bot.
- Swapped the priority of the id to pick  to populate Activity.From.Id

bug: Slack Adapter - Prioritize User.id as From.Id

---

libraries/AdaptiveExpressions/BuiltinFunctions/Contains.cs
libraries/AdaptiveExpressions/FunctionUtils.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

Fixes #5563
Support object comparison in `==`
1. Support object comparison in `contains`
2. Support object comparison for operator `==` and `!=`

Support object comparison in ==

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapterBotComponent.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapterBotComponent.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapterBotComponent.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapterBotComponent.cs

Fixes #5581
Currently, SDK adapters register their component using the full dependency injection approach, where IConfiguration gets passed by DI. The problem with this is that now the components receive a subsection of the IConfiguration, so the DI construction pattern cannot be used as-is. The solution is to register sdk adapter components as follows:
```csharp
services.AddSingleton<IBotFrameworkHttpAdapter, SlackAdapter>(sp => new SlackAdapter(configuration));
```
where `configuration` is the IConfiguration passed in `Botcomponent.ConfigureServices()`.
Workaround is to add this line to the startup.cs 
```csharp
services.AddSingleton<IBotFrameworkHttpAdapter, SlackAdapter>(sp => new SlackAdapter(Configuration.GetSection(typeof(SlackAdapter).Assembly.GetName().Name)));
```
In addition to …

SDK Adapter components: Consume passed in IConfiguration instead of the one registered in DI

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapterBotComponent.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapterBotComponent.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapterBotComponent.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapterBotComponent.cs

Cherry pick of: https://github.com/microsoft/botbuilder-dotnet/pull/5582

[Cherry pick] SDK Adapter components: Consume passed in IConfiguration instead of the one registered in DI (#5582)

---

libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs

#minor
This PR reverts the change made in PR #5068 in the token refresh, causing the functional test  `TokenTests_RefreshTestLoad` in `GetTokenRefreshTests` to fail.
Reverted the change from `WaitAsync` to `Wait`  usage for Sempahore used in the refresh token.
Added the pragma warning for `VSTHRD103` removed in the change.

Fix refresh token load

---

libraries/AdaptiveExpressions/BuiltinFunctions/Json.cs

Fixes #5328
Updated code to return the native JsonReaderException message that doesn't expose the original json and still provides enough information about the parsing error.

Updated error handling so it doesn't return json content

---

libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
libraries/Microsoft.Bot.Builder/CloudAdapterBase.cs
tests/Microsoft.Bot.Builder.Tests/Adapters/TestAdapterTests.cs
tests/Microsoft.Bot.Builder.Tests/AllowNullIdTestAdapter.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpAdapterTests.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/DelayHelper.cs

Fixes https://github.com/microsoft/BotFramework-Composer/issues/7880
The cloud adapter tried to cast a delay activity's value to `int`. Because the value is an object, all numbers are boxed and therefore cannot be unboxed and cast to a different numeric type using a normal cast operation. We need to use `Convert.ToInt32` instead.
The problem was also present in the test adapter so I've fixed it there too. The problem was not present in the Bot Framework HTTP adapter, but for the sake of completeness I've included a test for it anyway. The problem was present in the allow-null-ID test adapter and I fixed it there because I saw that it's supposed to mimic the other adapters, but I didn't include a test for it because it's not part of a public library.
- Change `(int)` to `Convert.ToInt32` …

Fix invalid cast exception when sending delay activities through cloud adapter

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs

Fixes #5610
PUT method attempts to reference request.Content before setting it causing a NullReferenceExeption.
Move the request.Content assignment to a line before it is referenced.
Added unit tests for PUT method. All succeed after this change.

Fix PUT method in HttpRequest throws null reference exception

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackHelperTests.cs

Fixes #5602 
For an ephemeral message to be posted in Slack, the Slack message must contain, at a minimum, the `channel`, `text`, and `user` properties. Currently, the `user` property is not being assigned to the Slack `message` object resulting in a failed post. This PR fixes the issue allowing ephemeral messages to successfully post in Slack.
- In SlackClientWrapper.cs, added the `user` property to the `data` object sent to Slack's `api/chat.postEphemeral` endpoint.
- In SlackHelperTests.cs:
- Changed hard-coded string literals to constants
- Added the `Channel` and `User` properties to ChannelData
- Added asserts to test the `ephemeral`, `channel`, and `user` properties

Adds missing required 'user' property to PostMessageAsync method

---

libraries/Microsoft.Bot.Builder/BotAdapter.cs
libraries/Microsoft.Bot.Builder/CloudAdapterBase.cs
libraries/Microsoft.Bot.Builder/Teams/TeamsActivityExtensions.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs

Fixes #5488
Also updates the abstract class to avoid casts in the application code.

add create conversation to CloudAdapter

---

tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaTestsFixture.cs

Fixes #5668 
I just added double quotation to the name of output directory
- Microsoft.Bot.Builder.Dialogs.Declarative.Tests.SchemaTestsFixture

Fix Path for merge tests.schema output directory

---

Directory.Build.props

Fixes #5557
This fixes "WARNING: The licenseUrl element is deprecated" on package pushes to Nuget.org. The licenseUrl element is in the .nuspec file in each Nuget package. The .nuspec file is autogenerated by Visual Studio when it does the packaging in the build.
This implements the recommended new way to handle licenses: reference them in licenses.nuget.org. (Or physically include them in the package.) Ours is the MIT license.
Update Directory.Build.props replacing PackageLicenseUrl with PackageLicenseExpression.

Update package license handling

---

libraries/Microsoft.Bot.Schema/Teams/AppBasedLinkQuery.cs
libraries/Microsoft.Bot.Schema/Teams/AttachmentExtensions.cs
libraries/Microsoft.Bot.Schema/Teams/CacheInfo.cs
libraries/Microsoft.Bot.Schema/Teams/ChannelInfo.cs
libraries/Microsoft.Bot.Schema/Teams/ConversationList.cs
libraries/Microsoft.Bot.Schema/Teams/FileConsentCard.cs
tests/Microsoft.Bot.Schema.Tests/Teams/AppBasedLinkQueryTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/AttachmentExtensionsTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/CacheInfoTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/ChannelInfoTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/ConversationListTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/FileConsentCardTests.cs

Fixes #5567 
Part 1 of 8.
___
Current Coverage: 14.09%

[Part 1] Increase Microsoft.Bot.Schema.Teams code coverage

---

libraries/Microsoft.Bot.Schema/Teams/FileConsentCardResponse.cs
libraries/Microsoft.Bot.Schema/Teams/FileDownloadInfo.cs
libraries/Microsoft.Bot.Schema/Teams/FileInfoCard.cs
libraries/Microsoft.Bot.Schema/Teams/FileUploadInfo.cs
libraries/Microsoft.Bot.Schema/Teams/MeetingParticipantInfo.cs
libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayload.cs
tests/Microsoft.Bot.Schema.Tests/Teams/FileConsentCardResponseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/FileDownloadInfoTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/FileInfoCardTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/FileUploadInfoTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MeetingParticipantInfoTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MessageActionsPayloadTests.cs

Fixes #5626 
___
Part 2 of 8.
___
Coverage Raised to with this Chunk: 15.79%

[Part 2] Increase Microsoft.Bot.Schema.Teams code coverage

---

libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionAction.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionActionResponse.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionAttachment.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionParameter.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionQuery.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionQueryOptions.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionResponse.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionResult.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionSuggestedAction.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MessagingExtensionActionResponseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MessagingExtensionActionTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MessagingExtensionAttachmentTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MessagingExtensionParametersTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MessagingExtensionQueryOptionsTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MessagingExtensionQueryTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MessagingExtensionResponseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MessagingExtensionResultTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MessagingExtensionSuggestedActionTests.cs

Fixes #5645 
___
Part 4 of 8.
___
Coverage Raised to with this Chunk: 22.56%

[Part 4] Increase Microsoft.Bot.Schema.Teams code coverage

---

libraries/Microsoft.Bot.Schema/Teams/NotificationInfo.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCard.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardActionBase.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardActionCard.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardActionQuery.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardDateInput.cs
tests/Microsoft.Bot.Schema.Tests/Teams/NotificationInfoTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardActionBaseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardActionCardTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardActionQueryTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardDateInputTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardTests.cs

Fixes #5647 
___
Part 3 of 8.
___
Coverage Raised to with this Chunk: 18.58%

[Part 5] Increase Microsoft.Bot.Schema.Teams code coverage

---

libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardFact.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardHttpPOST.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardImage.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardInputBase.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardMultichoiceInput.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardMultichoiceInputChoice.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardFactTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardHttpPOSTTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardImageTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardInputBaseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardMultichoiceInputChoiceTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardMultichoiceInputTests.cs

Fixes #5661
___
Part 6 of 8.
___
Coverage Raised to with this Chunk: 14.93%

[Part 6] Increase Microsoft.Bot.Schema.Teams code coverage

---

libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardOpenUri.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardOpenUriTarget.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardSection.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardTextInput.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardViewAction.cs
libraries/Microsoft.Bot.Schema/Teams/SigninStateVerificationQuery.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardOpenUriTargetTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardOpenUriTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardSectionTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardTextInputTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/O365ConnectorCardViewActionTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/SigninStateVerificationQueryTests.cs

Fixes #5663 
___
Part 7 of 8.
___
Coverage Raised to with this Chunk: 19.12%

[Part 7] [Unit Tests - Code Coverage]: Microsoft.Bot.Schema.Teams

---

tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs

Addresses #5166
#minor
This PR updates `OAuthPromptTests.cs` to increase code coverage for `OAuthPrompt.cs` from 64% to 84%.
- Added unit tests for different parts of the `OAuthPrompt.cs` class.
- Moved reused variables to properties.
- Set OAuthPromptEndOnInvalidMessageSetting test to public to make it available.

[#5166] Add unit tests for Microsoft.Bot.Builder.Dialogs.OAuthPrompt

---

libraries/Microsoft.Bot.Connector/Authentication/UserTokenClientImpl.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/UserTokenClientImplTests.cs

Fixes #5166
This PR adds unit tests for the `UserTokenClientImpl.cs` to increase the code coverage from 15% to 65%
- Add unit tests in `UserTokenClientImplTests.cs` covering code from `UserTokenClientImpl.cs`.
- Add assembly IntervalVisibleTo tag to `UserTokenClientImpl.cs` to be available for the test class.

[#5166] Add unit tests for Microsoft.Bot.Connector.Authentication.UserTokenClientImpl 

---

libraries/AdaptiveExpressions/AdaptiveExpressions.csproj
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj
libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj
tests/Microsoft.Bot.Builder.TestBot.Shared/Microsoft.Bot.Builder.TestBot.Shared.csproj
tests/Microsoft.Bot.Builder.TestBot/Microsoft.Bot.Builder.TestBot.csproj

Addresses #5620
#minor
This PR upgrades Recognizers-Text packages to version [1.3.2](https://www.nuget.org/packages/Microsoft.Recognizers.Text/1.3.2). This is the latest version compatible with NetCore2.1. Once we drop support for NetCore2.1, we'll be able to upgrade to the latest version of Recognizers-Text ([1.7.0](https://www.nuget.org/packages/Microsoft.Recognizers.Text/1.7.0))
Updated the following projects to use version 1.3.2 of Recognizers-Text packages.
- libraries/AdaptiveExpressions/AdaptiveExpressions
- libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive
- libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs
- tests/Microsoft.Bot.Builder.TestBot.Shared/Microsoft.Bot.Builder.TestBot.Shared
- …

[#5620] Upgrade Microsoft.Recognizers to 1.3.2

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioHelper.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/TwilioAdapterTests.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/TwilioHelperTests.cs

Fixes #5569 
Twilio allows using both a "normal" phone number (`+15552223333`) or WhatsApp number (`whatsapp:+15552223333`), and only allows communication from one type to another. Example:
1. `+15552223333` can send to `+15559998888`
2. `whatsapp:+15552223333` can send to `whatsapp:+15559998888`
3. `+15552223333` CANNOT send to `whatsapp:+15559998888`
4. `whatsapp:+15552223333` CANNOT send to `+15559998888`
All outgoing messages in the Twilio adapter have their `Activity.From` populated by the developer input from `appsettings.json`. This is problematic if the bot is meant to use both regular and WhatsApp numbers.
1. Make providing `TwilioNumber` to `ActivityToTwilio()` optional
2. If `TwilioNumber` is not provided in `ActivityToTwilio()`, use `From.Id`
3. Do not pass `TwilioNumber`, by …

Adjust how Activity.From is populated when sending

---

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj

Fixes #5704
Update the description and project URL for the Orchestrator Recognizer package (which show up in Composer)
- `Description` text for Composer's Package Manager.  Text was copied from [js](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-ai-orchestrator/README.md) repo added by @scheyal
- `PackageProjectUrl` for the `View documentation` link in Package Manager.

Docs: Update Orchestrator description and ProjectURL for Composer

---

tests/Microsoft.Bot.Schema.Tests/Teams/TabContextTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabEntityContextTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabRequestTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabResponseCardTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabResponseCardsTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabResponsePayloadTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabResponseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabSubmitDataTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabSubmitTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabSuggestedActionsTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabsTestData.cs

Fixes #5708 
___
Part 8 of 10.
___
Original `Microsoft.Bot.Schema.Teams` Coverage: 71.40%
Coverage Raised to with this Chunk: 77.31%

[Part 8] [Unit Tests - Code Coverage]: Microsoft.Bot.Schema.Teams

---

libraries/Microsoft.Bot.Schema/Teams/TaskModuleContinueResponse.cs
libraries/Microsoft.Bot.Schema/Teams/TaskModuleMessageResponse.cs
libraries/Microsoft.Bot.Schema/Teams/TaskModuleRequest.cs
libraries/Microsoft.Bot.Schema/Teams/TaskModuleRequestContext.cs
libraries/Microsoft.Bot.Schema/Teams/TaskModuleResponse.cs
libraries/Microsoft.Bot.Schema/Teams/TaskModuleResponseBase.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TaskModuleActionTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TaskModuleCardResponseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TaskModuleContinueResponseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TaskModuleMessageResponseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TaskModuleRequestContextTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TaskModuleRequestTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TaskModuleResponseBaseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TaskModuleResponseTests.cs

Fixes #5714 
___
Part 9 of 10.
___
Original `Microsoft.Bot.Schema.Teams` Coverage: 71.40%
Coverage Raised to with this Chunk: 78.18%

[Part 9] [Unit Tests - Code Coverage]: Microsoft.Bot.Schema.Teams

---

libraries/AdaptiveExpressions/BuiltinFunctions/Bool.cs
libraries/AdaptiveExpressions/FunctionUtils.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_AllowInterruptionAlwaysWithFailedValidation.test.dialog

Fixes #5615 
[The docs](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#bool) state that at least `1` and `0` should convert to true/false, respectively.
However, currently all integers are evaluated as "True" (see tests, prior to this change).
Allowed converting `0` to false. All other integers will be considered "truthy" and convert to `True`. Some alternatives might be to:
1. Throw an error if `int` and not `1` or `0`,
2. Only `1` is `True` and all others are `False`
This just seemed to make the most sense to me.
* I'm okay nixing this PR; I just saw the docs didn't match
* I'm okay re-working the code such that only `1` is `True` and all other values are `False`
I originally tried making changes …

feat: AdaptiveExpressions: Allow 0 to convert as false bool

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.OAuthInput.schema
tests/Microsoft.Bot.Builder.TestBot.Json/testbot.schema
tests/tests.schema

Fixes:
- Composer docs [issue 121](https://github.com/MicrosoftDocs/composer-docs/issues/121)
- Related Composer [issue 6767](https://github.com/microsoft/BotFramework-Composer/issues/6767).
Also see Jonathan's [pr 5660](https://github.com/microsoft/botbuilder-dotnet/pull/5660)
This fixes the tests covering Jonathan Fingold's patch in the file Microsoft.OAuthInput.schema. He changed "dialog.token" to "turn.token". #minor
The same change made in tests/Microsoft.Bot.Builder.TestBot.Json/testbot.schema and tests/tests.schema.

Fix OAuth prompt should store in turn.token, not dialog.token

---

libraries/Microsoft.Bot.Schema/Teams/TaskModuleTaskInfo.cs
libraries/Microsoft.Bot.Schema/Teams/TeamDetails.cs
libraries/Microsoft.Bot.Schema/Teams/TeamInfo.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsChannelAccount.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsChannelAccountEx.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsChannelData.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsMeetingInfo.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsPagedMembersResult.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsParticipantChannelAccount.cs
libraries/Microsoft.Bot.Schema/Teams/TenantInfo.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TaskModuleTaskInfoTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TeamDetailsTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TeamInfoTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TeamsChannelAccountTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TeamsChannelDataTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TeamsMeetingInfoTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TeamsMeetingParticipantTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TeamsPagedMembersResultTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TeamsParticipantChannelAccountTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TenantInfoTests.cs

Fixes #5725 
___
Part 10 of 10.
___
Original `Microsoft.Bot.Schema.Teams` Coverage: 71.40%
Coverage Raised to with this Chunk: 87.51%

[Part 10] Increase Microsoft.Bot.Schema.Teams code coverage

---

libraries/Microsoft.Bot.Connector/Authentication/PasswordServiceClientCredentialFactory.cs

Add parameter validation to PasswordServiceClientCredentialFactory.CreateCredentialAsync

---

CodeCoverage.runsettings

Fixes #5703
This is a follow-on to PR #5723
Remove Azure.Queues.dll from CodeCoverage.runsettings CodeCoverage Include list.

Remove Azure.Queues.dll from CC report

---

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/AdaptiveTestingBotComponent.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisRecognizer.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Schemas/Microsoft.Test.AssertTelemetryContains.schema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertTelemetryContains.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestScript.cs
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisOracleTests.cs
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisV3OracleTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AskTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AskTests/AskName.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AskTests/CacheLuisRecognizer.test.dialog
tests/tests.schema

closes #5593 
In order to avoid two LUIS network calls from the child dialog for the same user query when interruptions are enabled. 
In this PR, Luis Recognizer would cache the luis result for each turn, using endpoint combines with application id as the key.

Fix: add cache for luis recognizer result to avoid extra requests

---

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs

Fixes #5676 
This PR updates the [CreateConversationAsync](https://github.com/microsoft/botbuilder-dotnet/blob/baf78d01d4c0b8ddae2d117a52d2a4bca1479683/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L1362) method to stop overriding the _conversationParameters.ChannelData_ with the TenantId.
- Updated **_BotFrameworkAdapter_** class to add the TenantId as a new property in _conversationParameters.ChannelData_ instead of overriding the object.
These images show a Teams bot failing on the _createConversation_ before the fix and working after applying it.

[#5676] BotFrameworkAdapter CreateConversationAsync overrides conversationParameters.ChannelData

---

libraries/Microsoft.Bot.Connector/Authentication/BotFrameworkClientImpl.cs
libraries/Microsoft.Bot.Connector/ConversationConstants.cs
libraries/Microsoft.Bot.Connector/Conversations.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
tests/Microsoft.Bot.Connector.Tests/ConversationsTest.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpClientTests.cs

Fixes #5592
PVA team needs ConversationId in the header of skills requests, bot Host to Skill, and Skill to Host. This change adds the header to these Http requests.
Updated existing tests to assert the new header.

Add conversation id header in skill requests

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Settings/SkillConfigurationEntry.cs
libraries/Microsoft.Bot.Connector/Authentication/AllowedSkillsClaimsValidator.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/AllowedSkillsClaimsValidationTests.cs
tests/Skills/Bot1/Startup.cs
tests/Skills/Bot2/Startup.cs

Fixes #5285 
Added AllowedSkillsClaimsValidator as needed to support skills in the AdaptiveRuntime so that allowedCallers are inferred correctly and validated from the configured skills.
Added AllowedSkillsClaimsValidator and add it as a singleton as an AuthenticationConfiguration in AddBotRunTimeSkills in ServiceCollectionExtensions.cs. 
Because AllowedSkillsClaimsValidator originally was part of the samples/test code and not part of the SDK this meant that there was now an ambiguous reference which had to be handled in the test code, and will need to be updated in the samples as well. It is possible to update the samples/test code to no longer have their own copies of the AllowedSkillsClaimsValidator and have them use the SDK version by having them instantiate the SDK version and pass …

Add AllowedSkillsClaimsValidator for Issue 5285

---

tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_SendHandoffActivity.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs

Fixes #5192
This PR adds unit tests for the [SendHandoffActivity](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendHandoffActivity.cs) class reaching 100% code coverage.
- Added Action_SendHandoffActivity.test.dialog script file.
- Added `Action_SendHandoffActivity` in ActionTests class.
- Added schema to the omitted list in `SchemaMergeTests` as it fails with the same [issue](https://stackoverflow.com/questions/63493078/why-does-validation-fail-in-code-but-work-in-newtonsoft-web-validator) that affects _Action_SendActivity.test.dialog_.
These images show the new test passing and the coverage for the class.

[#5192] Add unit tests for SendHandoffActivity

---

build/yaml/botbuilder-dotnet-ci.yml

Fixes #5756 
With both 2.1 and 3.1 reports uploading to coveralls.io, the last to be uploaded overwrites the first. Which one wins is random.

Disable code coverage reporting for netcoreapp 2.1

---

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs
tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorAdaptiveRecognizerTests.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5762
This should maybe be cherry-picked to 4.14, and patched.

Ensure the results of Orchestrator scoring are not readonly

---

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs
tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorAdaptiveRecognizerTests.cs

* Ensure the results of Orchestrator scoring can be added to for unknown intent
* Move .ToList()
* nullable result
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5762

fix: Ensure the results of Orchestrator scoring are not readonly (#5763)

---

tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs

#minor
Skip Microsoft.Bot.Builder.Dialogs.Adaptive.Tests.ActionTests.Action_MissingProperty if the dotnet core version is 2.1
The newly added adaptive action test "missingProperties" won't pass in dotnet 2.1 in Mac\Linux pipeline.  Our investigation shows it's related to some platform\runtime specific behavior causing the states between tests not well isolated somehow. 
Given we are also planning to drop 2.1 support, so skip this test for now to unblock other workstreams.

Skip Adaptive.Tests.ActionTests.Action_MissingProperty for dotnet 2.1 

---

tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs

The newly added adaptive-tests MissingProperty has a certain chance of failure in Mac\Linux, which is probably due to how tests are scheduled. 
In order unblock other PRs, ignore MissingProperty test temporarily. We will re-enable it once we find out how to solve this issue.
#minor

Skip MissingProperty test temporarily 

---

libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs
libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs

Fixes #5778 
Fix #5778 by ensuring `_checkedContainers` is consistent with actual blob storage
- `CreateIfNotExistsAsync` before add to `_checkedContainers` in `AzureBlobTranscriptStore`
- `CreateIfNotExistsAsync` before add to `_checkedContainers` in `BlobTranscriptStore`

fix #5778: CreateIfNotExistsAsync before add to _checkedContainers

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.csproj

#minor
Small fix.
Change `Microsoft.Bot.Builder.AI.Luis` folder name to `Microsoft.Bot.Builder.AI.LUIS`
Attach the original error in ubuntu:
```
error NU1603: Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime depends on Microsoft.Bot.Builder.AI.Luis (>= 4.11.0-local) but Microsoft.Bot.Builder.AI.Luis 4.11.0-local was not found. An approximate best match of Microsoft.Bot.Builder.AI.Luis 4.11.0 was resolved.
```

fix: Fix the case issue that would block the building in linux system

---

libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5793
When we send outgoing activities in the adapter for http flows, if they fail, we let the exception get thrown so that it reaches the top level adapter. Cloud adapter+  streaming also does not catch, so that errors flow to the handlers. 
However, outgoing activities on streaming when using the BotFrameworkHttpAdapter, we do catch the exceptions, log them and return null. The result is negative in a number of ways:
1- Errors are swallowed 
2- Callers cannot retry or handler errors in code
3- Developers expect OnError trigger to get called but when using streaming it does not (OneVoice ran in to this)
This change makes all outgoing activities treat errors consistently (by not hiding them) and solve the problems above.

Streaming: Surface exceptions like other paths to allow error handling in upper layers.

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Microsoft.AdaptiveDialog.uischema

Fixes #5566 
Hide the dialogs property of AdaptiveDialog in the Composer UI by adding it to the hidden list in the AdaptiveDialog.uischema file. 
Note that as of today this change will not be used by Composer, it is using a local copy of a uischema file that drives it's behavior, so another Issue and PR were created for this in the Composer repo:
[AdaptiveDialog has dialogs property added in declarative schema and that property should be hidden.](https://github.com/microsoft/BotFramework-Composer/issues/8387)
[fix: Added dialogs to hidden list for AdaptiveDialog in index.ts file](https://github.com/microsoft/BotFramework-Composer/pull/8388)
The change was also added here so that once Composer stops using the local file this change will already be reflected in the SDK …

Added dialogs property of AdaptiveDialog to the hidden list

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackHelperTests.cs

Fixes #5406 
Translates Hero Cards to Block Kit cards. Prior to this PR, all Hero Cards are converted to static images, so buttons don't work.
This specifies a pretty specific format that matches Hero Cards closely, but won't be a 1:1.

Convert HeroCards to BlockKit

---

libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs
tests/Microsoft.Bot.Streaming.Tests/Microsoft.Bot.Streaming.Tests.csproj
tests/Microsoft.Bot.Streaming.Tests/StreamingRequestHandlerTests.cs

Fixes #5816 
Changes method signatures in StreamingRequestHandler to 'virtual' to allow overrides:
- public async Task ListenAsync() -> public virtual async Task ListenAsync()
- public async Task<ResourceResponse> SendActivityAsync -> public virtual async Task<ResourceResponse> SendActivityAsync
- private void Server_Disconnected -> protected virtual void ServerDisconnected
New unit test creates class **BotFrameworkHttpAdapterSub** that inherits from **BotFrameworkHttpAdapter** and overrides method **CreateStreamingRequestHandler**. 
Class **StreamingRequestHandlerSub** inherits from **StreamingRequestHandler** and overrides **ListenAsync** and **ServerDisconnected**.
The test verifies these methods are called by the subclasses.

Make StreamingRequestHandler methods virtual

---

README.md

This will point to the new graph for v 4.14.0
Fixes #5843

Update interdependency graph URL in README.md

---

libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs

Fixes #5787 
We check whether `blob.Metadata.ContainsKey("Timestamp")` before calling `blob.Metadata["Timestamp"]` to avoid key not found exception.
Please let me know if the "skip if not exist" behavior is good or not.
- skip if `blob.Metadata.ContainsKey("Timestamp")` is False in GetTranscriptActivitiesAsync

check whether Metadata contains Timestamp

---

tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogBotTests.cs

Fixes #5402
Tests added to Microsoft.Bot.Builder.Dialogs.Adaptive.Tests\AdaptiveDialogBotTests.cs.
3 asserts added to AdaptiveDialogBotTurnState() for optional args.
4 tests added covering optional args:
AdaptiveDialogBot_ShouldNotThrowOnNullMemoryScope()
AdaptiveDialogBot_ShouldNotThrowOnNullPathResolver()
AdaptiveDialogBot_ShouldNotThrowOnNullDialog()
AdaptiveDialogBot_ShouldNotThrowOnNullLogger()
"ShouldThrow" tests added for the other args.

Add unit tests for AdaptiveDialogBot parameters

---

libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/AnalyzerOptions.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/EvaluationOptions.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/LoopDetected.lg
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5814

Add ThrowOnRecursive to LG EvaluationOptions

---

tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs

Fixes #5875
Microsoft.Bot.Builder.Dialogs.Loader.Tests.JsonLoadTests.JsonDialogLoad_HttpRequest fails intermittently.
Example builds where the test failed, having passed on the same commit: 266718, 265922, 264994.
Add retries to the flaky test.

Fix intermittent test failure in BotBuilder-DotNet-CI-PR-yaml

---

tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenValidationTests.cs

#minor
* Disable failing JwtTokenValidationTests
* Delete appid/password from tests

Cherry-Pick to 4.14: Delete appid/password from tests (#5836)

---

libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/AnalyzerOptions.cs
libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/LoopDetected.lg
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs

Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/5814
* Add ThrowOnRecursive to LG EvaluationOptions
* Address ThrowOnRecursive feedback
* Do not pass LgOptions to Analyzer constructor (they are available through the Templates instance)
* Add AnalyzerOptions

Cherry-Pick to 4.14: Add ThrowOnRecursive to LG AnalyzerOptions (#5872)

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ReplaceDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/IAdaptiveDialogDependencies.cs

Fixes #5624 
Adds change requested in #5656 by @carlosscastro 
- Moves new interface IAdaptiveDialogDependencies to Adaptive library
- Makes the new interface "internal"
- Makes the implementation method in "ReplaceDialog" non-virtual.

Move IAdaptiveDialogDependencies to Adaptive library

---

tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Base/ActiveObjectTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Base/ReaderWriterLockTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Base/ReleaserTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/CodeModels/CodeModelTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/CodeModels/CodePointTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/DataModels/CoercionTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/DataModels/DataModelsTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/DebuggerSourceMapTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/DebuggingBotAdapterExtensionsTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/DialogDebugAdapterTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Events/EventsTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Identifiers/IdentifierCacheTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Identifiers/IdentifierMutexTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Identifiers/identifierTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Protocol/ProtocolTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Transport/DebugTransportTests.cs

Fixes #5895
This PR increases the code coverage for the `Microsoft.Bot.Builder.Dialogs.Debugging` library from **39%** to **75%**.
Added unit tests for the following classes:
- Base/ActiveObject
- Base/ReaderWriterLock
- Base/Releaser
- CodeModels/CodeModel
- CodeModels/CodePoint
- DataModels/Coercion
- DataModels/DataModels
- DebuggerSourceMap
- DebuggingBotAdapterExtensions
- DialogDebugAdapter
- Events/Events
- Identifiers/IdentifierCache
- Identifiers/IdentifierMutex
- All classes in Protocol folder
- Transport/DebugTransport
Also, moved the _identifierTests_ class under the `Identifiers` folder.
The following images show the tests passing and the new code coverage.

[#5895] Increase Microsoft.Bot.Builder.Dialogs.Debugging code coverage

---

tests/Microsoft.Bot.Streaming.Tests/ConcurrentStreamTests.cs
tests/Microsoft.Bot.Streaming.Tests/ContentStreamTests.cs
tests/Microsoft.Bot.Streaming.Tests/NamedPipeTests.cs
tests/Microsoft.Bot.Streaming.Tests/NamedPipeTransportTests.cs
tests/Microsoft.Bot.Streaming.Tests/RequestTests.cs
tests/Microsoft.Bot.Streaming.Tests/ResponseTests.cs
tests/Microsoft.Bot.Streaming.Tests/SendOperationsTests.cs
tests/Microsoft.Bot.Streaming.Tests/TransportDisconnectedExceptionTests.cs
tests/Microsoft.Bot.Streaming.Tests/WebSocketTransportTests.cs

Fixes #5838
This PR increases the code coverage for the `Microsoft.Bot.Streaming` from **63%** up to **84%**, the changes are divided in two parts, see PR #5839 for Part 1.
- Added unit tests for:
- ConcurrentStream
- ContentStream
- NamedPipe
- NamedPipTransport
- Request
- Response
- SendOperations
- TransportDisconnected
- WebSocketTransport
The following image shows the before and after the changes that increased the code coverage.

[#5838][Part 2] Increase Microsoft.Bot.Streaming code coverage

---

tests/Microsoft.Bot.Builder.Azure.Tests/AzureQueueTests.cs

Fixes #5898
This PR increases the code coverage for the `Microsoft.Bot.Builder.Azure.Queues` from **82%** to **100%**.
Originally the coverage was **82%**, but these tests are skipped in the CI pipeline as they require the [AzureStorageEmulator](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator).
Added unit tests for:
- AzureQueueStorage
The following images show the tests passing and the new code coverage.

[#5898] Increase Microsoft.Bot.Builder.Azure.Queues code coverage

---

libraries/AdaptiveExpressions/FunctionUtils.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5917

Cherrypick 5925: Fix comparison policy of string in adaptive expressions

---

build/yaml/botbuilder-dotnet-ci.yml
build/yaml/vnextprototype/botbuilder-dotnet-ci-mac.yml
build/yaml/vnextprototype/botbuilder-dotnet-ci.yml
build/yaml/vnextprototype/ci-build-steps.yml
build/yaml/vnextprototype/ci-test-steps.yml
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisOracleTests.cs
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisV3OracleTests.cs
tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/LuisV3OracleTests.cs
tests/Microsoft.Bot.Streaming.Tests/Payloads/PayloadReceiverTests.cs

Fixes #minor
Adapt pipelines for vNextPrototype branch.
Fix tests to look for Microsoft.Bot.Builder.AI.Luis/5 in Windows instead of Microsoft.Bot.Builder.AI.Luis/4. MacLinux still uses v4, which is odd.
Fix test to expect Microsoft.Bot.Builder.AI.QnA/5 instead of v4. MacLinux still uses v4, which is odd.
Miscellaneous formatting fixes were made by an automated process.

Set up new pipelines for vNextPrototype branch.

---

.github/workflows/create-botbuilder-js-parity-issue.yml

Fixes #5978
Parity issues are created unless PR is tagged with `Automation: No parity`.
The workflow creates parity issues for JS, Java and Python.
Add v5 branch to create-botbuilder-js-parity-issue.yml

Add v5 branch to js-parity workflow

---

.editorconfig

#minor
Adds default (c) not to editorconfig so new files are created with the right copyright

Add default (C) in editorconfig

---

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisApplication.cs
libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerEndpoint.cs
libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ServiceCollectionExtensions.cs
tests/Microsoft.Bot.Configuration.Tests/ServiceTests.cs

Added obsolete attribute to classes that use obsolete objects from Configuration.
Added pragma to avoid warnings in test code.
Checked the dotnet samples and the deprecated members don't seem to be used there
Fixes #5996

Adds missing obsolete attributes to member that depend on obsolete types 

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookReferral.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookMessage.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookAdapterTests.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookHelperTests.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/Files/PayloadWithReferral.json
tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/Microsoft.Bot.Builder.Adapters.Facebook.Tests.csproj

Fixes #5948  
Add support for Facebook Referral parameter
This handles the second scenario of Facebooks messaging_referrals event here: https://developers.facebook.com/docs/messenger-platform/discovery/m-me-links/#reading_parameter
-  added FacebookReferral.cs class for deserialisation of Facebook referral event messaging_referrals
- added new property Referral on FacebookMessage

Add support for referral property in Facebook messaging_referrals event

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs

Ensure services are copied to new child context in ForEachElement

---

Directory.Build.props
libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisOracleTests.cs
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisV3OracleTests.cs
tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/LuisV3OracleTests.cs

Update connector client code to return and log the right assembly version.
Updated LocalPackageVersion in Directory.Build.props to use 0.0.0.0 so dev assembly versions can be easily identified in the logs.
Fixes #6072

Update connector client code to return and log the right assembly version.

---

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
libraries/Microsoft.Bot.Builder/ChannelServiceHandler.cs
libraries/Microsoft.Bot.Builder/Integration/BotFrameworkOptions.cs
libraries/Microsoft.Bot.Builder/Integration/IAdapterIntegration.cs
libraries/Microsoft.Bot.Builder/Skills/SkillHandler.cs
libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs
libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs
libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs
libraries/Microsoft.Bot.Connector/Authentication/EnterpriseChannelValidation.cs
libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs
libraries/Microsoft.Bot.Connector/Authentication/IChannelProvider.cs
libraries/Microsoft.Bot.Connector/Authentication/ICredentialProvider.cs
libraries/Microsoft.Bot.Connector/Authentication/IServiceClientCredentialProvider.cs
libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs
libraries/Microsoft.Bot.Connector/Authentication/SimpleChannelProvider.cs
libraries/Microsoft.Bot.Connector/Authentication/SimpleCredentialProvider.cs
libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandler.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandlerBase.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ConfigurationChannelProvider.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ConfigurationCredentialProvider.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ServiceCollectionExtensions.cs

Fixes #6022 
Added obsolete attribute to BotFrameworkHttpAdapter and related classes, in order to migrate to CloudAdapter.

Add obsolete attribute to BotFrameworkHttpAdapter and related classes.

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs

Fixes #6109
Updated method to not use the URL in the computed ID

Removes URL from OnComputId method

---

build/yaml/botbuilder-dotnet-ci-mac.yml
build/yaml/botbuilder-dotnet-ci.yml
build/yaml/botbuilder-dotnet-sign.yml
build/yaml/ci-build-steps.yml
build/yaml/sdk_dotnet_v4_org-feed-setup-steps.yml

Fixes #minor
Getting sources from an ADO feed with pass-through to NuGet.org has been mandated by MS cyber security.
Set up daily and CI pipelines to get dependencies from the organization-scoped ADO feed "SDK_Dotnet_V4_org".
https://dev.azure.com/FuseLabs/SDK_v4/_packaging?_a=feed&feed=SDK_Dotnet_V4_org
Not completed: the macLinux CI pipeline.

Set up DotNet pipelines for SDK_Dotnet_V4_org feed.

---

libraries/Microsoft.Bot.Builder/OAuth/IExtendedUserTokenProvider.cs
libraries/Microsoft.Bot.Builder/OAuth/IUserTokenProvider.cs

Add Obsolete attribute to IExtendedUserTokenProvider and IUserTokenProvider

---

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/CloudAdapter.cs

Log BadRequest in adapter

---

generators/vsix-vs-win/BotBuilderVSIX-V4/Directory.Build.props

Fixes #minor
The Directory.Build.props at the repo root gets used in building the VSIX templates solution, causing it to error.
Example: https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=287122&view=results
Add an empty Directory.Build.props so the root copy is not used.

Fix broken VSIX build

---

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj
libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj

Fixes #6019
> **Note:** The same dependency structure was corroborated for JavaScript and Python. Only JavaScript has the similar case as DotNet, whereas Python doesn't.
This PR removes redundant dependencies for `Dialogs.Adaptive`, `AI.Orchestrator` and `AI.QnA`.
- `Dialogs.Adaptive`
- Removed `AdaptiveExpressions` dependency reference from `<ProjectReference/>` and `<PackageReference/>`.
- `AI.Orchestrator`
- Removed `Microsoft.Bot.Builder.Dialogs` dependency reference from `<ProjectReference/>`.
- `AI.QnA`
- Removed `AdaptiveExpressions` and `Microsoft.Bot.Builder` dependencies' references from `<ProjectReference/>` and `<PackageReference/>`.
The following image shows the CI pipeline running successfully after the changes.

[#6019] Remove redundant project dependencies from AI Recognizers

---

libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs
libraries/Microsoft.Bot.Builder.Dialogs/DialogState.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogSetTests.cs

Fixes #4870
Note: this is potentially a breaking change. Bots with dialog ids differing in only upper and lower case will no longer recognize them as different dialogs.

Default DialogSet to case insensitive comparison

---

build/UnlistNpmPackagesOnMyGet.ps1
build/UnlistPackagesOnAzure.ps1
build/UnlistPackagesOnMyGet.ps1
build/UnlistPackagesOnNpm.ps1
build/UnlistPackagesOnNuGet.ps1

Fixes #5818
Feeds are MyGet, NuGet, Azure, npm.
Pipelines are:
[Unlist-DotNet-Packages-On-Azure](https://dev.azure.com/FuseLabs/SDK_v4/_release?definitionId=197&view=mine&_a=releases)
[Unlist-DotNet-Packages-On-MyGet](https://dev.azure.com/FuseLabs/SDK_v4/_release?definitionId=196&view=mine&_a=releases)
[Unlist-DotNet-Packages-On-NuGet](https://dev.azure.com/FuseLabs/SDK_v4/_release?definitionId=199&view=mine&_a=releases)
[Unlist-Packages-On-Npm](https://dev.azure.com/FuseLabs/SDK_v4/_release?definitionId=198&view=mine&_a=releases)
[View-Npm-Package-Versions-On-MyGet](https://dev.azure.com/FuseLabs/SDK_v4/_release?definitionId=200&view=mine&_a=releases) ("Unlist" is not supported. "View" is.)
The pipelines are currently configured to  not actually unlist, for safety. They can be activated …

Create pipelines to unlist deprecated packages on 4 feeds

---

build/yaml/botbuilder-dotnet-ci-pr-mac-v5.yml
build/yaml/botbuilder-dotnet-ci-pr-windows-v5.yml

Fixes #minor
This would change the build ID format from a date plus a counting number to the native build ID used by ADO.
It would affect these v5 pipelines: 
[BotBuilder-DotNet-CI-PR-MacOS](https://dev.azure.com/FuseLabs/SDK_v5/_build?definitionId=1418&_a=summary)
BotBuilder-DotNet-CI-PR-Windows
...making their ID format match the build ID format of the same v4 pipelines:
[BotBuilder-DotNet-CI-PR-(MacLinux)-yaml](https://dev.azure.com/FuseLabs/SDK_Public/_build?definitionId=741)
BotBuilder-DotNet-CI-PR-yaml
Having the native ID is valuable because it is a unique identifier. It appears in the build's URL.

Fix build ID to show each build's native ADO build ID

---

build/yaml/botbuilder-dotnet-sign.yml

Fixes #minor
Add task ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection

Add 'Component Detection' task to DotNet signing build.

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.Foreach.schema
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_Foreach_WithEvent.test.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestNestedForeachWithPromptCachedItems.test.dialog
tests/tests.schema

Fixes #6149
* Fix for when Actions are updated in ForEachElement
* use ForEachElement not Foreach in test
* Add Action_Foreach_WithEvent test
* Add example of foreach index and value to .schema
* Update tests.schema results
* Add TestForeachWithLargeItems back to active tests

Cherry-pick to 4.15: Fix for when Actions are updated in ForEachElement (#6143)

---

build/yaml/ci-build-steps.yml

The injected Component Governance task does not enable the option to fail the build when alerts are raised. This change adds the step to our build with the option to fail builds in case of alerts.
#minor

Add Component Governance to build

---

build/yaml/ci-test-steps.yml

Fixes #minor
Add succeeded() conditional to tests so tests will not run if a previous task fails.
Backdate Node.js to v 14.x.

DotNet pipeline tweaks

---

build/yaml/ci-test-steps.yml

Fixes #minor
This fixes CI build failures that happen when someone picks "Rerun failed jobs".
The step 'Publish Microsoft.Bot.Builder DLLs artifact' fails when it runs the second time with the error ##[error]Artifact BotBuilderDLLs-Release-Windows-netcoreapp31 already exists for build nnnnn. (A pipeline should be idempotent. ;-) )
Example: https://dev.azure.com/FuseLabs/SDK_Public/_build/results?buildId=289085&view=logs&j=3caee121-a023-5855-b1e2-fa52c30e4794&t=77840afb-f9eb-5759-8afb-e28266d81ed6
Added continueOnError: true to task.

Add continueOnError: true for publish

---

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/Fallback/datetime.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/ObjectPathTests.cs

Fixes #5924
**Original Issue:** microsoft/BotFramework-Composer#2731
This PR fixes an issue when using Adaptive Dialogs' `Microsoft.SetProperty` with a String Date expressed as [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`e.g. 2021-11-30T23:59:59:000Z`), the Dialogs' internal code that uses [NewtonsoftJSON](https://www.newtonsoft.com/json) to read and process the `Properties` will recognize and transform the String Date to a `JTokenType.Date` object causing an error when subsequent BuiltIn Functionalities (`e.g. trim(stringDateISO)`) receive a string as an input value.
This PR provides a solution to disable the `DataPaseHandling` when the JSON file is read, and when the `Property` object is cloned instead of Serializing/Deserializing the object.
- Added `DateParseHandling` option …

[#5924] Fix Adaptive Dialogs ISO Date String parsing to a JTokenType.Date Object

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpResponseMock.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpResponseMockContent.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Schemas/Microsoft.Test.HttpRequestSequenceMock.schema
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/HttpRequestMock/httpgzip.mock.dialog
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/TestScriptTests_HttpRequestMock.test.dialog
tests/Microsoft.Bot.Builder.TestBot.Json/testbot.schema
tests/tests.schema

fixes  https://github.com/MicrosoftDocs/composer-docs/issues/128
If you use your HTTP client to call another website, then by default it does not advertise that it supports compression. Which is a shame as it can reduce the payload of the response considerably. Most web servers will compress the response body when the request contains a header called Accept-Encoding. The value of this header specifies what kind of encodings are supported by the calling client. For example:
```
GET https://www.example.com
Accept: application/xml
Accept-Encoding: gzip, deflate
```
The server can respond with a compressed body:
```
200 OK
content-encoding: gzip
content-length: 17800
content-type: application/xml
<compressed>
```
The client now needs to decompress the body and return the contents. Your …

fix: Add automaticDecompression for httpRequest to avoid garbled code

---

libraries/Microsoft.Bot.Builder/FileTranscriptLogger.cs
libraries/Microsoft.Bot.Builder/MemoryTranscriptStore.cs
libraries/Microsoft.Bot.Builder/PagedResult.cs
libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConfiguration.cs
libraries/Microsoft.Bot.Connector/Authentication/ParameterizedBotFrameworkAuthentication.cs
libraries/Microsoft.Bot.Schema/AttachmentData.cs
libraries/Storage/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs
tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
tests/Microsoft.Bot.Builder.Tests/TranscriptBaseTests.cs
tests/Microsoft.Bot.Builder.Tests/TranscriptLoggerMiddlewareTests.cs
tests/Microsoft.Bot.Builder.Tests/Transcript_MiddlewareTests.cs
tests/Microsoft.Bot.Connector.Tests/AttachmentsTests.cs
tests/Microsoft.Bot.Schema.Tests/AttachmentTests.cs
tests/Storage/Microsoft.Bot.Builder.Azure.Blobs.Tests/TranscriptStoreBaseTests.cs

#minor
This PR removes the exclusions of the FxCop rule [CA1819](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1819) (Properties should not return arrays).
- Removed the rule exclusion and changed the property type from array to collection in the following classes:
- `Microsoft.Bot.Builder/PagedResult`: _Items_ property.
- `Microsoft.Bot.Connector/Authentication/AuthenticationConfiguration`: _RequiredEndorsements_ property.
- `Microsoft.Bot.Schema/AttachmentData`: _OriginalBase64_ and _ThumbnailBase64_ properties.
- Replaced the `Lenght` method with `Count` for the updated properties.
- Added `ToArray()` to the properties when needed.
This image shows the test passing after the changes.

[#6099] Remove low impact FxCop exclusions - Rule CA1819 (Part 1/2)

---

generators/dotnet-templates/README.md

Updated readme file to clarify when running the command `dotnet new corebot -n TestBot` expects to create project at 'TestBot/CoreBot' directory.
Fixes #6216

update readme file

---

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Choice.cs
libraries/Microsoft.Bot.Builder.Dialogs/Choices/Find.cs
libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
libraries/Microsoft.Bot.Builder.Dialogs/DialogInstance.cs
libraries/Microsoft.Bot.Builder.Dialogs/DialogState.cs
libraries/Microsoft.Bot.Builder.Dialogs/PersistedState.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptOptions.cs
testbots/Microsoft.Bot.Builder.TestBot.Shared/Dialogs/UserProfileDialog.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/CloudOAuthPromptTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs

#minor
This PR removes the exclusions of the FxCop rule [CA2227](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227) (Collection properties should be read-only).
- Added a constructor to `PromptOptions` class to set the prompt activity and the choices as almost every instance of this class had these two properties set.
- …

[#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 2/8)

---

libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs
libraries/Microsoft.Bot.Connector/Authentication/ManagedIdentityAuthenticator.cs
libraries/Microsoft.Bot.Connector/Authentication/MsalAppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/Retry.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/RetryTests.cs

Fixes #6099
This PR removes the exclusions of the FxCop rule **VSTHRD200** (Use "Async" suffix for async methods).
- Renamed method `Run` as `RunAsync` in the _Retry_ class.
- Updated references to the method and unit tests.

[#6099] Remove low impact FxCop exclusions - Rule VSTHRD200

---

generators/vsix-vs-win/BotBuilderVSIX-V4/BotBuilderTemplatesVSIX.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/Directory.Build.props
generators/vsix-vs-win/BotBuilderVSIX-V4/packages.config

Fixes #minor
Build VSIX-DotNet-templates/293117 against branch releases/4.15 failed. It also failed to build locally.
Add Directory.Build.props to the project folder to prevent the build's using the one at the repo root.
Update Analyzers references to v 16.x. This fixed the local build.

Fix BotBuilderTemplatesVSIX project in branch releases/4.15

---

libraries/Microsoft.Bot.Builder/BotStateSet.cs
libraries/Microsoft.Bot.Schema/Entity.cs
libraries/Microsoft.Bot.Schema/ExpectedReplies.cs
libraries/Microsoft.Bot.Schema/MicrosoftPayMethodData.cs
libraries/Microsoft.Bot.Schema/PagedMembersResult.cs
libraries/Microsoft.Bot.Schema/PaymentAddress.cs
libraries/Microsoft.Bot.Schema/PaymentDetails.cs
libraries/Microsoft.Bot.Schema/PaymentDetailsModifier.cs
libraries/Microsoft.Bot.Schema/PaymentMethodData.cs
libraries/Microsoft.Bot.Schema/PaymentRequest.cs
libraries/Microsoft.Bot.Schema/SemanticAction.cs
tests/Microsoft.Bot.Schema.Tests/ActivityTestData.cs

#minor
This PR removes the exclusions of the FxCop rule [CA2227](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227) (Collection properties should be read-only) in **Bot.Schema** classes.
- Microsoft.Bot.Builder/BotStateSet: BotStates.
- Microsoft.Bot.Schema/Entity: Properties
- Microsoft.Bot.Schema/ExpectedReplies: Activities.
- …

[#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 8/8)

---

libraries/Microsoft.Bot.Schema/Teams/ConversationList.cs
libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayload.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionAction.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionQuery.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionResult.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionSuggestedAction.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCard.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardActionCard.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardMultichoiceInput.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardOpenUri.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardSection.cs
libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardViewAction.cs
libraries/Microsoft.Bot.Schema/Teams/TabResponseCards.cs
libraries/Microsoft.Bot.Schema/Teams/TabSubmitData.cs
libraries/Microsoft.Bot.Schema/Teams/TabSuggestedActions.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsPagedMembersResult.cs
tests/Microsoft.Bot.Schema.Tests/Teams/MessageActionsPayloadTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabResponseCardsTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabSubmitDataTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabSuggestedActionsTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TabsTestData.cs

#minor
This PR removes the exclusions of the FxCop rule [CA2227](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227) (Collection properties should be read-only) in **Bot.Schema/Teams** classes.
- Microsoft.Bot.Schema/Teams/ConversationList: Conversations.
- Microsoft.Bot.Schema/Teams/MessageActionsPayload: Attachments, Mentions, and Reactions.
- Microsoft.Bot.Schema/Teams/MessagingExtensionAction: …

[#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 3/8)

---

libraries/Microsoft.Bot.Connector.Streaming/Payloads/ReceiveRequest.cs
libraries/Microsoft.Bot.Connector.Streaming/Payloads/ReceiveResponse.cs
libraries/Microsoft.Bot.Connector.Streaming/Payloads/StreamingRequest.cs
libraries/Microsoft.Bot.Connector.Streaming/Payloads/StreamingResponse.cs
libraries/Microsoft.Bot.Connector.Streaming/Session/StreamingSession.cs
libraries/Microsoft.Bot.Schema/TokenExchangeInvokeRequest.cs
libraries/Microsoft.Bot.Schema/TokenExchangeInvokeResponse.cs
libraries/Microsoft.Bot.Schema/TokenRequest.cs
libraries/Microsoft.Bot.Schema/TokenResponse.cs
libraries/Microsoft.Bot.Schema/Transcript.cs
tests/Microsoft.Bot.Connector.Streaming.Tests/Payloads/RequestTests.cs
tests/Microsoft.Bot.Connector.Streaming.Tests/Payloads/ResponseTests.cs
tests/Microsoft.Bot.Connector.Streaming.Tests/Session/StreamingSessionTests.cs
tests/Microsoft.Bot.Schema.Tests/TokenTests.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs

#minor
This PR removes the exclusions of the FxCop rule [CA2227](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227) (Collection properties should be read-only) in **Bot.Connector.Streaming** classes.
- **_Streams_** property: 
- Microsoft.Bot.Connector.Streaming/Payloads/ReceiveRequest
- …

[#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 4/8)

---

libraries/Microsoft.Bot.Connector/Authentication/BotFrameworkClientImpl.cs
libraries/Microsoft.Bot.Connector/Authentication/UserTokenClientImpl.cs
libraries/Microsoft.Bot.Connector/ConversationsEx.cs
libraries/Microsoft.Bot.Connector/OAuthClientOld.cs
libraries/Microsoft.Bot.Schema/AadResourceUrls.cs
libraries/Microsoft.Bot.Schema/ChannelAccount.cs
libraries/Microsoft.Bot.Schema/ConversationAccount.cs
libraries/Microsoft.Bot.Schema/ConversationMembers.cs
libraries/Microsoft.Bot.Schema/ConversationParameters.cs
libraries/Microsoft.Bot.Schema/ConversationsResult.cs
tests/Microsoft.Bot.Connector.Tests/ConversationsTests.cs
tests/Microsoft.Bot.Connector.Tests/OAuthConnectorTests.cs
tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs
tests/Microsoft.Bot.Schema.Tests/ConversationTests.cs
tests/Microsoft.Bot.Schema.Tests/IActivityExtensionsTests.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs

#minor
This PR removes the exclusions of the FxCop rule [CA2227](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227) (Collection properties must be read-only).
- Microsoft.Bot.Schema/AadResourceUrls: ResourceUrls.
- Microsoft.Bot.Schema/ChannelAccount: Properties.
- Microsoft.Bot.Schema/ConversationAccount: Properties.
- …

[#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 5/8)

---

libraries/Microsoft.Bot.Builder.AI.QnA/Utils/QnACardBuilder.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
libraries/Microsoft.Bot.Builder/ActivityFactory.cs
libraries/Microsoft.Bot.Builder/MessageFactory.cs
libraries/Microsoft.Bot.Schema/AnimationCard.cs
libraries/Microsoft.Bot.Schema/AudioCard.cs
libraries/Microsoft.Bot.Schema/BasicCard.cs
libraries/Microsoft.Bot.Schema/HeroCard.cs
libraries/Microsoft.Bot.Schema/MediaCard.cs
libraries/Microsoft.Bot.Schema/OAuthCard.cs
libraries/Microsoft.Bot.Schema/ReceiptCard.cs
libraries/Microsoft.Bot.Schema/SigninCard.cs
libraries/Microsoft.Bot.Schema/SuggestedActions.cs
libraries/Microsoft.Bot.Schema/ThumbnailCard.cs
libraries/Microsoft.Bot.Schema/VideoCard.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs
tests/Microsoft.Bot.Connector.Streaming.Tests/Integration/EndToEndMiniLoadTests.cs
tests/Microsoft.Bot.Connector.Tests/ConversationsTests.cs
tests/Microsoft.Bot.Schema.Tests/CardExTest.cs

#minor
This PR removes the exclusions of the FxCop rule [CA2227](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227) (Collection properties should be read-only) in **Cards** classes.
- **_Media_** and **_Buttons_** properties:
- Microsoft.Bot.Schema/AnimationCard
- Microsoft.Bot.Schema/AudioCard
- Microsoft.Bot.Schema/BasicCard
- …

[#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 6/8)

---

generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/appsettings.Development.json
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/appsettings.Development.json
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/appsettings.Development.json
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/appsettings.Development.json

Fixes #minor
Fix the warning in VS 2019 when creating a bot project from a VSIX template: "The file appsettings.Development.json could not be found within the project templates. Continuing to run, but the resulting project may not build properly."
Add appsettings.Development.json files.

Fix VS warning from v 4.15.2 VSIX bot templates

---

build/yaml/botbuilder-dotnet-ci.yml

Fixes #minor
When the dotnet CI-PR pipeline's Build stage fails, the API_Compatibility_Validation stage should be skipped. But it runs anyway, wasting pipeline time and resources.
This fixes that.

In CI pipeline, make API compatibility run only when warranted.

---

build/yaml/botbuilder-dotnet-sign.yml

Fixes #minor
This fixes incorrect PreviewPackageVersion and ReleasePackageVersion resolution in pipeline BotBuilder-DotNet-Signed-daily-v5.
Versions currently use UTC date. They should use the local date, the date that is embedded in the build number and that is shown in the build datetime listings.

Fix incorrect date in v5 package versioning 

---

build/yaml/sdk_dotnet_v4_org-feed-setup-steps.yml

Fixes #minor
PR validation checks fail against forks with error "403 Forbidden": For security reasons forks do not have access to our private feed, SDK_Dotnet_V4_org.
This adds a conditional for PRs against forks, allowing forks to resolve dependencies from the public Nuget.org feed.

Fix PR validation builds against forks

---

libraries/Directory.Build.props
tests/Microsoft.Bot.Connector.Streaming.Tests/Microsoft.Bot.Connector.Streaming.Tests.csproj

Fixes #6174
Update additional 3rd party dependencies beyond those of PR #6191
This completes the updates for Issue #6174
ReportGenerator 5.0.3 -> 5.0.4
Microsoft.CodeAnalysis.FxCopAnalyzers 3.0.0 (deprecated) -> Microsoft.CodeAnalysis.NetAnalyzers 5.0.3

Update v5 dependencies to latest versions - Part 2

---

build/PublishToCoveralls.ps1
build/yaml/ci-build-steps.yml
build/yaml/ci-test-steps.yml

Fixes #minor
In pipeline BotBuilder-DotNet-CI-PR-yaml, the task that uploads test results to coveralls.io has been failing. This fixes it.

Fix Publish To Coveralls in the CI build

---

build/yaml/botbuilder-dotnet-ci-mac.yml
build/yaml/sdk_dotnet_v4_org-feed-setup-steps.yml

Fixes #minor
This fixes a regression from PR #6227.
The nuget restore task fails when a nuget.config file is not created. So instead of skipping nuget.config creation for forks, this now points sources to nuget.org for forks.
Also fixes mac PR builds against forks.

Fix PR validation builds against forks no. 2

---

build/yaml/ci-post-to-github-steps.yml
build/yaml/ci-test-steps.yml
build/yaml/sdk_dotnet_v4_org-feed-setup-steps.yml

Fixes #minor
Smooth out fork handling in CI builds.
Skip the failing task "Remove SDK_Dotnet_V4_org feed..."
Add clarifying log message 'System.PullRequest.IsFork = True'

Improved fork handling in CI pipeline

---

libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateErrors.cs
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs
tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs

Fixes #6269 
- Remove customer data from error messages
- Update unit tests
To avoid making changes to the public surface area, method parameters are not being changed. This introduces a rule violation that is being bypassed.

Remove customer data from error logging

---

libraries/Microsoft.Bot.Builder.Dialogs/Extensions.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
libraries/Microsoft.Bot.Builder/ActivityFactory.cs
libraries/Microsoft.Bot.Schema/AnimationCard.cs
libraries/Microsoft.Bot.Schema/AudioCard.cs
libraries/Microsoft.Bot.Schema/BasicCard.cs
libraries/Microsoft.Bot.Schema/CardEx.cs
libraries/Microsoft.Bot.Schema/CardImage.cs
libraries/Microsoft.Bot.Schema/ContentTypes.cs
libraries/Microsoft.Bot.Schema/HeroCard.cs
libraries/Microsoft.Bot.Schema/MediaCard.cs
libraries/Microsoft.Bot.Schema/OAuthCard.cs
libraries/Microsoft.Bot.Schema/ReceiptCard.cs
libraries/Microsoft.Bot.Schema/SigninCard.cs
libraries/Microsoft.Bot.Schema/ThumbnailCard.cs
libraries/Microsoft.Bot.Schema/VideoCard.cs
testbots/Skills/Parent/ParentBot.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/CloudOAuthPromptTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/SkillDialogTests.cs
tests/Microsoft.Bot.Connector.Tests/ConversationsTests.cs

Addresses #6100
#minor
This PR consolidates the Card classes that were split into different files.
- Removed the _partial_ modifier from the different Card classes and removed the partial _CustomInit_ method.
- Created `ContentTypes` class with the definition for the Cards' content type.
- Removed the `partial` modifier from the `Extensions` class.
- Define new `CardEx` class with the extension methods `toAttachment()` used for the cards.

[#6100] Remove unnecessary partial classes - Consolidate Cards

---

libraries/Microsoft.Bot.Schema/Teams/AppBasedLinkQuery.cs
libraries/Microsoft.Bot.Schema/Teams/CacheInfo.cs
libraries/Microsoft.Bot.Schema/Teams/ChannelInfo.cs
libraries/Microsoft.Bot.Schema/Teams/ConversationList.cs
libraries/Microsoft.Bot.Schema/Teams/FileConsentCardResponse.cs
libraries/Microsoft.Bot.Schema/Teams/MeetingDetails.cs
libraries/Microsoft.Bot.Schema/Teams/MeetingDetailsBase.cs
libraries/Microsoft.Bot.Schema/Teams/MeetingEndEventDetails.cs
libraries/Microsoft.Bot.Schema/Teams/MeetingEventDetails.cs
libraries/Microsoft.Bot.Schema/Teams/MeetingInfo.cs
libraries/Microsoft.Bot.Schema/Teams/MeetingParticipantInfo.cs
libraries/Microsoft.Bot.Schema/Teams/MeetingStartEventDetails.cs
libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayload.cs
libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadApp.cs
libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadAttachment.cs
libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadBody.cs
libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadConversation.cs
libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadFrom.cs
libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadMention.cs
libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadReaction.cs
libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadUser.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionAction.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionActionResponse.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionAttachment.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionParameter.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionQuery.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionQueryOptions.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionResponse.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionResult.cs
libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionSuggestedAction.cs

Addresses #6100
#minor
This PR removes the `partial` modifier from classes with only one definition in **_Microsoft.Bot.Schema/Teams_**.
- Removed the `partial` modifier from classes with only one definition.
- Removed partial method `CustomInit` and the constructor that was using it.
- Removed unnecessary using statements.

[#6100] Remove unnecessary partial classes - Schema/Teams classes (1/2)

---

libraries/Microsoft.Bot.Schema/ConversationMembers.cs
libraries/Microsoft.Bot.Schema/ConversationParameters.cs
libraries/Microsoft.Bot.Schema/ConversationResourceResponse.cs
libraries/Microsoft.Bot.Schema/ConversationsResult.cs
libraries/Microsoft.Bot.Schema/ReceiptItem.cs
libraries/Microsoft.Bot.Schema/ResourceResponse.cs
libraries/Microsoft.Bot.Schema/SemanticAction.cs
libraries/Microsoft.Bot.Schema/SignInResource.cs
libraries/Microsoft.Bot.Schema/TextHighlight.cs
libraries/Microsoft.Bot.Schema/Thing.cs
libraries/Microsoft.Bot.Schema/ThumbnailUrl.cs
libraries/Microsoft.Bot.Schema/TokenExchangeRequest.cs
libraries/Microsoft.Bot.Schema/TokenExchangeResource.cs
libraries/Microsoft.Bot.Schema/TokenRequest.cs
libraries/Microsoft.Bot.Schema/TokenResponse.cs
libraries/Microsoft.Bot.Schema/TokenStatus.cs
libraries/Microsoft.Bot.Schema/Transcript.cs

Addresses #6100
#minor
This PR removes the `partial` modifier from classes with only one definition in **_Microsoft.Bot.Schema_**.
- Removed the `partial` modifier from classes with only one definition.
- Removed partial method `CustomInit` and the constructor that was using it.
- Removed unnecessary using statements.

[#6100] Remove unnecessary partial classes - Schema classes (2/2)

---

libraries/Microsoft.Bot.Schema/AadResourceUrls.cs
libraries/Microsoft.Bot.Schema/AttachmentData.cs
libraries/Microsoft.Bot.Schema/AttachmentInfo.cs
libraries/Microsoft.Bot.Schema/AttachmentView.cs
libraries/Microsoft.Bot.Schema/Error.cs
libraries/Microsoft.Bot.Schema/ErrorResponse.cs
libraries/Microsoft.Bot.Schema/ExpectedReplies.cs
libraries/Microsoft.Bot.Schema/Fact.cs
libraries/Microsoft.Bot.Schema/InnerHttpError.cs
libraries/Microsoft.Bot.Schema/MediaEventValue.cs
libraries/Microsoft.Bot.Schema/MediaUrl.cs
libraries/Microsoft.Bot.Schema/MessageReaction.cs
libraries/Microsoft.Bot.Schema/PagedMembersResult.cs
libraries/Microsoft.Bot.Schema/PaymentAddress.cs
libraries/Microsoft.Bot.Schema/PaymentCurrencyAmount.cs
libraries/Microsoft.Bot.Schema/PaymentDetails.cs
libraries/Microsoft.Bot.Schema/PaymentDetailsModifier.cs
libraries/Microsoft.Bot.Schema/PaymentItem.cs
libraries/Microsoft.Bot.Schema/PaymentMethodData.cs
libraries/Microsoft.Bot.Schema/PaymentOptions.cs
libraries/Microsoft.Bot.Schema/PaymentRequestComplete.cs
libraries/Microsoft.Bot.Schema/PaymentRequestCompleteResult.cs
libraries/Microsoft.Bot.Schema/PaymentRequestUpdate.cs
libraries/Microsoft.Bot.Schema/PaymentRequestUpdateResult.cs
libraries/Microsoft.Bot.Schema/PaymentResponse.cs
libraries/Microsoft.Bot.Schema/PaymentShippingOption.cs

Addresses #6100
#minor
This PR removes the `partial` modifier from classes with only one definition in **_Microsoft.Bot.Schema_**.
- Removed the `partial` modifier from classes with only one definition.
- Removed partial method `CustomInit` and the constructor that was using it.
- Removed unnecessary using statements.
- Added null validation for constructor's parameters in **_AttachmentData_** class.

[#6100] Remove unnecessary partial classes - Schema classes (1/2)

---

libraries/Microsoft.Bot.Builder/ActivityHandler.cs
libraries/Microsoft.Bot.Schema/SearchInvokeOptions.cs
libraries/Microsoft.Bot.Schema/SearchInvokeResponse.cs
libraries/Microsoft.Bot.Schema/SearchInvokeTypes.cs
libraries/Microsoft.Bot.Schema/SearchInvokeValue.cs
tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
tests/Microsoft.Bot.Schema.Tests/SearchQueryTests.cs

Fixes #5643
`OnInvokeActivityAsync` here: 
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-type-ahead-search-adaptive-cards/csharp/TypeaheadSearch/Bots/ActivityBot.cs#L85
Would be changed to:
```cs
protected override async Task<SearchInvokeResponse> OnSearchInvokeAsync(ITurnContext<IInvokeActivity> turnContext, SearchInvokeValue invokeValue, CancellationToken cancellationToken)
{
var packageResult = JObject.Parse(await(new HttpClient()).GetStringAsync($"https://azuresearch-usnc.nuget.org/query?q=id:{invokeValue.QueryText}&prerelease=true"));
if (packageResult == null)
{
// no results available, return 204
return new SearchInvokeResponse
{
Type = "application/vnd.microsoft.search.searchResponse",
StatusCode = 204
};
}
else
{
var packageList = …
```

Add support for search invoke

---

libraries/Microsoft.Bot.Builder/EventFactory.cs
tests/Microsoft.Bot.Builder.Tests/EventFactoryTests.cs

Fixes #6240 
This PR fixes an issue in `CreateHandoffEvent` in `EventFactory.cs` where the function expects that the handoff context will be non-null, but no error checking is performed. Thus, the function breaks and throws a null exception if no context is supplied. For example, if a handoff event is created in Composer and no context is specified in the action, this error will occur.
- Adds a null check in `CreateHandoffEvent` in `EventFactory.cs` to only try to convert the handoff context to a `JObject` if it is not null.
Ran the unit tests and attempted the scenario in a fresh Composer bot. Both ran without failing.

Fix for null exception on null handoff context in CreateHandoffEvent

---

libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs

Fixes #6278 
When sending an activity over web sockets, if we encounter a non 200 status code, we are only logging the status code. This change logs the detailed error message along with the status code to enable better debugging.

Log error message from Streaming web socket response.

---

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/CloudAdapter.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs

Fixes #6281 
When checking for an active web socket connection to send a proactive message, the ServiceUrl on the connection is compared to the ServiceUrl on the activity. This check is failing when the ServiceUrl is null. This PR will ignore the connection that has no ServiceUrl.

Do not check for streaming activity if ServiceUrl is null.

---

FunctionalTests/ExportedTemplate/LinuxDotNet/template-with-preexisting-rg.json

Fixes #minor
This fixes pipeline BotBuilder-DotNet-Functional-Tests-Linux-yaml.
##[error]InvalidResourceEntity: Invalid sku name for ABS. Allowed values: F0, S1.
Fix is the same as in https://github.com/microsoft/BotBuilder-Samples/pull/3732

Fix sku values in ARM template

---

build/PublishToCoveralls.ps1
build/yaml/ci-test-steps.yml

Fixes #minor
The current coveralls.net relies on the outdated .NET Core sdk 2.1.
Update build\PublishToCoveralls.ps1 to use coveralls.net 3.0.0.
Drop task "Use .NET Core sdk 2.1" which was required by the older version.

Update pipeline to coveralls.net v 3.0.0

---

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterOAuthTests.cs
tests/Microsoft.Bot.Builder.Tests/MockAppCredentials.cs

Fixes #6308
We cache OAuthClients by appId so changing the endpoint only affects newly created clients that are not already cached.  This PR adds the endpoint to the cache key so we can support changing the endpoint at runtime.
- Added OAuthEndpoint to the cache key for the _oAuthClients cache
Added tests for

Add oAuthEndpoint to _oAuthClients cache key

---

generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/DeploymentTemplates/README.md
generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/DeploymentTemplates/README.md
generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/DeploymentTemplates/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/DeploymentTemplates/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/DeploymentTemplates/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/DeploymentTemplates/README.md

Fixes #6229
This PR adds a README file with descriptions for the ARM template parameters in each bot generator template.
- Added a README file with descriptions for the ARM template parameters in:
- Dotnet-templates
- Microsoft.BotFramework.CSharp.CoreBot
- Microsoft.BotFramework.CSharp.EchoBot
- Microsoft.BotFramework.CSharp.EmptyBot
- BotBuilderVSIX-V4
- CoreBot
- EchoBot
- EmptyBot
README.md view from GitHub

[#6229] Add descriptions to ARM template parameters files

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs

Fixes #6313
This PR adds support to ForEachElement to properly handle RepromptDialog event after an interruption.

Handle DialogEvents.RepromptDialog in ForEachElement

---

build/yaml/botbuilder-dotnet-ci-webex-test.yml

Fixes #minor
Test SendAndReceiveWebexMessageShouldSucceed() fails intermittently.
System.Net.WebException: The remote server returned an error: (400) Bad Request.
Could it be that the deployed bot does not always have enough time to spin up?
Add task 'Sleep 1 minute for bot to settle'

BotBuilder-DotNet-Webex-Functional-Test-yaml intermittently fails

---

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterOAuthTests.cs
tests/Microsoft.Bot.Builder.Tests/MockAppCredentials.cs

#minor
* Add oAuthEndpoint to _oAuthClients cache key
* Add CreateOAuthClientWithDifferentEndpoints test
Authored-by: Craig Jensen <crjens@hotmail.com>

fix: Add oAuthEndpoint to _oAuthClients cache key (#6298)

---

libraries/Microsoft.Bot.Builder.Azure/AssemblyInfo.cs
libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobStorageTests.cs

Addresses #6292
#minor
This PR removes the existing Functional tests for the `AzureBlobStorage` class and replaces them with unit tests that don't require the use of the Azure Storage Emulator.
- Updates the `AzureBlobStorage` class, adding a new internal constructor that receives an instance of _CloudBlobClient_. This constructor is for the use of the tests only.
- Replaces the existing tests in the `AzureBlobStorageTests` class with unit tests for each method, constructor, method validations, etc, reaching 89% of code coverage.
The following images show the new unit tests and the code coverage.

[#6292] Add unit tests for AzureBlobStorage

---

libraries/Microsoft.Bot.Connector/Channels.cs

Fixes #5678
This PR updates the Channels enum adding Outlook and marking Twilio as obsolete.
- Added new channel Outlook.
- Marked Twilio as obsolete.

[#5678] Channels "enumeration" is out of date

---

libraries/Microsoft.Bot.Connector/Channels.cs

Fixes #6339
This PR marks the unsupported channels as deprecated.
Unsupported channels:
- Cortana
- EnterpriseChannel
- Kaizala
- Kik
- SkypeForBusiness
- Unsupported channels are marked as deprecated in Microsoft.Bot.Connector/Channels.cs
This screenshot shows the unit tests passing

[#6339] Mark deprecated channels as obsolete in Channels enum

---

libraries/Microsoft.Bot.Builder.Azure/AssemblyInfo.cs
libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs
tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionedStorageTests.cs

Addresses #6292
#minor
This PR removes the existing Functional tests and as a replacement, it adds support for internal testing to the `CosmosDbPartitionedStorage` class, and introduces all the necessary unit tests, increasing the **code coverage up to 86%**.
- Updates the `CosmosDbPartitionedStorage` class, adding a new internal constructor.
- Updates the `CosmosDbPartitionedStorage.DocumentStoreItem` class accessibility from `private` to `internal`, so it can be accessed from the tests.
- Adds new unit tests to the `CosmosDbPartitionedStorageTests` class for each method, constructor, method validations, etc.
The following image shows the new unit tests and the code coverage.

[#6292] Update CosmosDbPartitionedStorage from Functional to Unit tests

---

libraries/Microsoft.Bot.Builder.Azure.Queues/AssemblyInfo.cs
libraries/Microsoft.Bot.Builder.Azure.Queues/AzureQueueStorage.cs
tests/Microsoft.Bot.Builder.Azure.Tests/AzureQueueStorageTests.cs

Addresses #6292
#minor
This PR removes the existing Functional tests and as a replacement, it adds support for internal testing to the `AzureQueueStorage` class, and introduces all the necessary unit tests, increasing the **code coverage up to 100%**.
- Updates the `AzureQueueStorage` class, adding a new internal constructor.
- Adds new unit tests to the `AzureQueueStorageTests` class for each method, constructor, method validations, etc.
The following image shows the new unit tests and the code coverage.

[#6292] Update Azure Queues from Functional to Unit tests

---

build/yaml/botbuilder-dotnet-ci-facebook-test-secondary.yml
build/yaml/botbuilder-dotnet-ci-facebook-test.yml
build/yaml/botbuilder-dotnet-ci-slack-test.yml
build/yaml/botbuilder-dotnet-ci-twilio-test.yml
build/yaml/botbuilder-dotnet-ci-webex-test.yml
build/yaml/botbuilder-dotnet-functional-test-linux.yml
build/yaml/botbuilder-dotnet-functional-test-windows.yml
build/yaml/botbuilder-dotnet-functional-tests-setup.yml
build/yaml/functional-test-setup-steps.yml

Fixes #5977
This PR updates the FunctionalTests pipelines to target .NET6.
**_Note: The PR depends on PR #6332 with the changes in the test projects_.**
- Updated the _vmImages_ from windows-2019 to windows-2022.
- Changed framework from netcoreapp3.1 to net6.0 in `build/yaml/functional-test-setup-steps.yml`.
Here we can see the pipelines working after the changes.

[#5977] Update projects to .Net 6 - Functional Test pipelines

---

libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs

#minor
This PR fixes the using blocks in the _LogActivityAsync_ method of _AzureBlobTranscriptStore_ class that was causing the Functional Tests to fail with the `The specified blob does not exist` error. 
- Updated _LogActivityAsync_ method to leave the _SetMetadaAsync_ outside the _blobStream_'s using scope.
This image shows the functional tests (BotFramework-FunctionalTests) and the unit tests passing after the change.

Fix AzureBlobTranscriptStore tests - The specified blob does not exist

---

libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs
libraries/Microsoft.Bot.Builder.AI.QnA/Utils/QnACardBuilder.cs

Fixes #6351
Store qnaId in the prompts so that its readily available everytime the prompt is clicked
- Changed prompt type from "imBack" to "messageBack"
- pass qnaId as value in prompts
- Check if value has qnaId before resetting dialogOptions.

Add QnAId in value attribute of multi-turn prompts.

---

generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/template.json
generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/README.md
generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/.template.config/template.json
generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/README.md
generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.template.config/template.json
generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.vstemplate
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.Tests.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBotWithTests.vstemplate
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.vstemplate
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.vstemplate
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/README.md

Fixes #6323
This PR updates the bot templates in `dotnet-templates` and `vsix-vs-win` to target .NET6 as default.
It also updates the README file of each bot.
- Updated template.json of the following bots to target .NET6:
- dotnet-templates
- EchoBot
- CoreBot
- EmptyBot
- vsix-vs-win
- EchoBot
- CoreBot
- CoreBot with tests
- EmptyBot
- Updated .csproj of the vsix-vs-win bots
- Updated the README files' _Install .NET CLI_ section

[#6323] Update generators and vsix to target Net 6 by default

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj
libraries/AdaptiveExpressions/AdaptiveExpressions.csproj
libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj
libraries/Microsoft.Bot.Builder.Azure.Blobs/Microsoft.Bot.Builder.Azure.Blobs.csproj
libraries/Microsoft.Bot.Builder.Azure.Queues/Microsoft.Bot.Builder.Azure.Queues.csproj
libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs
libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj
libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj
libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj
libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj
libraries/Microsoft.Bot.Connector.Streaming/Microsoft.Bot.Connector.Streaming.csproj
libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj
libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj
libraries/Parsers/Microsoft.Bot.Builder.Parsers.LU/Microsoft.Bot.Builder.Parsers.LU.csproj
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
tests/Microsoft.Bot.Builder.AI.Luis.TestUtils/Microsoft.Bot.Builder.AI.Luis.TestUtils.csproj
tests/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.Tests.csproj
tests/Microsoft.Bot.Builder.TestBot.WebApi/Microsoft.Bot.Builder.TestBot.WebApi.csproj
tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj
tests/Microsoft.Bot.Schema.Tests/Microsoft.Bot.Schema.Tests.csproj

Addresses #6392
#minor
**_Note: The setting of the MaxDepth property for the rest of the json serialization/deserialization ([comment](https://github.com/microsoft/botbuilder-dotnet/issues/6392#issuecomment-1167583077)) will be addressed in another PR._**
This PR updates the version of the Newtonsoft.Json dependency to 13.0.1.
It also adds a custom CosmosDB Serializer and sets the MaxDepth property to fix the error `The reader's MaxDepth of 64 has been exceeded.` in some unit tests and integration tests.
Updated the following projects:
- libraries:
- Microsoft.Bot.Builder.Adapters.Slack
- AdaptiveExpressions
- Microsoft.Bot.Builder.AI.Luis
- Microsoft.Bot.Builder.Azure.Blobs
- Microsoft.Bot.Builder.Azure.Queues
- Microsoft.Bot.Builder.Azure
- Microsoft.Bot.Builder.Dialogs.Debugging
- …

[#6392] Bump Newtonsoft.Json from 12.0.3 to 13.0.1

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioHelper.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexHelper.cs
libraries/AdaptiveExpressions/BuiltinFunctions/Json.cs
libraries/AdaptiveExpressions/BuiltinFunctions/JsonStringify.cs
libraries/AdaptiveExpressions/BuiltinFunctions/String.cs
libraries/AdaptiveExpressions/Expression.cs
libraries/AdaptiveExpressions/ExpressionProperties/ExpressionProperty.cs
libraries/AdaptiveExpressions/Memory/SimpleObjectMemory.cs
libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV3.cs
libraries/Microsoft.Bot.Builder.AI.LUIS/V3/LuisRecognizer.cs
libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs
libraries/Microsoft.Bot.Builder.AI.QnA/CustomQuestionAnswering.cs
libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs
libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs
libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs
libraries/Microsoft.Bot.Builder.AI.QnA/Utils/LanguageServiceUtils.cs
libraries/Microsoft.Bot.Builder.AI.QnA/Utils/TrainUtils.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandler.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/HttpHelper.cs

Addresses #6392
#minor
This PR adds the setting of the `MaxDepth` property in all the JSON Serialize/Deserialize operations.
- Set MaxDepth = null in **_JsonConvert.SerializeObject_**, **_JsonConvert.DeserializeObject_**, and **_JsonTextReader_** instances of the following projects:
- Microsoft.Bot.Builder.Adapters.Facebook
- Microsoft.Bot.Builder.Adapters.Slack
- Microsoft.Bot.Builder.Adapters.Twilio
- Microsoft.Bot.Builder.Adapters.Webex
- AdaptiveExpressions
- Microsoft.Bot.Builder.AI.LUIS
- Microsoft.Bot.Builder.AI.Orchestrator
- Microsoft.Bot.Builder.AI.QnA
- Microsoft.Bot.Builder.Integration.AspNet.Core
These images show the unit tests and the FunctionalTests pipeline successfully executed.

[#6392] Bump Newtonsoft.Json from 12.0.3 to 13.0.1 - Set MaxDepth property (1/4)

---

libraries/Microsoft.Bot.Configuration/BotConfiguration.cs
libraries/Microsoft.Bot.Connector.Streaming/Transport/TransportHandler.cs
libraries/Microsoft.Bot.Connector/Authentication/BotFrameworkClientImpl.cs
libraries/Microsoft.Bot.Connector/Authentication/UserTokenClient.cs
libraries/Microsoft.Bot.Connector/ConnectorClient.cs
libraries/Microsoft.Bot.Connector/OAuthClientOld.cs
libraries/Microsoft.Bot.Connector/Teams/TeamsConnectorClient.cs
libraries/Microsoft.Bot.Schema/Entity.cs
libraries/Microsoft.Bot.Streaming/Payloads/Assemblers/ReceiveRequestAssembler.cs
libraries/Microsoft.Bot.Streaming/Payloads/Assemblers/ReceiveResponseAssembler.cs
libraries/Microsoft.Bot.Streaming/ReceiveResponseExtensions.cs
libraries/Microsoft.Bot.Streaming/SerializationSettings.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot/Bots/PrimaryBot.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/Bots/EchoBot.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.TestBot/Bots/EchoBot.cs
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Contoso_App.cs
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Contoso_App_V3.cs
tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/Contoso_App.cs
tests/Microsoft.Bot.Builder.TestBot.Shared/Bots/DialogAndWelcomeBot.cs
tests/Microsoft.Bot.Builder.TestBot.Shared/CognitiveModels/FlightBooking.cs
tests/Microsoft.Bot.Builder.TestBot.Shared/HttpHelper.cs
tests/Microsoft.Bot.Builder.TestBot.WebApi/Bots/DialogAndWelcomeBot.cs
tests/Microsoft.Bot.Connector.Streaming.Tests.Client/Program.cs
tests/Microsoft.Bot.Streaming.Tests/Utilities/MockBot.cs
tests/Skills/Bot1/Bot1.cs
tests/Skills/Bot2/Bot2.cs

Addresses #6392
#minor
This PR adds the setting of the `MaxDepth` property in all the JSON Serialize/Deserialize operations.
- Set MaxDepth = null in **_JsonConvert.SerializeObject_**, **_JsonConvert.DeserializeObject_**, and **_JsonTextReader_** instances of the following projects:
- libraries/Microsoft.Bot.Configuration/BotConfiguration.cs
- libraries/Microsoft.Bot.Connector.Streaming/Transport/TransportHandler.cs
- libraries/Microsoft.Bot.Connector/Authentication/BotFrameworkClientImpl.cs
- libraries/Microsoft.Bot.Schema/Entity.cs
- libraries/Microsoft.Bot.Streaming/Payloads/Assemblers/ReceiveRequestAssembler.cs
- And in the test bots and apps of the following projects:
- Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot
- Microsoft.Bot.Builder.Adapters.Slack.TestBot
- …

[#6392] Bump Newtonsoft.Json from 12.0.3 to 13.0.1 - Set MaxDepth property (3/4)

---

generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Bots/DialogAndWelcomeBot.cs
generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CognitiveModels/FlightBooking.cs
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Bots/DialogAndWelcomeBot.cs
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CognitiveModels/FlightBooking.cs
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Bots/DialogAndWelcomeBot.cs
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CognitiveModels/FlightBooking.cs

Fixes #6392
This PR adds the setting of the `MaxDepth` property in all the JSON Serialize/Deserialize operations.
- Set MaxDepth = null in **_JsonConvert.SerializeObject_**, **_JsonConvert.DeserializeObject_**, and **_JsonTextReader_** instances in the generators/Core bot templates.
This image shows the CoreBot working as expected after the changes:

[#6392] Bump Newtonsoft.Json from 12.0.3 to 13.0.1 - Set MaxDepth property (4/4)

---

build/PublishToCoveralls.ps1

Fixes #minor
PublishToCoveralls.ps1 is failing in builds now that build agents are running Windows 2022.
Path to CodeCoverage.exe adjusted to work in both Windows 2019 and Windows 2022.

Fix PublishToCoveralls.ps1 for Windows 2022

---

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityExtensions.cs
libraries/Microsoft.Bot.Schema/Teams/ChannelInfo.cs
libraries/Microsoft.Bot.Schema/Teams/TeamDetails.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsChannelData.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsChannelDataSettings.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityExtensionsTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/ChannelInfoTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TeamDetailsTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TeamsChannelDataTests.cs

Add settings.selectedChannel to TeamsChannelData and Type to ChannelInfo and TeamDetails

---

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs
libraries/Microsoft.Bot.Schema/Teams/ReadReceiptInfo.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/ReadReceiptInfoTests.cs

Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/6357

Add Teams read receipt event

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.csproj
libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj

Fixes #6408
Component governance triggered on Microsoft.ApplicationInsights.AspNetCore dependency. 
Upgrade Microsoft.ApplicationInsights to 4.20 in Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime and Microsoft.Bot.Builder.Integration.ApplicationInsights.Core

Testing narrow appinsights update

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs

Catch HttpRequestException in HttpRequest

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.csproj
libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj

Fixes #minor
Update App Insights dependencies and net core dependencies to safe versions to be compatible with PVA

Lowered AppInsights requirements

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs

Fixes #6355
This PR adds the ability to load dynamically dialogs when the bot is restarted during a conversation.
- Adds a step to gather the dialog resource when isn't found in the dialogs stack from the `ResourceExplorer` to be loaded automatically into the dialogs stack.
The following image shows the dialog working from a Composer bot and the new unit test passing.

[#6355] ContinueDialog fails to find dynamically loaded dialog after bot restart

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/RegexRecognizerTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/RegexRecognizerTests/RegexRecognizerTests_Priority.test.dialog

Fixes #6434
This PR updates the AdaptiveDialog's OnRecognizeAsync method to take into consideration the priority set for the intents when there is more than one result with the same score.
- Updated the `OnRecognizeAsync` method to choose the topIntent considering both score and priority.
- Removed the break from the `RecognizeAsync` method to return all the intents that match the pattern.
- Added a unit test to cover the priority scenario in `RegexRecognizerTests`.
- Added test script `RegexRecognizerTests_Priority.test.dialog`
These images show the bot not recognizing the correct intent before and the bot returning the right intent according to its priority after the changes.

[#6434] Priority broken for RegexRecognizer

---

libraries/AdaptiveExpressions/BuiltinFunctions/IsMatch.cs
tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs

Fixes #6354
This PR fixes the issue where the `isMatch` adaptive expression built-in function returns the error message `regular expression is empty` when the value is null or an empty string to just being processed by the evaluator instead.
- Updates the `IsMatch` built-in function to handle empty strings and null values by the evaluator.
- Adds new unit tests to handle empty string and null values for the `IsMatch` function.
The following image shows the tests passing successfully.

[#6354] isMatch adaptive expression returns error when value is null or empty string

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs

Fixes #6428
This PR fixes the malfunctioning of the ForEachElement loop when there're recursive calls to the _ContinueDialogAsync_ method by reacquiring the child dialog state after finishing the _ContinueDialogAsync_ execution. 
- Updated the `RunItemsAsync` method of the **_ForEachElement_** class to call the _GetActionScopeState_ method again after finishing the _ContinueDialogAsync_ execution.
- Added a unit test in the `AdaptiveDialogTests` class to cover the scenario with recursive calls to the _ContinueDialogAsync_ method.
These images show the _ForEachElement_'s behavior before and after the fix.

[#6428] Adaptive ForEachElement loop's incorrectly when changes cause ContinueDialogAsync to be recalled

---

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
libraries/Microsoft.Bot.Schema/OAuthCard.cs
libraries/Microsoft.Bot.Schema/SignInResource.cs
libraries/Microsoft.Bot.Schema/TokenPostResource.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs

Fixes #minor
N/A
This PR introduces support for passing through a token post resource via botbuilder. The token post resource contains a sas url for directly posting a token from a client to the bot framework token service. Botbuilder gets this url from token service and passes it onto the client.
- Add support for token post resource
- Support optional token post resource inside oauthcard
- Added unit tests

Support passing sas token url's for token service

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_Foreach_Nested_WithCancel.test.dialog

Fixes #6430
This PR fixes the issue in the `ForEachElement` action that wasn't exiting the loop after a call to the _CancelAllDialogs_ action.
The fix also considers the nested _ForEachElement_ loops scenario.
- Updated the `ShouldEndDialog` method of the _ForEachElement_ class to consider also _Cancelled_ status as well as _Complete_ to end the dialogs.
- Added a unit test in the `ActionTests` class to cover the nested ForEachElement's loops with a _CancelAllDialogs_ call scenario.
- Added the `Action_Foreach_Nested_WithCancel.test.dialog` test script.
These images show the issue fixed after the changes.

[#6430] Adaptive ForEachElement does not exit when child action CancelAllDialogs is called

---

build/ExtractCompressNuGet.ps1

Fixes #minor
ExtractCompressNuGet.ps1 has commented-out outmoded powershell patching code.
This cleans that up.

Clean up ExtractCompressNuGet.ps1 in dotnet

---

libraries/Microsoft.Bot.Builder/ChannelServiceHandlerBase.cs
libraries/Microsoft.Bot.Builder/Skills/CloudSkillHandler.cs
libraries/Microsoft.Bot.Builder/Skills/SkillHandlerImpl.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ChannelServiceController.cs
tests/Microsoft.Bot.Builder.Tests/Skills/CloudSkillHandlerTests.cs

Fixes #6432
This PR fixes the error thrown when executing the **_TeamsInfo.GetMemberAsync_** from a skill bot implementing the method in the **_CloudSkillHandler_** class.
- Added the _HandleGetConversationMemberAsync_ and _OnGetConversationMemberAsync_ methods in `ChannelServiceHandlerBase`.
- Added the _OnGetConversationMemberAsync_ method in the `CloudSkillHandler` class.
- Added the implementation of the _OnGetMemberAsync_ method in the `SkillHandlerImpl` class.
- Added the _GetConversationMemberAsync_ method in the `ChannelServiceController` class.
- Added unit test in `CloudSkillHandlerTests`.
These images show the skill bot retrieving the member's information successfully and the new unit test passing.

[#6432] TeamsInfo.GetMemberAsync(...) doesn't work properly in Skill Bot scenario, it returns http 405 error

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BaseInvokeDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs
libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_LoadDialogFromProperty.test.dialog

Fixes #6433
This PR fixes an issue where the `ComponentDialog` cannot be found in the `Dialogs stack` and in the `ResourceExplorer` when using `AdaptiveDialogs`, adding a condition to evaluate the resource existence before trying to load it into the dialogs stack.
Additionally, it reworks the solution to load the dialog resource from the DialogContext instead when it cannot find the dialog (more information can be found in this [comment](https://github.com/microsoft/botbuilder-dotnet/issues/6355#issuecomment-1222208111)).
- Adds a pre-condition before trying to load the dialog from the `ResourceExplorer`.
- Added a unit test validating the new condition when using `ComponentDialogs` with `AdaptiveDialogs`.
- Added `FindDialog` method in the `AdaptiveDialog` class, that detects when there …

[#6433] Error in AdaptiveDialog.ContinueActionAsync with native dialog SDK

---

libraries/Microsoft.Bot.Connector/Teams/TeamsOperations.cs

Fixes #6446
This PR adds the cancellation token in the `TeamsOperations` class methods to be passed in to the `GetResponseAsync` method.
- Update `TeamsOperations` method, adding the cancellation token to the `GetResponseAsync` method call.

[#6446] TeamsInfo GetTeamChannelsAsync, GetTeamDetailsAsync don't pass along the cancellation token

---

build/yaml/botbuilder-dotnet-ci-webex-test.yml
build/yaml/botbuilder-dotnet-functional-test-linux.yml
build/yaml/botbuilder-dotnet-functional-test-windows.yml

Fixes #minor
3 DotNet Functional Test pipelines have been intermittently failing. Probable cause: newly created Azure resources don't always have enough settling time before the test bot is deployed. That causes deployment to fail.
Reorder tasks so the new Azure  resources have more settling time before bot is deployed.

Fix intermittent DotNet Functional Test failures

---

build/yaml/botbuilder-dotnet-ci.yml

Fixes #minor
Pipeline is broken. This should fix it.

Fix typo in botbuilder-dotnet-ci.yml

---

codeql3000.yml

Fixes #minor
This file allows CodeQL analysis to run in YAML pipelines, per new security requirements. 
See: [BAP Global Static Code Analysis](https://microsoft.sharepoint.com/:p:/t/BAGFundamentals/EXgAspg49xlMgdzRwAf_qFYB77t52eymYMofUHjtWfgt6g?e=fkZVHT&isSPOFile=1&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cv-brucehaley%40microsoft.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA5MDQwMDcwNyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)

Add codeql3000.yml file.

---

ApiCompatBaseline.txt
build/yaml/botbuilder-dotnet-ci.yml
build/yaml/ci-api-validation-steps.yml
build/yaml/ci-post-to-github-steps.yml
build/yaml/ci-test-steps.yml

Fixes #minor
Task 'Verify publish compat results success' is now redundant. It compensated for a bug in the 'Publish compat results to GitHub' task which has been fixed.
Fix API validation to download all packages for both the contract and the implementation: Presence of the dependent packages for both gets more accurate validating. (For example, the assembly:TypeForwardedTo statement is then supported.)
- Remove task 'Verify publish compat results success'.
- Fix download to get all packages for API compare. (https://github.com/dotnet/arcade/issues/9725).
- Add task 'Publish compat results to Artifacts'. This makes results more accessible to forks, as they are not published to forked PRs.
- Add file ApiCompatBaseline.txt. This replaces the functionality of the var …

API compatibility validation improvements, DotNet

---

build/yaml/botbuilder-dotnet-ci-facebook-test-secondary.yml
build/yaml/botbuilder-dotnet-ci-facebook-test.yml
build/yaml/botbuilder-dotnet-ci-slack-test.yml
build/yaml/botbuilder-dotnet-ci-webex-test.yml
build/yaml/botbuilder-dotnet-functional-test-linux.yml
build/yaml/botbuilder-dotnet-functional-test-windows.yml
build/yaml/ci-build-steps.yml

Fixes #minor
Using the latest NuGet fixes "NuGet restore" error "Project ... is not compatible with net60". The error results from using an old version.

Add task 'Use NuGet latest' to pipelines

---

build/AdoWorkitemsToGithubIssues.ps1
build/CopyAdoWorkitemsToGithubIssues.ps1

Fixes #minor
CodeQL analysis creates work item bugs in ADO here: https://dev.azure.com/fuselabs/SDK_v4/_workitems/recentlyupdated/
This new pipeline, [Copy-CodeQL-Workitems-to-Github](https://dev.azure.com/FuseLabs/SDK_v4/_build?definitionId=1489&_a=summary), copies those work items to their appropriate repos in GitHub.
Work items for botbuilder-dotnet are copied here: https://github.com/microsoft/botbuilder-dotnet/issues
Work items for botbuilder-js are copied here: https://github.com/microsoft/botbuilder-js/issues
After copying, each work item is tagged and commented thus:
Sample: https://dev.azure.com/fuselabs/SDK_v4/_workitems/edit/77284/
Each new GitHub issue is assigned to tracyboehrer, labeled "bug", and shows a link back to the originating work item, thus:
Sample: …

New pipeline to copy CodeQL work items from ADO to GitHub

---

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs

Fixes #6525 
This PR adds a new invoke handler for the invoke name composeExtension/anonymousQueryLink.
This invoke will get triggered when an user pastes a link for an app that has opted in to the zero install link unfurling feature. The interface is identical to existing handler for composeExtension/queryLink, but the user sensitive information will be anonymized for anonymousQueryLink.
- Add new invoke handler for composeExtension/anonymousQueryLink
UT + manual E2E testing

Add new handler for anonymous query link invoke

---

libraries/Microsoft.Bot.Connector.Streaming/Application/StreamingConnection.cs
libraries/Microsoft.Bot.Connector.Streaming/Application/StreamingTransportClient.cs
libraries/Microsoft.Bot.Connector.Streaming/Transport/NamedPipeTransport.cs
libraries/Microsoft.Bot.Connector.Streaming/Transport/StreamingTransport.cs
libraries/Microsoft.Bot.Connector.Streaming/Transport/WebSocketTransport.cs
tests/Microsoft.Bot.Connector.Streaming.Tests/Integration/WebSocketTransportClientServerTests.cs
tests/Microsoft.Bot.Connector.Streaming.Tests/Transport/WebSocketTransportTests.cs

Fixes #6306
NamedPipe Reconnection did not fix well by the previous PR for this issue(#6306), the disconnect issue(ib/ob false) still occur.
This pr add retry in NamedPipeTransport, and will fix NamedPipe ib/ob false issue, after customer update their SDK and I publish new version of DL-ASE.
This change is backward compatibility, verified in Testing.
1.  Add a callback in  NamedPipeTransport.ConnectAsync to correctly set the IsConnect property.
Because NamedPipeTransport.ConnectAsync implemetations handle both connectAsync and processAsync, can't find out the correct time to set the IsConnected status outside.
2. Add retry logic in NamedPipeTransport.ConnectAsync, to avoid connect exception. This does happen sometimes in Azure.
5. Add random timeout in retry logic, to avoid dead lock when …

Fix NamedPipe reconnection

---

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/FacebookChatTests.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookWrapperTests.cs

Fixes #6518
This PR fixes the SM02200 CodeQL alert by replacing the deprecated HMAC algorithm with a SHA2-based HMAC instead in the [VerifySignature](https://github.com/microsoft/botbuilder-dotnet/blob/main?path=/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs#L119&amp;lineStartColumn=31&amp;lineEndColumn=95) method of the **_FacebookClientWrapper_** class.
- Replaced HMAC algorithm with SHA256 in the _VerifySignature_ method of the _FacebookClientWrapper_ class.
- Updated expected hash in _FacebookWrapperTests_.
- Replaced HMAC with SHA256 in the _CreateHubSignature_ method of the _FacebookChatTests_ class.
These images show the unit tests and the functional tests successfully executed after the changes.

[#6518] CodeQL alert SM02200: Weak hmacs in microsoft/microsoft/botbuilder-dotnet/botbuilder-dotnet

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs

Fixes #6438
This PR updates the _**HttpRequest**_ class in _Dialogs.Adaptive_ to handle binary data in the request's body. 
Also, it updates the **_Action_HttpRequest_** test to cover this scenario.
- Updated the **_BeginDialogAsync_** method in the _**HttpRequest**_ class to handle the case of binary data in the request's body using _ByteArrayContent_ to provide the HTTP content instead of _StringContent_.
- Refactored the switch case to remove duplicated code.
- Updated the **_Action_HttpRequest_** test in _Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests_ class adding a new _HttpRequest_ trigger to cover this scenario.
These images show a request with binary data sent using the HttpRequest action before and after the changes.

[#6438] It's not possible to send binary data with the HttpSend activity

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs

Fixes #6511
This PR suppresses the CodeQL SM02200 alert related to using the SHA1 encryption algorithm in **_WebexClientWrapper_** class.
The alert can't be fixed because the [Webex API](https://developer.webex.com/docs/api/guides/webhooks#handling-requests-from-webex) uses SHA1 encryption for the messages' signature.
- Added comment to suppress SM02200 alert in the _ValidateSignature_ method.
The unit tests passed after the change.

[#6511] CodeQL alert SM02200: Weak hmacs - Suppress alert for WebexClientWrapper

---

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs
libraries/Microsoft.Bot.Builder/MemoryStorage.cs
tests/Microsoft.Bot.Builder.Tests/BotStateTests.cs

Fixes #6506 #6508 #6509
This PR fixes the CodeQL SM02211 alert related to unsafe `JsonSerializer` `TypeNameHandling` usage.
- Updates the `MemoryStorage` disabling the alert.
- Added a unit test validating that the setting is required.
- Updates the `ObjectPath`, removing the global serialization setting and setting the `TypeNameHandling` to the default `None`.
- Updates the `ResourceExplorer`, removing the `TypeNameHandling` property defaulting to `None`.
The following image shows the tests for the three classes passing successfully.

Fix CodeQL SM02211 alert

---

libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs

Fixes #6512
This PR fixes the CodeQL SM00431 alert related to exposing an exception to the end user ([more information](https://codeql.github.com/codeql-query-help/csharp/cs-information-exposure-through-exception/)).
- Updates response SetBody parameter usage, changing from the whole exception to just the message.
The following image shows the before and after the applied fix, using the CodeQL query tool.

[#6512] CodeQL alert SM00431: Information exposure through an exception

---

libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs
libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs
libraries/Microsoft.Bot.Connector/Authentication/EnterpriseChannelValidation.cs
libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs
libraries/Microsoft.Bot.Connector/Authentication/ParameterizedBotFrameworkAuthentication.cs
libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs

Fixes #6513 #6507 #6505 #6504 #6503 #6502 #6501
This PR suppresses the CodeQL SM03926 alerts related to disabled **_ValidateAudience_** properties in **_TokenValidationParameters_** class.
The alerts can't be fixed because the validations take place manually in the code.
- Added comment to suppress SM03926 alerts in the following classes:
- ChannelValidation
- EmulatorValidation
- EnterpriseChannelValidation
- GovernmentChannelValidation
- ParameterizedBotFrameworkAuthentication
- SkillValidation
The unit tests passed after the changes.

Fix CodeQL alert SM03926: Security sensitive JsonWebTokenHandler validations are disabled

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs
libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs
libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs
libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs
libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs
tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/BlobsStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionedStorageTests.cs
tests/Microsoft.Bot.Builder.Tests/AllowedTypesSerializationBinderTests.cs

Fixes #6515 #6516 #6517 #6519 #6520
This PR fixes the CodeQL SM02211 alert related to unsafe `JsonSerializer` `TypeNameHandling` usage.
For these cases, it implements a custom [SerializationBinder](https://www.newtonsoft.com/json/help/html/SerializeSerializationBinder.htm), allowing only the types that are defined in the configuration or related ones.
- Adds the `AllowedTypesSerializationBinder` class to allow only types that are defined in the instance.
- Adds tests for the `AllowedTypesSerializationBinder` class.
- Updated `BlobsStorage`, `AzureBlobStorage`, and `CosmosDbPartitionedStorage` classes to implement the binder.
- Updated `BlobsTranscriptStore` setting the `TypeNameHandling` to None.
The following image shows the tests passing successfully and the error message when a type …

Fix CodeQL SM02211 alert - SerializationBinder

---

libraries/Microsoft.Bot.Connector/Authentication/ParameterizedBotFrameworkAuthentication.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs

Fixes #6510
This PR suppresses the CodeQL SM03926 alerts related to disabled _ValidateAudience_ properties in _TokenValidationParameters_ class.
The alert can't be fixed because the validations take place manually in the code.
- Added comment to suppress SM03926 alerts in the following classes:
- ParameterizedBotFrameworkAuthentication
- JwtTokenExtractorTests
Unit tests passed.

[#6510] Suppress CodeQL SM03926 alerts

---

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptOptions.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptTests.cs

Fixes #6531
This PR adds the new _RecognizeLanguage_ property in the **_PromptOptions_** class to be used in the _onRecognizedAsync_ method allowing a different language than the one determined by the activity.
It also updates the _onRecognizedAsync_ method of the **_ConfirmPrompt_** class to use this property solving the issue when a ConfirmPrompt is used along with a TranslationMiddleware.
- Updated **_PromptOptions_** class adding the **_RecognizeLanguage_** property.
- Updated the **_onRecognizedAsync_** method of the **_ConfirmPrompt_** class using the new property.
- Added a unit test in **_ConfirmPromptTests_** to cover the new test case.
These images show a bot using the translator service and the confirm prompt working as expected.

[#6531] Prompt validation of confirm prompt in chatbot is not working for newly added language

---

libraries/Microsoft.Bot.Builder/ActivityHandler.cs
libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs
tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs

This PR aims to extend the Bot SDK so that developers can consume newly added events that Teams will emit to the bot. They are:
`TeamsMessageEdit` - a user editing a message in Teams.
`TeamsMessageUndelete` - a user undo a deleted message in Teams.
`TeamsMessageSoftDelete` - a user soft deleting a message in Teams.
closes: https://github.com/microsoft/botbuilder-dotnet/issues/6565
Extended `ActivityHandler `to handle `MessageUpdate `and `MessageDelete` activity types and dispatch functions for activity types.
Extended `TeamsActivityHandler `to handle `MessageUpdate `(with subtypes `TeamsMessageEdit `and `TeamsMessageUndelete`) and `MessageDelete `(with subtype `TeamsMessageSoftDelete`) teams events.
**ActivityHandler Class**
- Added `OnMessageUpdateActivityAsync `method and …

Support Teams message edit, message soft delete, message undelete activities

---

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkHttpAdapter.cs
tests/Microsoft.Bot.Connector.Streaming.Tests/Integration/EndToEndMiniLoadTests.cs

Fixes #6543
This PR fixes the CodeQL SM00431 alert related to exposing an exception to the end user ([more information](https://codeql.github.com/codeql-query-help/csharp/cs-information-exposure-through-exception/)).
- Update response _ConnectWebSocketAsync_ usage, passing exception message.
- Update _EndToEndMiniLoadTests_ not to expose exception bodies.
CodeQL local report for exception exposure with no alerts:
Tests passed after the changes:

[CodeQL] Fix remaining SM00431 alerts

---

build/yaml/sign-steps.yml

Fixes #minor
BotBuilder-DotNet-Signed-daily pipeline is failing when signing:
"You must install or update .NET to run this application.
"App: D:\a\_tasks\EsrpCodeSigning"

Update ESRP signing task to v2

---

libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs
libraries/Microsoft.Bot.Connector/Teams/TeamsOperations.cs
libraries/Microsoft.Bot.Connector/Teams/TeamsOperationsExtensions.cs
libraries/Microsoft.Bot.Schema/Teams/OnBehalfOf.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsMeetingNotification.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsMeetingNotificationChannelData.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsMeetingNotificationInfo.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsMeetingNotificationOnBehalfOf.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsMeetingNotificationRecipientFailureInfo.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsMeetingNotificationRecipientFailureInfos.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsMeetingNotificationSurface.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs

**Description**
This feature aims to extend the dot Net Bot SDK so that developers can send targeted meeting notifications in Microsoft Teams meetings.
Add `TeamsInfo.SendMeetingNotificationAsync`
Closes  #6571
**Changes**
`Microsoft.Bot.Builder/Teams`
- add `SendMeetingNotificationAsync `method in `TeamsInfo.cs`
`Microsoft.Bot.Connector/Teams`
- Construct and send meeting notification request 
`Microsft.Bot.Schema/Teams`
- Create classes for Teams meeting notification
**Testing**
Test `SendMeetingNotificationAsync` for different status codes in `TeamsInfoTests.cs`.

Support bot sdk dot net for targeted meeting notification

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendHandoffActivity.cs

#minor
This PR fixes the casting error found in the [Telephony unit tests](https://github.com/microsoft/botframework-components/blob/main/tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/CallTransferTests.cs) when the _handoff context_ is an object.
- Updated _BeginDialogAsync_ method in _SendHandoffActivity_ class replacing the _JObject_ cast with the _JObject.FromObject_ parse method.
These images show the _Telephony_ tests working after the fix and the _Dialogs.Adaptive_ tests passing:

Fix cast issue in SendHandoffActivity action

---

libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs

Fixes #6563
This PR catches the SecurityTokenExpiredException when a JWT token is expired.
- Added catch block on the ValidateTokenAsync method of the JwtTokenExtractor class.
- Added unit test for the JwtTokenExtractor class.
- Added unit test for the CloudAdapter class.
These images show the new unit tests passing.

[#6563] Expired JWT token exception not being handled

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendHandoffActivity.cs
libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs

4.19.1 Patch

---

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/CloudAdapter.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs

Fixes #6577 
This PR adds a log in the `ProcessAsync` method of the `CloudAdapter` class to show more information about the `UnauthorizedAccessException` exceptions.
Additionally, it updates the `CloudAdapter` unit tests.
- Added log to `ProcessAsync` method in `CloudAdapter.cs`.
- Updated `ExpiredTokenShouldThrowUnauthorizedAccessException` unit test in `CloudAdapterTests.cs`.
_The following image shows the error message with the new log._
_The updated test passing._

[#6577] Can you add a log line for this exception?

---

libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs
libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs
libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs
tests/Microsoft.Bot.Builder.Tests/AllowedTypesSerializationBinderTests.cs

Fixes #6582
Fixes #6584
This PR refactors the `AllowedTypesSerializationBinder` class to allow custom types to be loaded dynamically, this includes types from BotBuilder and the project who is using it (e.g. a bot sample).
Also, the process verifies the serialized and deserialized types are allowed or valid, otherwise it will fail with the following message sample:
- Adds the `LoadTypes` method to dynamically load types from external projects (e.g. a bot sample), internal libraries (BotBuilder, with its nested related types).
- Adds `Verify` method, that validates after serializing and deserializing an object, it has all valid or allowed types, otherwise it will fail.
- Removed `CleanupTypes` method, since all types are now saved equally into the Storage, and validated when read or write. …

[#6582, #6584] Incorrect serialization of state when using Blob or CosmosDB storage in v4.19.x

---

libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs
libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs
libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs

#minor
This PR skips the `TypeNameHandling.All` restriction for Azure and Blobs Storage serializes.

Skip TypeNameHandling CodeQL issue from Azure and Blobs packages

---

libraries/AdaptiveExpressions/TimeZoneConverter.cs

Fixes #6591
This PR fixes the concurrency issue in the _TimeZoneConverter_ class by changing the Dictionaries to be thread-safe and also adding a static constructor to the class to execute the _LoadData_ method only once.
- Updated **_TimeZoneConverter_** class adding a static constructor and using _ConcurrentDictionary_.
Here we can see concurrent tests failing before the changes and the same tests passing after the changes.

[#6591] Concurrency issue with TimeZoneConverter

---

libraries/Parsers/Microsoft.Bot.Builder.Parsers.LU/Microsoft.Bot.Builder.Parsers.LU.csproj

Disabled warning CA1507 in Parsers.LU

---

libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs
libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs
libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs
libraries/Microsoft.Bot.Builder/AllowedTypesSerializationBinder.cs
tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/BlobsStorageTests.cs
tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionedStorageTests.cs
tests/Microsoft.Bot.Builder.Tests/AllowedTypesSerializationBinderTests.cs

Fixes #6590
This PR refactors the use of `AllowedTypesSerializationBinder` to be optionally provided through a `JsonSerializer` configuration across Blobs and CosmosDB storage constructors.
Behavior of `AllowedTypesSerializationBinder`:
- It will only be used in the Blobs and CosmosDB storage when provided through the `JsonSerializer.SerializationBinder`, otherwise it will not execute any related code to the class.
- When provided, it will evaluate which types need to be allowed and fail with a message to do so.
- When provided with all the types to allow, it will behave as normal, but with an extra layer of security to allow only desired types in the application.
- Removed all code that was making _Blobs_, _AzureBlobs_ (removed altogether, since it's deprecated) and _CosmosDB_ storage …

[#6590] Error while saving bot state to azure blob storage

---

libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs

Fixes #6599 
The `ResetOption` method in the `QnAMakerDialog` class attempts to cast the QnAId from the context into an int64. Microsoft Teams sends back a JObject which causes this conversion to fail. This PR modifies the casting logic to attempt a `long.TryParse` first, and defaults the QnAId to 0 if the conversion is not possible.
- Add a TryParse of the QnAId object. Take the casted variable if it succeeds, or a default value of 0 if it fails.
All QnA tests passing.

fix: Custom Question Answering in MS Teams

---

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityExtensions.cs
libraries/Microsoft.Bot.Schema/Teams/TeamsChannelData.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityExtensionsTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TeamsChannelDataTests.cs

Fixes #6596
This PR adds the _OnBehalfOf_ property to send messages via bots on behalf of another user in Teams.
It also adds unit tests to cover the new code.
- Added the **_OnBehalfOf_** property in the _TeamsChannelData_ class.
- Added the _**TeamsGetTeamOnBehalfOf**_ method to return the current activity's _OnBehalfOf_ list.
The following image shows the message of the bot on behalf of another user in the Teams channel.
The following image shows the related unit test passing.

[#6596] TeamsChannelData need OnBehalfOf

---

libraries/Microsoft.Bot.Builder/TelemetryConstants.cs
libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs
tests/Microsoft.Bot.Builder.Tests/TelemetryMiddlewareTests.cs

Fixes #6616
This PR adds _ActivityID_ and _ConversationID_ properties to telemetry when using the _Direct Line Service App_ extension.
- Added _ActivityIdProperty_ property in _TelemetryConstants_ class.
- Added _ActivityID_ and _ConversationID_ properties in the Fill methods in _TelemetryLoggerMiddleware_ class.
- Updated unit tests in _TelemetryMiddlewareTests_.
The following images show the properties logged in Application Insights and the unit tests passing.

[#6616] Telemetry not logging ActivityID and ConversationID

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperties.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperty.cs

#minor
This PR updates the **_SetProperty_** and **_SetProperties_** actions to save the state after setting the properties to avoid user scope properties losing their value.
Related Composer issue [#9533](https://github.com/microsoft/BotFramework-Composer/issues/9533)
- Added a call to [DialogStateManager's SaveAllChanges](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs#L426) method after setting the property value in **_SetProperty_** and **_SetProperties_** adaptive actions.
These images show the User scope variable keeping its value after performing a token exchange operation.

USER scope variable values do not transfer to skill when SSO is configured

---

libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs
libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorageOptions.cs
libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionedStorageTests.cs

Fixes #6560
This PR adds the _CosmosDB_ authentication method through _TokenCredential_ in _CosmosDbPartitionedStorage_.
- Upgraded _Microsoft.Azure.Cosmos_ package from 3.15.1 to 3.32.2 to get the _CosmosClient_ constructor that uses _TokenCredential_.
- Added _TokenCredential_ property to _CosmosDbPartitionedStorageOptions_ class.
- Updated validation to throw if _AuthKey_ and _TokenCredential_ properties are null.
- Added the alternative to create a _CosmosClient_ using the _TokenCredential_ if provided.
The following image shows the information saved in CosmosDB after creating the client using Azure credentials.

[#6560] Allow TokenCredential authentication in CosmosDbPartitionedStorage

---

libraries/Microsoft.Bot.Schema/Converters/SurfaceConverter.cs
libraries/Microsoft.Bot.Schema/Teams/MeetingTabIconSurface.cs
libraries/Microsoft.Bot.Schema/Teams/SurfaceType.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs

Fixes #6622
Support MeetingTabIconSurface in Meeting Notification API
- Support MeetingTabIconSurface 
- Update surface converter with MeetingTabIconSurface
- Update unit test
Updated unit test TestSendMeetingNotificationAsync with an additional surface that surface type is MeetingTabIcon

Support MeetingTabIconSurface in Meeting Notification API

---

libraries/Microsoft.Bot.Schema/ActivityEx.cs
tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs

Fixes #5820
This PR updates the Activity's **_ApplyConversationReference_** method to prioritize the activity's _locale_ over the reference _locale_.
- Updated **_ApplyConversationReference_** method in _ActivityEx_ class to use the activity's _locale_ first. If it's null, use the reference's _locale_.
- Updated unit tests to assert the right _locale_ values.
These images show the overridden _locale_ property (before) and how it's kept after the changes.
**BEFORE**:
**AFTER**:

[#5820] Outgoing Activity Locale being Overwritten

---

libraries/Microsoft.Bot.Streaming/Payloads/RequestManager.cs
libraries/Microsoft.Bot.Streaming/Transport/WebSocket/WebSocketClient.cs
tests/Microsoft.Bot.Streaming.Tests/Payloads/RequestManagerTests.cs
tests/Microsoft.Bot.Streaming.Tests/Utilities/FauxSock.cs
tests/Microsoft.Bot.Streaming.Tests/WebSocketClientServerTests.cs
tests/Microsoft.Bot.Streaming.Tests/WebSocketTransportTests.cs

Fixes #6624
This PR ports the changes from [PR#4461](https://github.com/microsoft/botbuilder-js/pull/4461) to reject all pending requests when the websocket is disconnected. 
- Added new `RejectAllResponses` method in **_RequestManager_** class.
- Added call to `RejectAllResponses` in _OnConnectionDisconnected_ of **_WebSocketClient_**.
- Added a unit test to cover the new method in **_RequestManagerTests_**.
- Refactored **_WebSocketTransportTests_** to follow the implementation in JS:
- Move _WebSocketClient_ and _WebSocketServer_ tests to the new class **_WebSocketClientServerTests_**. 
- Move the **_FauxSock_** class to the `Utilities` folder for reuse by the test classes.
These images show the pending requests being rejected after the fix and the new unit tests passing.

[#6624] port: [#4452][#4456][#4460][botframework-streaming] Should reject pending requests on disconnection

---

libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/ConstantHttpClientFactory.cs
libraries/Microsoft.Bot.Connector/Authentication/IJwtTokenProviderFactory.cs
libraries/Microsoft.Bot.Connector/Authentication/JwtTokenProviderFactory.cs
libraries/Microsoft.Bot.Connector/Authentication/ManagedIdentityAppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/ManagedIdentityAuthenticator.cs
libraries/Microsoft.Bot.Connector/Authentication/ManagedIdentityServiceClientCredentialsFactory.cs
libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/MsalAppCredentials.cs
libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ConfigurationServiceClientCredentialFactory.cs
tests/Microsoft.Bot.Builder.Tests/MockAppCredentials.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/AppCredentialsTests.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/ManagedIdentityAppCredentialsTests.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/ManagedIdentityAuthenticatorTests.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/ManagedIdentityServiceClientCredentialsFactoryTests.cs
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Mocks/MockAppCredentials.cs

Fixes #6589
This PR migrates ADAL related functionality to MSAL internally.
> **Note:** The public `JwtTokenProviderFactory` class has been deprecated since its all related to ADAL functionality, said class is only being used for MSI classes, these classes will no longer use the deprecated provider and instead use the MSAL functionality.
- `AppCredentials.BuildAuthenticator` has been deprecated and the `BuildIAuthenticator` method should be used instead.
- Added `BuildIAuthenticator` method to the `CertificateAppCredentials` class, providing the MSAL authenticator instance, also the internal class variables have been changed to minimize the ADAL implementation without generating breaking changes.
- Deprecated `JwtTokenProviderFactory` since it's no longer used in MSI related classes …

[#6589] Default to MSAL and eliminate ADAL without breaking changes

---

libraries/Microsoft.Bot.Builder.AI.QnA/Utils/LanguageServiceUtils.cs
tests/Microsoft.Bot.Builder.AI.QnA.Tests/LanguageServiceTests.cs

Fixes https://github.com/microsoft/botframework-sdk/issues/6588
This PR fixes an issue where the `userId` property was empty when displaying the AzureDiagnostics table in the Log Analytics workspace resource.
- Added `userId` property to the `query-knowledgebases` request in the `LanguageServiceUtils` file.
- Added unit test in the `LanguageServiceTests` file to validate when the `userId` property is empty.
- Updated failing tests in the `LanguageServiceTests` file.
The following images show the unit tests passing and the AzureDiagnostics logs from the Language service resource.

[#6588] UserId not being passed to AzureDiagnostics

---

libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs
libraries/Microsoft.Bot.Builder.AI.QnA/Utils/QnACardBuilder.cs
tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs

Fixes Internal IcM Issue #373550043
Port of changes from https://github.com/microsoft/botbuilder-js/pull/4467
Fixes #6630 
This PR allows for choosing Adaptive Cards formatted for use in Microsoft Teams instead of the default Hero Cards. This is done to support markdown formatting in QnA and CQA responses since Teams only supports markdown in Adaptive Cards. Changes are made in `QnACardBuilder.cs` and `QnAMakerDialog.cs`.
Using the new cards simple requires adding code in the bot to take in a new environment variable: UseTeamsAdaptiveCard = "true" and pass it to the QnA dialog constructor. If no changes are made, the bot will default to a Hero card.
- Create new methods to generate adaptive and hero cards
- Modify the card builder class to take in a new bool field to allow for choosing …

Add support for Teams Adaptive cards in QnA Dialog

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs
libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs
libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
libraries/Microsoft.Bot.Builder/MessageFactory.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoiceFactoryTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicesChannelTests.cs
tests/Microsoft.Bot.Builder.Tests/MessageFactoryTests.cs

Fixes #6086
This PR enables Suggested Actions for _MSTeams_ in Dialogs Prompts and Adaptive Dialogs Inputs.
- Updated **_ChoiceInput_** , **_ConfirmInput_** , **_ChoicePrompt_**, and **_ConfirmPrompt_** classes to pass to the  _AppendChoices_ method the _conversationType_ and the list of recipient's ids, necessary to send suggested actions in the _MSTeams_ channel.
- Updated _AppendChoices_ method in **_InputDialog_** and **_Prompt_** overloading it to receive the new parameters _conversationType_ and _toList_ and pass them to the _ForChannel_ method.
- Updated _SupportsSuggestedActions_ method in **_Channel_** class to include the MSTeams channel in the switch case.
- Overloaded the _ForChannel_ method in **_ChoiceFactory_** and the _SuggestedActions_ method of the **_MessageFactory_** …

[#6086] Teams is adding support for suggested actions in 1-1 chats

---

libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs
tests/Microsoft.Bot.Builder.Azure.Tests/BlobsStorageTests.cs

Fixes #6346
This PR enables MSI authentication for Azure Blob Storage.
- Added a new constructor with the necessary parameters for creating the blob storage client using a _tokenCredential_.
The following image shows a bot saving data in the blob storage after using the _tokenCredential_ to authenticate.
The following image shows the new unit test passing.

[#6346] Add Azure Storage (BlobStorage.cs) using a managed identity

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs

#minor
This PR allows sending GET requests by adding a body to the request's content.
Composer related issue: [#9158](https://github.com/microsoft/BotFramework-Composer/issues/9158).
- Modified the switch clause to move the GET request case, to allow the body to be added to the request content.
The following image shows the GET request sent with a body in the content.

Allow sending GET requests with a body

---

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs
libraries/Microsoft.Bot.Schema/Teams/BotConfigAuth.cs
libraries/Microsoft.Bot.Schema/Teams/ConfigAuthResponse.cs
libraries/Microsoft.Bot.Schema/Teams/ConfigResponse.cs
libraries/Microsoft.Bot.Schema/Teams/ConfigResponseBase.cs
libraries/Microsoft.Bot.Schema/Teams/ConfigTaskResponse.cs
libraries/Microsoft.Bot.Schema/Teams/InvokeResponseBase.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerNotImplementedTests.cs
tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/BotConfigAuthTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/ConfigAuthResponseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/ConfigResponseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/ConfigTaskResponseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TaskModuleContinueResponseTests.cs
tests/Microsoft.Bot.Schema.Tests/Teams/TaskModuleMessageResponseTests.cs

Fixes #6634
Support new bot invoke type: config.
- Support new config invoke requests, including config/submit and config/fetch.
- Support related bot schema for Bot config responses.
E2E manual tests against local changes for various config requests and responses.
Unit Tests.

Support Bot new invoke type: config

---

libraries/Microsoft.Bot.Connector.Streaming/Application/StreamingTransportClient.cs
libraries/Microsoft.Bot.Connector.Streaming/Session/StreamingSession.cs
libraries/Microsoft.Bot.Connector.Streaming/Transport/TransportHandler.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/CloudAdapter.cs

Fixes #6649
- Fixes the high performance logging in the **StreamingTransportClient** from using the wrong `EventId.Name`
- Specifically `_clientCompleted` and `_clientKeepAliveSucceed`
- Adds `NamedPipeConnectionStarted` and `NamedPipeConnectionCompleted` for use in **CloudAdapter.ConnectNamedPipeAsync()** instead of using the incorrect `WebSocketConnectionStarted` and `WebSocketConnectionCompleted`.
- Minor cleanup in logs for **StreamingSession** and **TransportHandler**

fix: cleanup streaming high-perf logs

---

build/yaml/ci-test-steps.yml

Explicitly adding 3.1 to test steps.

---

libraries/AdaptiveExpressions/parser/ExpressionParser.cs

Fixes #6656
This PR addresses a memory leak issue in the `ExpressionParser` class. Previously, the `ExpressionParser` class used a `ConcurrentDictionary` to cache parsed expressions, which could lead to excessive memory usage over time. This PR changes the `ExpressionParser` class to use an `LRUCache` instead, which has a maximum capacity and uses a least-recently-used policy to evict entries from the cache when the maximum capacity is reached. This change should help to mitigate the memory leak issue.
- Changed the `ExpressionParser` class to use an `LRUCache` instead of a `ConcurrentDictionary` for caching parsed expressions.
This change was tested using a console application that demonstrates the memory leak issue in `ExpressionParser`: …

Use LRUCache in ExpressionParser for efficient memory usage

---

libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/MsalAppCredentials.cs

#minor
This PR fixes an issue in MSAL where the `Authority` for Government, Office 365 GCC High and DoD was not set in the MSAL credentials' application level.
- Added `WithAuthority` to Certificate, Microsoft and Msal app credentials when creating the client application builder.
The following images show the tests passing successfully and the Echo bot working in Public Cloud.

Add WithAuthority to MSAL client application builder

---

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/CloudAdapter.cs

Fixes #6642
This PR validates the request's content before using it to create the body of streaming requests.
- Added validation of content before reading the data to create the request's body in _CreateSteamingRequestAsync_.
The following image shows the handle of the null content.

[#6642] Handle null content

---

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
libraries/Microsoft.Bot.Builder/Integration/IAdapterIntegration.cs
libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandler.cs
libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandlerBase.cs

Fixes #6644
This PR removes the _**Obsolete**_ tags from the _BotFrameworkAdapter_ class and its related classes.
Removed tags and added the suggestion of the use of _CloudAdapter_ in the following classes:
- BotMessageHandler 
- BotFrameworkHttpAdapter
- BotMessageHandlerBase
- IAdapterIntegration
- BotFrameworkHttpAdapterBase
- BotFrameworkAdapter

[#6644] Remove BotFrameworkAdapter Obsolete annotation

---

tests/Microsoft.Bot.Builder.TestBot.WebApi/packages.config

#minor
It doesn't appear this is even used, but is triggering alerts.

Updated stray Microsoft.Rest.ClientRuntime dependency

---

libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentials.cs

Fixes #6673
After upgrade from ADAL to MSAL auth library, sendX5C flag was not set and it breaks SN+I authentication with AAD app registrations.
Added sendX5C flag to ConfidentialClientApplicationBuilder.WithCertificate() method.
Tested locally and also on our repo by implementing this fix on an inherited class.

#6673 - Fix of SNI auth not working in Cert based authentication

---

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs

#minor
Closes IcM: https://portal.microsofticm.com/imp/v3/incidents/details/403753372/home
This PR addresses concurrency issues observed in the `InterfaceConverter`'s `ReadJson` method. The changes ensure thread-safe operations when deserializing JSON concurrently.
- Replaced `Dictionary<string, T>` type declarations with `ConcurrentDictionary<string, T>` for rangeReferences, cachedRefDialogs and cachedTypes.

Resolve concurrency issues in InterfaceConverter's ReadJson method

---

libraries/Microsoft.Bot.Connector.Streaming/Session/StreamingSession.cs
libraries/Microsoft.Bot.Streaming/ProtocolAdapter.cs

Fixes #6683
This PR fixes an issue where, while using _DLASE_, the bot threw a timeout issue while streaming, due to not generating a response in the initial request.
Therefore, if the streaming process in the initial request takes longer than 15 seconds to finalize and generate a response, the bot will throw a timeout issue.
Sending a response (`HTTP 202 (Accepted)`) before starting to process all streaming requests addressed the issue and will not generate a timeout issue.
- Add `SendResponseAsync` call to the `StreamingSession` class to send an HTTP 202 (Accepted) response before starting processing all streaming information.
- Add `Accepted` StatusCode condition to `ProtocolAdapter` for Streaming and `StreamingSession` for Connector.Streaming. This allows to detect when the Accepted …

fix: [#6683] Timeout issue when using DLASE

---

libraries/Microsoft.Bot.Schema/SharePoint/BaseHandleActionResponse.cs
libraries/Microsoft.Bot.Schema/SharePoint/CardViewHandleActionResponse.cs
libraries/Microsoft.Bot.Schema/SharePoint/NoOpHandleActionResponse.cs
libraries/Microsoft.Bot.Schema/SharePoint/QuickViewHandleActionResponse.cs

Fixes #6613 
The PR fixes serialization of `responseType` property for the `HandleActionResponse`.
Newtonsoft does not serialize inherited property without a setter. So the property has been changed to private readonly field with initialization from child classes using constructor's parameter.
Full flow test using locally served bot and SharePoint Online

[SharePointActivityHandler]: fix responseType serialization

---

tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs

#minor
Related https://github.com/microsoft/botbuilder-js/pull/4560
This PR disables the `ExpiredTokenShouldThrowUnauthorizedAccessException` test due to invalid SigningKey value in the token. This will be skipped for now until a fix is provided, so it doesn't block new PR merges.

fix: Disable failing expired token test in CloudAdapter

---

libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs
tests/Microsoft.Bot.Builder.AI.QnA.Tests/LanguageServiceTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogExtensionsTests.cs

#minor
This PR adds error detection when the internal `RunAsync` method fails using `AdaptiveDialogs`, otherwise, the original `Exception` gets lost.
> e.g.: original exception containing circular reference errors, it's captured by the `dialogContext.EmitEventAsync` to send the error as a message, then, it proceeds to fail, and the error thrown in the stack is the circular reference error, and the original exception gets lost.
- Added `try/catch` around the `EmitEventAsync` when used in the `InternalRunAsync` method. If there is an error, it will be captured and thrown as an `AggregateException` containing the original and new error.
- Added unit test to validate this behavior.
- Updated unit test failing with similar behavior.
The following image shows the pipeline working and how the …

Add error detection when EmitEventAsync fails in internal RunAsync

---

libraries/Microsoft.Bot.Connector/Authentication/MsalAppCredentials.cs

#minor
This PR adds the necessary MSAL settings to manage the cached access token value and not request a new value on each request.
- Added _**SetCacheOptions**_ to the _AppTokenCache_ of the _ClientApplication_ in _MsalAppCredentials_ class.
The following images show the interaction with the bot and the token values in every message.

Enable MSAL settings to save access token in cache

---

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorBotComponent.cs
libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs

Add obsolete warning to Orchestrator classes

---

tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj

System.IdentityModel.Tokens.Jwt bump

---

libraries/Microsoft.Bot.Schema/SharePoint/AceData.cs

Fixes #6729
The PR adds `IsVisible` property to the AceData class to implement the #6729  feature request.
```csharp
public class AceData
{
// ...
/// <summary>
/// Gets or sets the visibility of the Adaptive Card Extension.
/// </summary>
/// <value>The value is the flag that indicates if the Adaptive Card Extension is visible. Default to true.</value>
[JsonProperty(PropertyName = "isVisible")]
public bool? IsVisible { get; set; }
// ...
}
```

feat: Add IsVisible property to AceData

---

libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs

#minor
This PR ports from Javascript the header **_blobContentType_** in the BlobStorage writing, setting the value as _application/json_ to the uploaded blobs.
- Added **_blobContentType_** as _application/json_ to the httpHeaders of the blobs to upload.
The following image shows the reading of the **_blobContentType_** value as application/json.

port: [#4587] Add blob content type header

---

libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs

Fixes #6697
This PR allows showing the typing indicator before every message bot.
- Added _**ProcessTypingAsync**_ method in _ShowTypingMiddleware_ class.
- Added _StartTyping_ process to every activity iteration in the _OnSendActivities_ method execution.
The following image shows the typing indicator being displayed between the different messages sent by the bot.

fix: [#6697] Typing middleware not working as expected in teams as well as web chat channel

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguagePolicy.cs

#minor
From IcM where the older zh-CN locale was specified in WebChat, and CultureInfo.GetCultures only has the newer (and standard) zh-hans-* and zh-hants-*.

Manually adding zh-CN and zh-TW to LanguagePolicy

---

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj

Updated NuGet.Packaging

---

libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj

Microsoft.IdentityModel.Protocols.OpenIdConnect bump

---

libraries/Microsoft.Bot.Builder/ActivityFactory.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs
tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/NormalStructuredLG.lg

#minor
**Related _BF-Composer Issue:_** https://github.com/microsoft/BotFramework-Composer/issues/9692
This PR adds a validation to avoid sending object values as the activity's _text_ and _speak_. 
With this change, we are matching JS implementation.
- Added a validation for the text and speak properties in the **_BuildActivity_** method of the _ActivityFactory_ class.
- Added a unit test to cover this case in **_ActivityFactoryTests_**.
- Added a new _messageActivity_ template to use in the new test. 
These images show how the property was displayed before and after the fix.

Fix error when building activity with non-string text

---

libraries/Microsoft.Bot.Builder/SharePoint/SharePointActivityHandler.cs
libraries/Microsoft.Bot.Builder/SharePoint/SharePointSSOTokenExchangeMiddleware.cs
libraries/Microsoft.Bot.Connector/Channels.cs
libraries/Microsoft.Bot.Schema/SharePoint/QuickViewResponse.cs
libraries/Microsoft.Bot.Schema/SignInConstants.cs

Fixes
This change allows SharePoint Bot Driven Aces to use SSO.
Currently a bot driven ace in SharePoint can only use the magic code flow.  This flow is not ideal as it requires a user to copy and paste a code from a different window or at a minimum we get flicker of the window being shown.  This change allows us to use the SSO flow so that not authentication prompts are shown.
#minor
Adds a new cardExtension/token activity for doing a token exchange.
- 
-
-
Used a debug string in SharePoint and copied the bot builder bits locally to produce a bot running on ngrok.

Support Sso for SharePoint bot ACEs

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperties.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperty.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs

Fixes #6746
This PR moves the _SaveAllChanges_ functionality from the _SetProperty_ and _SetProperties_ classes to the _OAuthInput_ class.
Additionally, addressing the old issue (https://github.com/microsoft/BotFramework-Composer/issues/9533), that introduced this change.
- Removed _SetProperty_ and _SetProperties_ _SaveAllChanges_ functionality, as it was causing message duplication in the Slack adapter.
- Added the _SaveAllChanges_ functionality to the _OAuthInput_ class, before sending the _OAuthCard_ from the Skill to the Root to exchange the SSO token, and not loose state.
The following image shows an SSO bot working, retrieving the user's state after exchanging the token, correctly.

fix: [#6746] Move SaveAllChanges method from SetProperty to OAuthInput

---

libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConstants.cs
libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs

#minor
This PR includes a dynamic way to validate the access token _**issuer**_ value depending on the tenant ID used in Emulator.
- Added logic to validate the _**tid**_ and _**issuer**_ values to allow the Single Tenant authentication in EmulatorValidation.
The following image shows the Emulator working with a bot using Single Tenant authentication.

feat: Support Single Tenant authentication through BotFramework-Emulator

---

libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs

#minor
Fixes # 6752
This PR fixes the Dispose error avoiding the dispose of faulted tasks.
- Added _**if**_ condition to dispose tasks that are not faulted.
The following image shows the bot responding correctly to other requests after an error has occurred.

fix: [#6752] The ShowTypingMiddleware throws System.ObjectDisposedException when an exception occurs in the bot

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReply.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyOneOf.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserActivity.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserTyping.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestScript.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/ActivityTemplate.cs
libraries/Microsoft.Bot.Builder.Testing/XUnit/XUnitDialogTestLogger.cs
libraries/Microsoft.Bot.Builder/FileTranscriptLogger.cs
libraries/Microsoft.Bot.Builder/TokenResolver.cs
libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs
libraries/Microsoft.Bot.Connector/Authentication/ManagedIdentityAuthenticator.cs
libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
tests/Microsoft.Bot.Connector.Tests/Authentication/ManagedIdentityAuthenticatorTests.cs

Microsoft.Identity.Client bump

---

libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs

New LGTM suppression syntax - BlobsStorage

---

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs

#minor
Makes it easier to see auth errors due to misconfiguration.

Logging UnauthorizedAccessException in BotFrameworkHttpAdapter

---

build/yaml/botbuilder-dotnet-functional-test-linux.yml
build/yaml/functional-test-setup-steps.yml

Addresses #6741
#minor
This PR updates the Functional Test yamls to target .NET 8 instead of .NET 6.
> Note: The adapters' functional test pipelines didn't require updating, but we tested them with the bots targeting .NET 8.
- Updated  `functional-test-setup-steps.yml` to target the net8.0 framework.
- Updated `botbuilder-dotnet-functional-test-linux.yml` to add  the self-contained flag to the publish command, as starting .NET 8 this is no longer the default behavior ([documentation](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/runtimespecific-app-default)).
These images show the Functional Test pipelines working after the changes.

[#6741] Update functional test pipelines to .NET8

---

generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/template.json
generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/README.md
generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/.template.config/template.json
generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/README.md
generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.template.config/template.json
generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/README.md
generators/dotnet-templates/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.vstemplate
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.Tests.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.vstemplate
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBotWithTests.vstemplate
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.vstemplate
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/README.md
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.vstemplate
generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/README.md

Fixes #6741
This PR updates all generators from `net6` to `net8`.
- `Templates` 
- Updates all related files where the `net6` configuration appear, changing it to `net8`.
- Default template installation to `net8`, but leave `net6` and `net8` as supported options. Since we maintained both in the SDK.
- `VSIX`
- Updates all related files to target `net8`.
- Fixed an issue when generating the `CoreBotWithTests` sample failed because it was referencing nonexistent files.
The following images show all three bots working and the update reference in the VSIX samples.

[#6741] Update generators templates and VSIX to .Net 8

---

libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/CertificateServiceClientCredentialsFactory.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/CertificateServiceClientCredentialsFactoryTests.cs

#minor
This PR adds Audience to CertificateAppCredentials, so it is passed correctly when calling a Skill bot. Additionally, these changes take into consideration the PR https://github.com/microsoft/botbuilder-dotnet/pull/6694, so the improvement isn't lost in the process.
- Added missing `oAuthScope` parameter to `libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentials.cs`.
- Improved `libraries/Microsoft.Bot.Connector/Authentication/CertificateServiceClientCredentialsFactory.cs` by reverting the changes made in the PR https://github.com/microsoft/botbuilder-dotnet/pull/6694, but maintaining the improvement.
- It creates a new instance of `CertificateAppCredentials` per Audience, instead of having just one with the default `api.botframework`.
- Added unit test to …

fix: Add Audience for Certificate auth to work with Skills

---

libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/CertificateGovernmentAppCredentials.cs
libraries/Microsoft.Bot.Connector/Authentication/CertificateServiceClientCredentialsFactory.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/CertificateServiceClientCredentialsFactoryTests.cs

Fixes #6805 
This change also handles certificate auth against private clouds as the PasswordServiceClientCredentialFactory does.

CertificateServiceClientCredentialsFactory handles public, Gov, and private clouds

---

libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs
tests/Microsoft.Bot.Builder.Azure.Tests/BlobsTranscriptStoreTests.cs

Fixes #6798
This PR allows the use of Token Credentials to authenticate and create an instance of _BlobsTranscriptStore_.
- Added constructors in _BlobsTranscriptStore_ with _**blobServiceUri**_ and _**tokenCredentials**_ as parameters. 
- Added constructor validations in unit tests.
The following images show the bot working and saving transcripts using _BlobsTranscriptStore_ instantiated with token credentials.

fix: [#6798] Not able to create instance of BlobsTranscriptStore using TokenCredential instead of connectionString and containerName

---

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexHelper.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.TestBot/Bots/EchoBot.cs
tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexAdapterTests.cs

#minor
This PR updates the `Thrzn41.WebexTeams` package from `1.6.2` to `1.8.1`, and fixes the error `[CS0104](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0104): 'Attachment' is an ambiguous reference between 'Microsoft.Bot.Schema.Attachment' and 'Thrzn41.WebexTeams.Version1.Attachment'`.
- Updated `Thrzn41.WebexTeams` package from `1.6.2` to `1.8.1`.
- Updated `Attachment` references to be `Schema.Attachment` due to ambiguous reference between BotBuilder and WebexTeams packages.
The following image shows the unit tests and CI pipeline passing successfully.

[#6825] Update and fix WebexTeams issues

---

generators/vsix-vs-win/BotBuilderVSIX-V4/BotBuilderTemplatesVSIX.csproj
generators/vsix-vs-win/BotBuilderVSIX-V4/packages.config
libraries/Directory.Build.props
libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestScript.cs
libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
libraries/Microsoft.Bot.Builder/TurnContext.cs

#minor
This PR updates the `Microsoft.VisualStudio.Threading.Analyzers` from `15.8.122` to `17.10.48`, and fixes the [VSTHRD200](https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD200.md) issue with internal methods.
- Updated `Microsoft.VisualStudio.Threading.Analyzers` to latest version in BotBuilder and VSIX projects.
- Updated some internal methods that required the `Async` suffix due to the `VSTHRD200` error alert.
The following image shows the CI pipeline working, and an echo bot generated with VSIX templates.

[#6825] Update Threading.Analyzers

---

libraries/Directory.Build.props
libraries/Microsoft.Bot.Builder/TokenResolver.cs

#minor
This PR replaces deprecated `Microsoft.CodeAnalysis.FxCopAnalyzers` with `Microsoft.CodeAnalysis.NetAnalyzers` as suggested in [this guide](https://learn.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2022).
- Replaced  `Microsoft.CodeAnalysis.FxCopAnalyzers` with `Microsoft.CodeAnalysis.NetAnalyzers` latest version.
- Updated `TokenResolver` logs due to [CA2017](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2017) issue.
The following image shows the CI pipeline working.

[#6825] Replace deprecated FxCopAnalyzers with NetAnalyzers

---

libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi.csproj

#minor
This PR adds the `Microsoft.Bcl.AsyncInterfaces` package to `Microsoft.Bot.Builder.Azure` project, forcing 1.x version to 8.x, solving the [MSB3277](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb3277?view=vs-2022&f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(MSBuild.ResolveAssemblyReference.FoundConflicts)%26rd%3Dtrue) warnings.
- Added `Microsoft.Bcl.AsyncInterfaces` to `Microsoft.Bot.Builder.Azure` project, forcing to use 8.x version instead of 1.x that caused the conflict.
- Updated `System.Diagnostics.DiagnosticSource` in `Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi` project, solving [MSB3245](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb3245?view=vs-2022) warning.
The following images show the CI …

[#6825] Fix Microsoft.Bcl.AsyncInterfaces warnings

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj
libraries/Microsoft.Bot.Builder.Testing/Microsoft.Bot.Builder.Testing.csproj
tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/Microsoft.Bot.Builder.Adapters.Facebook.Tests.csproj
tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft.Bot.Builder.Adapters.Slack.Tests.csproj
tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/Microsoft.Bot.Builder.Adapters.Twilio.Tests.csproj
tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Microsoft.Bot.Builder.Adapters.Webex.Tests.csproj
tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Microsoft.Bot.Builder.AI.Luis.Tests.csproj
tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests.csproj
tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/Microsoft.Bot.Builder.AI.LuisV3.Tests.csproj
tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/Microsoft.Bot.Builder.ApplicationInsights.Tests.csproj
tests/Microsoft.Bot.Builder.Dialogs.Tests/Microsoft.Bot.Builder.Dialogs.Tests.csproj
tests/Microsoft.Bot.Builder.Dialogs.Tests/TextPromptTests.cs
tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj
tests/Microsoft.Bot.Connector.Streaming.Tests/Microsoft.Bot.Connector.Streaming.Tests.csproj
tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj
tests/Microsoft.Bot.Streaming.Tests/Microsoft.Bot.Streaming.Tests.csproj
tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj
tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests.csproj

#minor
This PR updates the **_moq_** version in the unit test projects and fixes the compatibility issues that appeared after the update.
- Updated _**moq**_ from 4.13.1 to 4.20.7
- Fixed use of _IsNullOrEmpty_ method in _TextPromptWithNaughtyStrings_ unit test.
The following image shows the unit test running successfully.

fix: [#6825] Update moq

---

libraries/Microsoft.Bot.Builder.Azure.Queues/AzureQueueStorage.cs

#minor
This PR adds a comment to clarify the _**TypeNameHandling**_ alert thrown in _AzureQueueStorage_.
- Added CodeQL comment to _JsonSerializerSettings_ instantiation in _AzureQueueStorage_ constructors.
This PR doesn't require a testing proof.

fix: Avoid SM02211 issue alert

---

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/Microsoft.Bot.Builder.FunctionalTests.csproj
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj
libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioHelper.cs

#minor
This PR updates the `Twilio` package from `5.37.2` to `7.2.2`, and fixes the [NU1701](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701) issue.
- Updated `Twilio` in TwilioAdapter and FunctionalTests projects.
- Updated TwilioAdapter from netstandard2.0 to netstandard2.1.
- Fixed StringComparison issue in TwilioAdapter.
The following images show the CI and Functional Tests pipelines.

[#6825] Update Twilio package

---

libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs

Fix for Skills endorsement check

---

libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs

Fixes #6841
This PR updates the **_InterceptOAuthCardsAsync_** method in _SkillDialog_ to support _CloudAdapter_ in combination with _expect replies_ delivery mode.
- In _InterceptOAuthCardsAsync_ added a call to _UserTokenAccess.ExchangeTokenAsync_ method, which handles both adapters.
This image shows the token exchanged for SSO using _CloudAdapter_ and _expect replies_.

[#6841] SkillDialog.InterceptOAuthCardsAsync doesn't support CloudAdapter

---

libraries/Microsoft.Bot.Schema/Attachment.cs
libraries/Microsoft.Bot.Schema/Converters/AttachmentMemoryStreamConverter.cs
tests/Microsoft.Bot.Schema.Tests/AttachmentTests.cs

Fixes #6771
This PR fixes an issue with DLASE when a MemoryStream instance is being used as an Activity.Attachment, e.g. a file. The ReadTimeout issue is caused when trying to serialize the non-serializable MemoryStream instance.
- Adds the `AttachmentMemoryStreamConverter` to serialize and deserialize a MemoryStream instance.
- Serialize (WriteJson): It recursively searches and replaces all instances of MemoryStream to a serializable class, containing a type and a buffer array. 
- Deserialize (ReadJson): It recursivelly searches and converts all objects of type MemoryStream to a MemoryStream instance with the buffer array.
- Adds unit tests to cover cases previous to the JsonConverter addition, and using the JsonConverter.
The following images show the bot working, and the unit tests …

[#6771] Fix Attachment issue when it has a MemoryStream instance

---

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs
libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ServiceCollectionExtensions.cs

#minor
This PR disables the adaptive sampling used in the telemetry client to avoid skipping logs due to big amount of concurrent users and events.
- Set to false property **_EnableAdaptiveSampling_** of telemetry settings in _ServiceCollectionExtensions_ classes.
The following image shows the logs saved correctly in the Application Insights resource.

fix: Disable telemetry adaptive sampling

---

libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs
tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDBKeyEscapeTests.cs

Fixes #6768
This PR implements a custom _GetHashCode_ method to return the same hash code even on different bots' runs. This code is used in _CosmosDBKeyEscape_ to truncate keys that are longer than 255 characters.
- Created the `GetDeterministicHashCode` method in the _CosmosDBKeyEscape_ class to replace the call to _String.GetHashCode_.
- Updated `Long_Key_Should_Be_Truncated` unit test to use the new method and verify its result.
These images compare the hash codes returned by the GetHashCode and GetDeterministicHashCode methods in two different bot runs.

[#6768] CosmosDBKeyEscape.TruncateKeyIfNeeded return different value after compiled

---

libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs
tests/Microsoft.Bot.Connector.Tests/Authentication/EmulatorValidationTests.cs

#Fixes #6877
This PR adds support for every possible token issuer version in Emulator authentication.
- Added 3 new valid token issuers in token emulator validation.
- Added unit tests to check IsTokenFromEmulator performance.
The following image shows the new unit tests working.

fix:[#6877] Bot is not accepting v2 tokens from Bot Framework Emulator - Single Tenant Bots

---

libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs

Fixes #6861
This PR adds the 412 error capture of the _BlobsStorage_ to be handled by _TeamsSSOTokenExchangeMiddleware_.
- Added **_catch_** to capture 412 in _WriteAsync_ method of _BlobsStorage_.
The following image shows the error being captured.

fix: [#6861]TeamsSSOTokenExchangeMiddleware.DeduplicatedTokenExchangeIdAsync fails on BlobStorage ETag validation

---

.github/workflows/create-botbuilder-parity-issues.yml

#minor
This PR fixes the create parity issue github action by matching the PR labels correctly.
- Changed `parity` to title case `Parity`.
The following image shows the "Bad credentials" error from our fork repository, meaning that is thrown after the condition is correctly met.

Fix create parity issue github action

---

libraries/Microsoft.Bot.Builder.AI.QnA/CustomQuestionAnswering.cs
libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs
libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj
libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerEndpoint.cs
libraries/Microsoft.Bot.Builder.AI.QnA/Utils/HttpRequestUtils.cs
tests/Microsoft.Bot.Builder.AI.QnA.Tests/LanguageServiceTests.cs
tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs

Fixes #6889
This PR adds the ability to use a Managed Identity ClientId to authenticate to the Language service.
- Added the _Azure.Identity_ package as dependency in `Microsoft.Bot.Builder.AI.QnA`.
- Added the **_ManagedIdentityClientId_** property to the `QnAMakerEndpoint` class.
- Added an internal constructor in `QnAMakerDialog` to handle the Managed Identity Client Id.
- Added _WithEndpointKey_ and _WithManagedIdentityClientId_ methods to the `QnAMakerDialog` class to configure which authentication the request will use.
- Added the ability to detect and get the MSI token in the `HttpRequestUtils` class.
The following images show the [48.customQABot-all-features](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/48.customQABot-all-features) sample …

[#6889] CQA to support TokenCredential instead of key

---

libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs

Fixes https://github.com/microsoft/BotBuilder-Samples/issues/4037
This PR adds the ComponentRegistration class to register the memory scopes (turn, this, etc.) in the dialog state manager.
_Note: this change is already applied in botbuilder-js, now botbuilder-dotnet does the same._
- Added ComponentRegistration to DialogStateManager to register dialog memory scopes.
The following image shows the CQA bot working correctly.

[#4037] Add ComponentRegistration for memory scopes
