microsoft/botbuilder-dotnet

libraries/Microsoft.Bot.Builder/BotContext.cs, libraries/Microsoft.Bot.Builder/IBotContext.cs, tests/Microsoft.Bot.Builder.Tests/BotContext_Tests.cs
This PR addresses the following:
1. Add optional speak parameter to the Reply() method. Aligns with the JS SDK. 
2. Adds IActivity overload to the Reply() method. Aligns with the JS SDK. Addresses Issue #76. 
3. Moves Activity to a separate class, separating it from the IActivity.cs definition. This should have been done ages ago! 
4. Adds tests for the Reply method(s). Surprised these tests didn't already exist. We have more technical debt around lack of tests than I expected.
=> Addresses Issue #76. Normalized "Reply" with JS codebase.

libraries/Microsoft.Bot.Builder/Middleware/TemplateManager.cs
=> Fixed, per discussion with Gabo

libraries/Microsoft.Bot.Builder/MessageFactory.cs, tests/Microsoft.Bot.Builder.Tests/MessageFactoryTests.cs
As per discussion with @Stevenic regarding issue #152 - added inputHint as an optional parameter to each method on the MessageFactory class (makes sense to have this given we are optionally sending SSML already).  This brings the class inline with changes made by @stevenic on the JS side in the MessageStyler class.
=> Added optional inputHint to methods on the MessageFactory

samples/Connector.EchoBot/Controllers/MessagesController.cs, tests/Microsoft.Bot.Connector.Tests/JwtTokenValidationTests.cs, tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj
- Fix tests and bot connector sample (#126)
- Change tests project target framework to `netcoreapp2.0`
=> Fix BotConnector solution

libraries/Microsoft.Bot.Builder/FlexObject.cs
Exposes serialization settings so that it can be customized for DI 
Fixes #141
=> expose jsonserialization settings for customization

Microsoft.Bot.Builder.sln, samples/Microsoft.Bot.Samples.Ai.QnA/Controllers/MessagesController.cs, samples/Microsoft.Bot.Samples.Ai.QnA/Microsoft.Bot.Samples.Ai.QnA.csproj
Updated references within and re-added the QnA Maker sample
=> Fixed QnA sample

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, samples/AlarmBot-Cards/BotController.cs, samples/AlarmBot/BotController.cs, samples/Microsoft.Bot.Samples.Ai.QnA/Controllers/MessagesController.cs, samples/Microsoft.Bot.Samples.CustomMiddleware/Controllers/MessagesController.cs, samples/Microsoft.Bot.Samples.EchoBot-AspNet461/BotController.cs
Fixing the misspelling of 'ProcessActivity'
=> fix 'ProcessActivity' spelling

libraries/Microsoft.Bot.Builder.Core/MessageFactory.cs, tests/Microsoft.Bot.Builder.Tests/MessageFactoryTests.cs
Fixes #200. 
Done against the correct branch this time. :)
=> Fixes to suggested ACtions, #200

libraries/Microsoft.Bot.Builder.Core/BotContext.cs
=> Parameter naming fix, to match other constructor and recent refactoring.

samples/AlarmBot-Cards/AlarmBot-Cards.csproj, samples/AlarmBot/AlarmBot.csproj, tests/Microsoft.Bot.Builder.Prompts.Tests/Microsoft.Bot.Builder.Prompts.Tests.csproj, tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj
Cleanup build warnings when Release mode is set. This make a big difference on the build server.
=> Build Warning Cleanup around async methods in Release

libraries/Microsoft.Bot.Builder.Prompts/BasePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/ConfirmPrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/DateTimePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/Microsoft.Bot.Builder.Prompts.csproj, libraries/Microsoft.Bot.Builder.Prompts/NumberPrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/NumberWithUnitPrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/PercentagePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/PhonePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/PromptValidator.cs, libraries/Microsoft.Bot.Builder.Prompts/RangePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/TextPrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/ValuePrompt.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/AgePromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/ConfirmPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/CurrencyPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/DimensionPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/NumberPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/OrdinalPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/PhoneNumberPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/RangePromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/TemperaturePromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/TextPromptTests.cs
* Changed all response types to be an object with status code so validators can give feedback on validation violations
* Added ConfirmPrompt with unit tests
=> Changed to use RecognizeResult with status code and added ConfirmPrompt

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
=> Nuget config for ASP.NET integration projects

libraries/Microsoft.Bot.Builder.Core/BotContext.cs, libraries/Microsoft.Bot.Builder.Core/BotContextWrapper.cs, libraries/Microsoft.Bot.Builder.Core/IBotContext.cs, tests/Microsoft.Bot.Builder.Core.Tests/BotContextTests.cs
=> Support IMessageActivity on the Context Send methods. This allows the MessageFactory to easily send.

libraries/Microsoft.Bot.Builder.Prompts/AgePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/CurrencyPrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/DimensionPrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/Microsoft.Bot.Builder.Prompts.csproj, libraries/Microsoft.Bot.Builder.Prompts/NumberPrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/OrdinalPrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/PercentagePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/PhonePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/RangePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/TemperaturePrompt.cs, samples/AlarmBot-Cards/AlarmBot-Cards.csproj, samples/AlarmBot-Cards/DateTimeRecognizerExtensions.cs, samples/AlarmBot/AlarmBot.csproj, samples/AlarmBot/Models/AlarmBotContext.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/Microsoft.Bot.Builder.Prompts.Tests.csproj, tests/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.Tests.csproj
Addresses issue in #304. 
Updated to latest version of Microsoft.Recognizers.Text (and realted) nuget packages. This was a breaking changing, requiring minor code changes.
=> Updated to latest Recognizers.Text Nuget packages

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
Needed to enable proactive messaging. Planning a more thorough fix in the near future, but this is needed to unblock customer.
=> Fixes to BotFrameworkAdapter for Proactive Messaging

samples/AlarmBot/Responses/AddAlarmResponses.cs, samples/AlarmBot/Responses/DefaultResponses.cs, samples/AlarmBot/Responses/ResponseHelpers.cs, samples/AlarmBot/Startup.cs, samples/AlarmBot/Topics/AddAlarmTopic.cs, samples/AlarmBot/Topics/DefaultTopic.cs, samples/AlarmBot/Topics/DeleteAlarmTopic.cs, samples/AlarmBot/Topics/ShowAlarmsTopic.cs, samples/AlarmBot/responses/DeleteAlarmResponses.cs, samples/AlarmBot/responses/ShowAlarmsResponses.cs
=> Remove Batch() operations from the AlarmBot sample for simplicity.

libraries/Microsoft.Bot.Builder.Core/MiddlewareSet.cs, tests/Microsoft.Bot.Builder.Core.Tests/MiddlewareSetTests.cs
Remove all use of LINQ, reduce allocations, reduce number of invocations.
=> Improve perf of MiddlewareSet pipeline execution

libraries/Microsoft.Bot.Builder.Core/IBot.cs, libraries/Microsoft.Bot.Builder.Core/IMiddleware.cs, libraries/Microsoft.Bot.Builder.Core/Microsoft.Bot.Builder.Core.csproj
=> Adding reference documentation

libraries/Microsoft.Bot.Builder.Core/Assertions.cs, libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs
- With tweaks to two assertion methods: use IEnumerable<T> in place of List<T> or T[].
=> Add doc XML to Assertions and to BotAdapter

libraries/Microsoft.Bot.Builder.Core/ITurnContext.cs, libraries/Microsoft.Bot.Builder.Core/TurnContext.cs
- Fix a couple comments in TurnContext.
- Add comments for new parameters and methods in TurnContext.
=> Add doc XML to ITurnContext.

libraries/Microsoft.Bot.Builder.Core.Extensions/MessageFactory.cs, libraries/Microsoft.Bot.Builder.Core.Extensions/Microsoft.Bot.Builder.Core.Extensions.csproj
- and turn on documentation XML in the build for the Core.Extensions library.
=> Add doc XML to MessageFactory

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkOptions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ServiceCollectionExtensions.cs
@drub0y Please review an make suggestions/corrections as necessary.
=> Add doc XML to integration core library

tests/Microsoft.Bot.Builder.Ai.QnA.Tests/Microsoft.Bot.Builder.Ai.Tests.csproj
An old project file was blocking the build. Removed it.
=> Removed old QnA Maker Test File

libraries/Microsoft.Bot.Builder.Ai.QnA/Microsoft.Bot.Builder.Ai.QnA.csproj, libraries/Microsoft.Bot.Builder.Ai.Translation/LocaleConverter.cs, libraries/Microsoft.Bot.Builder.Ai.Translation/Microsoft.Bot.Builder.Ai.Translation.csproj, libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic.csproj, libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj, samples/AlarmBot-Cards/AlarmBot-Cards.csproj, samples/AlarmBot/AlarmBot.csproj, samples/Microsoft.Bot.Samples.Ai.QnA.Translator/Microsoft.Bot.Samples.Ai.QnA.Translator.csproj, samples/Microsoft.Bot.Samples.EchoBot-AspNetWebApi/Microsoft.Bot.Samples.EchoBot-AspNetWebApi.csproj, samples/Microsoft.Bot.Samples.EchoBot-Console/Microsoft.Bot.Samples.EchoBot-Console.csproj, tests/FormTest/FormTest.csproj, tests/Microsoft.Bot.Builder.Ai.LUIS.Tests/Microsoft.Bot.Builder.Ai.LUIS.Tests.csproj, tests/Microsoft.Bot.Builder.Ai.QnA.Tests/Microsoft.Bot.Builder.Ai.QnA.Tests.csproj, tests/Microsoft.Bot.Builder.Ai.Translation.Tests/Microsoft.Bot.Builder.Ai.Translation.Tests.csproj, tests/Microsoft.Bot.Builder.Azure.Tests/Microsoft.Bot.Builder.Azure.Tests.csproj, tests/Microsoft.Bot.Builder.Classic.Tests/Microsoft.Bot.Builder.Classic.Tests.csproj, tests/Microsoft.Bot.Builder.Core.Extensions.Tests/Microsoft.Bot.Builder.Core.Extensions.Tests.csproj, tests/Microsoft.Bot.Builder.Core.Tests/Microsoft.Bot.Builder.Core.Tests.csproj, tests/Microsoft.Bot.Builder.Prompts.Tests/Microsoft.Bot.Builder.Prompts.Tests.csproj, tests/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.Tests.csproj, tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj, tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj, tests/Microsoft.Bot.Schema.Tests/Microsoft.Bot.Schema.Tests.csproj
Reverts Microsoft/botbuilder-dotnet#401 due to broken build
=> Revert "Upgraded DateTime Recognizer and removed Luis cognitive Nuget"

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotProactiveMessageHandler.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotProactiveMessageHandler.cs
Fixes issues related to the proactive endpoint that the ASP.NET
integration libraries where it was calling the base
`BotAdapter::ContinueConversation` vs the `BotFrameworkAdapter`
specific overload of `ContinueConversation` which takes the `botAppId`.
This adds the ability to specify the `botAppId` as either an HTTP
header named `"MS-BotFramework-BotAppId"` or a querystring parameter
named just `"BotAppId"`.
=> Add support for BotAppId via proactive endpoint

libraries/Microsoft.Bot.Builder.Core.Extensions/TranscriptLoggerMiddleware.cs
additional code review feedback from stevenic
=> use applyConversationReference for DeleteMessage Activity

libraries/Microsoft.Bot.Builder.Core/TurnContext.cs, tests/Microsoft.Bot.Builder.Core.Tests/TurnContextTests.cs
=> Do not set the Responded Flag based on TraceActivities.

Microsoft.Bot.Builder.sln, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj
Dialogs package didn't have nuget package metadata
=> update dialogs project file to builder nuget package

libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
=> Fixes a couple issues with the AzureBlobStorage implementation

libraries/Microsoft.Bot.Builder.Core.Extensions/Microsoft.Bot.Builder.Core.Extensions.csproj
Addresses #451
(I needed something simple and mindless to do. This seemed like a perfect candidate).
=> Removed System.Dynamic dependency from Core.Extensions.

Microsoft.Bot.Builder.sln, libraries/Microsoft.Bot.Builder.Ai.LUIS/Microsoft.Bot.Builder.Ai.LUIS.csproj, libraries/Microsoft.Bot.Builder.Ai.QnA/Microsoft.Bot.Builder.Ai.QnA.csproj, libraries/Microsoft.Bot.Builder.Ai.Translation/Microsoft.Bot.Builder.Ai.Translation.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj
- don't generate nugets for this config
- do generate documention XML for all libraries
- do include all library projects
- don't include test or sample projects
=> Update the `documentation` build configuration

libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs
Copied same documentation XML comments from BoBuilder-JS version.
Also, made some private method static.
=> Add XML comments to AzureBlobTranscriptStore + minor improvements

Microsoft.Bot.Builder.sln, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptDelegates.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandler.cs
#472 
Note that the LUIS Recognizer is not being fixed here, as it's being changed in PR #477. We'll need to visit that one seperatly.
=> Change some scopes, per issue #472

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Waterfall.cs, libraries/Microsoft.Bot.Builder.Prompts/ChoicePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/Channel.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/Choice.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/ChoiceFactory.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/ChoiceFactoryOptions.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/Find.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/FindChoicesOptions.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/FindValuesOptions.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/FoundChoice.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/FoundValue.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/ModelResult.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/RecognizeChoices.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/SortedValue.cs, libraries/Microsoft.Bot.Builder.Prompts/Choices/Tokenizer.cs, libraries/Microsoft.Bot.Builder.Prompts/Microsoft.Bot.Builder.Prompts.csproj, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogChoicePromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/ChoiceFactoryTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/ChoicePromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/ChoicesRecognizersTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/ChoicesTokenizerTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/NumberPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/TestState.cs
Complete port of choice prompt form JavaScript.
Majority of unit tests are exact ports of Steve's at the lower/inner level.
Samples and additional feature in ConfirmPrompt will be follow on checkins.
=> choice prompt

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
Addresses #464 
The payload coming from the Bot To the Emulator now matches the Node payload. The behavior of SendTo/ReplyTo now is the same across the two frameworks. 
```
{
"channelId": "emulator",
"conversation": {
"id": "094fcec0-44fd-11e8-9621-99dda7b8036a|livechat"
},
"from": {
"id": "027494a0-44ee-11e8-9621-99dda7b8036a",
"name": "Bot",
"role": "bot"
},
"id": "0caab991-44fd-11e8-a396-93301aa0a129",
"localTimestamp": "2018-04-20T17:43:46-07:00",
"recipient": {
"id": "default-user",
"role": "user"
},
"replyToId": "0c9b2930-44fd-11e8-a396-93301aa0a129",
"serviceUrl": "http://localhost:51427",
"text": "You sent 'foo'",
"timestamp": "2018-04-21T00:43:46.473Z",
"type": "message"
}
```
=> Align BotFramework Send Behavior with Node per #464

libraries/Microsoft.Bot.Builder.Ai.LUIS/Microsoft.Bot.Builder.Ai.LUIS.csproj, libraries/Microsoft.Bot.Builder.Ai.QnA/Microsoft.Bot.Builder.Ai.QnA.csproj, libraries/Microsoft.Bot.Builder.Ai.Translation/Microsoft.Bot.Builder.Ai.Translation.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic.csproj, libraries/Microsoft.Bot.Builder.Core.Extensions/Microsoft.Bot.Builder.Core.Extensions.csproj, libraries/Microsoft.Bot.Builder.Core/Microsoft.Bot.Builder.Core.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.Prompts/Microsoft.Bot.Builder.Prompts.csproj, libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
doc files were not being built as part of release build and so weren't included in nupkg files
=> fix generation of doc files for Release build

libraries/Microsoft.Bot.Builder.Core.Extensions/MessageFactory.cs, libraries/Microsoft.Bot.Builder.Core/ITurnContext.cs, tests/Microsoft.Bot.Builder.Core.Extensions.Tests/MessageFactoryTests.cs
@cleemullins This addresses #482 as raised by @Stevenic. Appropriate methods updated as well as xml comments for others that call them.
=> Set InputHint to AcceptingInput by default on outgoing activities

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/DateTimePrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/Microsoft.Bot.Builder.Prompts.csproj, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogDateTimePromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/DateTimePromptTests.cs
datetime prompt including integration in dialogs
=> added DateTimePrompt

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/AttachmentPrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/AttachmentPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/AttachmentPromptTests.cs, tests/Microsoft.Bot.Builder.Prompts.Tests/AttachmentPromptTests.cs
=> add attachment prompt and dialog

libraries/Microsoft.Bot.Builder.Ai.QnA/QnAMaker.cs, tests/Microsoft.Bot.Builder.Ai.QnA.Tests/QnAMakerTests.cs
Added additional checks as per #479
=> Improved error checking for QnAMaker

samples/Microsoft.Bot.Samples.Ai.Luis.Dispatch/LuisDispatchBot.cs
Updates to use new types and fix typos
=> Update sample for new types

Microsoft.Bot.Builder.Samples.sln, samples-final/AspNetCore-SinglePrompt-Bot/AspNetCore-SinglePrompt-Bot.csproj, samples-final/AspNetCore-SinglePrompt-Bot/Program.cs, samples-final/AspNetCore-SinglePrompt-Bot/SinglePromptBot.cs, samples-final/AspNetCore-SinglePrompt-Bot/SinglePromptState.cs, samples-final/AspNetCore-SinglePrompt-Bot/Startup.cs, samples-final/AspNetCore-SinglePrompt-Bot/appsettings.json, samples-final/AspNetCore-SinglePrompt-Bot/readme.md, samples-final/AspNetCore-SinglePrompt-Bot/wwwroot/default.htm
Add sample bot using `TextPrompt`
=> SinglePrompt bot sample

Microsoft.Bot.Builder.Samples.sln, samples-final/AspNetCore-ConversationUpdate-Bot/AspNetCore-ConversationUpdate-Bot.csproj, samples-final/AspNetCore-ConversationUpdate-Bot/ConversationUpdateBot.cs, samples-final/AspNetCore-ConversationUpdate-Bot/Program.cs, samples-final/AspNetCore-ConversationUpdate-Bot/Startup.cs, samples-final/AspNetCore-ConversationUpdate-Bot/appsettings.json, samples-final/AspNetCore-ConversationUpdate-Bot/readme.md, samples-final/AspNetCore-ConversationUpdate-Bot/wwwroot/default.htm
Add a sample bot that shows how to handle different type of messages.
=> ConversationUpdate sample bot

Microsoft.Bot.Builder.Samples.sln, samples-final/AspNetCore-MultiplePrompts-Bot/AspNetCore-MultiplePrompts-Bot.csproj, samples-final/AspNetCore-MultiplePrompts-Bot/MultiplePromptsBot.cs, samples-final/AspNetCore-MultiplePrompts-Bot/MultiplePromptsState.cs, samples-final/AspNetCore-MultiplePrompts-Bot/Program.cs, samples-final/AspNetCore-MultiplePrompts-Bot/Startup.cs, samples-final/AspNetCore-MultiplePrompts-Bot/appsettings.json, samples-final/AspNetCore-MultiplePrompts-Bot/readme.md, samples-final/AspNetCore-MultiplePrompts-Bot/wwwroot/default.htm
Add a sample bot that shows how to use multiple prompts.
=> MultiplePrompts sample bot

samples-final/AspNetCore-ConversationUpdate-Bot/AspNetCore-ConversationUpdate-Bot.csproj, samples-final/AspNetCore-ConversationUpdate-Bot/ConversationUpdateBot.cs, samples-final/AspNetCore-ConversationUpdate-Bot/Program.cs, samples-final/AspNetCore-ConversationUpdate-Bot/Startup.cs, samples-final/AspNetCore-ConversationUpdate-Bot/wwwroot/default.htm, samples-final/AspNetCore-EchoBot-With-State/AspNetCore-EchoBot-With-State.csproj, samples-final/AspNetCore-EchoBot-With-State/EchoBot.cs, samples-final/AspNetCore-EchoBot-With-State/EchoState.cs, samples-final/AspNetCore-EchoBot-With-State/Program.cs, samples-final/AspNetCore-EchoBot-With-State/Startup.cs, samples-final/AspNetCore-MultiplePrompts-Bot/AspNetCore-MultiplePrompts-Bot.csproj, samples-final/AspNetCore-MultiplePrompts-Bot/MultiplePromptsBot.cs, samples-final/AspNetCore-MultiplePrompts-Bot/MultiplePromptsState.cs, samples-final/AspNetCore-MultiplePrompts-Bot/Program.cs, samples-final/AspNetCore-MultiplePrompts-Bot/Startup.cs, samples-final/AspNetCore-MultiplePrompts-Bot/wwwroot/default.htm, samples-final/AspNetCore-RichCards-Bot/AspNetCore-RichCards-Bot.csproj, samples-final/AspNetCore-RichCards-Bot/Program.cs, samples-final/AspNetCore-RichCards-Bot/RichCardsBot.cs, samples-final/AspNetCore-RichCards-Bot/Startup.cs, samples-final/AspNetCore-RichCards-Bot/wwwroot/default.htm, samples-final/AspNetCore-SinglePrompt-Bot/AspNetCore-SinglePrompt-Bot.csproj, samples-final/AspNetCore-SinglePrompt-Bot/Program.cs, samples-final/AspNetCore-SinglePrompt-Bot/SinglePromptBot.cs, samples-final/AspNetCore-SinglePrompt-Bot/Startup.cs, samples-final/Console-EchoBot-With-State/Console-EchoBot-With-State.csproj, samples-final/Console-EchoBot-With-State/Program.cs
Update botbuilder dependencies to latest version and minor namespace fixes.
=> Update samples dependencies

Microsoft.Bot.Builder.Samples.sln, samples-final/AspNetCore-QnA-Bot/AspNetCore-QnA-Bot.csproj, samples-final/AspNetCore-QnA-Bot/Program.cs, samples-final/AspNetCore-QnA-Bot/QnABot.cs, samples-final/AspNetCore-QnA-Bot/Startup.cs, samples-final/AspNetCore-QnA-Bot/appsettings.json, samples-final/AspNetCore-QnA-Bot/readme.md, samples-final/AspNetCore-QnA-Bot/smartLightFAQ.tsv, samples-final/AspNetCore-QnA-Bot/wwwroot/default.htm
Add a sample bot that shows how to use QnAMaker middleware.
=> QnAMaker sample bot

libraries/Microsoft.Bot.Builder.Ai.LUIS/Generator/InstanceData.cs, libraries/Microsoft.Bot.Builder.Ai.LUIS/Generator/IntentData.cs
=> Add open-ended properties to intent and instance data.

README.md
added preview to readme and remove experimental
=> Update readme for Preview

samples-final/AspNetCore-ConversationUpdate-Bot/AspNetCore-ConversationUpdate-Bot.csproj, samples-final/AspNetCore-EchoBot-With-State/AspNetCore-EchoBot-With-State.csproj, samples-final/AspNetCore-Luis-Dispatch-Bot/AspNetCore-Luis-Dispatch-Bot.csproj, samples-final/AspNetCore-Luis-Dispatch-Bot/appsettings.json, samples-final/AspNetCore-MultiplePrompts-Bot/AspNetCore-MultiplePrompts-Bot.csproj, samples-final/AspNetCore-QnA-Bot/AspNetCore-QnA-Bot.csproj, samples-final/AspNetCore-QnA-Bot/appsettings.json, samples-final/AspNetCore-RichCards-Bot/AspNetCore-RichCards-Bot.csproj, samples-final/AspNetCore-SinglePrompt-Bot/AspNetCore-SinglePrompt-Bot.csproj, samples-final/Console-EchoBot-With-State/Console-EchoBot-With-State.csproj
Update botbuilder to 4.0.1-preview
=> Update samples dependencies to 4.0.1-preview

tests/Microsoft.Bot.Builder.Ai.LUIS.Tests/LuisRecognizerMiddlewareTests.cs
Add a verification for environment variables defined to avoid failing test
=> Check for LUIS environment variables defined

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandlerBase.cs
=> Better handle IBot dependency resolution exceptions in WebAPI

Microsoft.Bot.Builder.Samples.sln
The solution points to old project folders after "Cleanup samples" was merged.
=> Fix Microsoft.Bot.Builder.Samples.sln

libraries/Microsoft.Bot.Builder.Core/Adapters/ConsoleAdapter.cs, libraries/Microsoft.Bot.Builder.Core/Adapters/TestAdapter.cs, libraries/Microsoft.Bot.Builder.Core/TurnContext.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
Optimizations focusing _mainly_ on the `TurnContext::SendActivities` implementation, but includes a couple small optimizations for the various `BotAdapter` subclasses `SendActivities` implementations as well.
Here are the benchmark results that focus only on the `TurnContext::SendActivities` implementation optimizations:
``` ini
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.17134
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
[Host]     : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3101.0
DefaultJob : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3101.0
```
|                   Method | NumberOfActivities | NumberOfHandlers |      Mean |     Error |    StdDev |    Median | Scaled | ScaledSD |  Gen 0 | Allocated | …
=> SendActivities Performance Optimizations

libraries/Microsoft.Bot.Builder.Dialogs/OAuthPromptOptions.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Builder.Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs, samples/MIcrosoft.Bot.Samples.Dialog.Prompts/OAuthPromptBot.cs, samples/MIcrosoft.Bot.Samples.Dialog.Prompts/Startup.cs
1) added a sample for auth to the existing prompt project.
2) minor fixes (that are also done in the node code too)
=> Add an auth prompt sample. Also fix minor bugs

Microsoft.Bot.Builder.Samples.sln, samples-final/AspNetCore-CardActions-Bot/AspNetCore-CardActions-Bot.bot, samples-final/AspNetCore-CardActions-Bot/AspNetCore-CardActions-Bot.csproj, samples-final/AspNetCore-CardActions-Bot/CardActionsBot.cs, samples-final/AspNetCore-CardActions-Bot/Program.cs, samples-final/AspNetCore-CardActions-Bot/Startup.cs, samples-final/AspNetCore-CardActions-Bot/appsettings.json, samples-final/AspNetCore-CardActions-Bot/readme.md, samples-final/AspNetCore-CardActions-Bot/wwwroot/default.htm, samples-final/AspNetCore-HelpAndCancel-Bot/AspNetCore-HelpAndCancel-Bot.bot, samples-final/AspNetCore-HelpAndCancel-Bot/AspNetCore-HelpAndCancel-Bot.csproj, samples-final/AspNetCore-HelpAndCancel-Bot/HelpAndCancelBot.cs, samples-final/AspNetCore-HelpAndCancel-Bot/MessageState.cs, samples-final/AspNetCore-HelpAndCancel-Bot/Program.cs, samples-final/AspNetCore-HelpAndCancel-Bot/Startup.cs, samples-final/AspNetCore-HelpAndCancel-Bot/appsettings.json, samples-final/AspNetCore-HelpAndCancel-Bot/readme.md, samples-final/AspNetCore-HelpAndCancel-Bot/wwwroot/default.htm, samples-final/AspNetCore-SimplePrompt-Bot/AspNetCore-SimplePrompt-Bot.bot, samples-final/AspNetCore-SimplePrompt-Bot/AspNetCore-SimplePrompt-Bot.csproj, samples-final/AspNetCore-SimplePrompt-Bot/Program.cs, samples-final/AspNetCore-SimplePrompt-Bot/SimplePromptBot.cs, samples-final/AspNetCore-SimplePrompt-Bot/SimplePromptState.cs, samples-final/AspNetCore-SimplePrompt-Bot/Startup.cs, samples-final/AspNetCore-SimplePrompt-Bot/appsettings.json, samples-final/AspNetCore-SimplePrompt-Bot/readme.md, samples-final/AspNetCore-SimplePrompt-Bot/wwwroot/default.htm
- SimplePrompt-bot -> Prompting with Primitives
- CardActions-bot -> Postback with buttons
- HelpAndCancel-bot -> Bot Framework Cancel/Help at any level sample
=> New samples

libraries/Microsoft.Bot.Builder.Core/Adapters/TestAdapter.cs, libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs
removed this for now - at least we will be consistent
we should consider plumbing the cancellation everywhere
#366
=> removed cancellation token for now

libraries/Microsoft.Bot.Builder.Core.Extensions/MessageFactory.cs, libraries/Microsoft.Bot.Schema/SuggestedActionsEx.cs, tests/Microsoft.Bot.Builder.Core.Extensions.Tests/MessageFactoryTests.cs
- Update MessageFactory.SuggestedActions to accept IEnumerable.
- Add test against the updated MessageFactory output.
=> Generalize SuggestedActions from taking IList to IEnumerable

libraries/Microsoft.Bot.Builder.Ai.Translation/CustomDictionary.cs, libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/Autofac/Dialogs/Conversation.cs, libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/ConnectorEx/IChannelCapability.cs, libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/ConnectorEx/ResumptionCookie.cs, libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/Dialogs/PromptDialog.cs, libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs, libraries/Microsoft.Bot.Builder.Dialogs/Internal/AttachmentPromptInternal.cs, libraries/Microsoft.Bot.Builder.Dialogs/Internal/BasePromptInternal.cs, libraries/Microsoft.Bot.Builder.Dialogs/Internal/OAuthPromptInternal.cs, libraries/Microsoft.Bot.Builder.Dialogs/Internal/TextPromptInternal.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptDelegates.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptResult.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptStatus.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptValidator.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, tests/Microsoft.Bot.Builder.Core.Extensions.Tests/ShowTyping_MiddlewareTests.cs
Invalid XML cref warnings were breaking the ref doc build. Hopefully, this PR will unblock the doc builds.
=> Fix compiler warnings that were breaking the ref doc build.

libraries/Microsoft.Bot.Builder.Ai.Translation/TranslationMiddleware.cs, tests/Microsoft.Bot.Builder.Ai.Translation.Tests/TranslatorMiddlewareTests.cs
Added test to ensure public member are virtual in the class and be overridden and also a specialized test class to check the overridden value in the new middleware.
=> Made OnTurn in TranslationMiddleware virtual so it can be overridden.

libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EndorsementsValidator.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/EndorsementsRetrieverTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/EndorsementsValidatorTests.cs, tests/Microsoft.Bot.Connector.Tests/JwtTokenValidationTests.cs
Updates to Token Endorsements in V4 SDK
=> Token Endorsements

libraries/Microsoft.Bot.Builder.Ai.LUIS/LuisRecognizerMiddleware.cs, libraries/Microsoft.Bot.Builder.Ai.Translation/CustomDictionary.cs, libraries/Microsoft.Bot.Builder.Ai.Translation/PostProcessor/PostProcessingUtilities.cs, libraries/Microsoft.Bot.Builder.TemplateManager/TemplateManager.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/Core/Extensions/BotState.cs, libraries/Microsoft.Bot.Builder/Core/Extensions/FileTranscriptStore.cs, libraries/Microsoft.Bot.Builder/Core/Extensions/MemoryTranscriptStore.cs, libraries/Microsoft.Bot.Connector/AttachmentsEx.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs, libraries/Microsoft.Bot.Schema/ActivityEx.cs, libraries/Microsoft.Bot.Schema/IActivity.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ServiceCollectionExtensions.cs
These fixes should improve the reference documentation generated from the /// comments.
=> Fix various doc XML warnings

libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
=> add bot.builder package to build

libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
remove the package dependency no longer necessary now this package just depends on CosmosDB
=> remove NuGet dependency on azure.storage

libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorageOptions.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
Making Cosmos DB Storage class more DI-able by pulling the configuration into a configuration class which is easier to DI
=> Making Cosmos DB Storage Class more DI-Able

libraries/Microsoft.Bot.Builder.Ai.Translation/TranslationMiddleware.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorageOptions.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs, libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkConfigurationBuilder.cs
Fixing CS errors: 157x, 1580, and 1591.
=> Fix new doc XML issues introduced recently

libraries/Microsoft.Bot.Builder/BotAdapter.cs, libraries/Microsoft.Bot.Builder/Integration/BotFrameworkOptions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ServiceCollectionExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkConfigurationBuilder.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/HttpConfigurationExtensions.cs, tests/Microsoft.Bot.Builder.Tests/OnErrorTests.cs, tests/Microsoft.Bot.Builder.Tests/OnTurnErrorTests.cs
changed the name ErrorHandler to OnError. @Stevenic pointed out I was inconsistent.
=> changed name of ErrorHandler to be consistent

doc/UserAgents.md
Trying a PR, to see if it gives a useful mechanism for reviewing and commenting on a doc proposal. Normally this should probably be an Issue, but I'm interested in seeing how this works as a reviewing mechanism...
=> A Proposal for more robust User Agents in the Bot Framework

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptTests.cs
Make parity with js!
https://github.com/Microsoft/botbuilder-dotnet/issues/644
=> Fix botbuilder-dotnet/issues/644 - Choice override on ConfirmPrompt

tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
_For issue #780. Originally [BotBuilder/issues/4888](https://github.com/Microsoft/BotBuilder/issues/4888)._ 
___
Issue **#780** has actually been addressed by the code currently in the repo, whereas the original poster is using [4.0.1-preview](https://github.com/Microsoft/botbuilder-dotnet/releases/tag/4.0.1-preview). To make sure this doesn't break going forward I've added a test for the described case.
=> add Waterfall DateTimePrompt test

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandlerBase.cs
=> Fixed AspNet.WebApi media type issue

Microsoft.Bot.Builder.sln, tests/Microsoft.Bot.Builder.Dialogs.Tests/ComponentDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot/Microsoft.Bot.Builder.TestBot.csproj, tests/Microsoft.Bot.Builder.TestBot/Program.cs, tests/Microsoft.Bot.Builder.TestBot/Startup.cs, tests/Microsoft.Bot.Builder.TestBot/TestBot.cs, tests/Microsoft.Bot.Builder.TestBot/TestBotAccessors.cs, tests/Microsoft.Bot.Builder.TestBot/appsettings.Development.json, tests/Microsoft.Bot.Builder.TestBot/appsettings.json, tests/Microsoft.Bot.Builder.TestBot/wwwroot/default.htm
Add TestBot Project in the main Visual Studio Solution as a tool for debugging internal components of the SDK.
=> Add TestBot as a tool for debugging

libraries/Microsoft.Bot.Configuration/BotConfiguration.cs, libraries/Microsoft.Bot.Configuration/GlobalSuppressions.cs, libraries/Microsoft.Bot.Configuration/ServiceTypes.cs, libraries/Microsoft.Bot.Configuration/Services/AppInsightsService.cs, libraries/Microsoft.Bot.Configuration/Services/AzureService.cs, libraries/Microsoft.Bot.Configuration/Services/BlobStorageService.cs, libraries/Microsoft.Bot.Configuration/Services/BotService.cs, libraries/Microsoft.Bot.Configuration/Services/CosmosDbService.cs, libraries/Microsoft.Bot.Configuration/Services/GenericService.cs, tests/Microsoft.Bot.Configuration.Tests/ConfigurationLoadAndSaveTests.cs, tests/Microsoft.Bot.Configuration.Tests/ConnectionTests.cs, tests/Microsoft.Bot.Configuration.Tests/Microsoft.Bot.Configuration.Tests.csproj, tests/Microsoft.Bot.Configuration.Tests/test.bot
* AppInsights with keys
* Generic with configuration keys
* CosmosDB
* BlobStorage
* Auto assign ids
* relax names to be anything
* refactored to have AzureService shared class
* added serviceName to azure service classes
=> add new services to configuration

tests/Microsoft.Bot.Builder.TestBot/BotBuilderTestBot.bot, tests/Microsoft.Bot.Builder.TestBot/TestBot.cs
Added .bot file for the V4 emulator and added a bunch of comments
I also removed the rest if there was an earlier response - might conflict with future "Typing" middleware.
=> Added .bot file for the V4 emulator and added bunch of comments

libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs
=> Unescape Id in ListTranscriptsAsync

libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs, libraries/Microsoft.Bot.Builder/IBot.cs, libraries/Microsoft.Bot.Builder/IMiddleware.cs, libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
@daveta , Please double check the comments I added to the ConnectorClientEx.cs file.
=> Fix various docXML issues.

libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs, tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobTranscriptStoreTests.cs
=> Added AzureBlobTranscript Unit Tests

libraries/Microsoft.Bot.Builder.Dialogs/WaterfallDialog.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs, tests/Microsoft.Bot.Builder.Azure.Tests/Microsoft.Bot.Builder.Azure.Tests.csproj
=> Solution for deserialization bug #871

tests/Microsoft.Bot.Builder.Tests/BotAdapterTests.cs, tests/Microsoft.Bot.Builder.Tests/BotFrameworkOptionsTests.cs, tests/Microsoft.Bot.Builder.Tests/BotStateSetTests.cs, tests/Microsoft.Bot.Configuration.Tests/ConfigurationLoadAndSaveTests.cs, tests/Microsoft.Bot.Configuration.Tests/test.bot
Low pri: Add some test cases where little or no coverage.
=> Add some coverage test cases to config, stateset, adapter

samples-final/2.AspNetCore-ConversationUpdate-Bot/ConversationUpdateBot.cs
=> Updated ConversationUpdate-Bot Sample

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogStatus.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogTurnResult.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogTurnStatus.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ActivityPromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/AttachmentPromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ComponentDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptLocTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DateTimePromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/NumberPromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/TextPromptTests.cs, tests/Microsoft.Bot.Builder.TestBot/TestBot.cs
Enables cancel all logic in ComponentDialog and ability to add interruption in derived class.
=> added dialog status to dialogturnresult

libraries/Microsoft.Bot.Configuration/BotConfiguration.cs, tests/Microsoft.Bot.Configuration.Tests/ConfigurationLoadAndSaveTests.cs
To fix this issue: https://github.com/Microsoft/botbuilder-dotnet/issues/902
=> BotConfiguration: Support for sync operations + documentation consistency

libraries/Microsoft.Bot.Configuration/Services/AppInsightsService.cs, libraries/Microsoft.Bot.Configuration/Services/BlobStorageService.cs, libraries/Microsoft.Bot.Configuration/Services/CosmosDbService.cs, libraries/Microsoft.Bot.Configuration/Services/EndpointService.cs, libraries/Microsoft.Bot.Configuration/Services/GenericService.cs, libraries/Microsoft.Bot.Configuration/Services/LuisService.cs, libraries/Microsoft.Bot.Configuration/Services/QnAMakerService.cs, tests/Microsoft.Bot.Configuration.Tests/ConnectionTests.cs
added unit tests to verify that this works
=> We need to check for NullOrEmpty on encrypted properties before we call Encrypt or Decrypt

libraries/Microsoft.Bot.Builder/BotState.cs, libraries/Microsoft.Bot.Builder/IPropertyManager.cs, libraries/Microsoft.Bot.Configuration/BotConfiguration.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ConfigurationChannelProvider.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/HttpConfigurationExtensions.cs
this implemented DCR #933 
(rest of delta get rid of 3 spacing based warnings)
=> [DCR:933] add IPropertyManager interface to bot state 

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisApplication.cs, libraries/Microsoft.Bot.Configuration/Services/LuisService.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisApplicationTests.cs, tests/Microsoft.Bot.Configuration.Tests/ConnectionTests.cs
Fix for https://github.com/Microsoft/botbuilder-tools/issues/450
=> change to use region or endpoint

libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs, libraries/Microsoft.Bot.Builder/ITranscriptStore.cs, libraries/Microsoft.Bot.Builder/MemoryTranscriptStore.cs, libraries/Microsoft.Bot.Builder/TranscriptInfo.cs, tests/Microsoft.Bot.Builder.Tests/TranscriptBaseTests.cs
Schema has a transcript object which is THE transcript, wheras this API returns metadata about transcripts.
=> Rename ListTranscripts transcript -> to TranscriptInfo

libraries/Microsoft.Bot.Configuration/BotConfiguration.cs, tests/Microsoft.Bot.Configuration.Tests/ConfigurationLoadAndSaveTests.cs, tests/Microsoft.Bot.Configuration.Tests/Microsoft.Bot.Configuration.Tests.csproj, tests/Microsoft.Bot.Configuration.Tests/legacy.bot
rename secretKey -> padlock
Update unit tests
=> DCR: Change secretKey to padlock

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/MainDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/MainDialogTest.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
Implement DCR https://github.com/Microsoft/botbuilder-dotnet/issues/962
=> Add MainDialog and unit tests

libraries/Microsoft.Bot.Configuration/Services/QnAMakerService.cs, tests/Microsoft.Bot.Configuration.Tests/Microsoft.Bot.Configuration.Tests.csproj, tests/Microsoft.Bot.Configuration.Tests/ServiceTests.cs
fix for Microsoft/botbuilder-tools#502
=> make qnamaker ensure that hostname has /qnamaker suffix

libraries/Microsoft.Bot.Builder.Dialogs/Choices/FindChoicesOptions.cs, libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/ConfigurationChannelProvider.cs
These mostly fix issues that create broken links in the generated documentation.
=> Fix broken doc XML and some minor spelling and grammar issues.

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisApplication.cs
=> fix LuisApplication bad endpoint error

CodeCoverage.runsettings, README.md, build/PublishToCoveralls.ps1
The PR Build has been updated. This branch might have coveralls integration!
=> Initial scripts for coveralls integration

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs
=>  add LuisRecognizer.TopIntent and tests

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisApplication.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.LUIS.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerEndpoint.cs, libraries/Microsoft.Bot.Configuration/Services/QnAMakerService.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisApplicationTests.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
Adds configuration based construction.
=> add configuration based constructor

libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj
This gives us confirm prompt working in Chinese and Dutch.
We are still missing German and French.
=> update recognizer packages to 1.1.1

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs
Should fix missing confirm buttons in webchat.
=> updated supportsSuggestedActions() for directline & webchat

libraries/Microsoft.Bot.Connector/Authentication/GovernmentAuthenticationConstants.cs, libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/HttpConfigurationExtensions.cs, tests/Microsoft.Bot.Connector.Tests/MicrosoftGovernmentAppCredentialsTests.cs
=> Updating US Gov constants

libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorageOptions.cs, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDBKeyEscapeTests.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
Updated to latest CosmosDB NuGet Package.
Extracted Key Escaping into a dedicated class (with tests).
Added numerous CTor exception tests.
Added additional parameter checking on methods.
Plumbed through CancellationToken to CosmosDB Calls
Fixed race condition around Initialization
=> Fixes and Updates to the CosmosDB Storage Provider

tests/Microsoft.Bot.Connector.Tests/BaseTest.cs, tests/Microsoft.Bot.Connector.Tests/ConversationsTest.cs, tests/Microsoft.Bot.Connector.Tests/SessionRecords/Connector.Tests.ConversationsTest/CreateConversationWithCustomHeader.json, tests/Microsoft.Bot.Connector.Tests/SessionRecords/Connector.Tests.ConversationsTest/DeleteActivityWithCustomHeaders.json, tests/Microsoft.Bot.Connector.Tests/SessionRecords/Connector.Tests.ConversationsTest/GetActivityMembersWithCustomHeaders.json, tests/Microsoft.Bot.Connector.Tests/SessionRecords/Connector.Tests.ConversationsTest/GetConversationMembersWithCustomHeader.json, tests/Microsoft.Bot.Connector.Tests/SessionRecords/Connector.Tests.ConversationsTest/GetConversationPagedMembersWithCustomHeaders.json, tests/Microsoft.Bot.Connector.Tests/SessionRecords/Connector.Tests.ConversationsTest/ReplyToActivityWithCustomHeaders.json, tests/Microsoft.Bot.Connector.Tests/SessionRecords/Connector.Tests.ConversationsTest/SendToConversationWithCustomHeaders.json, tests/Microsoft.Bot.Connector.Tests/SessionRecords/Connector.Tests.ConversationsTest/UpdateActivityWithCustomHeaders.json
- Update the AssertTracingFor feature to support additional assertions
=> Add CustomHeaders unit tests for Conversations

libraries/Microsoft.Bot.Configuration/Services/LuisService.cs, tests/Microsoft.Bot.Configuration.Tests/ServiceTests.cs
update getEndpoint() for us gov data center
=> Cherry-pick pull request #1076 from 4.1 for US Gov Data centers

libraries/Swagger/ConnectorAPI.json, libraries/Swagger/StateAPI.json
Adds support for activity
- duration
- localtimezone
- history api
=> update connector lib with latest swagger

samples/Basic-Bot/BasicBot.cs, samples/Basic-Bot/BasicBot.csproj, samples/Basic-Bot/Dialogs/Greeting/GreetingDialog.cs, samples/Basic-Bot/Keys.cs, samples/Basic-Bot/LanguageGenerationMiddleware.cs, samples/Basic-Bot/LanguageGenerationUtilities.cs, samples/Basic-Bot/Startup.cs, samples/Basic-Bot/TemplateResponses.cs, samples/Cafe-Bot/Cafe-Bot.csproj, samples/Cafe-Bot/FallbackMessages.cs, samples/Cafe-Bot/Keys.cs, samples/Cafe-Bot/LanguageGenerationUtilities.cs, samples/Cafe-Bot/MultiTurnPromptsBot.cs, samples/Cafe-Bot/TemplateResponses.cs, samples/Simple-Prompt-Bot/Keys.cs, samples/Simple-Prompt-Bot/LanguageGenerationUtilities.cs, samples/Simple-Prompt-Bot/Simple-Prompt-Bot.csproj, samples/Simple-Prompt-Bot/SimplePromptBot.cs, samples/Simple-Prompt-Bot/TemplateResponses.cs
- Updating the endpoints used by the samples to use the production endpoints depending on the user provided azure region. 
- Creating a sample middleware for the language generation used in the basic bot sample.
=> Updating the endpoints used by the samples to use the production endpoints

libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/API/ServiceAgent.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/Microsoft.Bot.Builder.AI.LanguageGeneration.csproj
Update LG package to latest one.
Put LG service error information in Exception.
=> Update LG package to latest one.

libraries/Microsoft.Bot.Builder/Integration/BotFrameworkOptions.cs
=> Obsolete the BotFrameworkOptions::State property

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisDelegatingHandler.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/EmptyLuisResponseClientHandler.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/NullAdapter.cs
=> add user agent to LUIS calls

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisDelegatingHandler.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/EmptyLuisResponseClientHandler.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/InterceptRequestHandler.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
- add user agent header to QnA calls
=> add user agent header to QnA calls

libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs
replace await with ContinueWith in Transcript middleware
=> replace await with ContinueWith in Transcript middleware

libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/API/DefaultRegionalEndpointProvider.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/API/EndpointProvider.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/API/IEndpointProvider.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/Engine/Pipeline/IResolverPipelineFactory.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/Engine/Pipeline/Processors/RequestBuilder/IRequestBuilder.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/Engine/Pipeline/Processors/RequestBuilder/RequestBuilder.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/Engine/Pipeline/ResolverPipeline.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/Engine/Pipeline/ResolverPipelineFactory.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/Resolver/LanguageGenerationApplication.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/Resolver/LanguageGenerationOptions.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/Resolver/LanguageGenerationResolver.cs, samples/Basic-Bot/LanguageGenerationUtilities.cs, samples/Basic-Bot/Startup.cs, samples/Cafe-Bot/LanguageGenerationUtilities.cs, samples/Cafe-Bot/MultiTurnPromptsBot.cs, samples/Simple-Prompt-Bot/LanguageGenerationUtilities.cs, samples/Simple-Prompt-Bot/SimplePromptBot.cs, tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/LanguageGenerationApplicationTests.cs, tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/LanguageGenerationResolverTests.cs, tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/Microsoft.Bot.Builder.Ai.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/Mocks/CompositeRequestMock.cs, tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/Mocks/CompositeResponseMock.cs, tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/Mocks/ServiceAgentMock.cs, tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/TestData/lgModelForTesting.lg, tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/UtilitiesTests.cs, tests/Microsoft.Bot.Builder.AI.LanguageGeneration.Tests/testSettings.json
Modifying the LG application identifying object to require the application name, region, locale, and version.
=> Modifying the LG application identifying object

libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/TelemetryBotIdInitializer.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/TelemetryInitializerTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/TelemetryInitializerTests.cs
Add ChannelId to Request/CustomEvent.   Add tests as well.
=> Add ChannelId to initializer

libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs, libraries/Microsoft.Bot.Builder/Integration/IAdapterIntegration.cs, libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/BotFrameworkOptionsTests.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/ServiceCollectionExtensionsTests.cs
Cleanup of minor stylecop warnings.
=> Fix stylecop warnings

libraries/Microsoft.Bot.Builder.Dialogs.Flow/SequenceDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Flow/Steps/ClearVarStep.cs, libraries/Microsoft.Bot.Builder.Dialogs.Flow/Steps/EndDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Flow/Steps/IfElseStep.cs, libraries/Microsoft.Bot.Builder.Dialogs.Flow/Steps/SetVarStep.cs, libraries/Microsoft.Bot.Builder.Dialogs.Flow/Steps/StepSequence.cs, libraries/Microsoft.Bot.Builder.Dialogs.Flow/Steps/SwitchStep.cs, libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialogBase.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogInstance.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogState.cs, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ActivityPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/StateMap.cs, libraries/Microsoft.Bot.Builder.Dialogs/WaterfallDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
Pending features:
+ JsonPath query, set and get
+ Bug where user state is not persisted (currently worked around)
+ Port all tests from Node.js + ObservableDictionar
=> Memory: Initial draft implementation

libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/TemplateEngine.cs, libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/ThrowingErrorListener.cs
Add friendly exception message
=> Add friendly exception message

libraries/Microsoft.Bot.Builder/ActivityHandler.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
Includes a fix for bot-docs issue [881](https://github.com/MicrosoftDocs/bot-docs/issues/881).
=> Fix various doc XML issues

libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkHttpAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/packages.config
* gov fix for adapter
* add fix for user agent on MacOS
=> gov fix for adapter (#1431)

libraries/Microsoft.Bot.Builder/ActivityHandler.cs
=> Add documentation comments to ActivityHandler

tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/BotFrameworkHttpAdapterTests.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/Properties/AssemblyInfo.cs
=> [StyleCop] Fix all the warnings on AspNet.WebApi.Tests

libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ApplicationBuilderExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ServiceCollectionExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs
=> [StyleCop] Fix all the warnings on Integration.ApplicationInsights.Core

tests/Microsoft.Bot.Builder.Transcripts.Tests/CoreExtensionsTests.cs, tests/Microsoft.Bot.Builder.Transcripts.Tests/CoreTests.cs
- Add a blank line after closing brace
=> [StyleCop] Fix all warnings in Bot.Builder.Transcripts.Tests

tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs, tests/Microsoft.Bot.Schema.Tests/CardActionTest.cs, tests/Microsoft.Bot.Schema.Tests/EntitySchemaValidationTest.cs
- Add trailing comma in multi-line initializers
=> [StyleCop] Fix all warnings in Bot.Schema.Test project

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs
- Add documentation for constructor and parameters
=> [StyleCop] Fix all the warning in Bot.Builder.Dialogs

tests/Microsoft.Bot.Builder.Dialogs.Tests/ActivityPromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/AttachmentPromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicesRecognizersTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicesTokenizerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ComponentDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DateTimePromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogSetTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/EventActivityPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/MyWaterfallDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/NumberPromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/PromptValidatorContextTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/TestUtilities.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/TextPromptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
- Reorder parameters
- Remove trailing whitespace and add trailing commas
- Replace "" with string.Empty
- Fix spacing
=> [StyleCop] Fix all the warnings on Bot.Builder.Dialogs.Tests

libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/EmptyLuisResponseClientHandler.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisApplicationTests.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/MockedHttpClientHandler.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/TestUtilities.cs
- Reorder methods and fields
- Create a new file for a class
- Remove spaces
=> [StyleCop] Fix all the warnings in the AI.Luis.Tests project

libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj
- Add spacing
- Reorder constructor
=> [StyleCop] Fix all warnings on Bot.Builder

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs, libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/HttpRequest.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 11 - HttpRequest/HttpRequest.main.dialog
1. Support "GET", "POST" and JSON format body.
2. Dynamic replace all string (url), (headers) (JTokens in body) with the data in state(userstate, dialogstate etc.)
=> Add HttpRequest Step && Add Sample

libraries/Microsoft.Bot.Builder.Dialogs/DialogContextState.cs
When we tried to access the memory from a JArray. it will not return the expected result.
Add a JArray check to get the right value from memory
=> Fix the issue of GetValue from JArray

libraries/Microsoft.Bot.Connector/AttachmentsEx.cs, libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs, libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConstants.cs, libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EndorsementsRetriever.cs, libraries/Microsoft.Bot.Connector/Authentication/EndorsementsValidator.cs, libraries/Microsoft.Bot.Connector/Authentication/EnterpriseChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/GovernmentAuthenticationConstants.cs, libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/IChannelProvider.cs, libraries/Microsoft.Bot.Connector/Authentication/ICredentialProvider.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftGovernmentAppCredentials.cs, libraries/Microsoft.Bot.Connector/Authentication/OAuthConfiguration.cs, libraries/Microsoft.Bot.Connector/Authentication/Retry.cs, libraries/Microsoft.Bot.Connector/Authentication/RetryParams.cs, libraries/Microsoft.Bot.Connector/Authentication/SimpleChannelProvider.cs, libraries/Microsoft.Bot.Connector/Authentication/SimpleCredentialProvider.cs, libraries/Microsoft.Bot.Connector/Authentication/ThrottleException.cs, libraries/Microsoft.Bot.Connector/Authentication/TimeSpanExtensions.cs, libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs, libraries/Microsoft.Bot.Connector/ConversationsEx.cs, libraries/Microsoft.Bot.Connector/OAuthClientConfig.cs, libraries/Microsoft.Bot.Connector/OAuthClientOld.cs
- Fix documentation
- Fix spacing and commas
- Reorder methods and fields
=> [StyleCop] Fix all the warnings on Bot.Connector

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkHttpAdapter.cs
=> add UnauthorizedException handling to http adapter

libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/ServiceResolutionTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/TelemetryInitializerTests.cs
- Fix spacing
- Fix documentation
- Reorder usings
=> [Stylecop] Fix warnings in the AppInsight.WebApi.Tests project

libraries/Microsoft.Bot.Builder.ApplicationInsights/BotTelemetryClient.cs, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj
- Fix spacing
- Fix documentation
=> [StyleCop] Fix warnings in ApplicationInsights projects

libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, tests/Microsoft.Bot.Builder.AI.QnA.Tests/InterceptRequestHandler.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/MyTurnContext.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTraceInfoTests.cs
- Reorder methods
- Fix spacing
- Add a new file for a class
=> [StyleCop] Fix all the issues in the AI.QnA.Tests project

libraries/Microsoft.Bot.Builder.Dialogs/TextMessageActivityGenerator.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/AddToDo.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/ClearToDos.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/DeleteToDo.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/ShowToDos.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/ToDoBot.main.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/todo.lg, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
0. Fix a bug in TextMessageActivityGenerator.cs for multiple lines.
1. Add ShowTodo LG and remove the sendlist step.
2. add CancelIntent in Todo Bot Sample
3. Update the test cases
=> update todo sample

tests/Microsoft.Bot.Builder.TestBot.WebApi/LuisHelper.cs
Construct the LUIS recognizer correctly..
=> Fix testbot - construct LUIS Recognizer correctly

tests/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.Tests.csproj, tests/Microsoft.Bot.Builder.TemplateManager/TemplateManagerTests.cs
=> [StyleCop] Fix all the warnings on TemplateManager.Tests

tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/TelemetryWaterfallTests.cs
Create a method for instantiating new waterfalls and clean up the repeated code. This was requested on PR #1507
=> Optimize repeated code

doc/Language Generation/lg-file-format.md, doc/Language Generation/readme.md
- Readme.md to provide conceptual overview and use case
- lg-file-format.md to document the .lg file format and related concepts.
=> Language generation docs

tests/Microsoft.Bot.Builder.TestBot/BookingDetails.cs, tests/Microsoft.Bot.Builder.TestBot/Bots/DialogAndWelcomeBot.cs, tests/Microsoft.Bot.Builder.TestBot/Bots/DialogBot.cs, tests/Microsoft.Bot.Builder.TestBot/Dialogs/BookingDialog.cs, tests/Microsoft.Bot.Builder.TestBot/Dialogs/DateResolverDialog.cs, tests/Microsoft.Bot.Builder.TestBot/Dialogs/MainDialog.cs, tests/Microsoft.Bot.Builder.TestBot/Startup.cs
- Parameters formatting
- Single line comment spacing
- Elements and closing brace separation
- Format to the generic type constraint
- Trailing comma in multi-line initializers
=> [StyleCop] Fix warnings on Bot.Builder.TestBot

tests/Microsoft.Bot.Builder.Tests/TelemetryMiddlewareTests.cs
- Add/ Remove trailing whitespace
- Remove extra spaces
=> [StyleCop] Fix all the warnings on Bot.Builder.Tests

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/LuisRecognizerTests.cs
Functional Test for LUIS Recognizer is failing. Commenting out while I get the overall build working. 
Fixing this test is tracked in Issue #1661
=> Commented out failing LUIS test

README.md
Added Functional Test build badge
=> Updated Readme to include Functional Tests build badge

build/PublishToCoveralls.ps1
This lets us run it in the release I am creating.
=> Parameterize coveralls files path

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Microsoft.ILanguagePolicy.schema
When we moved ILanguagePolicy.schema to different assembly, a copy was left behind.
deleted the wrong copy
=> Duplicate schema file

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
=> update exception text

libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.LuisRecognizer.schema, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.main.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Startup.cs, samples/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs, samples/Microsoft.Bot.Builder.TestBot.Json/appsettings.json, samples/Microsoft.Bot.Builder.TestBot.Json/luconfig.json, samples/Microsoft.Bot.Builder.TestBot.Json/models.config, samples/Microsoft.Bot.Builder.TestBot.Json/models/tomlm/westus/ToDoLuis.en-us.lu.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/models/tomlm/westus/ToDoLuis.lu.dialog, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceExplorerTests.cs
so that we can bring in the environment folder output by LUBuild
change testbot to use models output of LUBuild
=> Change ResourceExplorer to allow ignoring of folders 

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/DeclarativeTypeLoader.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resolvers/IdRefResolver.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FileResource.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProvider.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/IResource.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/IResourceProvider.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LGLanguageGenerator.cs, samples/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceExplorerTests.cs
- IResource, IResourceProvider gives parity with being able to run bots in non-file system based enviroments such as web browser based bots.
=> Switch back to IResource model for parity with javascript 

libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
=> Expression: Support JToken 

libraries/Microsoft.Bot.Builder.Expressions.Parser/Expression.g4, libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs, libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
In this pr. two things were updated:
1. Add +- operator, we can use `-1` to get negative one, and `+1` to get positive one.
2. re-discuss the number of parameters of some functions. 
In this pr, I changed the parameters number as below:
- add: >=2
- sub: >=2
- mul: >=2
- div: >=2
- power: >=2
- min: >=1
- max: >=1
=> Expression: Add +- operators and re-discuss the number of parameters

libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/GetMethodExtensions.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
1. Add json test ,with same test data and test case of object
2. fix the below issue: 
```
var k = new JObject();// JObject  object
var isList = k is IList list; // true
```
In the case of this project, JObject should not be parsed to list
=> Add json test and fix IList bug

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputWrapper.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/NumberInput.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContextState.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/04 - TextInput/NumberInput.main.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/04 - TextInput/TextInput.main.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/AddToDo.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
1. add a HasValue function to avoild get the default(T) for bool and numbers. We don't need alwaysPrompt any more.
2. fix NumberPrompt accept non-number and set as 0 bug.
3. Added NumberInput tests
4. Re-enable todo bot test.
#1699 #1703
=> fix Inputs Bugs

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.RepeatDialog.schema, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogCommand.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/04 - TextInput/NumberInput.main.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/14 - RepeatDialog/RepeatDialog.main.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/15 - TraceAndLog/TraceAndLog.main.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/app.schema, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
- fix float bug with 4.4
- fixed repeatdialog to not go into infinite loop
- added sample.dialog files for RepeatDialog, TRace, Log, etc.
- added unit tests which test them
- added missing schema fiels
- updated schema
=> Misc schema/samples/unit tests cleanup 

Directory.Build.props, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugAdapter.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/package.json, libraries/Microsoft.Bot.Builder/Integration/BotFrameworkOptions.cs, samples/Microsoft.Bot.Builder.TestBot.Json/.vscode/launch.json, samples/Microsoft.Bot.Builder.TestBot.Json/Startup.cs
went from 100 lines of crazy dependency injection to 4 lines.
=> cleanup debug

libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/GetMethodExtensions.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/analyzer.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/ConditionFormatError.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
Increase test coverage to 90% ~ 95% (Except for generated code)
=> LG & Expression: Add more tests

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs
=> ComponentDialog: restore virtual OnBeginDialogAsync and make overridable methods virtual

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.SwitchCondition.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SwitchCondition.cs, samples/Microsoft.Bot.Builder.TestBot.Json/app.schema, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
```cs
new SwitchCondition()
{
Condition = "user.name",
Cases = new List<Case>()
{
new Case("'susan'", new List<IDialog>() { new SendActivity("hi susan") } ),
new Case("'bob'", new List<IDialog>() { new SendActivity("hi bob") } ),
new Case("'frank'", new List<IDialog>() { new SendActivity("hi frank") } )
},
Default = new List<IDialog>() { new SendActivity("Who are you?") }
},
```
=> Change Switch to be array of cases instead of dictionary

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/WaterfallDialog.cs
=> ComponentDialog: Fix nested componentDialog functionality + typos + cleanup

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.CancelAllDialogs.schema, samples/Microsoft.Bot.Builder.TestBot.Json/app.schema
=> CancelAllDialogs had extra properties

libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/IntentRule.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/UnknownIntentRule.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EditArray.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EndDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/HttpRequest.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/InitProperty.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/LogStep.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SaveEntity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SendActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContextState.cs, libraries/Microsoft.Bot.Builder.Dialogs/ObjectExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs, samples/Microsoft.Bot.Builder.TestBot.Json/readme.md, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/DialogContextStateTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
- add TryGetValue
- change HasValue and GetValue to use TryGetValue
- change GetValue to throw if value not there
- Consolidate GetValue/TryGetValue/HasValue as object extensions
- Fix Prompt to use validator to validate that value is there and valid (fixing numberPrompt to not need AlwayPrompt)
=> Change GetValue to use TryGetValue() and throw if value is not there

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/10 - ChoiceInput/ChoiceInput.main.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.AddItem.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.DeleteItem.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.ShowItems.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
- Change ChoiceInput to return Value instead of FoundChoice object.
- updated unit tests and dialog files
#1781
=> [Adaptive] [DCR] Choice input should just return 'value' and not the full object it returns now

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BaseInvokeDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SaveEntity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SetProperty.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SwitchCondition.cs, libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs, samples/Microsoft.Bot.Builder.TestBot.Json/Program.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MiscTests.cs
misc bug fixes
- added/fixed computeIds for steps
- Prompt retry set to false  instead of retry:true
- fixed duplicate registration of steps.dialogs
=> SaveEntity forces plan.nextStep to restart

samples/declarative-hack-April-11-README.md
No need to merge this - these are just for the hack. 
Updates hack notes
=> [DO NOT MERGE] Update notes for Declarative hack April 25th

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
=> Cancellation: Temporary fix to only continue recursion when parent exists

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs
=> fix none score for regex none to 1.0

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs, libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs, samples/Microsoft.Bot.Builder.TestBot.Json/BotBuilderTestBot.bot, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MiscTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/RecognizerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/SelectorTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
This surfaced with the behavior of IfCondition while there was an active input.
- Added unit test
- Added port of typescript logic to C# 
- (incidently) cleaned up all of our CreateTestFlow() methods to user new .UseXXX()
=> AdaptiveDialog consultation processing was out of sync with js

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SaveEntity.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MiscTests.cs
=> allow @ in entity name

libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileParser.g4, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/BasicList.lg
=> Lg: Bug fix: LG parser doesn't allow white space between IF and :

samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.AddItem.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.DeleteItem.dialog, samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.ShowItems.dialog
1. Remove useless set property step in this sample.
2. Add list name confirmation.
=> Sample Bots: Fix to do luis bot

libraries/Microsoft.Bot.Builder/Inspection/InspectionMiddleware.cs
- add trim to text in message for inspect command processing
=> fixed issues form testing with Teams

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/DateTimeInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/NumberInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/TextInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/CodeStep.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/DebugBreak.cs
=> Input controls are missing debug annotations for debugging code dialogs

Microsoft.Bot.Builder-Standard.sln, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugTransport.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs, samples/Microsoft.Bot.Builder.TestBot.Json/.vscode/launch.json, samples/Microsoft.Bot.Builder.TestBot.Json/Program.cs, samples/Microsoft.Bot.Builder.TestBot.Json/TestBotLG.cs, samples/Microsoft.Bot.Builder.TestBot.Json/appsettings.Development.json, samples/Microsoft.Bot.Builder.TestBot.Json/appsettings.json, samples/Microsoft.Bot.Builder.TestBot.Json/luis.settings.tom.json, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Composition.Tests/Microsoft.Bot.Builder.Dialogs.Composition.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/.vscode/tasks.json, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceExplorerTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs, tests/Microsoft.Bot.Builder.Tests/TranscriptUtilities.cs, tests/Microsoft.Bot.Configuration.Tests/ConfigurationLoadAndSaveTests.cs, tests/Microsoft.Bot.Configuration.Tests/ConnectionTests.cs, tests/Microsoft.Bot.Connector.Tests/AttachmentsTests.cs, tests/Microsoft.Bot.Connector.Tests/OAuthConnectorTests.cs
- case needs to be correct
- separator chars need to be correct
- reading project files need to translate paths
=> All unit tests build and pass on linux

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/EventRule.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/IntentRule.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/Rule.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SendActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/CodeModel.cs, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugAdapter.cs, libraries/Microsoft.Bot.Builder.Dialogs/IItemIdentity.cs
Sample output
```
Set breakpoints for AddToDo.dialog
Set breakpoints for Steps.main.dialog
Set breakpoint at SendActivity(Step 1)
Set breakpoint at SendActivity(Step 2)
Set breakpoint at SendActivity(Step 3)
Set breakpoints for ToDoBot.main.dialog
Set function breakpoints.
conversationUpdate ==> Started
conversationUpdate ==> Exited
conversationUpdate ==> Started
conversationUpdate ==> Exited
'what can I do with...' ==> Started
'what can I do with...' ==> consultDialog    ==> AdaptiveDialog(TestBot.cs:54)
Set breakpoint at SaveEntity(title)
Set breakpoint at IfCondition((user.todos == null)|InitProperty[$user.todos])
Set breakpoint at InitProperty[$user.todos]
Set breakpoint at RegexRecognizer
Set breakpoint at IntentRule(AddIntent)[]
Set breakpoint at IntentRule(DeleteIntent)[]
Set …
```
=> Cleanup debugger logging

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/8.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
Fix https://github.com/Microsoft/botbuilder-dotnet/issues/1845
=> LG: Fix default scope is not passed with lgTemplate

libraries/Microsoft.Bot.Builder/Inspection/InspectionSession.cs, libraries/Microsoft.Bot.Builder/Inspection/InterceptionMiddleware.cs
- (improved) warning message when runtime fails to connect to sidecar emulator
- order of events - attempt to send state last
=> improved error message for connection failure and order of state trace

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptValidatorContext.cs
Fixes: https://github.com/Microsoft/botbuilder-dotnet/issues/1859
=> Another instance of Convert.Int32

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptValidatorContext.cs
Fixes: https://github.com/Microsoft/botbuilder-dotnet/issues/1859
=> Cherry Pick 97cd740bc8bfdf4dbbf0647e9abf7c3e43fdf730 (cosmos cast issue)

libraries/Microsoft.Bot.Builder.LanguageGeneration.GrmCheckers/GrammarChecker.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/GrammarCheckerTests.cs
add cortana-style grammar checker and test
=> update grammar checker

libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/Microsoft.Bot.Builder.Dialogs.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Tests/ReplaceDialogTest.cs
=> Set DialogSet TelemetryClient in Dialog.run extension

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpAdapterTests.cs
- this encapsulates the necessary setup for gov in a new constructor
- this PR so far just contains the dotnet core update
=> additional constructor and unit test

libraries/Microsoft.Bot.Builder.AI.TriggerTrees/Node.cs, libraries/Microsoft.Bot.Builder.AI.TriggerTrees/TriggerTree.cs, tests/Microsoft.Bot.Builder.AI.TriggerTrees.Tests/Tests.cs
Add the ability to remove a trigger.
=> Implement RemoveTrigger for trigger tree

libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/4.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/5.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/analyzer.lg
=> LG: Support @ prefix for expressions

libraries/Microsoft.Bot.Builder/BotState.cs, libraries/Microsoft.Bot.Builder/Inspection/InspectionMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/BotStateTests.cs
- add Get function to BotState for parity with JavaScript
this fixes https://github.com/microsoft/botbuilder-js/issues/896
=> parity with JavaScript

libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
* fix the return value
* add tests
* improve the equal checks in UT
=> [Expression] Fix int() is evaluated to float

libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileParser.g4, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/switchcase.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/SwitchCaseFormatError.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/SwitchCaseWarning.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineThrowExceptionTest.cs
Add SWITCH CASE support in LG and test cases for switch case functions
=> [LG] add switch case support

libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/CaseInsensitive.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
Fixes microsoft/botbuilder-dotnet#1942
=> [LG] ignore case sensitive

libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, libraries/Microsoft.Bot.Builder.Expressions/ExpressionType.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Add R2 functions in collections and conversions:
Here is a list of functions added this time:
Array, Binary, Base64, Skip, Take, SubArray, dataUri related, guid, etc
Also, test cases are added correspondingly, which are the same as those in TS.
=> [Expression] add r2 functions

UsingMyGet.md, tests/Microsoft.Bot.Builder.AI.QnA.Tests/Microsoft.Bot.Builder.AI.QnA.Tests.csproj, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/Microsoft.Bot.Builder.ApplicationInsights.Tests.csproj, tests/Microsoft.Bot.Builder.Azure.Tests/Microsoft.Bot.Builder.Azure.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Tests/ComponentDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/Microsoft.Bot.Builder.Dialogs.Tests.csproj, tests/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.Tests.csproj, tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj, tests/Microsoft.Bot.Builder.Transcripts.Tests/Microsoft.Bot.Builder.Transcripts.Tests.csproj, tests/Microsoft.Bot.Configuration.Tests/Microsoft.Bot.Configuration.Tests.csproj, tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj, tests/Microsoft.Bot.Schema.Tests/Microsoft.Bot.Schema.Tests.csproj, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj, tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/Microsoft.Bot.ApplicationInsights.WebApi.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests.csproj
Updated and consolidated test framework packages.
=> Fixes the daily functional tests

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs
To address bot-docs issue [1193](https://github.com/MicrosoftDocs/bot-docs/issues/1193).
=> Clarify ref docs around `NextAsync`.

libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LGAdapterExtensions.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LanguageGeneratorManager.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/TemplateEngineLanguageGenerator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/TextMessageGeneratorTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Renderer.Tests/LGGeneratorTests.cs
* clean up comments
* refactor constructors
* plumb through resourceLoader so we can support #import for TemplateEngine.
=> Add resourceLoader callback to LanguageGenerators

libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LanguageGenerationRenderer.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LanguageGeneratorManager.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/TemplateEngineLanguageGenerator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFile.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGImport.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGParser.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGSource.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs, samples/Microsoft.Bot.Builder.TestBot.Json/TestBotLG.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineThrowExceptionTest.cs
* changed language of LG engine to minimize dependency on files
* renamed fileResolverDelegate to ImportResolverDelegate
* hooked up resource resolver to template generator
* updated unit tests
=> cleaned up LG Resource import delegate and hooked up to resource

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Choice.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactoryOptions.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceRecognizers.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/Find.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/FindChoicesOptions.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/FindValuesOptions.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/FoundChoice.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/FoundValue.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/ModelResult.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/Token.cs, libraries/Microsoft.Bot.Builder.Dialogs/Choices/Tokenizer.cs
Pull in missing content from the equivalent JavaScript ref docs.
=> Update docXML comments in Dialogs.Choices folder

CodeCoverage.runsettings
Add the new .Testing DLL to the list of projects against which Code Coverage is tested.
=> Add new Testing library to Code Coverage Metrics

libraries/Microsoft.Bot.Configuration/BotConfiguration.cs, libraries/Microsoft.Bot.Configuration/Services/AppInsightsService.cs, libraries/Microsoft.Bot.Configuration/Services/AzureService.cs, libraries/Microsoft.Bot.Configuration/Services/BlobStorageService.cs, libraries/Microsoft.Bot.Configuration/Services/BotService.cs, libraries/Microsoft.Bot.Configuration/Services/ConnectedService.cs, libraries/Microsoft.Bot.Configuration/Services/CosmosDbService.cs, libraries/Microsoft.Bot.Configuration/Services/DispatchService.cs, libraries/Microsoft.Bot.Configuration/Services/EndpointService.cs, libraries/Microsoft.Bot.Configuration/Services/FileService.cs, libraries/Microsoft.Bot.Configuration/Services/GenericService.cs, libraries/Microsoft.Bot.Configuration/Services/LuisService.cs, libraries/Microsoft.Bot.Configuration/Services/QnAMakerService.cs, libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConfiguration.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetrySaveBodyASPMiddleware.cs, tests/Microsoft.Bot.Builder.TestBot/Dialogs/MainDialog.cs, tests/Microsoft.Bot.Builder.TestBot/Startup.cs, tests/Microsoft.Bot.Configuration.Tests/ConnectionTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/TestConfigurationRetriever.cs
- Add/remove spacing
- Separate _TestConfigurationRetriever_ class to its own file
- Fix field accessors
- Fix upper/lowercase letters
- Remove unnecessary using statements
- Change file encoding from _UTF-8_ to _UTF-8 with BOM_
=> [StyleCop] Fix all the warnings on Bot.Connector.Authentication.Tests

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, samples/Microsoft.Bot.Builder.TestBot.Json/appsettings.json
=> Adaptive: selector configuration in Begin and Continue dialog for when AddTransient is used

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder/ActivityHandler.cs
Reverts microsoft/botbuilder-dotnet#2117
=> Revert "issue 1960 private to public"

libraries/Microsoft.Bot.Builder.Expressions.Parser/Expression.g4, libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs, libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, libraries/Microsoft.Bot.Builder.Expressions/ExpressionType.cs, libraries/Microsoft.Bot.Builder.Expressions/Extensions.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
1. Convert short hand from identifier to operator
2. fix issue: #1969
=> Refactor Shorthand

libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactoryOptions.cs, libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ActivityPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/AttachmentPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DateTimeResolution.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPromptSettings.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptOptions.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptRecognizerResult.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptValidatorContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/TextPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/NumberPromptTests.cs
Also modified the `NumberPrompt<T>` constructor.
=> Add /// comments to files in the Dialogs.Prompts directory.

libraries/Microsoft.Bot.Builder.Expressions.Parser/Expression.g4, libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs, libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, libraries/Microsoft.Bot.Builder.Expressions/ExpressionType.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
This preserves easy access to the full entity.
=> Add @@ as an alias for a full entity.

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
Fix two issues:
https://github.com/microsoft/botbuilder-dotnet/issues/2119
https://github.com/microsoft/botbuilder-dotnet/issues/1820
Add choice property for getting choices from memory.
=> [Adaptive] Add ChoiceProperty & Fix Issues

libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
Fixes: https://github.com/microsoft/BotBuilder-Samples/issues/1524
=> Remove Microsoft.Extensions.* from integration libraries and downgrade in core

libraries/Microsoft.Bot.Builder/ActivityHandler.cs, tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
Moved this code in from the sample repo.
If we want to take this for 4.5 I can add this to the JS and we can remove the extra code in the sample when  we point the teams sample at 4.5.
=> added MessageReaction to ActivityHandler

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/DirectLineClientTests.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisApplication.cs, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisUtil.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs, libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs, libraries/Microsoft.Bot.Builder/BotAdapter.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/IBotTelemetryClient.cs, libraries/Microsoft.Bot.Builder/IUserTokenProvider.cs, libraries/Microsoft.Bot.Builder/Integration/IAdapterIntegration.cs, libraries/Microsoft.Bot.Builder/TelemetryLoggerConstants.cs, libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs, libraries/Microsoft.Bot.Configuration/BotConfigurationExtensions.cs, libraries/Microsoft.Bot.Connector/Authentication/EndorsementsValidator.cs, libraries/Microsoft.Bot.Connector/OAuthClientOld.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ServiceCollectionExtensions.cs
Fixed some mistakes in comments
=> Fix mistakes in comments

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Schema/ActivityExtensions.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
- change oauth prompt to accepting
- add comment to mention
- disable broken jwt token test (should this even be a unit test?)
=> change oauth prompt to accepting, add comment to mention, disable test

tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
Issue Tracking the "Fixing" of this test is #2213
=> Comment out Code relating to a broken test

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/DateTimeInput.cs
fix the input data source for choice and datetime.
#2215
=> [Adaptive] Fix a bug of inputs

libraries/Microsoft.Bot.Builder.Expressions.Parser/Expression.g4, libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs, libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, libraries/Microsoft.Bot.Builder.Expressions/ExpressionType.cs, libraries/Microsoft.Bot.Builder.Expressions/Extensions.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
=> [Expression] support variable path shorthand

libraries/Microsoft.Bot.Builder.LanguageGeneration/Diagnostic.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/ErrorListener.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/ImportResolver.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGException.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGParser.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGResource.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineThrowExceptionTest.cs
=> Refine static checker

libraries/Microsoft.Bot.Builder.LanguageGeneration/LGTemplate.cs
Fix issue: https://github.com/microsoft/botbuilder-js/issues/986
=> Fix "lg parser unexpected output \r\n <EOF>"

libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/MultiLanguageGeneratorBase.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/ResourceMultiLanguageGenerator.cs
=> Throw error message when generator not found in multi language render

libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LanguageGeneratorManager.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/ImportResolver.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGResource.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/Import/import3.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/import.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
=> Fix ImportResolverDelegate bug

libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
Purely to solve the current problem. 
Fix: #2223
=> Make setProperty case sensitive

libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LanguageGeneratorManager.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Renderer.Tests/Fallback/import.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Renderer.Tests/LGGeneratorTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
=> LG in adaptive dialog don't support imports with relative path

Directory.Build.props
Cherrypick of #2262 from master
=> Point Nuget packages to a valid icon file.

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ComponentDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/CancelAndHelpDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/GetBookingDetailsDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/BookingDialogTestsDataGenerator.cs
Cherry pick of commit 25c95d1 which is PR #2259
=> Reverts PR 1993

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/SequenceContext.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/ForEachPage.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
=> Fix Input Dialog defaultValue issue and ForeachPage Listproperty

libraries/Microsoft.Bot.Builder.StreamingExtensions/Microsoft.Bot.Builder.StreamingExtensions.csproj, tests/Microsoft.Bot.StreamingExtensions.Test/Microsoft.Bot.StreamingExtensions.Tests.csproj
Update the Streaming Extensions to use the 4.5.1 SDK.
=> Update Streaming Extensions to 4.5.1 SDK references

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Builder/BotAdapter.cs, libraries/Microsoft.Bot.Builder/IMiddleware.cs, libraries/Microsoft.Bot.Builder/ITurnContext.cs, libraries/Microsoft.Bot.Builder/ITurnContextExtensions.cs, libraries/Microsoft.Bot.Builder/Integration/BotFrameworkOptions.cs, libraries/Microsoft.Bot.Builder/Integration/IAdapterIntegration.cs, libraries/Microsoft.Bot.Builder/MemoryTranscriptStore.cs, libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs, libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs, libraries/Microsoft.Bot.Connector/OAuthClientOld.cs, tests/Microsoft.Bot.Builder.TestBot.Tests/Framework/SimpleMockFactory.cs, tests/Microsoft.Bot.Builder.TestBot.WebApi/Bots/DialogBot.cs, tests/Microsoft.Bot.Builder.TestBot/Bots/DialogBot.cs, tests/Microsoft.Bot.Builder.Tests/Adapters/TestAdapterTests.cs, tests/Microsoft.Bot.Builder.Tests/BotStateTests.cs, tests/Microsoft.Bot.Builder.Tests/SimpleAdapter.cs, tests/Microsoft.Bot.Builder.Tests/TurnContextTests.cs
=> Fix misspellings

libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/EvalExpression.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
=> fix @{expression} in LG does not get the expected results

libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs, libraries/Microsoft.Bot.Builder/ITurnContext.cs, libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
- update ConnectorClient.cs
- update ITurnContext.cs
=> Add, review and revise /// comments

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogTurnStatus.cs, libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs
with minor incidental updates to DialogTurnStatus.
=> Update /// comments for WaterfallStepContext and DialogContext

libraries/Microsoft.Bot.Schema/ActivityEx.cs, libraries/Microsoft.Bot.Schema/ITraceActivity.cs
- Updated `ITraceActivity` to keep descriptions in sync.
=> Update the Activity class /// comments

libraries/Microsoft.Bot.Builder.Dialogs/LanguagePolicy.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/RecognizerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
First response to this bug: https://github.com/microsoft/BotFramework-Emulator/issues/1668.
However, we are waiting for more repro steps to be 100% sure that nothing else is needed to unblock that bug.
=> Adaptive: Ignore casing on locale + tests

libraries/Microsoft.Bot.Builder.AI.LuisV3/LuisPredictionOptions.cs, libraries/Microsoft.Bot.Builder.AI.LuisV3/LuisRecognizer.cs, tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/Microsoft.Bot.Builder.AI.LuisV3.Tests.csproj
Fix XML comments and switch log to allow defaulting to Luis setting.
=> Remove unneeded dependency to fix build break.

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/AttachmentInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/DateTimeInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/NumberInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/TextInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.TextInput.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/baseInputSchema.json, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MiscTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs, tests/Microsoft.Bot.Builder.TestBot.Json/Samples/04 - TextInput/TextInput.main.dialog
Fix #2332 
And also fix the turnCount issue.
=> Make allowInterruptions enum

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/Configuration/EnvironmentConfig.cs, FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/GetTokenRefreshTests.cs, FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/JwtTokenExtractorTests.cs, FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/TestConfigurationRetriever.cs
=> FunctionalTests: move JwtTokenExtractor tests to Functional tests and consume app id and password from environment

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.NumberInput.schema, schemas/sdk.schema, tests/Microsoft.Bot.Builder.TestBot.Json/app.schema
=> fix typo in schema

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Events/OnIntent.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs, libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs, libraries/Microsoft.Bot.Builder.Expressions/ExpressionType.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/EventTests.cs, tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Bug : #2354 
* fix exists() to work with any object (array or object)
* added unit tests
=> fix OnIntent Entities constraint

tests/Microsoft.Bot.Builder.TestBot.Tests/Microsoft.Bot.Builder.TestBot.Tests.csproj, tests/Microsoft.Bot.Builder.TestBot.WebApi/Web.config, tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj, tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/Microsoft.Bot.ApplicationInsights.WebApi.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/app.config
This PR updates some package dependencies such that unit tests pass on a fresh machine.
=> updating packages to enable tests to pass

libraries/Microsoft.Bot.Builder.LanguageGeneration/ErrorListener.cs
fix line number error in errorListener. line number should start from 1
=> [LG] fix line number error in errorListener

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioHelper.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/Microsoft.Bot.Builder.Adapters.Twilio.Tests.csproj
Broken on internalsvisibleto. https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=75247&view=results
...from PR [Botkit] Add Twilio adapter port #2290.
https://github.com/microsoft/botbuilder-dotnet/pull/2290
=> Fix signing build BotBuilder-DotNet-Signed-daily #190814-1

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
=> map adaptive card value submission into -> intent/entities

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/baseInputSchema.json, schemas/sdk.schema, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.TestBot.Json/app.schema
Implementation of DCR #2422 
DefaultValueResponse is template to send if you have MaxTurnCount and it has been exceeded.
=> Add DefaultValueResponse property to InputDialog

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs
=> move emit Activity into dialogContext so it works with old dialog pumps

libraries/Microsoft.Bot.Builder.AI.QnA/Models/QnAMakerTraceInfo.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerOptions.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
Addition of a new optional parameter (qnaId) in GenerateAnswer body.
- Support for QnA Id added 
Test case added
=> [QnA Maker] multi-turn SDK support for QnAID

libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs
ComponentDialog.cs tried to access `PersistedDialogState` directly in three places without using `TryGetValue` or checking to see if the key is present. This can generate a cryptic "The given key was not present in the dictionary" exception in certain cases: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/148
We may have been confident that the key would always be present because it's initialized in `ComponentDialog.BeginDialogAsync`. However, consider these possibilities:
1. `BeginDialogAsync` is overridden
2. `PersistedDialogState` is deleted
If we do want to throw an exception then it should be more explanative. However, I opted to not throw an exception at all by just accounting for situations when the key isn't present.
=> Fix PersistedDialogState

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs, libraries/Microsoft.Bot.Connector/Authentication/MicrosoftGovernmentAppCredentials.cs, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
Ran performance analysis over load testing to verify performance is not affected by this change under load.
=> Authentication: Change Semaphore to SemaphoreSlim, improve logging and error handling

CodeCoverage.runsettings, Microsoft.Bot.Builder.sln, libraries/Microsoft.Bot.Builder.Teams/Class1.cs, libraries/Microsoft.Bot.Builder.Teams/Microsoft.Bot.Builder.Teams.csproj, libraries/Microsoft.Bot.Connector.Teams/Class1.cs, libraries/Microsoft.Bot.Connector.Teams/Microsoft.Bot.Connector.Teams.csproj, libraries/Microsoft.Bot.Schema.Teams/Microsoft.Bot.Schema.Teams.csproj, libraries/Microsoft.Bot.Schema.Teams/Placeholder.cs
This PR adds 3 (currently empty) projects:
1. Microsoft.Bot.Builder.Teams
2. Microsoft.Bot.Connector.Teams
3. Microsoft.Bot.Schema.Teams
Each of these projects is configured for Stylecop and FxCop. Each one emits a (currently empty NuGet package, and has all the proper signing properties and properties set. 
Next up, as part of this PR, is to make sure the CI system builds them and pushes the NuGet packages out to MyGet.
=> Initial pass of adding the Teams packages into the build.

libraries/Microsoft.Bot.Schema/ActivityExtensions.cs, tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs
Fixing the bug here:
https://github.com/microsoft/botbuilder-dotnet/issues/2504
=> updating mention stripping scenario for Teams

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs
Close #2102
* concat Attachments if exist in Prompt::AppendChoices
- if it is carousel AttachmentLayout, it will be weird..
* add test ShouldSendPromptUsingAppendedHeroCard
=> Concat Attachments if exist in Prompt::AppendChoices

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnCancelDialog.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnError.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnRepromptDialog.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnBeginDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCancelDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCondition.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnConversationUpdateActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCustomEvent.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnDialogEvent.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnEndOfConversationActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnError.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnEventActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnHandoffActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnIntent.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnInvokeActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnMessageActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnMessageDeleteActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnMessageReactionActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnMessageUpdateActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnRepromptDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnTypingActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnUnknownIntent.cs, schemas/sdk.schema, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ConditionalsTests.cs, tests/Microsoft.Bot.Builder.TestBot.Json/CustomSteps/MultiplyDialog.cs, tests/Microsoft.Bot.Builder.TestBot.Json/TestBotHttpAdapter.cs, tests/Microsoft.Bot.Builder.TestBot.Json/app.schema
DialogEvents has CancelDialog, RepromptDialog and Error events, so added On conditionals for those and unit tests
Cleaned up verbage in comments.
=> Add OnCancelDialog, OnRepromptDialog, OnError

libraries/Microsoft.Bot.Builder.Teams/TeamsActivityHandler.cs, tests/Microsoft.Bot.Builder.Teams.Tests/TeamsActivityHandlerTests.cs
Add composeExtension/onCardButtonClicked
BotMessagePreviewAction.submit to .send (there is no submit)
=> Add Teams composeExtension/onCardButtonClicked

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.InputDialog.json, schemas/sdk.schema, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.TestBot.Json/app.schema
=> Bring back Value property back to InputDialogs

tests/Teams/ActionBasedMessagingExtension-FetchTask/AdaptiveCardHelper.cs, tests/Teams/ActionBasedMessagingExtension-FetchTask/Bots/ActionBasedMessagingExtensionFetchTaskBot.cs, tests/Teams/ActionBasedMessagingExtension-FetchTask/CardResponseExtentions.cs, tests/Teams/ActionBasedMessagingExtension-FetchTask/SubmitExampleData.cs, tests/Teams/ActionBasedMessagingExtension-FetchTask/TeamsAppManifest/manifest.json
Add OnTeamsMessagingExtensionBotMessagePreviewSendAsync 
and OnTeamsMessagingExtensionBotMessagePreviewEditAsync 
to ActionBasedMessagingExtensionFetchTaskBot
Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/2619
=> [Teams] Messaging Extension Preview Send/Edit

recognizers-text/Utterance Changes/Differences.md
New documentation to the Readme file was added in order to make the purpose of the folder more clear.
=> Add description to Recognizers-Text folder Readme

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.HttpRequest.schema, schemas/sdk.schema
- Updating HttpRequest action schema to include all supported methods
=> Update schema to reflect supported http methods

libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/PathResolvers/AtPathResolver.cs, libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs
#2663 
Change @ to resolve to turn.recognized.entities.first() and added a first() which tries [0][0] and then fallsback to [0]
=> fix @ to resolve to first of array or first of array o arrays

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ActivityGenerator.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/MessageGeneratorTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/microsoft.bot.builder.dialogs.adaptive.templates.tests.csproj
=> Fix Structure LG+ ActivityGenerator should work without Adaptive issue

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperty.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
- Removed SetProperty hack to clear dialog stack.
- Corrected logic for what gets evaluated for users input.
- Tweak to the way interruptions are handled.
- Updated unit tests.
=> Reworked InputDialogs core processing flow

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EndDialog.cs
=> remove old ctor parameter which is not used anymore

libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/ErrorStructuredTemplate.lg
=> fix structured-lg static checker

libraries/Microsoft.Bot.Builder.AI.QnA/IQnAMakerClient.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerActionBuilder.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerDialog.cs
By introducing a new IQnaMakerClient interface
=> [DO NOT MERGE] QnAMaker: decouple QnaMakerDialog from the QnaMaker client

libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/2.lg
=> add in-template comment support

libraries/Microsoft.Bot.Builder.AI.QnA/Models/QnAResponseContext.cs, libraries/Microsoft.Bot.Builder.Ai.QnA/Models/QnaMakerPrompt.cs
=> QnaMaker: rename Prompt -> QnaMakerPrompt

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ActivityGenerator.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/MessageGeneratorTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/NormalStructuredLG.lg
=> Make card/activity type insensitive in structured lg

libraries/Microsoft.Bot.Builder.LanguageGeneration/CustomizedMemoryScope.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/LoopScope.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
=> Fix loop serializer loop issue

libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs
=> Fix the issue of object clone

tests/Teams/Scenarios.sln
Add missing dependency to `Microsoft.Bot.Streaming` package.
=> Add missing reference to scenarios

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/TemplateEngineLanguageGenerator.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LGAdapterExtensions.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/MessageGeneratorTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/test.en.lg, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/test.fr.lg, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/test.lg, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/test.zh-cn.lg, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
=> Add multi language support in LG import

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs/Constants/TurnPath.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
fixes #2567 
Add turn.activityProcessed which is set by an input when it uses the activity.
added unit test from bug report
=> Add turn.activityProcessed to input dialogs

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.InputDialog.json, schemas/sdk.schema, tests/Microsoft.Bot.Builder.TestBot.Json/app.schema
fixes #2592 
Forgot to update the schema files for the new property.
=> update schema for value property on InputDialogs

libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/StructuredTemplate.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
Support to expand structured lg in expand function
=> support to expand structured lg

libraries/Microsoft.Bot.Builder.AI.QnA/Utils/ActiveLearningUtils.cs
Active learning low score variation multiplier value
- PreviousLowScoreVariationMultiplier to 0.7
- MaxLowScoreVariationMultiplier to 1.0
=> [QnAMaker] Active learning low score variation multiplier value

libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/ErrorStructuredTemplate.lg
Allow structured type to be limited to these characters：
```
letter
number
-
_
.
```
=> Add structured type check

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptTests.cs
Fix bug in confirm prompt to ensure it respects style setting in prompt options sent via PromptAsync
=> Fix bug in confirm prompt to ensure it respects style setting

libraries/Microsoft.Bot.Builder.Skills/Adapters/BotFrameworkSkillHostAdapter.cs, libraries/Microsoft.Bot.Builder.Skills/Integration.AspNet.Core/BotFrameworkHttpSkillsServer.cs, libraries/Microsoft.Bot.Builder.Skills/SkillHostAdapter.cs, tests/Microsoft.Bot.Builder.Skills.Tests/Integration.AspNet.Core/BotFrameworkHttpSkillsServerTests.cs, tests/Microsoft.Bot.Builder.Skills.Tests/Microsoft.Bot.Builder.Skills.Tests.csproj, tests/Microsoft.Bot.Builder.Skills.Tests/SkillAdapterTests.cs
* Fix InvokeResponse bug
* Fix Activity Clone on forward bug
* Signature changes requested by PowerVA
* new unit tests
=> Cherry pick PR# 2926 Skills fixes from master

libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs
=> pass on cancellation

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ActivityFactory.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj
=> remove adaptivecard package from LG

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexHelper.cs
Fixed "The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')" issue
=> Fixed unit tests fails

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
Looks like GetActiveDialogState(...) is never used.
=> Removed unused code

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookEntry.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookResponseEvent.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Message.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookAdapterTests.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/Microsoft.Bot.Builder.Adapters.Slack.TestBot.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft.Bot.Builder.Adapters.Slack.Tests.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/TwilioAdapterTests.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Microsoft.Bot.Builder.Adapters.Webex.Tests.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexAdapterTests.cs
- Added ILogger to each adapter
- Replace exception thrown when sending non-message activities with a call to LogTrace
- Fixed warnings in Facebook adapter
=> Adapter updates ahead of GA

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EmitEvent.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.EmitEvent.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Templates/Microsoft.StaticActivityTemplate.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnRepromptDialog.schema, schemas/sdk.schema, tests/Microsoft.Bot.Builder.TestBot.Json/app.schema
Microsoft.OnRepromptDialog.schema:
ReprmptDialog -> RepromptDialog
Microsoft.StaticActivityTemplate.schema:
This allows you to defina static Activity object -> This allows you to define a static Activity object
Fixed EmitEvent, code and schema not aligned issue. and support eventValue as an expression.
=> Fix schema typo + Fix EmitEvent code and schema not aligned

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptCultureModels.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs
[related PR](https://github.com/microsoft/botbuilder-dotnet/pull/2960)
=> Choice/Confirm Prompt Null locale cherry pick from 4.6 to Master

.github/workflows/stale-issues.yml
The action this calls is here: https://github.com/actions/stale
=> Set up a stale issues github action

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.Testing/Microsoft.Bot.Builder.Testing.csproj, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, libraries/Microsoft.Bot.Expressions/Microsoft.Bot.Expressions.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/Microsoft.Bot.Builder.Adapters.Facebook.Tests.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft.Bot.Builder.Adapters.Slack.Tests.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/Microsoft.Bot.Builder.Adapters.Twilio.Tests.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Microsoft.Bot.Builder.Adapters.Webex.Tests.csproj, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Microsoft.Bot.Builder.AI.Luis.Tests.csproj, tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/Microsoft.Bot.Builder.AI.LuisV3.Tests.csproj, tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/Microsoft.Bot.Builder.ApplicationInsights.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/microsoft.bot.builder.dialogs.adaptive.templates.tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests.csproj, tests/Microsoft.Bot.Builder.Dialogs.Tests/Microsoft.Bot.Builder.Dialogs.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.Skills.Tests/Microsoft.Bot.Builder.Skills.Tests.csproj, tests/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj, tests/Microsoft.Bot.Builder.TestBot/Microsoft.Bot.Builder.TestBot.csproj, tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj, tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj, tests/Microsoft.Bot.Expressions.Tests/Microsoft.Bot.Expressions.Tests.csproj, tests/Microsoft.Bot.Streaming.Tests/Microsoft.Bot.Streaming.Tests.csproj, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj, tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/Microsoft.Bot.ApplicationInsights.WebApi.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests.csproj, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests.csproj
Also upgrade recognizers to latest
=> Consolidate most nuget packages

libraries/Microsoft.Bot.Builder/Inspection/InspectionMiddleware.cs
=> make inspection middleware inspect bot traffic within a team

tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/MessageGeneratorTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/NormalStructuredLG.lg
A common dynamic generation scenario.
=> [Lg] TestMultiExternalAdaptiveCardActivity

libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs, prototypes/DialogToDialog/DialogChildBot/Bots/SkillBot.cs, prototypes/skill-manifest-schema-1-0-0.json
Add maxLength to string fields, and add activityBase for csharp codegen to produce good code
=> Skill manifest schema suggestions

tests/Microsoft.Bot.Streaming.Tests/Mocks/MockPayloadSender.cs, tests/Microsoft.Bot.Streaming.Tests/WebSocketTransportTests.cs
Fixes #2848
Minor cleanup of warnings and using statements.
=> Fix Warnings in Streaming Tests Codebase

doc/CommonExpressionLanguage/prebuilt-functions.md, doc/CommonExpressionLanguage/readme.md
Array and object are not supported to be used directly.
=> [Docs] fix Explanation

libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs, prototypes/DialogToDialog/DialogChildBot/Bots/SkillBot.cs, prototypes/skill-manifest-schema-1-0-0.json
Reverts microsoft/botbuilder-dotnet#3016
=> Revert "Skill manifest schema suggestions"

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
=> rename internal property to _adaptive

libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs, libraries/Microsoft.Bot.Expressions/BuiltInFunctions.cs, libraries/Microsoft.Bot.Expressions/Memory/SimpleObjectMemory.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/MemoryAccess.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs, tests/Microsoft.Bot.Expressions.Tests/ExpressionEngineTests.cs
Add some test cases to demonstrate the new approach of memory access, ie "accumulating the path as long as possible and ask the memory once".
=> Add tests around memory access path

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ActivityChecker.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ActivityFactory.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/MessageGeneratorTests.cs
extract lgtype and fix escape issue
=> fix escape issue and extract magic code

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/DialogManager.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/DialogContextExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/DialogStateManager.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/DialogStateManagerConfiguration.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/BotStateMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/ClassMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/ConversationMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/MemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/UserMemoryScope.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogStateManagerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs
* Add DialogStateManagerConfiguration so memory scopes are not globally static
* Add async methods to properly load/save BotState based memory scopes.
=> Make DialogStateManager  non-static configurable and async load/save

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_TextInputWithValueExpression.test.dialog
=> support InputDialog.value as an expression

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs
Report error message when importResolver failed to resolve.
=> Report error message when importResolver failed to resolve.

libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/QnAMaker/QnAMakerDialog2.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.QnAMakerDialog.schema, schemas/sdk.schema, tests/Microsoft.Bot.Builder.TestBot.Json/app.schema
schema and comment updates for #2910
=> update schema for strictFilters (and add missing top property)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCondition.cs, libraries/Microsoft.Bot.Builder.Dialogs/Debugging/SourcePoint.cs, libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs
this allows you to inspect object in debugger and see where it came from
=> add source location property to dialogs and triggers

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/RepeatDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveTests/AdaptiveDialog_BindingOptionsAcrossAdaptiveDialogs/AdaptiveDialog_BindingOptionsAcrossAdaptiveDialogs.AgeDialog.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveTests/TestBindingTwoWayAcrossAdaptiveDialogs.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveTests/TestBindingTwoWayAcrossAdaptiveDialogsDefaultResultProperty.test.dialog
=> Change AdaptiveDialog to options as the initial state

libraries/Microsoft.Bot.Builder.AI.LUIS/V3/LuisRecognizer.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/BotStateMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/ConversationMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/MemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/UserMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Testing/TestScript.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ServiceCollectionExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot/Startup.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Startup.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/Startup.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.TestBot/Startup.cs, tests/Microsoft.Bot.Builder.Skills.Tests/Skills.Tests/ChannelApiMiddlewareTests.cs, tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterOAuthTests.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/FauxSock.cs
=> clean up misc warnings..

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperties.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperty.cs
Bug #2678 
If value expression fails on set property we should throw exception
=> throw on expression error for set property value

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/QnAMaker/QnAMakerDialog2.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.QnAMakerDialog.schema, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/QnAMakerUtils/MockQnAMakerClient.cs
upport for Ranker type and IsTest in Adaptive and Composer.
=> [QnAMaker] Support for Ranker type and IsTest in Adaptive and Composer.

tests/Microsoft.Bot.Builder.TestBot.Json/Samples/BugRepo/AskForName.dialog, tests/Microsoft.Bot.Builder.TestBot.Json/Samples/BugRepo/BugRepo.main.dialog, tests/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
Is this the correct way to use now?
=> add resultProperty

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/ConditionalSelector.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/MostSpecificSelector.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/TrueSelector.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/SelectorTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/SelectorTests/SelectorTests_ConditionalSelector.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/SelectorTests/SelectorTests_TrueSelector.test.dialog
Also a bug and just kill time..
=> add Conditional/True selector tests

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/InTemplate.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/IsTemplate.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
=> add IsTemplate function

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
=> Sets CallerId on outgoing activities from the skill

libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Utils/QnACardBuilder.cs
No Match prompt removed 
Markdown support
=> [QnA Maker] No Match prompt removed and markdown support.

build/yaml/botbuilder-dotnet-ci-mac.yml, build/yaml/botbuilder-dotnet-ci.yml, build/yaml/botbuilder-dotnet-sign.yml
=> Clean up YAML build scripts

libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs, tests/Microsoft.Bot.Builder.Tests/Adapters/TestFlowTests.cs
To make sure the bot really ends.
Unexpected replies once happend in VA-Skill interactions in solutions project.
=> add TeatFlow.AssertNoReply and tests

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ActivityChecker.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ActivityFactory.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/MessageGeneratorTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests.csproj
=> support lg output in activityfactory directly

Changes.md, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggerSourceMap.cs
Will the extension be open sourced?
=> change to start <= line <= end

libraries/Microsoft.Bot.Schema/ActivityExtensions.cs
=> Updating mention stripping scenario for Teams with special character support

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnIntent.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionScopeTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionScopeTests/ActionScope_Goto_OnIntent.test.dialog
Change to the base implementation.
=> Fix OnIntent with ActionScope_Goto_OnIntent test

build/yaml/functional-test-setup2-steps.yml
This fixes the 2nd of 2 files. First was fixed in #3224
=> Second file: Add argument "--framework netcoreapp3.0" to Create PublishedBot.zip

libraries/Microsoft.Bot.Configuration/BotConfiguration.cs, libraries/Microsoft.Bot.Configuration/BotConfigurationExtensions.cs, libraries/Microsoft.Bot.Configuration/EncryptUtilities.cs, libraries/Microsoft.Bot.Configuration/ServiceTypes.cs, libraries/Microsoft.Bot.Configuration/Services/AppInsightsService.cs, libraries/Microsoft.Bot.Configuration/Services/AzureService.cs, libraries/Microsoft.Bot.Configuration/Services/BlobStorageService.cs, libraries/Microsoft.Bot.Configuration/Services/BotService.cs, libraries/Microsoft.Bot.Configuration/Services/ConnectedService.cs, libraries/Microsoft.Bot.Configuration/Services/CosmosDbService.cs, libraries/Microsoft.Bot.Configuration/Services/DispatchService.cs, libraries/Microsoft.Bot.Configuration/Services/EndpointService.cs, libraries/Microsoft.Bot.Configuration/Services/FileService.cs, libraries/Microsoft.Bot.Configuration/Services/GenericService.cs, libraries/Microsoft.Bot.Configuration/Services/LuisService.cs, libraries/Microsoft.Bot.Configuration/Services/QnAMakerService.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3188
(also add more specific error message for null region)
=> Add Obsolete attribute to all Microsoft.Bot.Configuration classes

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
=> Applied changes from the 4.7.1 PR

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ChannelServiceController.cs
=> Made ChannelServiceController abstract

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/SlackClientTest.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FileResource.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProvider.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/IResource.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/IResourceProvider.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
* add comments to resource explorer classes
* Fix functional unit tests which are broken local if no environment variable.
=> Make FolderResourceProvider extensions externally onfigurable.

build/yaml/botbuilder-dotnet-ci-slacktest.yml
=> Change Azure Subscription references to var.

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/FacebookChatTests.cs, build/yaml/botbuilder-dotnet-ci-facebook-test.yml
Adds a YAML file to set up a pipeline to run the functional test for Facebook
This pull request depends on the test added in the PR #3250 
We added the file `botbuilder-dotnet-ci-facebook-test.yml` inside the build/yaml folder.
The next steps will guide you through the configuration of a build pipeline based on this YAML file.
- Azure DevOps organization.
- Azure subscription. Required to create and delete Azure resources.
- App registration in [Azure Portal](https://portal.azure.com/), we need its **AppId** and **AppSecret**. More info [here](https://docs.microsoft.com/en-us/graph/auth-register-app-v2).
- Configure an Azure Connection Service (Steps below).
- Create a Facebook application and get the Facebook variables. (Steps below).
For this step, you will need …
=> Add build YAML for Facebook functional test

tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
For https://github.com/microsoft/botbuilder-js/issues/1619
=> Create test for waterfall cancellation telemetry

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/WebexClientTest.cs
This pull request adds the "Adapters" category to the Webex functional tests. 
This change allows executing the functional test without running the adapter's ones. 
- Add Adapters test category
=> [Webex][Functional test] Add "Adapters" Test Category

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.InputDialog.json, schemas/sdk.schema
=> [Adaptive] Updates to description text for inputs

Microsoft.Bot.Builder.Skills.sln
Further streamlining of the Microsoft.Bot.Builder.Skills.sln
=> remove custom adapters from Skills.sln

build/yaml/botbuilder-dotnet-functional-test-linux.yml, build/yaml/botbuilder-dotnet-functional-test-windows.yml
--filter "TestCategory=FunctionalTests&TestCategory!=Adapters"
=> Fix functional tests filter

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ActivityFactory.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/MessageGeneratorTests.cs
ref: #3344
Remove default value when just using the text activity.
=> Remove default value for inputHint from activityFactory

build/yaml/botbuilder-dotnet-sign.yml, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj, libraries/AdaptiveExpressions/AdaptiveExpressions.csproj, libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.ApplicationInsights/Microsoft.Bot.Builder.ApplicationInsights.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj, libraries/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj, libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj, libraries/Microsoft.Bot.Builder.Testing/Microsoft.Bot.Builder.Testing.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj, tests/AdaptiveExpressions.Tests/AdaptiveExpressions.Tests.csproj
This for projects in Microsoft.Bot.Builder.sln.
Ref: Issue #2992
SourceLink has been removed from AdaptiveExpressions.Tests.csproj because that is a test project.
=> Update to Microsoft.SourceLink.GitHub

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj
These 3 packages lack SourceLink. Adding it to them.
=> Add SourceLink to these 3 projects

doc/Build CI/readme.md
This pull request adds the BotBuilder SDK Build Process Documentation. It contains general information about the build process configured for all repositories in the SDK. 
**Table of content**
- Short introduction 
- Build Process Comparison Table
- Pipeline details
The idea is to have an easy to read the documentation of the build process configured in the BotBuilder SDK. Also, it allows the user to have an idea of the parity level between the libraries.
=> [Doc] Add Build Process Documentation

build/yaml/botbuilder-dotnet-ci.yml, build/yaml/ci-test-steps.yml
=> Coveralls fix

build/yaml/botbuilder-dotnet-functional-tests-setup.yml, build/yaml/botbuilder-dotnet-sign.yml, build/yaml/botbuilder-dotnet-simple-build-test.yml
=> Comment out vars that are supposed to be set in azure

libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFile.cs
make some renaming and fix the variable issue.
=> fix LG small issue

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.HttpRequest.schema, schemas/sdk.schema, tests/Microsoft.Bot.Builder.TestBot.Json/app.schema
=> add contentType to HttpAction

libraries/AdaptiveExpressions/ExpressionFunctions.cs, libraries/AdaptiveExpressions/ExpressionType.cs, tests/AdaptiveExpressions.Tests/ExpressionEngineTests.cs
close #3465
close #3462
add new function `flatten` and `unique`
add object support for `indicesAndValues`
=> Add new function in expression

build/yaml/botbuilder-dotnet-functional-test-linux.yml, build/yaml/botbuilder-dotnet-functional-test-windows.yml
For [BotBuilder-DotNet-Functional-Tests-Windows-yaml](https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=834&_a=summary) and [BotBuilder-DotNet-Functional-Tests-Linux-yaml](https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=779&_a=summary)
=> Set up key vault storage for functional test build secrets

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/SlackClientTest.cs, build/yaml/botbuilder-dotnet-ci-slacktest.yml
[BotBuilder-Dotnet-Slack-Functional-Tests-yaml](https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=773&_a=summary)
=> Set up key vault for slack functional tests secrets

libraries/Microsoft.Bot.Builder/ActivityHandler.cs, libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs, tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
fixes #3446 
(duplicate code and new compiler warning introduced with sso fixes)
=> clean up activityhandler and teamsactivityhandler

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisExtensions.cs, tests/Microsoft.Bot.Builder.TestBot.Json/Program.cs, tests/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
TestBot was no longer working because Tom remove the connection to user-secrets.  Added that back in and fixed some other minor issues.
=> Fix issues with TestBot.

libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggerSourceMap.cs, tests/Microsoft.Bot.Builder.TestBot.Json/.vscode/launch.json
fix https://github.com/microsoft/botbuilder-dotnet/issues/3516
=> Fix null reference in debugger

build/yaml/botbuilder-dotnet-ci.yml, build/yaml/ci-test-steps.yml
This renames the var to fit the key vault secret's name.
=> Set up CI build to get coveralls token from key vault

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj
=> Microsoft.Bot.Builder.Dialogs.Adaptive.Testing had release labels for creating nuget

libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs, libraries/Microsoft.Bot.Builder/TurnContext.cs, libraries/Microsoft.Bot.Connector/ConversationsExtensions.cs
Addressing build warnings of type: CS1570: XML comment has badly formed XML.
=> Fix for Issue #3525

libraries/AdaptiveExpressions/parser/ExpressionParser.cs
fix CS3021 warnings refer to https://github.com/tunnelvisionlabs/antlr4cs/issues/10#issuecomment-66999851
close: #3526
=> fix Antler Parser build warnings 

libraries/AdaptiveExpressions/ExpressionFunctions.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Make expression support long type
=> Make expression support long

libraries/Microsoft.Bot.Builder.AI.QnA/Utils/HttpRequestUtils.cs
For supporting QnAMaker V2 integration
=> [QnA Maker] header change for adding "Ocp-Apim-Subscription-Key"

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackPayload.cs
Fixes #3733 #3726 #3725 #3724 
* Adds missing values to SlackPayload model 
* Expose SlackClientWrapper via public property
=> Slack adapter updates for dialog interactions

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
Updates appId argument check in GetAppCredentialsAsync as mentioned in issue #3590
=> Updates appId argument check in GetAppCredentialsAsync #3590

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.OAuthInput.schema, schemas/sdk.schema
=> Fix OAuth bug

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/RepeatDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_RepeatDialog.test.dialog
Pass options as BeginDialog, ReplaceDialog.
Add test to verify options are set.
Related https://github.com/microsoft/BotFramework-Composer/issues/2499
=> fix repeat option

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_Foreach_Empty.test.dialog
=> fix foreach empty and add test case

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/HttpHelper.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/HttpHelperTests.cs
=> Ensure BOM is not written to response body in HttpHelper

.github/CODEOWNERS
Add in initial set of code owners to make Pull Requests and related operations more clear.
=> Add initial code owners to packages

.github/CODEOWNERS
Add me and @chrimc62 as code owners of LG and Expression packages, including tests packages.
=> Code owner update for LG & expression library

libraries/AdaptiveExpressions/ExpressionFunctions.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Fixes: #3762 
Fix checking null value in expression
=> [LG]  fix null check in expression

.github/CODEOWNERS
Update "Bot.BotBuilder" to "Bot.Builder"
=> Fix typo in code owners

libraries/Microsoft.Bot.Configuration/Services/LuisService.cs
Addresses #3583 
Adds a custom endpoint property to the LuisService class, so that a custom endpoint can be set if LUIS is being used within a container.
=> Add custom endpoint property to the LuisService class

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/Skills/SkillHandler.cs, libraries/Microsoft.Bot.Schema/CallerIdConstants.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs, tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs, tests/Microsoft.Bot.Builder.Tests/Skills/SkillHandlerTests.cs
This PR applies the callerID updates from https://github.com/microsoft/botbuilder-dotnet/pull/3753 to the 4.8 branch
=> Applies #3753 to 4.8

libraries/Microsoft.Bot.Builder/TurnContext.cs
Fix typo in TurnContext.DeleteActivityInternalAsync
=> Rename updateHandlers to deleteHandlers 

libraries/Microsoft.Bot.Builder/ActivityHandler.cs, libraries/Microsoft.Bot.Builder/HealthCheck.cs, libraries/Microsoft.Bot.Schema/HealthCheckResponse.cs, libraries/Microsoft.Bot.Schema/HealthResults.cs, tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
healthcheck feature fixes #3313
=> healthcheck feature

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3774
=> Change onTeamsMemberAdded for Teams to use getMember()

libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplatesParser.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/EmptyLGFile.lg
close: #3809
Support empty lg file.
=> Support empty LG file

.gitignore, Directory.Build.props, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj, libraries/AdaptiveExpressions/AdaptiveExpressions.csproj, libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.ApplicationInsights/Microsoft.Bot.Builder.ApplicationInsights.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj, libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj, libraries/Microsoft.Bot.Builder.Testing/Microsoft.Bot.Builder.Testing.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj, libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
* Add missing contentFiles attribute
* remove over inclusion of json files in adaptive assembly
* add publishRepositoryUrl to msbuild
=> bump assembly version 4.8 => 4.9

build/yaml/botbuilder-dotnet-ci-facebook-test.yml, build/yaml/botbuilder-dotnet-ci-slack-test.yml, build/yaml/botbuilder-dotnet-ci-twilio-test.yml, build/yaml/botbuilder-dotnet-ci-webex-test.yml, build/yaml/botbuilder-dotnet-functional-test-linux.yml, build/yaml/botbuilder-dotnet-functional-test-windows.yml
Prevents functional test build collisions creating and deleting resource groups
=> Set CI trigger to batch changes

libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/TestData/QnaMaker_TopNAnswer_DisableActiveLearning.json
=> [QnAMaker] Volitile LowScoreVariation and Active Learning Issue fix

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs, libraries/Microsoft.Bot.Builder/StringUtils.cs
fixes #3828
Copy SendOAuthCardAsync, RecognizeTokenAsync from https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
=> OAuthInput: create parity with OAuthPrompt

libraries/Microsoft.Bot.Builder.AI.QnA/Models/QnAMakerTraceInfo.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerOptions.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerRecognizerTests.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
=> MetadataBoost dead code cleanup

tests/Microsoft.Bot.Builder.TestBot.Json/testbot.schema, tests/tests.schema
dialog:merge has also been updated.
=> Remove $id from schema to prevent tests from changing assets.

libraries/AdaptiveExpressions/AdaptiveExpressions.csproj, libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj, libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, tests/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj, tests/tests.schema
* change Dialogs.Adaptive, AdaptiveExpressions, LanguageGeneartion, Delcarative to release version 
* clean up dependencies to be miminum
=> Update project files for release

libraries/AdaptiveExpressions/AdaptiveExpressions.csproj, libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj, libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, tests/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj, tests/tests.schema
fixes #3871 
* change to release version (#3870)
* clean up dependencies to be miminum
=> Cherry pick #3870

build/AnalyzeDeps/AnalyzeDeps.ps1, build/AnalyzeDeps/InterdependencyGraph.html, build/AnalyzeDeps/deps.html.tpl
Partially fixes: https://github.com/microsoft/botbuilder-dotnet/issues/3413
Still need to add something like: https://github.com/Azure/azure-sdk-for-net/blob/master/eng/pipelines/aggregate-reports.yml#L29 to our build pipeline.
=> Add generation scripts and interdependency graph

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/3922
=> Do NOT call TeamsInfo.getMember for the bot

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.HttpRequest.schema
https://github.com/microsoft/BotFramework-Composer/pull/3003
This is to update resultProperty description in composer UX.
We already updated in the composer side, this is just to bring this to the sdk side.
=> update resultProperty descption of http request step

tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Related https://github.com/microsoft/botbuilder-dotnet/issues/3902
It is better if we have a full comparison testing template.
=> test comparisons for null

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj
=> Update Nuget.Client to resolve circular reference exception

libraries/AdaptiveExpressions/ExpressionFunctions.cs, libraries/AdaptiveExpressions/ExpressionType.cs, tests/AdaptiveExpressions.Tests/BadExpressionTests.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
close: #3610
Add sentenceCase function, that convert the first letter to upper case.
=> Add sentenceCase && titleCase builtin function

libraries/Microsoft.Bot.Builder.LanguageGeneration/MultiLanguageLG.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/MultilanguageLGTest.cs
=> Make data and locale optional in multilingual LG

libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs
=> Don't throw exception on unhandled VersionChangeDetected event

libraries/AdaptiveExpressions/parser/ExpressionParser.cs
close: #4005
Add cache for expression antlr parsing result.
=> Cache Expression parsing result

libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/Expand.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
fix https://github.com/microsoft/botbuilder-dotnet/issues/3973
=> fix corner case of expander when empty array occurs in structured lg

libraries/AdaptiveExpressions/ExpressionFunctions.cs, libraries/AdaptiveExpressions/ExpressionType.cs, tests/AdaptiveExpressions.Tests/BadExpressionTests.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
fixes: #4016 
add floor, ceiling, round pre-built functions
floor(3.51) = 3
floor(4.00) = 4
ceiling(3.51) = 4
ceiling(4.00) = 4
round(3.51) = 4
round(3.55, 1) = 3.6
round(3.12134, 3 = 3.121
=> Add floor, ceiling, round pre-built functions

libraries/Microsoft.Bot.Builder/AdapterExtensions.cs, libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
- Fixes warnings in ref doc build, primarily.
- Also fixes a small amount of wording and grammar.
=> Update doc XML

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/EvaluationOptions/StrictModeFalse.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/EvaluationOptions/StrictModeTrue.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
fix  #3972: strict mode issue in expander
=> fix strict mode issue in expander

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/ExpandText.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
close: #3968
Add `expandText` LG function to eval the plain text and get the data binding result.
=> add expandText LG function

tests/Microsoft.Bot.Builder.Tests/Adapters/TestAdapterTests.cs, tests/Microsoft.Bot.Builder.Tests/Adapters/TestFlowTests.cs, tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj
=> Porting Adapters folder to Xunit

tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs, tests/Microsoft.Bot.Schema.Tests/CardActionTest.cs, tests/Microsoft.Bot.Schema.Tests/EntitySchemaValidationTest.cs, tests/Microsoft.Bot.Schema.Tests/Microsoft.Bot.Schema.Tests.csproj, tests/Microsoft.Bot.Schema.Tests/Teams/TeamsChannelDataTests.cs
=> Migrating Schema to Xunit

tests/AdaptiveExpressions.Tests/AdaptiveExpressions.Tests.csproj, tests/AdaptiveExpressions.Tests/BadExpressionTests.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs, tests/AdaptiveExpressions.Tests/ExpressionPropertyTests.cs, tests/AdaptiveExpressions.Tests/LRUCacheTest.cs, tests/AdaptiveExpressions.Tests/RewriteTests.cs, tests/AdaptiveExpressions.Tests/TriggerTrees/Tests.cs
=> Porting adaptiveexpressions tests to xunit

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
fixes https://github.com/microsoft/botbuilder-dotnet/issues/4131
=> Teams + SSO: Update OAuthcard channel support and return 412 instead of 409 on sso fail

tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/MultilanguageLGTest.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesParseTreeTest.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
=> Port LanguageGeneration to Xunit

libraries/Microsoft.Bot.Configuration/Services/LuisService.cs
=> Add [Obsolete] attribute to Microsoft.Bot.Configuration.LuisService

libraries/Microsoft.Bot.Builder/BotState.cs, libraries/Microsoft.Bot.Builder/IStatePropertyAccessor.cs
=> Remove references to MissingMemberException

tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/LuisApplicationTests.cs, tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/LuisV3OracleTests.cs, tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/Microsoft.Bot.Builder.AI.LuisV3.Tests.csproj
=> Refactoring AI Luis V3 to Xunit

.github/CODEOWNERS
Update codeowners to use the follow teams as code owners:
- @microsoft/bb-dotnet
- @microsoft/bf-admin
- @microsoft/bf-adaptive
=> [Engineering] Update codeowners

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj
=> Remove preview tag from adapters

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnUnknownIntent.schema
=> fix for OnUnknownIntent title.

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.DateTimeInput.schema
=> fix outputformat property on DateTime input

libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogExtensionsTests.cs
Fixes https://github.com/microsoft/botframework-sdk/issues/5852
=> Add EndOfConversationCodes to EndOfConversation activity from Skill

libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/TelemetryMiddlewareTests.cs
=> Added null checks in telemetry logger middleware

libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs
Fixes #4247
Additional null checks for telemetry logging.
=> Add additional null checks to telemetry logger middleware.

libraries/Microsoft.Bot.Builder/ActivityHandler.cs, tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4287
=> Add installation update to ActivityHandler

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Observers/CycleDetectionObserver.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Parsers/TemplateExpressionParser.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProvider.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProviderExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/Resource.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
Relates to #2367 
- Applied Dispose pattern to some classes.
- Excluded some CA2000 errors (related to ownership transfer)
- Added comment for TaskDelay code in ResourceExplorer.
=> Adds FxCop to Dialogs.Declarative.

libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerRecognizerTests.cs
=> Set qna answer startIndex and endIndex

libraries/Microsoft.Bot.Schema/SpeechConstants.cs
=> added EmptySpeakTag constant

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityExtensions.cs, libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs, libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs
Adds the various summary, param, and return documentation for the Teams classes.
=> Adding documentation for Teams classes

libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs, libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugTransport.cs, tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbPartitionStorageTests.cs
- Added CultureInfo and StringComparison where needed.
- Fixed some ArgumentException calls that were using the wrong parameters.
- Implemented IDisposable pattern for CosmosDbPartitionedStorage and CosmosDbStorage
=> Added FxCop to Azure project.

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs
Some manual additions to the cherry picks as there was some divergence with the fxcop changes and others in the last few days.
=> Update master with SSO + Teams changes. Cherry picked main changes + test update.

tests/Microsoft.Bot.Builder.TestBot.Json/Samples/11 - HttpRequest/HttpRequest.main.dialog
Fixes HttpTests
Changed petco requests to use https instead http so the test would pass
=> Changed test to use https (petco was returning 405 for http)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SignOutUser.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SignOutUser.schema, tests/tests.schema
Fixes #4265 
description was wrong.
updated comment
updated schema description.
verified schema could be merged. (tests.schema)
=> fix comment and schema description of SignoutUser.Userid property.

tests/Directory.Build.props
Adding warning xunit2017 to ignore list.
=> Adding xunit2017

libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/Resources/naughtyStrings.txt, tests/Microsoft.Bot.Builder.Dialogs.Tests/TextPromptTests.cs
=> Testing naughty strings against TextPrompt

libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs
Fixes #5853
- adds another constructor to QnAMakerDialog
- we intend a deeper refactoring of this code in the next milestone - this change just adds the missing constructor
=> add constructor overload

libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateErrors.cs
=> Fix InternalsVisibleTo of LanguageGeneration

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Actions/AssertCondition.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpRequestSequenceMock.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpResponseMock.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReply.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyOneOf.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/TestAction.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserConversationUpdate.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserDelay.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserSays.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserTyping.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestScript.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/UserTokenMocks/UserTokenBasicMock.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/UserTokenMocks/UserTokenMock.cs
=> Adding missing docs to dialog.adaptive.testing

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.Ask.schema, tests/tests.schema
Cherry-pick from master into 4.10.
=> Cherry-pick #4432 into 4.10 Fix Microsoft.Ask schema

.github/ISSUE_TEMPLATE/-net-sdk-bug.md, .github/ISSUE_TEMPLATE/-net-sdk-feature-request.md
bugs will apply needs-triage and bug
feature requests will apply needs-triage and feature-request
=> Updated issue templates to apply default labels

build/yaml/botbuilder-dotnet-ci-slack-test.yml, tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/DeploymentTemplates/template-with-new-rg.json
=> Fix ARM template template-with-new-rg.json for Slack

Microsoft.Bot.Builder.sln, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.AttachmentInput.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ChoiceInput.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ConfirmInput.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Templates/Microsoft.StaticActivityTemplate.schema, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Schemas/Microsoft.IActivityTemplate.schema, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs, tests/tests.schema, tests/tests.uischema
This is in conjunction with the fixes in bf cli dialog:merge. 
Enable schema tests. (Although needed to filter out one test which is valid but fails validation.)
Switch to public schema references.
=> Enable schema merge tests

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Schemas/Microsoft.Test.CustomEvent.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyActivity.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/TestScriptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/TestScriptTests_AssertReply_Assertions_Failed.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/TestScriptTests_CustomEvent.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs, tests/Microsoft.Bot.Builder.TestBot.Json/Program.cs, tests/Microsoft.Bot.Builder.TestBot.Json/Startup.cs, tests/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs, tests/tests.schema, tests/update, tests/update.cmd
Added missing schema for Microsoft.Test.CustomEvent.
Removed comments from test script.
Fixed update scripts.
Made it so asserts show the activity and added tests.
Added --dialog to TestBot so you don't have to rename files.
=> Fixes for test scripts.

libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
Fixes dotnet sdk version of:  https://github.com/microsoft/botbuilder-js/issues/2714
for more info see: 
https://github.com/microsoft/botbuilder-dotnet/pull/3855
=> Set WaterfallStepContext.Parent correctly

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BeginSkill.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/CrossTrainedRecognizerSet.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.BeginSkill.schema
https://github.com/microsoft/botbuilder-dotnet/commit/06153032d5e55e89ac10b7158d446f3c4abe452c
and
https://github.com/microsoft/botbuilder-dotnet/commit/5515b8c6a1b860cf9b4ca9de8f7f9d81256b3b34
=> Cherry-pick to 4.10: CrossTrainedRecognizer and allowInterruptionForSkill

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReply.cs
Either you could have a description or get detailed information on the differences.  Make it so you get both kinds of information.
=> Improve error message for tests.

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
Cherry pick for #4596 
Fixes #4556
=> Add catch for JsonException in GetBodyContent. (#4596)

build/yaml/sign-steps.yml
Other ESRP service connections are deprecated and will be deleted.
=> Switch to ESRP Code Signing Connection 2020a

.github/CODEOWNERS
Fixes #4540
See PR #4553 or Issue #4540 for more details.
=> [Cherry-pick to main] add specific owners for TestBot.Json & TestProtocol

libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Schemas/Microsoft.QnAMakerRecognizer.schema, tests/Microsoft.Bot.Builder.AI.QnA.Tests/Microsoft.Bot.Builder.AI.QnA.Tests.csproj, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/TestScriptTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/HttpRequestMock/httpqnaanswer.mock.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/HttpRequestMock/httpqnaintent.mock.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/HttpRequestMock/httpqnalevel1.mock.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/HttpRequestMock/httpqnanoanswer.mock.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/HttpRequestMock/httpqnaprompts.mock.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/HttpRequestMock/httpqnatopnanswer.mock.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/TestScriptTests_HttpRequestQnAMakerDialogMock.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/TestScriptTests_HttpRequestQnAMakerRecognizerMock.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/QnAMakerUtils/MockQnAMakerClient.cs, tests/tests.schema
Close #4451
mock qna recognizer and dialog by http request mock
- mock qna recognizer and dialog like http request action i.e. use httpclient from TurnState if exists
- fix some bugs
add TestScriptTests_HttpRequestQnaRecognizerMock from QnAMakerRecognizerTests, TestScriptTests_HttpRequestQnAMakerDialogMock from QnAMakerTests
=> mock qna recognizer and dialog like http request action

build/yaml/botbuilder-dotnet-ci-facebook-test.yml, build/yaml/botbuilder-dotnet-ci-webex-test.yml
Fixing references to the pipeline variables.
=> Remove env prefix from pipeline variables

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
=> Fix the timeout login in OAuthInput

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4477
=> Fix OAuthInput on Teams

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/4477
=> Cherry-Pick to 4.10: Fix OAuthInput on Teams (#4660)

libraries/AdaptiveExpressions/parser/ExpressionAntlrLexer.g4, libraries/AdaptiveExpressions/parser/ExpressionAntlrParser.g4, libraries/AdaptiveExpressions/parser/ExpressionParser.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
issue link: #4506
Achieve a variable depending on a condition.
For example:
`a ? b : c `,  if 'a' is true, return b, otherwise return c.
which is equals to `if(a, b, c)`
=> [Expression]Support Conditional Operator

libraries/AdaptiveExpressions/ExpressionFunctions.cs, libraries/AdaptiveExpressions/parser/ExpressionAntlrLexer.g4, libraries/AdaptiveExpressions/parser/ExpressionAntlrParser.g4, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
issue link: #4506
Nullish coalescing adds the ability to truly check nullish values instead of falsey values. 
For example:
`a ?? b ?? c`, if a is null/undefined return b, if b is also null or undefined return c
=> [Expression]Support Nullish Coalescing feature

tests/Microsoft.Bot.Builder.Dialogs.Tests/SkillDialogTests.cs
Fixes the CI pipeline broken build.
=> Change Assert to verify collection size.

build/yaml/botbuilder-dotnet-ci-mac.yml, build/yaml/botbuilder-dotnet-ci.yml
Add PR and CI builds for branch lu-parser.
=> Add branch lu-parser to CI builds.

build/yaml/ci-build-steps.yml, libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj, nuget.config
=> updated reference version of Microsoft.BotFramework.Orchestrator

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorerOptions.cs, libraries/Microsoft.Bot.Builder/BotState.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_BeginDialog_With_Dup_Dialog_Ref/AdaptiveDialog_BeginDialog_With_Dup_Dialog_Ref.test.dialog
=> Cherry-picks from main

build/yaml/botbuilder-dotnet-sign.yml, build/yaml/sign-steps.yml
Fixes:
Missing ESRP service connection
Error NETSDK1004: Assets file 'D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\obj\project.assets.json' not found.
=> Update ESRP connection + add a package restore

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj
=> updated reference to latest version of Microsoft.BotFramework.Orchestrator

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReply.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AskTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AskTests/DefaultOp.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AskTests/Luis2Ops.mock.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AskTests/oneProperty.json
Fixes #3984
Cleaned up the entity logic to be easier to understand and added a preference for the default operation if recognizer returns multiple operations.
Added test for default operation preference.
=> Prefer default operation

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj
Fixes #
This way we won't ever have to update reference in the csproj until at least main version change.  Thanks Bruce for the tip!
- 
-
-
=> use wildcard reference for Microsoft.BotFramework.Orchestrator

libraries/Microsoft.Bot.Schema/Teams/Generated/MessagingExtensionAction.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4709
=> Add 'state' to MessagingExtensionAction

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
=> Cherry-Prick: update resource explorer load to use GetComponentRegistration

libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs
=> additional issuers in emulator validation

libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs, libraries/Microsoft.Bot.Connector/Teams/TeamsConnectorClientEx.cs
Fixes 1/2 of https://github.com/microsoft/botbuilder-dotnet/issues/4829
=> Dispose TeamsConnectorClient

libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs, libraries/Microsoft.Bot.Builder/TurnContext.cs
Fixes #https://github.com/microsoft/botframework-solutions/issues/3574
=> Fix issues with ExpectReplies and Invoke in SkillDialog

build/ExtractCompressNuGet.ps1
Same as PR #4896 for main branch.
=> Remove the patch install from ExtractCompressNuGet.ps1 (4.11)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnChooseIntent.uischema
refs microsoft/botframework-composer#4628
=> add OnChooseIntent uischema

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestScript.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs
This fixes the issue for PVA by reverting the change to RootDialog.
=> Revert the change on RootDialog while still allowing LG functions.

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestScript.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs
This reverts previous changes while still allowing LG functions to be used in dialog expressions.
=> Cherry-pick of dialog manager fix for PVA

libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/SettingsMemoryScope.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/CustomizedMemory.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/SettingsStateTests/SettingsStateTests_SettingsTest.test.dialog
Fixes #4722
- make settings memory scope immutable
- update test
- fix CustomizedMemory
=> make settings immutable

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.LogAction.uischema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SendActivity.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.TraceActivity.uischema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnChooseIntent.uischema, tests/tests.schema, tests/tests.uischema
This includes PRs below and the updates to tests.schema/uischema
https://github.com/microsoft/botbuilder-dotnet/pull/4923 
https://github.com/microsoft/botbuilder-dotnet/pull/4911 
https://github.com/microsoft/botbuilder-dotnet/pull/4914
=> Cherry-picks for 4.11

libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/Transcript_MiddlewareTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4734
=> Add IsNullOrEmpty to TranscriptLoggerMiddleware.EnsureActivityHasId

Microsoft.Bot.Builder.sln, libraries/copySchemas.cmd
This is a script that copies C# schemas to botbuilder-js.
=> Add script for copying schemas.

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorAdaptiveRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs
=> updated summary for model/snapshot path properties

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorAdaptiveRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs
Fixes #
#4969 
Documentation updates to properties: ModelPath, SnapshotPathDisambiguationThreshold, DetectAmbiguousIntents
=> OrchestratorRecognizer documentation updates for 4.11 branch

libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentials.cs, libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentialsOptions.cs
In the BotFrameworkHttpAdapter override:
```cs
protected override Task<AppCredentials> BuildCredentialsAsync(string appId, string oAuthScope = null)
{
var cert = GetCertificateFromStore(_thumbPrint);
var options = new CertificateAppCredentialsOptions() 
{ 
AppId = appId, 
ClientCertificate = cert,
OauthScope = oAuthScope,
// CustomHttpClient = this.HttpClient, 
};
return Task.FromResult(new CertificateAppCredentials(options) as AppCredentials);
}
// From https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2
private static X509Certificate2 GetCertificateFromStore(string thumbPrint)
{
// Get the certificate store for the current user.
//var store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
var store = new …
```
=> Enable OAuthScope in CertificateAppCredentials

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEach.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/TestUtils.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestForeachWithPromptInConversationUpdate.test.dialog
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4976
Note: we might want to cherry-pick this to 4.11
=> End the dialog if the list to iterate is null in ForEach

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.InputDialog.schema, tests/tests.schema, tests/tests.uischema
Update test schemas.
Fixes #4342 
Adds min/max to InputDialog.schema maxTurnCount so that Composer can validate the field.
=> Add min/max for turn count.

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnChooseEntity.uischema, tests/tests.schema, tests/tests.uischema
Fixes #5012 
Created uischema and reviewed the combined schema.
=> Add .uischema for OnChooseEntity.

README.md, dailyBuilds.md
=> Add daily builds instructions

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EditArray.cs
=> Add clarification to EditArray Remove

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.DeleteActivity.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.GetActivityMembers.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.UpdateActivity.schema, tests/Microsoft.Bot.Builder.TestBot.Json/testbot.schema, tests/tests.schema
Fixes #4499
Update scheme sample, and fix some error memory variable
Existed test: 
https://github.com/microsoft/botbuilder-dotnet/blob/d5726a7d10ea9dc1b446ec23165353d6ed955f01/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_DeleteActivity.test.dialog#L17
=> Update the schema sample

libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5035
=> Update TranscriptLoggerMiddleware set turnContext.Activity.From.Role

libraries/Microsoft.Bot.Builder/ActivityHandler.cs, tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5078
=> Add add-upgrade and remove-upgrade for InstallationUpdate

tests/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj, tests/Microsoft.Bot.Builder.TestBot.Json/TestBotHttpAdapter.cs
Composer has added the ability to set SetTestOptions randomValue and randomSeed to control randomness in your bot. This adds the ability to consume those value in TestBot.json.
=> Add the ability to consume SetTestOptions in TestBot.

libraries/Microsoft.Bot.Builder/TokenResolver.cs
___
Edit by @stevengum:
This PR refactors the TokenResolver class which provides support for User OAuth in Streaming scenarios.
It is related to https://github.com/microsoft/botbuilder-dotnet/pull/5096
=> Prep TokenResolver for CloudAdapter

libraries/Microsoft.Bot.Builder/ConversationState.cs
=> Remove stranded CA2208 restore

tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
=> Add test for NumericEvaluator

tests/Microsoft.Bot.Builder.TestBot/appsettings.json
Fixes TestBot Functional tests.
=> Update OAuthUrl in TestBot

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendHandoffActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SendHandoffActivity.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SendHandoffActivity.uischema
Fixes #5189 
Adds a SendHandoffActivity adaptive action.
=> Add SendHandoffActivity action

tests/Microsoft.Bot.Streaming.Tests/WebSocketTransportTests.cs
Fix a race condition in the streaming connect test.
We've seen this test fail sometimes - it doesn't appear related to the new streaming code higher up the stack - although there is a change to one class that was used here.
So that class shouldn't have been used here - it is better and more precise to use a mock.
The problem in the test appears to be a race. The test starts a background task, it seems the background task could switch the IsConnected to false depending on the state of the underlying "faux" socket. This change is to initialize that "faux" socket to open.
=> fix a race condition in the streaming connect test

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj
Update Orchestrator Recognizer to use R12 package.
#5222 
Update package reference to [R12 Orchestrator Package](https://www.nuget.org/packages/Microsoft.BotFramework.Orchestrator/4.12.0-rc1.preview)
=> Update orchestrator package reference for R12

libraries/Microsoft.Bot.Builder/ActivityHandler.cs, libraries/Microsoft.Bot.Schema/AdaptiveCardAuthentication.cs, libraries/Microsoft.Bot.Schema/AdaptiveCardInvokeAction.cs, libraries/Microsoft.Bot.Schema/AdaptiveCardInvokeResponse.cs, libraries/Microsoft.Bot.Schema/AdaptiveCardInvokeValue.cs, tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5159
=> Add OnAdaptiveCardInvokeAsync to ActivityHandler

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SendHandoffActivity.uischema
Update handoff action uischema to show in Composer action menu.
=> Update handoff action uischema to show in Composer action menu

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SendHandoffActivity.uischema
=> Cherry-Pick: Update handoff action uischema to show in Composer action menu (#5231)

libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/Extensions/ServiceCollectionExtensions.cs, tests/integration/Microsoft.Bot.Builder.Integration.Runtime.Tests/Extensions/AdapterRegistrationTests.cs
=> Runtime: Fix bug in CoreAdapter registration. SkillHttpClient needs a BotAdapter registered

tests/Microsoft.Bot.Streaming.Tests/WebSocketTransportTests.cs
Add an addition wait to fix race in Web socket connect test
=> Add an additional wait to fix race in Web socket connect test

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs
Send Handoff Activity was not registered, which caused an error when using this within Composer.
=> Register the SendHandoffActivity action

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5267
=> Use HttpRequestMessage for headers, and dispose created HttpClient in HttpRequest

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioClientWrapper.cs, libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorAdaptiveRecognizer.cs, libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs, libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ContinueConversationLater.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/BotStateMemoryScope.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/MemoryTranscriptStore.cs
This fixes https://github.com/microsoft/botbuilder-dotnet/issues/5273 for me, however: why is the build not failing in the pipeline, or on other dev's machines?
=> Fix CA2208 warnings as errors

libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/Microsoft.Bot.Builder.Integration.Runtime.csproj
It also fixes minor bug for checking applying the Plugins dependency version.
Fixes #5295
=> Fixes Runtime to depend on preview version of Adaptive.Teams

libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/Microsoft.Bot.Builder.Integration.Runtime.csproj
It also fixes minor bug for checking applying the Plugins dependency version.
Fixes #5295
=> Fixes Runtime to depend on preview version of Adaptive.Teams.

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_TextInputWithInvalidResponse.test.dialog
=> Do nothing when the activity is null

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_TextInput_WithEmptyPrompt.test.dialog
=> Check null for input prompt

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnCommandActivity.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnCommandActivity.uischema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnCommandResultActivity.schema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnCommandResultActivity.uischema, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnCommandActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnCommandResultActivity.cs, libraries/Microsoft.Bot.Builder/ActivityHandler.cs, libraries/Microsoft.Bot.Schema/ActivityEx.cs, libraries/Microsoft.Bot.Schema/ActivityTypes.cs, libraries/Microsoft.Bot.Schema/CommandResultValue.cs, libraries/Microsoft.Bot.Schema/CommandValue.cs, libraries/Microsoft.Bot.Schema/ICommandActivity.cs, libraries/Microsoft.Bot.Schema/ICommandResultActivity.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ConditionalsTests.cs, tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs, tests/tests.schema, tests/tests.uischema
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5282
ToDo:
- add more unit tests
- Workout details of returning Status400BadRequest from NotSupportedException?
=> Add Command and CommandResult activity types

libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/CoreBotAdapter.cs
=> CoreBotAdapter is missing EoC logic (Skill bot)

libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5349
=> Expose StreamingRequestHandler creation in BotFrameworkHttpAdapter

libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/ConfigurationAdaptiveDialogBot.cs, libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/Extensions/ServiceCollectionExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/ServiceFactory.cs
Fixes #5331 
Having the factory also avoids ambiguity on the MemoryStorage constructor.
=> try add storage and its dependencies

libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/CoreBotAdapter.cs, libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/Extensions/ServiceCollectionExtensions.cs, tests/Auth/bot-authentication/Startup.cs
=> Update CoreBotAdapter to derive from CloudAdapter

libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/Extensions/ServiceCollectionExtensions.cs
=> add middleware to services as IMiddlewware so they can be found

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorAdaptiveRecognizer.cs
Fixes #
#5339 
Moved activity tracking code to after entity scoring.
=> Activity tracking for OrchestratorAdaptiveRecognizer needs to be done after entity scoring

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj
Another PR will be sent in the botframework-components repo to remove the component from there
=> Orchestrator: make a component by adding bf-component tag

libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/Extensions/ServiceCollectionExtensions.cs, libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/Microsoft.Bot.Builder.Integration.Runtime.csproj, tests/Auth/bot-authentication/Startup.cs, tests/integration/Microsoft.Bot.Builder.Integration.Runtime.Tests/Extensions/SkillRegistrationTests.cs, tests/integration/Microsoft.Bot.Builder.Integration.Runtime.Tests/Extensions/StorageRegistrationTests.cs
=> update services collection in adaptive runtime

libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
=> mark DialogManager property on DialogContext as obsolete

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialogBot.cs
=> load the resource on the first turn

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/ConfigurationAdaptiveDialogBot.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/ConfigurationLanguagePolicy.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialogBot.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogBotTests.cs
=> make LanguagePolicy pluggable in AdaptiveDialogBot

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.OAuthInput.schema, tests/tests.schema
Fixes #5434 
Updated the property path for OAuthInput to default to "turn.token". Also updated the description to warn against changing this value.
=> Updated default property path for OAuthInput

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.HttpRequest.schema, tests/tests.schema
Fixes #5433 
Updated schema for HttpRequest to default to returning results to "turn.results".
=> Updated default ResultProperty for HttpRequest

libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/TurnMemoryScope.cs
=> turn memory scope includesnapshot to false

.github/workflows/pr-style.yml
This action will validate that PRs include a linked issue.
Fixes #5459
=> ci: pr style linting

libraries/Microsoft.Bot.Schema/OAuthCard.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5460
=> CherryPick: add jsonProperty to TokenExchangeResource (#5461)

libraries/Microsoft.Bot.Schema/ActivityEx.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5451
=> Add AsCommandActivity and AsCommandResultActivity

libraries/Microsoft.Bot.Schema/ActivityEx.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5451
=> CherryPick: (#5452) Add AsCommandActivity and AsCommandResultActivity 

libraries/Microsoft.Bot.Builder/Teams/TeamsSSOTokenExchangeMiddleware.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5473
=> Add Teams SSO Token Exchange middleware

libraries/Microsoft.Bot.Builder/Teams/TeamsSSOTokenExchangeMiddleware.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5473
=> CherryPick (#5475): Add Teams SSO Token Exchange middleware 

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj
#minor
Cherry pick of https://github.com/microsoft/botbuilder-dotnet/pull/5478
=> [Cherry pick] SDK Adapters: include schemas guaranteeing no duplicates in package

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj
Fixes #5485 
Update package reference to Microsoft.BotFramework.Orchestrator GA 4.13.0
=> feat: Update to point at Orchestrator 4.13

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EmitEvent.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.EmitEvent.schema, tests/tests.schema
Fixes #5307 
Added a new "Handled Property" property which lets you specify where to return a flag indicating if the event was handled.
=> Added HandledProperty to EmitEvent action

tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests/Extensions/StorageRegistrationTests.cs
=> Runtime: Enabled and corrected StorageRegistrationTests

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs
Cherry pick of https://github.com/microsoft/botbuilder-dotnet/pull/5512
=> [Cherry pick] Runtime: Allow components and startup overriding IBot and IBotTelemetryClient (#5512)

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj, libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs
=> Upgrade Microsoft.BotFramework.Orchestrator to v 4.13.1

libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj, libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs
* Upgrade Microsoft.BotFramework.Orchestrator to v 4.13.1
* Log model path in failed load model exception
* Log entity model path in load model exception if specified
* Update OrchestratorRecognizer.cs
=> Cherry-pick Upgrade Microsoft.BotFramework.Orchestrator to v 4.13.1 (#5525)

libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs, libraries/Microsoft.Bot.Builder/Teams/TeamsSSOTokenExchangeMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsSSOTokenExchangeMiddlewareTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5482
and
https://github.com/microsoft/botbuilder-dotnet/issues/5487
=> Add TeamsSSOTokenExchangeMiddleware tests

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SignOutUser.cs
=> add logic to call UserTokenClient when present (#5532)

libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/analyzer.lg, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Fixes https://github.com/microsoft/botbuilder-js/issues/3619
Support analyze recursive functions in `AnalyzeTemplate` API.
=> [LG] Fix recursive functions error in analyzer

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
* SSO + adaptive runtime: Save state before sending OAuthCard to prevent race conditions.
* OAuthInput: fix typo in comment
* Allow null Title and Text for OAuthInput
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5516
Co-authored-by: Eric Dahlvang <erdahlva@microsoft.com>
=> Cherry-pick SSO + adaptive runtime: Save state before sending OAuthCard to prevent race conditions (#5543)

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Skills/SkillHttpClient.cs
=> Skills: Obsolete SkillHttpClient

libraries/AdaptiveExpressions/BuiltinFunctions/ConvertFromUtc.cs, libraries/AdaptiveExpressions/BuiltinFunctions/GetTimeOfDay.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Cherry-pick the fixes to #5552.
#minor
=> [Cherry-pick] Support timestamp without timezone postfix in getTimeOfDay (#5551)

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisAdaptiveRecognizer.cs, libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs, libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/AdaptiveRecognizer.cs
Fixes microsoft/BotFramework-Composer#7533
microsoft/BotFramework-Composer#7661
=> Cherry-Pick to 4.13: Update telemetry LogPersonalInformation config path for recognizers

build/yaml/botbuilder-dotnet-ci-facebook-test.yml
#minor
Disable CI and PR trigger for facebook functional tests.
=> Update botbuilder-dotnet-ci-facebook-test.yml for Azure Pipelines

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BaseInvokeDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EndDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperties.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperty.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/JsonExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/SettingsMemoryScope.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_SetProperty.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/SettingsStateTests/SettingsStateTests_SettingsTest.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/test.settings.json
Fixes #5609
Fix the double evaluation and filter sensitive settings
=> Fix double evaluation and filter sensitive settings

tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests/Extensions/FeatureTests.cs
=> Added missing Runtime Feature tests

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BaseInvokeDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EndDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperties.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperty.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/JsonExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/SettingsMemoryScope.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_SetProperty.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/SettingsStateTests/SettingsStateTests_SettingsTest.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/test.settings.json
Fix the double evaluation and filter sensitive settings
=> cherry-pick (4.13): Fix double evaluation and filter sensitive settings (#5641)

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorAdaptiveRecognizer.cs, libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs, libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ContinueConversationLater.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/BotStateMemoryScope.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/CloudAdapterBase.cs, libraries/Microsoft.Bot.Builder/MemoryTranscriptStore.cs
Cherry-pick of #5666 plus a fix to CloudAdapterBase.
=> Fix warning as errors in branch 4.11

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorAdaptiveRecognizer.cs, libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs, libraries/Microsoft.Bot.Builder.Azure.Queues/ContinueConversationLater.cs, libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/BotStateMemoryScope.cs, libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, libraries/Microsoft.Bot.Builder/MemoryTranscriptStore.cs
Warnings as errors are breaking the build. These changes are a subset of #5274 merged into 'main'.
=> Fix warnings as errors in branch 4.10

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/SettingsMemoryScope.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/SettingsStateTests/SettingsStateTests_SettingsTest.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/test.settings.json
Fix double evaluation and filter sensitive settings
=> cherry-pick (4.9): Fix double evaluation and filter sensitive settings (#5641)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BaseInvokeDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EndDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperties.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperty.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/JsonExtensions.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/SettingsMemoryScope.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_SetProperty.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/SettingsStateTests/SettingsStateTests_SettingsTest.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/test.settings.json
Fix double evaluation and filter sensitive settings
=> cherry-pick (4.12): Fix double evaluation and filter sensitive settings (#5641)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Scopes/SettingsMemoryScope.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/SettingsStateTests/SettingsStateTests_SettingsTest.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Tests/MemoryScopeTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/test.settings.json
Fix double evaluation and filter sensitive settings
=> cherry-pick (4.8): Fix double evaluation and filter sensitive settings (#5641) 

libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/TurnMemoryScope.cs, tests/Auth/bot-authentication/AuthenticationBot.csproj, tests/Auth/bot-authentication/appsettings.json, tests/Auth/bot-authentication/snapshot.dialog
=> flip turn memory scope to be included in the snapshot

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_AllowInterruptionWithMaxCount.test.dialog
Fixes #5611
The turn count would increase only `turn.interrupte` is set to false.
=> fix: Maxturn count increase while interruption in composer prompts

libraries/Microsoft.Bot.Builder.AI.Orchestrator/README.md
=> Orchestrator package readme

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ChannelServiceExceptionFilterAttribute.cs
=> remove exception handled

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs
Fixes #5598
Just a step I'm sure we could do more.
=> addition remark doc comments

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
=> updated obsolete message according to feedback

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.BeginSkill.uischema, tests/tests.uischema
* use correct header schema for BeginSkill
* Update tests.uischema
* Cherry pick from #5767 
#minor
=> [Cherry-pick] Use correct header schema for BeginSkill (#5767)

tests/AdaptiveExpressions.Tests/BadExpressionTests.cs
Fixes #5775
Remove duplicate tests in adaptive expressions.
=> fix: clean up tests in adaptive expressions

libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs
#minor
Cherry picking https://github.com/microsoft/botbuilder-dotnet/pull/5803 into 4.13 for PVA fix.
=> chore: [Cherry pick] Streaming error handling into 4.13

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/MultiLanguageRecognizer.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MultiLanguageRecognizerTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/MultiLanguageRecognizerTests/MultiLanguageRecognizerTest_RecognizerCaseInsensitivity.test.dialog
Fixes #5479
Change MultiLanguageRecognizer to case insensitive
=> Make Multi-language recognizer case-insensitive

libraries/Microsoft.Bot.Connector/Authentication/MsalAppCredentials.cs
=> MSAL auth: fix log entry text

libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs, tests/Microsoft.Bot.Streaming.Tests/Microsoft.Bot.Streaming.Tests.csproj, tests/Microsoft.Bot.Streaming.Tests/StreamingRequestHandlerTests.cs
* Make methods virtual
* Move package reference
Fixes #5816
=> [Cherry-pick] Make StreamingRequestHandler methods virtual (#5828)

tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenValidationTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5831
=> Delete appid/password from tests

libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs, tests/Microsoft.Bot.Streaming.Tests/Microsoft.Bot.Streaming.Tests.csproj, tests/Microsoft.Bot.Streaming.Tests/StreamingRequestHandlerTests.cs
=> [Cherry-pick to 4.14] Make StreamingRequestHandler methods virtual (#5828)

libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs
=> [Cherry-pick to 4.14] Streaming: Surface exceptions like other paths to allow error handling in upper layers. (#5803)

libraries/Microsoft.Bot.Connector/Channels.cs
=> Add "omnichannel" to Channels

libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs, tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorAdaptiveRecognizerTests.cs
=> Prevent duplicate None labels from being added twice

libraries/Microsoft.Bot.Streaming/ProtocolAdapter.cs, libraries/Microsoft.Bot.Streaming/StreamExtensions.cs
=> Add key for InternalsVisibleTo in Microsoft.Bot.Streaming

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj, tests/Microsoft.Bot.Streaming.Tests/Microsoft.Bot.Streaming.Tests.csproj
=> Cherry-Pick: Update Microsoft.AspNetCore.Http to 2.1.22 (#5936)

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs, tests/Microsoft.Bot.Streaming.Tests/Payloads/PayloadReceiverTests.cs
=> add control property

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
* add control property
* disable fragile test
#minor
=> Cherry-pick to 4.13: add control property (#5943)

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs, tests/Microsoft.Bot.Streaming.Tests/Payloads/PayloadReceiverTests.cs
* add control property
* disable fragile test
#minor
=> CherryPick to 4.15: add control property (#5943)

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/FacebookChatTests.cs, build/yaml/botbuilder-dotnet-ci-facebook-test.yml
Fixes #minor
Add "clear message queue" before running FB test.
Enable pipeline CI, PR triggers.
=> Facebook functional test fixes

libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
=> flip enableFromFile to false by default and fix unit tests

libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs, libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
=> #minor CherryPick control property to 4.14

libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
#minor
* flip enableFromFile to false by default and fix unit tests
* fxi unit test
=> #minor Cherry-Pick to 4.13: flip enableFromFile to false by default and fix unit tests (#5953)

libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs, tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
#minor
* flip enableFromFile to false by default and fix unit tests
* fxi unit test
=> #minor Cherry-Pick to 4.15: flip enableFromFile to false by default and fix unit tests (#5953)

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPromptSettings.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs
* Add ShowSignInLink to OAuthPromptSettings
* Refactor tests
Fixes #5887
=> [Cherry-pick to 4.14] Add ShowSignInLink to OAuthPromptSettings (#5906)

libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs, libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPromptSettings.cs, libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs
* Add ShowSignInLink to OAuthPromptSettings
* Refactor tests
Fixes #5887
=> [Cherry-Pick to 4.13] Add ShowSignInLink to OAuthPromptSettings (#5906)

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/DirectLineClientTests.cs
Fixes #minor
This test has been failing intermittently in pipeline [BotBuilder-DotNet-Functional-Tests-Linux-yaml](https://dev.azure.com/FuseLabs/SDK_v4/_build?definitionId=779&_a=summary).
Apply the same fix as was done for https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/tests/Samples.EchoBot.FunctionalTests/DirectLineClientTests.cs
=> Fix test SendDirectLineMessage()

libraries/AdaptiveExpressions/AdaptiveExpressions.csproj, libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj, libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj, libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj, libraries/Microsoft.Bot.Builder.ApplicationInsights/Microsoft.Bot.Builder.ApplicationInsights.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj, libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj, libraries/Microsoft.Bot.Builder.Testing/Microsoft.Bot.Builder.Testing.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Connector.Streaming/Microsoft.Bot.Connector.Streaming.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj, libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj, libraries/Storage/Microsoft.Bot.Builder.Azure.Blobs/Microsoft.Bot.Builder.Azure.Blobs.csproj, libraries/Storage/Microsoft.Bot.Builder.Azure.Cosmos/Microsoft.Bot.Builder.Azure.Cosmos.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
Fixes #6026 
This change affects the daily builds in Azure Pipelines. No suffix is added to local builds.
=> Add 'preview' suffix to all package versions

build/yaml/botbuilder-dotnet-sign.yml, build/yaml/ci-build-steps.yml, build/yaml/sign-steps.yml
=> Add signing pipeline yaml to v5 branch

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/LogAction.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/UpdateActivity.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/CrossTrainedRecognizerSet.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/MultiLanguageRecognizer.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RecognizerSet.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/ValueRecognizer.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TelemetryLoggerConstants.cs
also update 'GeneratorResult' events, adding a 'context' property.
Fixes #5020
=> Add TelemetryLoggerConstants for adaptive. 

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
=> Cherry-pick to 4.15: Ensure services are copied to new child context in ForEachElement (#6045)

build/yaml/botbuilder-dotnet-ci-mac.yml, build/yaml/vnextprototype/botbuilder-dotnet-ci-mac.yml
Fixes #6058
https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/
=> Update macOS .yaml to vmImage: 'macOS-latest'

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestForeachNullItems.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestForeachWithPromptCachedItems.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestNestedForeachWithPromptCachedItems.test.dialog
=> Cache items in ForEachElement

build/yaml/botbuilder-dotnet-ci-mac.yml, build/yaml/vnextprototype/botbuilder-dotnet-ci-mac.yml
* Update macOS .yaml
* Change mac vm image to macOS-1015
Fixes #6058
=> Cherry-Pick to 4.15: Update macOS .yaml to vmImage: 'macOS-latest' (#6059)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestForeachNullItems.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestForeachWithPromptCachedItems.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestNestedForeachWithPromptCachedItems.test.dialog
* Cache items in ForEachElement
* Add TestForeachWithPromptCachedItems
* Fix nested ForEachElement
* Remove this.foreachIndex from ForEachElement
Add nested ForEach test
Fixes #6056
=> Cherry-Pick to 4.15: Cache items in ForEachElement (#6057)

build/yaml/botbuilder-dotnet-sign.yml, build/yaml/sign-steps.yml
Fixes #minor
Need "software bill of materials" for our public facing products, per Presidential Executive Order.
Task 'Generate Software Bill of Materials' added to v5 signing build.
=> Add Software Bill of Materials task for C# for v5

tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Profiling/Program.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests/Extensions/RuntimeComponentTests.cs, tests/Microsoft.Bot.Configuration.Tests/ConfigurationLoadAndSaveTests.cs, tests/Microsoft.Bot.Configuration.Tests/EncryptionTests.cs
#minor
- Suppress CredScan errors for fake keys
- Remove legacy test
=> Suppress CredScan errors for fake keys

tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/DisableTestRunParallel.cs
=> Disabled parallel tests for Microsoft.Bot.ApplicationInsights.Core.Tests

libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicesChannelTests.cs
=> Teams now supports <= 50 Card Actions

Directory.Build.props, libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs, libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisOracleTests.cs, tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisV3OracleTests.cs, tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs, tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/LuisV3OracleTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicesChannelTests.cs, tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/DisableTestRunParallel.cs
Fixes #minor
Merge latest from main into v5.
=> Merge main into v5

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
Fixes #6091
note Components update to 4.15 is blocked: https://github.com/microsoft/botframework-components/pull/1288
=> Fix null ref exception in ForEachElement

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
=> Cherry-Pick to 4.15: Remove URL from OnComputId method (#6110)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
=> Cherry-Pick to 4.15: Fix null ref exception in ForEachElement (#6092)

build/yaml/botbuilder-dotnet-ci-mac.yml
#minor
Getting source from ADO feed in MAC build.
=> Setup DotNet v4 Mac pipeline for new feed

libraries/Microsoft.Bot.Builder/Inspection/InspectionMiddleware.cs, libraries/Microsoft.Bot.Builder/Inspection/InspectionState.cs, libraries/Microsoft.Bot.Builder/Inspection/InterceptionMiddleware.cs
=> Obsolete sidecar debugging classes

libraries/Microsoft.Bot.Builder/Teams/TeamsActivityExtensions.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityExtensionsTests.cs
=> Set TeamsNotifyUser Alert to opposite of AlertInMeeting

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialogBot.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/MultiLanguageGenerator.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/MultiLanguageGeneratorBase.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ResourceMultiLanguageGenerator.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/TemplateEngineLanguageGenerator.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs
=> Cherry pick to 4.15: Add top level lazy load on LanguageGeneratorManager (#6123)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.Foreach.schema, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_Foreach_WithEvent.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestNestedForeachWithPromptCachedItems.test.dialog, tests/tests.schema
=> Fix for when Actions are updated in ForEachElement

libraries/Microsoft.Bot.Builder/TelemetryConstants.cs, libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/TelemetryMiddlewareTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5023
=> Add ActivityTypeProperty to TelemetryLoggerMiddleware

.github/CODEOWNERS
#Minor
Updated codeowners file with latest from main
=> Updates code owners with latest from main

actions/verify-pr-labels/index.js
Fixes #minor
Fix validLabels casing in verify-pr-labels action.
=> Fix labels casing in parity check action

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestForeachWithEndDialog.test.dialog
=> Ensure EndDialog action within a ForEachElement will end the dialog

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs, libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestForeachWithEndDialog.test.dialog
* Ensure EndDialog action within a ForEachElement will end the dialog
* EndDialog from a nested ForEach
* Add clarifying comments to ForEachElement
Fixes #6161
=> CherryPick to 4.15: Ensure EndDialog action within a ForEachElement will end the dialog 

generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/Microsoft.BotFramework.CSharp.CoreBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/CoreBot.Tests.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CoreBot.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/Microsoft.BotFramework.CSharp.EchoBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Microsoft.BotFramework.EchoBot.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/Microsoft.BotFramework.CSharp.EmptyBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Microsoft.BotFramework.EmptyBot.csproj, generators/dotnet-templates/README.md, generators/vsix-vs-win/BotBuilderVSIX-V4/HOW_TO_VERSION.md, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.Tests.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.tests.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBotWithTests.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/source.extension.vsixmanifest
=> Update generators to 4.15.2

libraries/AdaptiveExpressions/Extensions.cs, tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
=> fix: Normalized number in number list

generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/Microsoft.BotFramework.CSharp.CoreBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/CoreBot.Tests.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CoreBot.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/Microsoft.BotFramework.CSharp.EchoBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Microsoft.BotFramework.EchoBot.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/Microsoft.BotFramework.CSharp.EmptyBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Microsoft.BotFramework.EmptyBot.csproj, generators/dotnet-templates/README.md, generators/vsix-vs-win/BotBuilderVSIX-V4/HOW_TO_VERSION.md, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.Tests.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.tests.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBotWithTests.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/source.extension.vsixmanifest
=> [Cherry-pick to 4.15] Update generators to 4.15.2 (#6178)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionScopeTests/ActionScope_Break.test.dialog
=> End ForEachElement on BreakLoop

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionScopeTests/ActionScope_Break.test.dialog
=> CherryPick to 4.15: End ForEachElement on BreakLoop (#6223)

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs, libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/DialogClassMemoryScope.cs, libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/DialogMemoryScope.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_ForEachElement_BeginDialog/AdaptiveDialog_ForEachElement_BeginDialog.test.dialog, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_ForEachElement_BeginDialog/AdaptiveDialog_ForEachElement_BeginDialog_innerDialog.dialog, tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs
=> ForEachElement as DialogContainer

libraries/Microsoft.Bot.Schema/Teams/TeamsChannelData.cs, tests/Microsoft.Bot.Schema.Tests/Teams/TeamsChannelDataTests.cs
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/6267
=> Add JsonExtensionData to TeamsChannelData

libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/CloudAdapter.cs, tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs
=> [Cherry-Pick] Do not check for streaming activity if ServiceUrl is null. (#6282)

libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs, tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterOAuthTests.cs, tests/Microsoft.Bot.Builder.Tests/MockAppCredentials.cs
Fixes #6298 
Cherry pick from main.
=> Add oAuthEndpoint to _oAuthClients cache key (#6298)

libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs
=> Add ApplicationName to CosmosDb client options for UserAgent

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
=> Cherry-Pick to 4.16: Handle DialogEvents.RepromptDialog in ForEachElement (#6325)

build/yaml/botbuilder-dotnet-ci.yml, build/yaml/ci-post-to-github-steps.yml
Fixes #minor
CI build pushes API compat results to the PR. But the task 'Verify publish compat results success' always reports failure. This fixes it.
=> Fix task 'Verify publish compat results success'

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Connector.Streaming/Microsoft.Bot.Connector.Streaming.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
Fixes #6340
Updated some projects to reference 2.1 libraries instead of 3.1
=> Changed min requirements for some libraries in the netstandard targetets

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.csproj, libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj, libraries/Microsoft.Bot.Connector.Streaming/Microsoft.Bot.Connector.Streaming.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
=> Changed min requirements for some libraries in the netstandard target  back to 2.1 versions (#6341)

libraries/Microsoft.Bot.Builder.AI.LUIS/LuisAdaptiveRecognizer.cs
=> Retrieve luis recognizer options from DialogContext.State

libraries/Microsoft.Bot.Schema/Teams/FileUploadInfo.cs
=> Remove unnecessary using directive

libraries/Microsoft.Bot.Schema/Teams/MeetingDetails.cs
=> fix: MeetingDetails dates are nullable

libraries/Microsoft.Bot.Schema/ConversationAccount.cs
=> minor: ConversationAccount/IsGroup: Correct typo in docs.

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
=> Use ActionScope.Actions in ForEachElement

libraries/Microsoft.Bot.Builder/SetSpeakMiddleware.cs, tests/Microsoft.Bot.Builder.Tests/SetSpeakMiddlewareTests.cs
This reverts commit c091272fd37041e50746cfc130750fee46c29736.
Fixes #5657
=> Revert "Multiple voice tags can now be added in speak field (#6315)"

generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/DeploymentTemplates/DeployUseExistResourceGroup/readme.md, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/DeploymentTemplates/DeployWithNewResourceGroup/readme.md, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/DeploymentTemplates/DeployUseExistResourceGroup/readme.md, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/DeploymentTemplates/DeployWithNewResourceGroup/readme.md, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/DeploymentTemplates/DeployUseExistResourceGroup/readme.md, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/DeploymentTemplates/DeployWithNewResourceGroup/readme.md
=> Reasonable ARM Template readme formatting

generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/Microsoft.BotFramework.CSharp.CoreBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/CoreBot.Tests.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CoreBot.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/Microsoft.BotFramework.CSharp.EchoBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Microsoft.BotFramework.EchoBot.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/Microsoft.BotFramework.CSharp.EmptyBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Microsoft.BotFramework.EmptyBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj
=> 4.17.1 bump for generators

tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/Microsoft.Bot.ApplicationInsights.WebApi.Tests.csproj
=> Removed Owin reference

tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/Microsoft.Bot.ApplicationInsights.WebApi.Tests.csproj
Co-authored-by: Tracy Boehrer <trboehre@microsoft.com>
Fixes #minor
=> Removed Owin reference (#6455)

libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs
Fixes #6459
This PR fixes an issue where the bot shows the typing indicator after it already has replied.
Moving away from running multiple background `Tasks` in a single `Conversation`, to having only one per `Conversation`, avoiding the execution disparity between each other.
- Added `OnSendActivities` listener to cancel the background task loop before a message is sent.
- Added two helper functions to start and finish the background task loop.
- Updated background `Task` and `CancellationToken` to be one per `Conversation`, instead of multiple ones.
The following image shows the before and after the applied fix.
=> [#6459] Typing indicator shown after bot has replied

build/yaml/botbuilder-dotnet-ci-slack-test.yml, build/yaml/botbuilder-dotnet-functional-test-linux.yml, build/yaml/botbuilder-dotnet-functional-test-windows.yml
Fixes #minor
Add task "Dir workspace".
=> Add diagnostics to DotNet FunctionalTests pipelines

build/yaml/botbuilder-dotnet-ci.yml
=> Enable CodeQL in pipelines (compliance)

libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs, tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
=> Ensure TeamsChannelData is supplied to ChannelData

build/CopyAdoWorkitemsToGithubIssues.ps1
Fixes #minor
Tweaks to log output in CopyAdoWorkitemsToGithubIssues.ps1
=> Tweaks to logging in Copy-CodeQL-Workitems-to-Github pipeline

generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/Microsoft.BotFramework.CSharp.CoreBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/CoreBot.Tests.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CoreBot.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/Microsoft.BotFramework.CSharp.EchoBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Microsoft.BotFramework.EchoBot.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/Microsoft.BotFramework.CSharp.EmptyBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Microsoft.BotFramework.EmptyBot.csproj, generators/dotnet-templates/README.md, generators/vsix-vs-win/BotBuilderVSIX-V4/HOW_TO_VERSION.md, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.Tests.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.tests.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBotWithTests.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/source.extension.vsixmanifest
=> Bumped generator dependency versions

libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/ServiceFactory.cs, tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests/Extensions/StorageRegistrationTests.cs
=> Throwing for invalid runtimeSettings.storage values or missing storage config

codeql3000.yml
=> Enabled TSA

.config/tsaoptions.json
=> Added tsaoptions.json

tests/Microsoft.Bot.Builder.TestBot.WebApi/packages.config, tests/Microsoft.Bot.Configuration.Tests/packages.config, tests/Microsoft.Bot.Schema.Tests/packages.config
=> Removed some lingering NewtonSoft <13 references

libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj
=> Updated NuGet.Packaging

libraries/Microsoft.Bot.Builder.Azure.Blobs/Microsoft.Bot.Builder.Azure.Blobs.csproj, libraries/Microsoft.Bot.Builder.Azure.Queues/Microsoft.Bot.Builder.Azure.Queues.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
#minor
Consolidation of multiple dependabot PR's
=> chore: Microsoft.Rest.ClientRuntime from 2.3.21 to 2.3.24

build/yaml/sign-steps.yml, libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj, libraries/Parsers/Microsoft.Bot.Builder.Parsers.LU/Microsoft.Bot.Builder.Parsers.LU.csproj, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj
=> Nuget Package updates

libraries/Microsoft.Bot.Builder.Azure.Blobs/Microsoft.Bot.Builder.Azure.Blobs.csproj, libraries/Microsoft.Bot.Builder.Azure.Queues/Microsoft.Bot.Builder.Azure.Queues.csproj, libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
=> Microsoft.Rest.ClientRuntime bump (#6662)

generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/Microsoft.BotFramework.CSharp.CoreBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/CoreBot.Tests.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CoreBot.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/Microsoft.BotFramework.CSharp.EchoBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Microsoft.BotFramework.EchoBot.csproj, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/Microsoft.BotFramework.CSharp.EmptyBot.nuspec, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.template.config/template.json, generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Microsoft.BotFramework.EmptyBot.csproj, generators/dotnet-templates/README.md, generators/vsix-vs-win/BotBuilderVSIX-V4/HOW_TO_VERSION.md, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.Tests.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.tests.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBotWithTests.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj, generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.vstemplate, generators/vsix-vs-win/BotBuilderVSIX-V4/source.extension.vsixmanifest
=> Generators to SDK 4.22.0

.github/workflows/create-botbuilder-parity-issues.yml
=> create-botbuilder-parity-issues.yml permissions

libraries/Microsoft.Bot.Builder/ChannelServiceHandler.cs, libraries/Microsoft.Bot.Connector/Authentication/AseChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/BuiltinBotFrameworkAuthentication.cs, libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/EnterpriseChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs, libraries/Microsoft.Bot.Connector/Authentication/ParameterizedBotFrameworkAuthentication.cs, libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/SkillValidationTests.cs
#minor
To assist in debugging auth issues.
=> Added messages for all UnauthorizedAccessException

Directory.Build.props, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
=> Microsoft.Identity.Client bump

libraries/Microsoft.Bot.AdaptiveExpressions.Core/Microsoft.Bot.AdaptiveExpressions.Core.csproj
=> AdaptiveExpression.Core framework

libraries/Microsoft.Bot.AdaptiveExpressions.Core/Microsoft.Bot.AdaptiveExpressions.Core.csproj
=> AdaptiveExpression.Core duplicated icon.png

libraries/Microsoft.Bot.AdaptiveExpressions.Core/Microsoft.Bot.AdaptiveExpressions.Core.csproj
=> Reverted AdaptiveExpressions.Core framework change

libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj, libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj, tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj
=> Bumped dependencies for System.Text.Json alert

build/yaml/botbuilder-dotnet-ci.yml
=> Disable manual component injection since it is injected
